rsyslog/rsyslog

contrib/imkmsg/imkmsg.c, contrib/imkmsg/kmsg.c, plugins/imklog/bsd.c, plugins/imklog/imklog.c
The previous fix for imkmsg in https://github.com/rsyslog/rsyslog/pull/138 was unreliable. Commit ac4fb31 updates it to make it reliable.
The same problem also affects the imklog plugin.  Commit 244d365 applies the same fix to imklog.
I also happened to notice an unrelated bugfix was recently applied to imklog but not imkmsg.  Commit 9b32fd5 applies that bug fix to imkmsg.
Thanks!
=> bugfix imklog/imkmsg: infinite loop on OpenVZ VMs

contrib/imkmsg/imkmsg.h
Sorry, I missed the header files in both imklog and imkmsg in my commits in https://github.com/rsyslog/rsyslog/pull/198 ... it looks like you fixed imklog.h in commit https://github.com/rsyslog/rsyslog/commit/7e309e38e81993e8752d1e4ec6d8844fcf1e03fb but did not fix imkmsg.h.  This commit fixes imkmsg.h.
Thanks!
=> fix build regression in imkmsg from ee035ef

platform/redhat/rsyslog.conf
the "For more information" doc path includes the string "*/", breaking c-style comment format. fixes #202.
=> bugfix header in platform/redhat/rsyslog.conf

plugins/mmnormalize/mmnormalize.c
With the recent changes, mmnormalize gives an error when specifying useRawMsg, even if 'variable' is not specified.
=> fix logic on 'variable' configuration validation, restore useRawMsg usability

configure.ac
This 2 patches enable rsyslog to be cross-compiled with mysql and pgsql support.
Previously mysql_config and pg_config where only searched for in PATH which would
normally pick up distribution files in turn breaking the compilation with library/include path
pollution and failure to link since they would be of a different architecture.
With the patches the user can specify the proper config files via ac_cv_prog_MYSQL_CONFIG
and ac_cv_prog_PG_CONFIG in the environment leaving the old behaviour of searching
in PATH to avoid breaking the usual builds.
HAVE_MYSQL_CONFIG and HAVE_PG_CONFIG were renamed to reflect the new reality
that it's a file spec rather than a boolean now.
=> Cross-compile fixes

runtime/rsyslog.h
It was caused by unchecked use of json_object as linked-hashtable. In that test, first few instances are strings, which causes segfault.
The segfault was showing an unknown frame because it was dereferencing hash_fn from invalid object.
=> Fix for ubuntu-12.04 json_array_looping.sh segfault

tools/omfwd.c
It now contains the errno as numerical value in order to be
able to more precisely nail down the problem cause. The
strerror() generated message sometimes seems to be a bit
questionable.
Also refactored error processing a bit to take advantage of
the improved error reporting subsystem.
=> imudp: more precise error message in case of send failure

plugins/omkafka/omkafka.c
stats:
- submitted: producer submitted message to broker.
- failures: producer failed to submit message to broker.
Topic is able to be a template, the topics are stored in the instanceData and the kafka_rd_t object has been moved into instanceData. This is alright because librdkafka is threadsafe and to acheive the dynamic topic results it is required.
The topics are stored in a hashtable due to librdkafka leaking memory when passing in a conf object, plus us keeping a local topic "list" makes the subsequent topic conf and rd_kafka_topic_new calls unnecessary. The move of the topic down the writeKafka is for dynamic parsing of the topic for each message that comes through.
Additional items:
- Added safety to rd_kafka_t destruction, where it flushes the queued messages before object …
=> omkafka: add stats and dynamic topic

action.c
When an action is suspended, rsyslog's memory consumption continues
to grow. On very busy systems, this can lead to system stability
errors as it is possible that rsyslog allocates too much memory.
The root cause of this issue is the invalid management of a string
cache index, which is reset to the beginning in the wrong function,
one that is not reached when suspended. This in turn leads to
continous increase of the cache.
This fix moves the reset to the proper location.
Note that this problem was not detectable by our valgrind tests
because proper cleanup was done on rsyslog termination (but only
then).
closes https://github.com/rsyslog/rsyslog/issues/253
=> bugfix: large memory consumption on suspended action

plugins/ommongodb/ommongodb.c
While reading through the ommongodb.c source, I noticed a comment was still referencing MySQL. I've updated this to reflect that `initMongoDB` is initializing a MongoDB connection.
I've also eliminated some trailing whitespace characters.
=> ommongodb comment update

tests/Makefile.am
Like reported by @mbiebl in http://thread.gmane.org/gmane.comp.sysutils.rsyslog/16640/focus=16643
=> tests: Add missing mmnormalize_*.rulebase files to EXTRA_DIST target

tests/Makefile.am
queue-persist.sh was called twice in Makefile.
=> tests: Run queue-persist.sh only once

ChangeLog, plugins/omudpspoof/omudpspoof.c
The file format template was used, which obviously does not work for
forwarding. Thanks to Christopher Racky for alerting us.
closes https://github.com/rsyslog/rsyslog/issues/268
=> bugfix: omudpspoof: invalid default send template in RainerScript format

runtime/cfsysline.c
on some platforms they misadressed memory, which could also lead
to a segfault on startup. The problem is NOT experience on amd686
in 64bit builds -- that's probably the reason this bug was uncovered
very late. We assume, it's present in all v8 versions.
Thanks to Michael Biebl for alerting us of it.
closes https://github.com/rsyslog/rsyslog/issues/270
=> bugfix: size-based legacy config statements did not work properly

runtime/msg.c
Rename the field for serializing pszStrucData so MsgSerialize and MsgDeserialize align.
=> Fix field name for pszStrucData in MsgSerialize (Issue #264)

plugins/omelasticsearch/omelasticsearch.c, tests/Makefile.am, tests/elasticsearch-bulk-errorfile-populated-default-format.sh, tests/elasticsearch-bulk-errorfile-populated-default-interleaved.sh, tests/elasticsearch-bulk-errorfile-populated-erroronly-interleaved.sh, tests/elasticsearch-bulk-errorfile-populated-erroronly.sh, tests/elasticsearch-error-format-check.py, tests/testsuites/elasticsearch-bulk-errorfile-populated-default-format.conf, tests/testsuites/elasticsearch-bulk-errorfile-populated-default-interleaved.conf, tests/testsuites/elasticsearch-bulk-errorfile-populated-erroronly-interleaved.conf, tests/testsuites/elasticsearch-bulk-errorfile-populated-erroronly.conf
Currently omelasticsearch dumps entire post data and response in error file in case for a failure in bulk insert mode. Wanted to introduce two format flags in action to format data in error file (Both of the flags can be used independently as well as together).
1. erroronly => This flag checks the response stream and logs only failed requests and response.
2. interleaved => This flag interleaves the request to its response and dumps it as pair.
When both flags are used we get only failed request in an interleaved format.
sample: action(server="localhost"
XXX
type="omelasticsearch"
XXX
errorfile="bad_message.log"
erroronly="on"
interleaved="on")
BugFix:
While checking if my code is causing any leaks or not, I found a valgrind error for "pWrkrData->batch.data" not sure if that was …
=> Adding new format support for error file in omelasticsearch bulk insert mode

runtime/linkedlist.c
Keep the destructed list in a consistent state as the provided
destructor may access the very same list again before llDestroy
finishes.
The previous approach could actually trigger a segmentation violation
error for specific scenarios and configurations.
In one particular case, destructing the list of rulesets lead to
shutdown of an action DA queue and spooling its messages to disk which
in turn triggered a search for the ruleset name of the message trought
the destructed list.
The change probably slightly degrades performace, but that shouldn't
have an observable effect in the current code base.
=> Make llDestroy safe

plugins/imuxsock/imuxsock.c
Setting a hostname via the legacy directive would lead to a crash
during shutdown caused by a double-free.
=> imuxsock: fix a crash when setting a hostname

plugins/imuxsock/imuxsock.c
Reverts rsyslog/rsyslog#307 ; merged into wrong branch (not an emergency fix, thus needs to go into master)
=> Revert "imuxsock: fix a crash when setting a hostname"

.travis.yml, ChangeLog, Makefile.am, configure.ac
We are now checking if we are running from git source. If we do that, we will require `rst2man` and `yacc`.
This PR is based on @davidelang report from http://lists.adiscon.net/pipermail/rsyslog/2015-April/thread.html#40318
=> Make configure checks dependend on build source

runtime/rsconf.c
Original changes ported from Ubuntu launchpad:
http://bazaar.launchpad.net/~cjwatson/ubuntu/trusty/rsyslog/repair-groups/revision/57/debian/patches/10-initgroups.patch
This is the fix for issue https://github.com/rsyslog/rsyslog/issues/296
=> Added code to set supplementary groups when dropping privileges.

plugins/imfile/imfile.c, runtime/srutils.c
The globbing currently only supports *, ? and []. This adds the ability to use {}.
input(type="imfile" File="/var/log/{*.log,dmesg,syslog}")
Should I open an issue too and link this pull request to it, or is just a pull request sufficient?
=> Added brace glob expansion to imfile wildcard

tests/Makefile.am, tests/abort-uncleancfg-badcfg-check.sh, tests/abort-uncleancfg-badcfg-check_1.sh, tests/abort-uncleancfg-goodcfg-check.sh, tests/testsuites/abort-uncleancfg-badcfg.conf, tests/testsuites/abort-uncleancfg-badcfg_1.conf
This is another test for the directive "$AbortOnUncleanConfig" with a invalid configuration. 
The test works with the return code of the configuration check. If the return code of the configuration check is not equals null then the test passed otherwise the test should returns a fail.
=> Testbench: add some tests for the directive $AbortOnUncleanConfig (bad case & good case)

ChangeLog, configure.ac
This PR only **adds** a new option, it doesn't change any known behavior if you don't use the new option, so this change doesn't break anything.
Reason for doing that:
1. You don't want `-g` in general. If your project is small, you don't mind but building a large project with `-g` if you aren't interested in debug information makes the compiled project unnecessary large.
2. `-g` can cause troubles, see https://blog.flameeyes.eu/2011/08/are-g-options-really-safe
3. Especially on Gentoo we don't like this option. People interested in debug information have their own options to build with debug information. Having an option to disable configure from setting the `-g` flag will save us a custom patch.
=> Add an option to disable the generation of debug symbols

tools/pmrfc3164.c
fixes a warning about potential uninitialized use. However, the warning
was invalid and based on incomplete static code analysis. Anyhow, we
"fix" it, as this does not add any real overhead - and it's nicer to
compile cleanly.
=> cosmetic: fix compiler warning

contrib/imczmq/README, contrib/imczmq/imczmq.c, contrib/omczmq/omczmq.c
This PR adds the ability for zeromq input and outputs to advertise their presence on UDP via the zbeacon API (see: http://api.zeromq.org/czmq3-0:zbeacon ) on networks that support UDP broadcast.
=> Add zbeacon UDP advertisement support to imczmq and omczmq

action.c
The default name generated for an action references a global counter
instead of the action-specific number. In practice this means that the
number in the name will be greater by at least one than the assined
number most of the time.
NB: The code generating various action-related messages is using the
action name inconsistently; sometimes the generated name is used,
sometimes the action number is used, thus producing "action N" or
"action N+1" identifiers at different locations in the code.
=> bugfix: fix default action naming

ChangeLog, compat/Makefile.am, compat/strndup.c, runtime/rsyslog.h
now added compatibility function. This came up on Solaris builds.
Thanks to Dagobert Michelsen for reporting the problem.
closes https://github.com/rsyslog/rsyslog/issues/347
=> bugfix: build system strndup was used even if not present

runtime/stream.c
Fix for [issue 357](https://github.com/rsyslog/rsyslog/issues/357).
Rsyslog crashes when using startmsg.regex in imfile because of empty log line.
=> Fix crash when log line is empty

ChangeLog, runtime/stream.c
Thanks to Ciprian Hacman for reporting the problem
closes https://github.com/rsyslog/rsyslog/issues/370
=> bugfix imfile: regex multiline mode ignored escapeLF option

plugins/omkafka/omkafka.c
Plugin omkafka had several data-races, this patchset fixes them.
The symptom was regular crashes under load. Most of them pointed to omkafka(and librdkafka) area (statistically).
This should fix all of them (or all that I could find by reading code).
@rgerhards I may not be capable of seeing more races in this. Im too tainted at this point. So please review carefully, it may have some more.
=> omkafka concurrency fixes

contrib/mmcount/mmcount.c, contrib/mmsequence/mmsequence.c, grammar/rainerscript.c, plugins/imjournal/imjournal.c, plugins/imuxsock/imuxsock.c, plugins/mmaudit/mmaudit.c, plugins/mmfields/mmfields.c, plugins/mmjsonparse/mmjsonparse.c, plugins/mmnormalize/mmnormalize.c, plugins/mmpstrucdata/mmpstrucdata.c, runtime/msg.c, runtime/msg.h, runtime/ruleset.c, tests/Makefile.am, tests/key_dereference_on_uninitialized_variable_space.sh, tests/testsuites/key_dereference_on_uninitialized_variable_space.conf
This change ensures global-variables are written and read atomically.
This makes things such as:
set $/count = $/count + 1;
set $.i = $/count % 16;
work across multiple threads.
It also kills an unused function.
=> Global variable atomicity

runtime/msg.c
This is a fix for [issue 367](https://github.com/rsyslog/rsyslog/issues/367).
=> Fix crash when using property parameter controlcharacters="escape"

tests/Makefile.am, tests/testsuites/key_dereference_on_uninitialized_variable_space.conf, tests/testsuites/sndrcv_relp_sender.conf
- Testbench imptcp_spframingfix.sh is now only executed
if imptcp is enabled
- Changed imptcp to imtcp in Testbenches sndrcv_relp.sh and
key_dereference_on_uninitialized_variable_space.sh. Tests failed
if imptcp was not enabled.
=> testbench: Fixed multiple minor problems

plugins/imjournal/imjournal.c
The leak was tiny and shutdown-time only.
=> bugfix: plug a memleak in imjournal

plugins/imjournal/imjournal.c
It is an error to pass an empty message to parser.SanitizeMsg() and doing so could crash the daemon. Besides, there's no point in doing so in the first place.
=> imjournal: don't sanitize empty messages

tools/omfile.c
required for open() flags.
See: http://pubs.opengroup.org/onlinepubs/007908775/xsh/fcntl.h.html
=> omfile: unconditionally include fcntl.h.

ChangeLog, action.c, runtime/librsksi_read.c, tools/omfwd.c, tools/pmrfc3164.c, tools/rsyslogd.c
Followup fix for 6fbacdc41d37ce3091709e71f6f0e66912237606
=> typo fix: paramter → parameter

ChangeLog, plugins/ompgsql/ompgsql.c
now transaction support is solidly disabled until we have enough requests
to implement it again. Module still works fine in single insert mode.
closes https://github.com/rsyslog/rsyslog/issues/399
=> bugfix ompgsql: transaction were improperly handled

plugins/ommysql/Makefile.am
under RHEL 7, we have an issue when gnutls is linked. For some reason
(autoconf magic?) we link ommysql against gnutls. I have not found the
root cause, but setting LIBS= below makes the problem go away. A better
solution would be appreciated, but for the time being this seems to
solve the issue.
closes https://github.com/rsyslog/rsyslog/issues/408
=> fix ommysql issues under RHEL7

runtime/rsconf.c
Default values for several global and main message queue parameters
were defined in two places which, over time, became inconsistent.
This merges the code used in resetConfigVariables and the rsconf_t
constructor. In cases where values for the same parameter differed,
the value with a more recent commit timestamp was used.
=> Harmonize resetConfigVariables values and defaults

runtime/srutils.c
The affected code is used to detect a race condition in between
testing for the existence of a directory and creating it if it didn't
exist.  The variable tracking the number of attempts wasn't reset for
subsequent elements in the path, thus limiting the number of
reattempts to one per the whole path, instead of one per each path
element.
This solution was provided by Martin Poole.
=> Fix race-condition detection in path-creation code

tools/Makefile.am
The problem was introduced due the changes of this commit:
https://github.com/rsyslog/rsyslog/commit/fb4fd2ddd2f08380ad65a8cafc5f124890b136ad
Removing librsyslog.a from the rscryutil_LDFLAGS solved the problem.
closes https://github.com/rsyslog/rsyslog/issues/447
=> usertools: Fixed issue making rscryutil (usertools enabled)

ChangeLog, configure.ac
as it turned out, this was due to a check for GnuTLS functions
with the side-effect that
AC_CHECK_LIB, by default, adds the lib to LIBS, if there is no
explicit action, what was the case here. So everything was now
linked against GnuTLS, which in turn made ommysql fail.
Thanks to Thomas D. (whissi) for the analysis of the ommysql/gnutls
problem and Thomas Heinrich for pointing out that AC_CHECK_LIB might
be the culprit.
=> bugfix: ommysql did not work when gnutls was enabled

runtime/stream.c
Here we need to free pThis->pszCurrFName in any case, even if
pThis->bDeleteOnClose is not true.  Otherwise we leak memory if
this stream gets reopened later, for instance after closing by
doSizeLimitProcessing.
=> fix memory leak in strmCloseFile

runtime/stream.c
Fix for issue #419 
Rsyslog crashes because the first log line is not matched by startmsg.regex and tries to add it to an uninitialised string.
=> Fix segfault when using startmsg.regex if first log line doesn't match

tests/imuxsock_ccmiddle.sh, tests/imuxsock_ccmiddle_root.sh, tests/imuxsock_hostname.sh, tests/imuxsock_traillf.sh, tests/imuxsock_traillf_root.sh, tests/syslog_caller.c
When built with --disable-liblogging-stdlog, syslog_caller fails
to compile. This will enable compilation when the library is not
used.
Resolves: #445
Signed-off-by: Louis Bouchard <louis.bouchard@canonical.com>
=> testbench: Add contitional compilation for liblogging-stdlog

runtime/stream.c
The patch was from AlexandreFenyo and is a result
of this bug report on freebsd.org:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199767#c4
closes https://github.com/rsyslog/rsyslog/issues/372
=> freebsd: Added a patch for console output on freebsd

configure.ac
In commit 3b13693 commiter uses variable before executing another block of code which sets this variable and any changes in that block won't apply.
This bug appears when user runs "make dist" in the git repo and the generated tarball doesn't contain rscryutil.1.
=> Fix generating rscryutil.1

ChangeLog, runtime/Makefile.am
This issue was introduced with commit fb4fd2ddd2f08380ad65a8cafc5f124890b136ad.
Fixes #479
=> Fix for parallel build issue "cannot find ../runtime/.libs/librsyslog.a: No such file or directory" (Fixes #479)

ChangeLog, tests/Makefile.am
Tests and config files were not included in the makefile,
so they were not added into the release tar.gz file.
closes: https://github.com/rsyslog/rsyslog/issues/484
=> testbench: Added mmpstrucdata valgrind tests into makefile

ChangeLog, configure.ac, plugins/mmnormalize/mmnormalize.c, runtime/rsyslog.h
This is possible due to a new API in liblognorm 1.1.2;
Note that the amount of error messages depends on the version of
liblognorm used. Consequently, liblognorm 1.1.2 is now required
to run mmnormalize.
**Note: merge only after buildbot tests indicate "OK"**
=> mmnormalize: liblognorm error messages are now reported

.travis.yml
Travis currently doesn't enable *mmnormalize* so we don't know from our CI that there's a problem with *mmnormalize* (see #489). This PR will enable *mmnormalize*.
Because there **is** currently a problem, Travis will fail. But nevertheless please merge, so we can keep track when this is fixed.
Link-ML: http://lists.adiscon.net/pipermail/rsyslog/2015-August/040997.html
=> Enable mmnormalize for test coverage within Travis

configure.ac
This commit fixes a number of issues that cropped up from these changes:
23c5b3e replace deprecated GnuTLS functions with newer ones if available
88f0651 bugfix: ommysql did not work when gnutls was enabled
ce560b6 build system: Failure action in AC_CHECK_LIB check for
The solution is based on the assumption that the call to AC_CHECK_LIB()
was added purely to satisfy the subsequent calls to AC_CHECK_FUNCS().
23c5b3e had the unintentional result of libgnutls being added to LIBS
and linked to undesired components.
The next commit removed libgnutls from LIBS which made the following
calls to AC_CHECK_FUNCS() nonfunctional.
Another commit made the processing not stop upon detecting a missing
component which, again, makes the calls to AC_CHECK_FUNCS() malfunction.
The solution is to get rid of …
=> Fix detection of the GnuTLS package

runtime/msg.c
Unexpected problems could occur when the msg object was modifed
while json_object_to_json_string_ext function is called.
closes https://github.com/rsyslog/rsyslog/issues/475 and https://github.com/rsyslog/rsyslog/issues/368
=> msg object: Added msglock when using $!all-json/$!all-json-plain

tests/tcpflood.c
On some architectures, calculation of edLen may lead to a
negative value when the value returned by rand() is less
than extraDataLen away from RAND_MAX. The negative value
passed to memset() triggers a glibc error. Forcing the
cast of rand() to be unsigned avoid the return of a negative
value.
Closes: #506
Signed-off-by: Louis Bouchard <louis.bouchard@canonical.com>
=> testbench: Fix potential buffer overflow detection

runtime/queue.c, runtime/stream.c
First issue: Error 14 was generated on the .qi file directory handle.
As the .qi filestream does not have a directory set, fsync
was called on an empty directory causing a error 14 in debug log.
closes https://github.com/rsyslog/rsyslog/issues/402
Second issue: When queue files existed on startup, the bSyncQueueFiles
strm property was not set to 1. This is now done in the
qqueueLoadPersStrmInfoFixup function.
closes https://github.com/rsyslog/rsyslog/issues/403
=> diskqueue: Fixed two minor issues when syncqueuefiles is enabled.

runtime/msg.c, template.c, template.h
Pads a string with spaces up to toChar field if string is shorter, if
string is equal then nothing is done and if string is longer then it
gets truncated.
From mailing list patch proposal.
=> Add fixed-width option

plugins/omelasticsearch/omelasticsearch.c
By default, CURL doesn't check if the HTTP request to elasticsearch fails. This leads to extra unnecessary processing and can trigger #500.
=> omelasticsearch: Fix CURL ignoring HTTP errors

runtime/tcpsrv.c
Added errmsg.LogError when configured listener limit is reached in input modules using tcpsrv.c.
=> imtcp: Added logerror output when MaxListeners limit is reached.

plugins/omtesting/omtesting.c
An argument given in microseconds was incorrectly labeled as given in milliseconds.
=> omtesting: fix unit labels

contrib/imczmq/imczmq.c, contrib/omczmq/omczmq.c
Some context here: this is a bug, where the pub/sub sockets are not binded/connected as they should be. So a user has to prebend the endpoint string with a ">" for a sub socket or a "@" for a pub socket, otherwise it will not work.
=> Czmq bind connect

contrib/imczmq/imczmq.c, contrib/omczmq/omczmq.c
If authtype is not set in the configuration and the pointer is NULL, both plugins crash.
=> Fix NULL pointer dereference in imczmq and omczmq

contrib/imczmq/imczmq.c
The topicList pointer was modified and overwritten, so at free time
there was a sigabort due to invalid pointer:
Error in `rsyslogd': free(): invalid pointer: 0x00000000021cde24
=> imczmq: fix abort on free

ChangeLog, tests/Makefile.am, tests/testsuites/gethostname.conf, tests/testsuites/rscript_random.conf, tests/testsuites/rscript_replace_complex.conf, tests/testsuites/rscript_wrap2.conf, tests/testsuites/rscript_wrap3.conf, tests/testsuites/stop_when_array_has_element.conf
Thanks to Michael Biebl for reporting this
see also https://github.com/rsyslog/rsyslog/issues/524
=> bugfix testbench: some tests using imptcp are run if module is disabled

contrib/omhiredis/README, contrib/omhiredis/omhiredis.c
This PR addresses https://github.com/rsyslog/rsyslog/issues/522
The plugin now has three "modes" that it supports:
1. "template"
This is the original mode that the plugin supported. You use an rsyslog template
to construct a command that is sent directly to redis. This mode currently has
an issue dealing with strings that contain spaces. It's useful for doing things
like incrementing counters for statistics.
```
module(load="omhiredis")
template(
name="simple_count"
type="string"
string="HINCRBY testcount %programname% 1")
*.*     action(
name="count_redis"
type="omhiredis"
mode="template"
template="simple_count"
)
```
2. "queue"
The queue mode will LPUSH your message to a redis list. Unlike the template
mode, it handles full rsyslog messages properly. If a template is not 
supplied, it …
=> omhiredis: add queue (list) and publish support

grammar/rainerscript.c, tests/Makefile.am, tests/rscript_re_extract.sh, tests/rscript_re_match.sh, tests/testsuites/rscript_re_extract.conf, tests/testsuites/rscript_re_match.conf
It was broken because fn-init was expecting exactly 2 args (which is fine for re_match) but re_extract has 5 args, which fails in init.
=> re_extract fixed

plugins/external/solr/rsyslog_solr.py
The previous pysolr approach worked nicely with batches, but it required parsing the JSON input to a dictionary, which we already know is a JSON, and writing it out again into the final string. That was too expensive (~10x more CPU-intensive than rsyslog under load). Also, it had the disadvantage that it raised the same exception when connection failed with when there was something wrong with a single document (so retrying would re-insert all the correct documents N times).
The httplib approach allowed me to retry on socket failures (and write to an error file when the retry count is exceeded) and write to the error file directly when there's a non-200 response code from Solr. Also, the external plugin is now taking onlu ~30% of rsyslog's CPU.
To get an idea of performance, I could max …
=> rsyslog -> Solr external plugin add batch update via httplib and error handling

plugins/imudp/imudp.c
rcvBuf is not terminated with a NULL Byte, so the dbgprintf was
printing the whole buffer.
=> imudp: Fixed a dbgprintf in processPacket function.

runtime/msg.c
The index offAfterPRI inside the message object is supposed
to point to the first char in rawmsgs after PRI. Unfortunately,
it seems NOT to be correct/consistent in all cases. imuxsock
and imudp seem to have other values than imptcp. Testbench
covers some of that. As a work-around, we caluculate
the value ourselfes.
=> fix rawmsg-after-pri property

configure.ac, plugins/omkafka/Makefile.am
For example, build librdkafka from source and static link.
I've verified the change on CentOS 6.5.  Is there any special reason this was turned off?
=> Make it possible to customize librdkafka location

Makefile.am, configure.ac, contrib/pmpanngfw/Makefile.am, contrib/pmpanngfw/README.md, contrib/pmpanngfw/pmpanngfw.c
Added a module in contrib directory to translate Palo Alto Networks NGFW logs into a format that can be parsed via mmnormalize. The module is based on pmsnare code.
Some details: Palo Alto Networks logs are in CSV format, with comma as separator and double quotes for quoting fields containing a comma. Double quotes inside quoted fields are doubled. Quoted fields are not easily managed via mmnormalize, this module then can be used to translate commas into tabs and quoted fields into plain fields.
Before starting the translation, the module applies a simple heuristic to check if the log is coming from a Palo Alto Networks device.
Sample config in the README.md file.
A script to automatically generate mmnormalize rulebase to extract fields from NGFW logs is available here: …
=> Added pmpanngfw

contrib/omrabbitmq/omrabbitmq.c
Refreshed the code of omrabbitmq to remove librabbitmq functions deprecated from v0.4.0 (August 2013).
I have also added new configuration options to optionally declare the target exchange and change the message delivery mode. Default behaviour is consistent with the current code, exchange is not declared and delivery mode is persistent.
Added configuration options:
- **exchange_type** type of exchange. If set the exchange is declared. Default: NULL
- **auto_delete** auto_delete flag for the declared exchange. If exchange_type is NULL this setting is ignored. Default: True
- **durable** durable flag for the declared exchange. If exchange_type is NULL this setting is ignored. Default: True
- **delivery_mode** delivery mode flag for the published messages. Default: 2 (persistent)
Original …
=> Removed deprecated functions from omrabbitmq and added configuration options

contrib/imczmq/imczmq.c, contrib/omczmq/omczmq.c
* omczmq - suspend / Retry handling - the output plugin can now recover from some error states due to issues with plugin startup or message sending
* omczmq - refactored topic handling code for ZMQ_PUB output to be a little more efficient
* omczmq - added ability to set a timeout for sends
* omczmq - set topics can be in separate frame (default) or part of message frame (configurable)
* omcmzq - code cleanup
* imczmq - code cleanup
* imczmq - fixed a couple of cases where vars could be used uninitialized
* imczmq - ZMQ_ROUTER support
* imczmq - Fix small memory leak from not freeing sockets  when done with them
=> contrib/omczmq and contrib/imczmq improvements

runtime/nsd_gtls.c
The callback given to [gnutls_certificate_set_retrieve_function](https://github.com/csoutherland/rsyslog/blob/6272aa12bcc025cb4ac285dfccae9ecc7418425d/runtime/nsd_gtls.c#651) is expected to set the appropriate server certificate during its execution. When the callback is not specified, it appears that [gnutls loops through the available credentials in order to find an appropriate certificate](https://gitlab.com/gnutls/gnutls/blob/gnutls_2_12_23/lib/auth_cert.c#L2084). Since we appear to be [using the real certificate](https://github.com/csoutherland/rsyslog/blob/6272aa12bcc025cb4ac285dfccae9ecc7418425d/runtime/nsd_gtls.c#1696) for the client side communication as well, it stands to reason that similar code should safely solve this problem. The only caveat is that this depends on my …
=> Possible fix for #575

runtime/msg.c
This is in unreleased code. There was a simple copy&paste error
introduced when we improved json locking. That results in locks
not being held properly for local variables.
=> fix regression in json var locking

contrib/imczmq/imczmq.c, contrib/omczmq/omczmq.c
This PR allows creation of on demand ephemeral CurveZMQ certs for encryption.
Clients may specify clientcertpath="*" to indicate they want an on demand generated cert.
=> omczmq/imcmzq: allow ephemeral client certs

runtime/msg.c
Fix issue #576: at the time `iTo` is being set based on `bufLen`, `iFrom` and `iTo` have been readjusted to be zero based instead of one based.  This issue predates f3bd7a2, but that commit then made it insert spaces if `iLen` referenced positions beyond the end of the string, which exposed this older mistake.
=> Address off-by-one issues introduced in f3bd7a2 resulting in extra whitespace in property expansions

tools/pmrfc5424.c
Note: this is untested and needs some more testing and verification before it actually can be merged. It's an extreme border case, so there is no hard need to merge quickly.
see also http://lists.adiscon.net/pipermail/rsyslog/2015-November/041555.html
=> bugfix: RFC5424 did not handle NILVALUE in datestamp

action.c, action.h
the wrkr instance table was not properly guarded.
This fixes a bug that was never reported, "just" caught by testbench.
=> bugfix: potential race when new action worker is created

action.c
(unreleased code)
The commit used debug coding, when --enable-rtinst was given, that
is not available in these functions (requires DEFiRet macro). That is
an old debug system which we need to reconsider anyways. So just do
not use it here.
=> fix regression from 38b9532354d84c902ac7ed7bb734f673e4d613dc

configure.ac, plugins/omkafka/Makefile.am
Detect package librdkafka existence first, then check -lrdkafka if
failed (in standard lib dir).
This is an enhanced version based on #502 and fixes #596.
Some test results below.
**Neither of librdkafka package and lib file is present**
```
checking for LIBRDKAFKA... no
checking for rd_kafka_produce in -lrdkafka... no
configure: error: cound not find rdkafka library
```
**Compiled librdkafa from source and installed lib to /usr/lib64/**
```
checking for LIBRDKAFKA... no
checking for rd_kafka_produce in -lrdkafka... yes
configure: WARNING: librdkafka is missing but library present, using -lrdkafka
checking librdkafka/rdkafka.h usability... yes
checking librdkafka/rdkafka.h presence... yes
checking for librdkafka/rdkafka.h... yes
```
**Static linking with With …
=> Detect librdkafa smartly

grammar/rainerscript.c
A static buffer is used in tokenToString() when creating a string to
represent an unrecognized token. There are a number of operators and
datatypes that were unrecognized, so this was used often. This change
avoids multiple threads writing over the same string, confusing the
debug output.
Note that this does not solve the problem, as this can still happen if
new datatypes or operators are added in the future, but it does take
care of the common cases known today.
=> Add common tokens in tokenToString

contrib/mmgrok/README
These are the complete steps needed to build on a RHEL / CentOS / Fedora box (but only verified on a Fedora 21 box).
=> Update build steps for RH/CentOS/Fedora

grammar/rainerscript.c, plugins/mmexternal/mmexternal.c, plugins/omprog/omprog.c
In rainerscript.c there was a wayward debug statement emitting a es str,
where the es string was converted to a c-string before printing, and
then freeing the memory. It would seem doing that on the fast path is
unnecessary, so we moved it under an explicit Debug test.
Searching for other uses of es_str2cstr() calls in dbgprintf() calls
(lowercase), which would mean that the memory allocation always occurs
even if the debugging is not enabled, we found two in omprog and
mmexternal.
In the modules that we touched, we switched to use DBGPRINTF() were
possible and logical, to avoid processing any parameters on the fast
path.
=> Bury es_str2cstr() calls under explicit Debug test

plugins/omelasticsearch/omelasticsearch.c, plugins/pmciscoios/pmciscoios.c
Enable IOSXR message format support, this can be enabled with the present.xr parser option.
Unsynchronised clocks can append dots (.) or asterisk (*) before the timestamps.
=> pmciscoios: Support for IOSXR type syslog messages and dots (.) before timestamps

contrib/omhttpfs/omhttpfs.c
The "mem->reply" is assigned for realloc function`s return value directly. If realloc function fails then mem->reply is assigned as NULL, but the original block is not freed. The original block pointed to by mem->reply will be leaked.
=> omhttpfs: If realloc function fails, the original block is not freed. The orignal block pointed to by mem->reply will be leaked

runtime/nsd_gtls.c, tests/imptcp_conndrop-vg.sh, tests/imptcp_conndrop.sh
When the connection was broken and gtlsRecordRecv returned a
failure, pszRcvBuf was not freed. The code to free pszRcvBuf has
been moved to finalize_it if iRet is not RS_RET_OK.
=> gnutls: fixed memory leak when gtlsRecordRecv returned a failure.

tests/Makefile.am
These tests were not included in the rsyslog-8.15.0 release tarball.
=> Add missing json_null{,_array} tests to dist target

tests/Makefile.am, tests/json_var_cmpr.sh, tests/rscript_eq_var.sh, tests/rscript_ge_var.sh, tests/rscript_gt_var.sh, tests/rscript_le_var.sh, tests/rscript_lt_var.sh, tests/rscript_ne_var.sh, tests/testsuites/json_var_cmpr.conf, tests/testsuites/rscript_eq_var.conf, tests/testsuites/rscript_ge_var.conf, tests/testsuites/rscript_gt_var.conf, tests/testsuites/rscript_le_var.conf, tests/testsuites/rscript_lt_var.conf, tests/testsuites/rscript_ne_var.conf
Don't change the first character of the variable name, since we need
that depending on its name space. Instead, determine the proper root
variable string that should be used.
Fixes #617.
=> Add tests for variable name comparison regressions

plugins/impstats/impstats.c, runtime/statsobj.c, runtime/statsobj.h
ES 2.0 no longer supports valid JSON and disallows dots inside names.
This adds a new "json-elasticsearch" format option which replaces
those dots by the bang ("!") character. So "discarded.full" becomes
"discarded!full".
This is a workaroud. A method that will provide more control over
replacemetns will be implemented some time in the future. For
details, see below-quoted issue tracker.
closes https://github.com/rsyslog/rsyslog/issues/713
=> impstats: support broken ElasticSearch JSON implementation

runtime/msg.c, runtime/rsyslog.h
We drop the use of the `RS_*_ext` macro since it is only used in one
place, and this change allows us to only perform the json-c call under
the mutex, and not the `strdup()` as well.  We add checks for NULL from
`json_*_string` and `strdup()`.
=> Check memory allocation of json return values

plugins/omelasticsearch/omelasticsearch.c
Two straightforward fixes: 
First, a custom serverport was always ignored and replaced by zero.
Second, url's ending in a bare '?' or '&' were produced, which confuses some versions of elasticsearch.
=> omelasticsearch bugfixes

plugins/ommail/ommail.c
Should be added the number of characters sent.
Not direct to add the number of all required to be sent.
=> ommail.c:Should be added the number of characters sent.

plugins/imfile/imfile.c, runtime/rsyslog.h
Seen in v8.14 and reproduced in master code (commit 8e974a3) as well.
The condition of inotify instance is not successfully initialized should be handled.
Default value for `max_user_instances` and `max_user_watches` are not large enough for high pressure conditions.
**In my real case**, rsyslog are deployed in `docker containers`, and all containers share one host's kernel, so it's easy to hit `max_user_instances` or `max_user_watches`'s limit, it causes initialization for new inotify instance's fail but no message is given, which confuses people meaningless.
=> Handling the condition of inotify instance's failed initialization

action.c, contrib/pmaixforwardedfrom/pmaixforwardedfrom.c, contrib/pmcisconames/pmcisconames.c, plugins/imfile/imfile.c, plugins/mmaudit/mmaudit.c, plugins/omelasticsearch/omelasticsearch.c, plugins/omhdfs/omhdfs.c, plugins/ommongodb/ommongodb.c, plugins/ommysql/ommysql.c, plugins/ompgsql/ompgsql.c, plugins/omrelp/omrelp.c, plugins/pmlastmsg/pmlastmsg.c, runtime/msg.c, runtime/nsdpoll_ptcp.c, runtime/nsdsel_gtls.c, tools/omfwd.c
those starting at column 0 are temporary debug aids during development.
Some of them I intend to keep in for a version or two. Some of them
I tend to forget later. This is a cleanup of those. Most are removed,
some are promoted to be permanently there - now indicated by proper
indention.
=> cleanup: remove dbgprintf's not intended to stay

plugins/imfile/imfile.c
`evFileHelper.name` is not allocated and not used at all, in typical
case its address is the same as the local variable `etry` in the same
stack (compiler optimization), assigning to `evFileHelper.name[0]`
actually corrupts the etry data structure and crashes the program.
Here's an example output from gdb session.
```
(gdb) p &evFileHelper.name
$6 = (char (*)[]) 0x7ffff6dfc930
(gdb) p &etry
$7 = (wd_map_t **) 0x7ffff6dfc930
(gdb)
```
=> Fix #718 caused by writing to unallocated address

plugins/imfile/imfile.c, runtime/stream.c, runtime/stream.h
Attempt to fix #511.  This is an enhanced version based on https://github.com/rsyslog/rsyslog/pull/514, works fine for us so far.  As discussed before, I added an opt-in flag 'reopenOnTruncate' and default is "off".
=> Reopen truncated file with opt-in flag 'reopenOnTruncate'

.travis.yml, CONTRIBUTING.md, tests/Makefile.am, tests/diag.sh, tests/travis/trusty.supp
That's probably also a forward-looking change assuming that travis at some time will drop support for 12.04.
Note that we still use clang on 12.04, and this is intentional.
=> travis: run testbench under Ubuntu 14.04

plugins/mmutf8fix/mmutf8fix.c, plugins/omelasticsearch/omelasticsearch.c, plugins/pmciscoios/pmciscoios.c
fix may be uninitialized warning after checking that all codepaths do properly initialize the variables
fixed missing const on variable declarations
=> Trivialfixes

plugins/imptcp/imptcp.c, runtime/rsyslog.h, tests/Makefile.am, tests/chkseq.c, tests/diag.sh, tests/imptcp_nonProcessingPoller.sh, tests/imptcp_veryLargeOctateCountedMessages.sh, tests/tcpflood.c, tests/testsuites/imptcp_nonProcessingPoller.conf
- io-work assignment model made #workers independent (earlier it was O(workers)), better work-starvation management
- fully concurrent poller and io-workers (no waiting for io-workers to be done before next poll)
- better message-content handing when reading inbound messages for octate-counted messages
- removed upper-limit on #workers
- enhanced tcpflood to allow producing octate-counted frames, some improvement in error-reporting
- some aesthetic changes
- created a new config-param (processOnPoller, which defaults to "on" in favor of backward comparability) and when turned off, doesn't dispatch any io-work on poller (leaving it completely free to just poll, which makes a lot of difference in maintaining high-throughput with low-latency). Will send a separate PR for …
=> ptcp performance improvements

plugins/imjournal/imjournal.c
Looks like a long standing off-by-one comparison issue with the
invocation of strncmp.  The constant string is only 3 or 6 characters
long, but the comparison length is 4 or 7.
=> imjournal: fix off-by-one error in name cmprs

grammar/lexer.l
This fixes a mistake in the lexer rule for hexadecimal number literals that prevented it from recognizing hex numbers containing more than one digit or the digits `8` or `9`.
=> Fix lexer bug affecting hex number literals.

.travis.yml, ChangeLog, configure.ac, grammar/lexer.l, runtime/lookup.c
We must make sure all supported platforms (except solaris) build.
Note that Solaris will not build any longer, except when libfastjson is manually installed.
closes https://github.com/rsyslog/rsyslog/issues/717
=> require libfastjson

plugins/imfile/imfile.c, runtime/stream.c, runtime/stream.h
Add an opt-in flag 'trimLineOverBytes' to determine if trim line when length of line over specified bytes number. 
Default value of 'trimLineOverBytes' is 0, means never trim line. 
If 'trimLineOverBytes' is positive number, we will truncate the line which length is greater than 'trimLineOverBytes'.
=> imfile: Trim line when length of line over specified bytes

tests/solaris/prep-libfastjson.sh
Solaris does not have libfastjson packages, which we require. So we
add a script for our buildbot tests that builds its own local copy
from libfastjson git. This at least ensures we can run the buildbot
tests again on rsyslog solaris.
=> buildbot: add script to build libfastjson on solaris buildbot runs

tests/Makefile.am, tests/msgvar-concurrency-array-event.tags.sh, tests/prop-all-json-concurrency.sh, tests/testsuites/exec_tpl-concurrency.conf, tests/testsuites/msgvar-concurrency-array-event.tags.conf, tests/testsuites/msgvar-concurrency-array-event.tags.rulebase, tests/testsuites/prop-all-json-concurrency.conf
Adds tests for concurrent variable access. Some need libfastjson because of a segfault in json-c (https://github.com/json-c/json-c/pull/211).
=> Testbench add var tests

grammar/lexer.l, outchannel.c, runtime/msg.c, template.c, template.h, tests/Makefile.am, tests/json_var_case.sh, tests/testsuites/json_var_case.conf, tests/testsuites/variable_leading_underscore.conf, tests/variable_leading_underscore.sh
The grammar now allows for leading underscores for variable names. This
addresses a problem stemming from the fact that the imjournal module
will create variables using the given name from systemd. All "trusted"
variables in systemd begin with a leading underscore.
Fixes #603.
=> Accept leading underscores for variable names

grammar/parserif.h
can lead to build problems on some platforms and may also
lead to runtime problems (though there are no known reports
of any).
Thanks to Radu Gheorghe for bringing this up.
=> bugfix: invalid definition in parser interface

runtime/statsobj.c
I think that the flow is wrong here and that the CEE cookie is currently added, regardless whether you pick json, json-elasticsearch or cee for impstats.
=> A CEE cookie shall only be added when using the CEE format

tests/Makefile.am, tests/imuxsock_ccmiddle_syssock.sh, tests/imuxsock_logger_syssock.sh, tests/imuxsock_traillf_syssock.sh, tests/testsuites/imuxsock_ccmiddle_syssock.conf, tests/testsuites/imuxsock_logger_syssock.conf, tests/testsuites/imuxsock_traillf_syssock.conf
We do not exectute them as root, but we assign a special name. This
is very close to the "real thing" but permits us to execute the
tests as part of CI platforms.
closes https://github.com/rsyslog/rsyslog/issues/807
=> testbench: add tests for imuxsock system log socket

plugins/omkafka/omkafka.c
this happened when the topic cache was full and an entry
needed to be evicted
=> omkafka: fix potential NULL pointer addressing

configure.ac
I hope to get away with this simple solution...
=> solaris: MAXHOSTNAMELEN is in different header file

runtime/nsd_gtls.c
Commit https://github.com/rsyslog/rsyslog/commit/1394e0bec2373e85e003b7320c6d12870424d483
changed how the receive buffer was freed in rcv() call. However Retry handling
was not considered properly. 
Closes https://github.com/rsyslog/rsyslog/issues/732
=> gnutls: Fix for issue #732

configure.ac
Fall back to AC_SEARCH_LIBS and AC_COMPILE_IFELSE header version check if PKG_CHECK_MODULES test fails; the Hiredis version in the EPLE6 repo, for example, doesn't include a pkg-config '.pc' file, which causes compilation of the omhiredis module to fail.
Fixes #752
Tested on Centos 6/7, Amazon Linux, Debian 7/8
=> Update autoconf check for hiredis library

plugins/imfile/imfile.c
If an imfile config accidently used a relative path name with no directory separators, the imfile config parsing routine would cause a buffer overflow.  This PR changes getBasename to return a -1 if a directory separator is not found in the File argument, and subsequently return a config error handling the condition a little more gracefully.
=> fix possible buffer overflow in imfile config parser

tools/logctl.c
Detected by clang static analyzer. Note that these leaks CAN happen in
practice and may even be pretty large. This was probably never detected
because the tool is not often used.
closes https://github.com/rsyslog/rsyslog/issues/854
=> bugfix logctl: fix multiple memory leaks

runtime/statsobj.c, tests/Makefile.am, tests/no-dynstats-json.sh, tests/no-dynstats.sh, tests/testsuites/no-dynstats-json.conf, tests/testsuites/no-dynstats.conf
This happens because we generate stats making assumption that every statsobj will have atleast one counter. This removes that assumption, so we generate valid json regardless of statsobj having counters (and origin field).
Reported here: http://lists.adiscon.net/pipermail/rsyslog/2016-March/042209.html
=> fixes incorrect formatting of stats when CEE/Json format is used

runtime/msg.c
There has to be actual json data in the message (from mmjsonparse,
mmnormalize, imjournal, ...) to trigger the crash. E.g.:
module(load="mmjsonparse")
action(type="mmjsonparse")
template(name="tpl" type="list") {
property(name="jsonmesg")
}
action(type="omfile" file="/tmp/json.log" template="tpl")
=> Fix double free in jsonmesg template

plugins/imptcp/imptcp.c, tests/imptcp_uds.sh, tests/imptcp_uds_unlink.sh, tests/testsuites/imptcp_uds.conf, tests/testsuites/imptcp_uds_unlink.conf
I need to use SOCK_STREAM AF_UNIX sockets and making imuxsock support it was shaping up to be way more complicated than using something that already deals with sessions. Wanted to get your eyes on this before I wrote up any documentation.
To use it:
```
module(load="imptcp")
input(type="imptcp" path="/path/to/stream.sock")
```
To test it:
```
logger -Tu /path/to/stream.sock "Hello there"
```
=> AF_UNIX support in imptcp module

runtime/rsconf.c
While this was supposed to receive an integer group ID, this did not
work. A group lookup was done instead (just liek with $PrivDropToGroup).
closes https://github.com/rsyslog/rsyslog/issues/889
=> fix $PrivDropToGroupID

runtime/ruleset.c
When running with debugging enabled, we'll often see the following
error:
error: unknown stmt type %u during iterateAll
Where "%u" is 4006 or 4007. This patch silences those errors by
adding them to the "ignore" case.
=> Silence unknown statement errors in debug logs

plugins/imrelp/imrelp.c
this happens immediately before rsyslog terminates, so it does
not really affect anything. However, it affects the testbench
as memory checkers may report this leak (clang 3.6 address
sanitizer was the first to do).
=> imrelp: fix cosmetic memory leak

plugins/imudp/imudp.c, plugins/omudpspoof/omudpspoof.c, runtime/net.c, runtime/net.h, tools/omfwd.c
Allow rsyslog to bind UDP ports even w/out specific interface being up at the moment.
Rather a proof of concept patch (originally by Marius) to open/track discussion of solution.
Alternatively, rsyslog could be ordered after networking, however, that might have some negative side effects. Also IP_FREEBIND is [recommended][1] by systemd documentation.
Cc: @nirmoy
[1]: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#whatdoesthismeanformeadeveloper
=> Enable socket bindings before network interface is up

runtime/tcps_sess.c, runtime/tcps_sess.h
Commit b0e8ce6c added a new variable to track processing of a single
message split into multiple packets. Several bits of code weren't
ported to the new variable and could cause mishandling.
Messages not terminated by a NL were discarded upon connection
termination.
=> Fix processing of partial messages over TCP

tests/Makefile.am, tests/omfwd-keepalive.sh, tools/omfwd.c
due to being inconsistently spelled. This lead to an internal
program error, which unfortunately was only reported to the
debug log.
This patch both fixes the problem and also emits the internal
program error message to the regular log stream (in case a similar
problem re-occurs in the future). A testbench test is also added.
closes https://github.com/rsyslog/rsyslog/issues/916
=> omfwd bugfix: keepalive action parameters did not work

tools/omfwd.c
A very small leak that manifests itself only on rsyslogd
termination. However, it affects QA tools including CI.
=> omfwd: fix cosmetic memleak

configure.ac, contrib/omhttpfs/omhttpfs.c, grammar/rainerscript.c, plugins/mmjsonparse/mmjsonparse.c, plugins/ommongodb/ommongodb.c, runtime/msg.c, runtime/rsyslog.h, tools/rsyslogd.c
as we now use libfastjson, we do no longer need to check for "new"
features, as these are always present in libfastjson (things
like json_object_object_get_ex()).
closes https://github.com/rsyslog/rsyslog/issues/935
=> cleanup: remove compatibility checks for old json-c

plugins/imfile/imfile.c
when deploy rsyslog to a large number of servers. We may only care about new logs after the deployment. In this case, logs generated before should be discarded, otherwise, there may be vast useless message burst on the central rsyslog receiver.
set **FreshStartTail**  to *on* (**default: off**)cause imfile to seek to the end/taill of input file at fresh start, which means only new log events will be processed.
=> add FreshStartTail input parameter to imfile

plugins/ommongodb/ommongodb.c, runtime/msg.c, runtime/ruleset.c
...and friends. This uses internals of the json library. It was
required when we used json-c, where distros often shipped versions
that did miss its clean counterpart. Now that we require
libfastjson, we can (and should) use the clean method.
closes https://github.com/rsyslog/rsyslog/issues/941
=> stop using fjson_object_object_foreachC()

runtime/msg.c
this will no longer be supported with 0.99.3 and above and is
also not needed at all
closes https://github.com/rsyslog/rsyslog/issues/944
=> do not access libfastjson private details

ChangeLog, tests/Makefile.am, tests/privdrop_common.sh, tests/privdropgroup.sh, tests/privdropgroupid.sh, tests/privdropuser.sh, tests/privdropuserid.sh
This is my proposal.
But this fix for issue #927 will uncover a new problem: When we are really testing impersonating another user (which root can only do per default) privdrop tests will fail because the user we drop to probably cannot write to *$SRCDIR/*. So the tests are failing because files like *rsyslog.out.log* or *rsyslogd.started* cannot be created and the test will run into a timeout.
This will be the case when running the testbench as root and for example the user didn't specify a user we should use so that we will fallback to *daemon* user.
Making *tests* world writeable would address this problem but only if the source path is also accessible by the user we will drop to (not guaranteed).
From my current view the right solution would be to create these files in */tmp* (sub …
=> Make privdrop tests more portable and robust

plugins/imfile/imfile.c
This PR addresses a possible memory issue when appending @cee prefixes to JSON log lines read via imfile.
=> imfile: fix memory corruption bug when appending @cee

tests/faketime_common.sh, tests/privdrop_common.sh
My fault, I misunderstood @rgerhards code comment from https://github.com/rsyslog/rsyslog/pull/875#issuecomment-196260504 when he told me to call `diag.sh exit`.
=> testbench: Add missing exit calls to {faketime,privdrop}_common.sh

tests/faketime_common.sh, tests/now-utc-casecmp.sh, tests/now-utc-ymd.sh, tests/now-utc.sh, tests/now_family_utc.sh, tests/privdrop_common.sh, tests/timegenerated-dateordinal-invld.sh, tests/timegenerated-dateordinal.sh, tests/timegenerated-utc-legacy.sh, tests/timegenerated-utc.sh, tests/timegenerated-uxtimestamp-invld.sh, tests/timegenerated-uxtimestamp.sh, tests/timegenerated-ymd.sh
Using `LD_PRELOAD` like suggested in https://github.com/wolfcw/libfaketime/issues/89 seems to be more robust.
Successfully tested against libfaketime-0.9.6 and git master on systems year 2038 compatible and not.
https://github.com/rsyslog/rsyslog/pull/964 should be merged first.
=>  testbench: Use LD_PRELOAD=libfaketime.so instead of faketime binary 

plugins/imdiag/imdiag.c, runtime/dynstats.c, runtime/dynstats.h, runtime/srUtils.h, runtime/srutils.c, runtime/statsobj.c, runtime/statsobj.h, tests/Makefile.am, tests/diag.sh, tests/diagtalker.c, tests/dynstats_overflow-vg.sh, tests/dynstats_overflow.sh, tests/dynstats_prevent_premature_eviction-vg.sh, tests/dynstats_prevent_premature_eviction.sh, tests/dynstats_reset-vg.sh, tests/dynstats_reset.sh, tests/testsuites/dynstats_overflow.conf, tests/testsuites/dynstats_reset.conf
This was responsible for non-resettable counters being reset on TTL expiry. This portion was missed out in the original implementation.
This doesn't need any documentation update (it just fixes existing deviation from expected behavior and docs already describes the correct behavior).
=> Fixed the dynstats unusedMetricTtl bug

plugins/ommysql/ommysql.c, plugins/ompgsql/ompgsql.c
MAXHOSTNAMELEN is defined in netdb.h on (at least) SunOS. Fixes build.
=> ommysql and ompgsql should include netdb.h

threads.c
The entry point was called at the wrong spot, only when the thread
had not already terminated by itself. This could cause various
cleanup to not be done.
closes https://github.com/rsyslog/rsyslog/issues/882
=> bugfix: afterRun entry point not correctly called

runtime/librsgt.h, runtime/librsksi.h, tests/ksi-extract-verify-long-vg.sh, tests/ksi-extract-verify-long.sh, tests/ksi-extract-verify-short-vg.sh, tests/ksi-extract-verify-short.sh, tests/ksi-verify-long-vg.sh, tests/ksi-verify-long.sh, tests/ksi-verify-short-vg.sh, tests/ksi-verify-short.sh, tools/rsgtutil.c
When network connection problems occur during ksi signature check,
a propper return status is used now (EX_UNAVAILABLE).
This tells the tests to set the SKIP return status to the testbench
in order to avoid false test fails.
=> rsgtutil: Enhanced error return status codes for verify and extract.

runtime/rsyslog.c, runtime/rsyslog.h, runtime/stream.c, threads.c
Note that this is below the usual 10MiB default, but should cause
no issues (output threads already use 4MiB stack size, for example).
This also addresses issues introduced by micro-libc's which only
provide very limited stack space by default.
closes https://github.com/rsyslog/rsyslog/issues/996
=> core: set default stack size to 4MiB

plugins/omelasticsearch/omelasticsearch.c
curl use SIGALRM to timeout handling. but it doesn't work in linux
threads and the signal is delivered to an *arbitary* threads which
almost guarantees crashing if a wrong thread picks up the signal.
```
(gdb) bt
#0  0x00007f8b8859aa6d in addbyter () from libcurl.so.4
#1  0x00007f8b8859b993 in dprintf_formatf () from libcurl.so.4
#2  0x00007f8b8859bfd5 in curl_mvsnprintf () from libcurl.so.4
#3  0x00007f8b8859ac42 in curl_msnprintf () from libcurl.so.4
#4  0x00007f8b8858bbf6 in Curl_failf () from libcurl.so.4
#5  0x00007f8b885826ef in Curl_resolv_timeout () from libcurl.so.4
#6  0x00007f8b88cf2dfd in clock_gettime () from /lib64/libc.so.6
#7  0x00007f8b6c01b1e0 in ?? ()
#8  0x00007f8b887d58e8 in Curl_crealloc () from libcurl.so.4
#9  0x00007f8b6c01a5a0 in ?? ()
#10 0x00007f8b887d58e8 in …
```
=> disable curl signal to avoid race in threads

tests/travis/install.sh
sometimes the travis build complains about inability to verify
correctness, which is probably related to ongoing build work. This
should solve the issue with PPAs (mostly our own).
=> travis: force install of non-OS-standard components

tests/diag.sh
So we do no longer need to wait on timeout if rsyslog segfaults.
=> testbench: detect rsyslog abort in startup phase

tests/diag.sh
was actually forgotten to be removed after some change
=> testbench: remove a debugging message which clutters test log

tests/CI/buildbot_cleanup.sh, tests/CI/gather_all_logs.sh
closes https://github.com/rsyslog/rsyslog/issues/1036
=> CI: add plubming to gather testbench error info in timeout case

plugins/imrelp/imrelp.c
librelp seems to emit some TLS error codes not (only) when enabling
TLS, but also when finalizing the listener. We have now duplicated
some checks to make sure the user gets a meaningful message.
closes https://github.com/rsyslog/rsyslog/issues/1019
=> imrelp: better error codes on unvailablity of TLS options

contrib/omamqp1/omamqp1.c
Fixes a bug that will prevent connecting to the message bus if a port number other than 5672 is in use.
=> omamqp1: bugfix - supply port number to message bus address

runtime/rsyslog.h, tools/omfile.c
If the file creation succeeds, but chown() failed, the file was
still writen, even if the user requested that this should be treated
as a failure case. This is corrected by this commit.
Alos, some refactoring was done to create better error messages.
=> bugfix omfile: handle chown() failure correctly

tests/Makefile.am, tests/sndrcv_relp_dflt_pt.sh
we have improved an existing test file so that it does not require special
configure options to make the testbench succeed.
=> testbench: activate a new relp test

.travis.yml
this needs to be done as the v8-devel PPA is no longer available
see also http://lists.adiscon.net/pipermail/rsyslog/2016-July/043092.html
=> travis: disable forward-compatibility test

.travis.yml, tests/travis/install.sh
the v8-devel PPA is now available again, so we can re-enable testing
with its help
=> travis: re-enable forward-compatibility test

runtime/batch.h, runtime/glbl.c, runtime/wti.h, tests/diag.sh, tests/inputname.sh, tools/rsyslogd.c
this enables us to put error messages to systemd journal; which is
especially useful as most distros by default throw away rsyslog
error messages.
=> make rsyslog log by default to syslog()

ChangeLog, configure.ac, plugins/ompgsql/ompgsql.c, tests/Makefile.am, tests/pgsql-basic.sh, tests/pgsql-template.sh, tests/testsuites/pgsql-basic.conf, tests/testsuites/pgsql-select-msg.sql, tests/testsuites/pgsql-select-syslogtag.sql, tests/testsuites/pgsql-template.conf, tests/testsuites/pgsql-truncate.sql
It seems that for the Postgres output we didn't have template support. It used the ` StdPgSQLFmt` template (with a space in the beginning) no matter what you gave it.
Sorry for the number of commits, I've tried to squash them in one but I only made matters worse :( Please let me know if I need to make any changes at this point.
Configuration sample that worked for me (with the patch):
```
module(load="imuxsock")
module(load="ompgsql")
$template mytemplate,"insert into SystemEvents (Message, Facility, FromHost, Priority, DeviceReportedTime, ReceivedAt, InfoUnitID, SysLogTag) values ('%msg%', %syslogfacility%, '%HOSTNAME%', %syslogpriority%, '%timereported:::date-pgsql%', '%timegenerated:::date-pgsql%', %iut%, '%syslogtag%')",STDSQL
*.* :ompgsql:localhost,Syslog,user,password;mytemplate
``` …
=> Add custom template support for ompgsql

runtime/lmsig_gt.c, tools/rsgtutil.c
We have seen some new warnings after moving to newer SUSE inside the
testbench, and thus a newer compiler versions. This commit fixes them.
=> cleanup: fix compiler warnings

plugins/imfile/imfile.c, tests/Makefile.am, tests/imfile-truncate.sh
This fixes
* ReopenOnTrucate was only honored when a state file existed
(see https://github.com/rsyslog/rsyslog/issues/1090)
* open processing could run into a loop
(see https://github.com/rsyslog/rsyslog/issues/1174)
replaces #1091
=> imfile: bugfix: ReopenOnTruncate processing, file open processing

configure.ac
where that symbol is supplied by libpthread.
Previously, config.log was saying:
```
configure:16659: checking for pthread_setschedparam
configure:16659: cc -o conftest -g -O2   conftest.c  >&5
/tmp/conftest-9fd24a.o: In function `main':
/usr/ports/sysutils/rsyslog8/work/rsyslog-8.19.0/conftest.c:149: undefined reference to `pthread_setschedparam'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
configure:16659: $? = 1
```
Note no '-lpthread' flags in that compiler command line.
Switching from AC_CHECK_FUNCS to AC_SEARCH_LIBS allows configure to
test for the presence of that function in that library where necessary.
Without pthread_setschedparam(), syslog traffic received via UDP from
a remote server does not get written out to disk files reliably when
the imudp …
=> Fix detection of pthread_setschedparam() on platforms such as FreeBSD

grammar/rainerscript.c, plugins/ommongodb/ommongodb.c, plugins/omudpspoof/omudpspoof.c, runtime/modules.c, runtime/queue.c, runtime/stringbuf.c
probably thanks to updated gcc on Fedora; generic code cleanup, not triggered by external event
=> fix a couple of compiler warnings that came up for the first time

Makefile.am, configure.ac, contrib/omtcl/Makefile.am, contrib/omtcl/omtcl.c, tests/Makefile.am, tests/omtcl.sh, tests/omtcl.tcl
An output module that calls a TCL procedure for each message.  This module can be used as an alternative to omshell/ompipe when fast output with custom processing or ad-hoc integration is needed.
=> Output Module TCL

configure.ac
This is because the previous versions have a bug that causes
invalid Unicode encoding for some non US-ASCII characters and
may also segfault (though unlikely) under this condition.
=> build system: require libfastjson 0.99.3

tests/daqueue-persist-drvr.sh, tests/daqueue-persist.sh
this is a regression from some month ago, when we changed
the shell calls. Only the first of three tests was executed.
=> testbench: fix only partially executed test

plugins/imuxsock/imuxsock.c, runtime/msg.c, runtime/msg.h, tools/iminternal.c, tools/rsyslogd.c
This fixes some issues we have with rsyslog internal message processing when the rsyslog instance emitting those messages is the same that needs to process them.
=> Fix issues with rsyslog internal messages in default mode

grammar/rainerscript.c, runtime/lookup.c, runtime/rsyslog.h, tests/Makefile.am, tests/fac_local0-vg.sh
Primarily fixes towards https://github.com/rsyslog/rsyslog/issues/1071.
The second-issue (funcdata free-at-destruct marker was uninitialized for prifilt) seems fairly unrelated, but since it has been found incidentally on the same thread, hence fixing it in the same PR.
=> Lookup table init error check and prifilt init fix

plugins/omelasticsearch/omelasticsearch.c, tests/Makefile.am, tests/es-basic-ha.sh, tests/es-basic-server.sh, tests/testsuites/es-basic-ha.conf, tests/testsuites/es-basic-server.conf
Resolves #1171 
Changing server parameter to accept an array of servers/uris and port to
defaultPort if not specified on a given uri. Adding dedicated curl handle
for checkConn and refactoring the curl setup a bit, using ES health check
with timeout. Added checkConnFailure stat counting and HA test
=> omelasticsearch high availability addressing of ElasticSearch cluster

runtime/stream.c
This causes a segfault. It happens whenever an object state larger
than 4095 byte is persisted. Then, incorrectly a try to rollover to
a new state file is tried, which will lead to a division by zero
as the necessary variables for this operation are not set because we
are NOT in circular mode.
This problem can happen wherever state files are written. It has been
experienced with imfile and queue files.
Many thanks to github user mostolog for his help in reproducing the
issue, which was very important to finally nail down this long-standing
bug.
closes https://github.com/rsyslog/rsyslog/issues/1239
closes https://github.com/rsyslog/rsyslog/issues/1162
closes https://github.com/rsyslog/rsyslog/issues/1074
=> bugfix: abort when persisting object state

contrib/mmgrok/README
This incorrect spelling may confusing people who follows `README.md`'s
instruction.
=> Fix an incorrect spelling of `mmgrok`'s README.md

tests/Makefile.am, tests/diag.sh, tests/empty-hostname.sh, tests/faketime_common.sh, tests/override_gethostname.c
This is a first in a series of tests that mimic specific cases using LD_PRELOAD to override APIs. We still have some issues with the method, and I need to iron them out on the testbench machines.
Note that the new test will fail with a segfault due to #1040 until the fix for this has been merged (which I did not do yet intentionally). This is actually what needs to happen to know the new testbench test (and method) will work.
=> testbench: add test for empty host name

runtime/queue.c, runtime/queue.h
For solving problem mentioned in issue #1135, New configuration item `queue.samplinginterval` is added, providing a way setting a interval of sampling logs by line.
=> Add configuration item `queue.samplinginterval` for queue

runtime/librsksi.c
The SHA-224 hash algorithm has been removed from the future releases, thus removed the usage of it.
=> Removed the use of the deprecated hash function SHA-224.

plugins/omlibdbi/omlibdbi.c
libdbi-driver-sqlite3 requires to provide a path to database split into two strings:
- absolute path, where the database file sits
- database filename itself.
This patch split the DBName parameter into two, and provide both to libdbi library.
The same stands for non-3-sqlite driver.
Tested against sqlite3. Not tested againt sqlite2, but regarding to the
libdbi-drivers-sqlite and libdbidrivers-sqlite3 documentation and code,
the approach is identical.
=> omlibdbi: fix suport for sqlite3

contrib/omhiredis/omhiredis.c
This PR introduces a new `dynakey` attribute.
If set to `on`, this causes omhiredis to treat the `key` attribute as the name of a template so that you can build a dynamic redis queue name or list key.
Absolutely _no_ warranty of quality or functionality is made here. It took me a while to get the thing to stop throwing Segfaults, so we're a way off production ready.
```
template(name="redis-key" type="list"){
constant(value="logs-from-")
property(name="syslogtag")
}
action(
action.resumeretrycount="-1"
action.resumeinterval="5"
queue.maxDiskSpace="1G"
queue.spoolDirectory="/var/spool/rsyslog"
queue.filename="plain-docker" 
queue.size="1000000" 
queue.type="LinkedList"
type="omhiredis"
mode="publish"
dynakey="on"
key="redis-key"
server="localhost"
template="plain-syslog"
)
```
``` …
```
=> Allow the key parameter of Omhiredis to point to a template

runtime/librsksi.c, runtime/librsksi.h, runtime/librsksi_read.c, runtime/lmsig_ksi.c, tools/rsgtutil.c
The following improvements/bugfixes were introduced:
- In case requesting the KSI signing is unsuccessful (no access to gateway, incorrect credentials, etc.) the server will not give up and continue the log signing. The block are still useful even if lack KSI signature.
- Added log messages for KSI signing events.
- Fixed extending of the KSI signature in rsgtutil, added support for new (KSI) signature format and added warning in case the signature is missing.
Some fixes were also introduced to libksi and this patch should be merged together with the latest patch to libksi (to be sent separately).
Tested manually.
=> Ksi ignore service fail

plugins/omelasticsearch/omelasticsearch.c
Make the omelasticsearch plugin compatible with ElasticSearch 2.x and 5.x and solves this [issue 1252](https://github.com/rsyslog/rsyslog/issues/1252)
I tested this against ElasticSearch 2.4 and 5.0
maintainer edit:
closes https://github.com/rsyslog/rsyslog/issues/1252
=> Improve compatibility with ElasticSearch 2.x and ElasticSearch 5.x 

runtime/librsksi.c, runtime/librsksi.h, runtime/lmsig_ksi.c
Enabling lmsig_ksi module to use the same file permissions as omfile. Tested manually.
=> Fixing issue #1267: allow lmsig_ksi to configure file persmissions

runtime/wtp.c, runtime/wtp.h
The shutdown sequence in wtp relies for its operation on signals and cancelation cleanup handlers. Previously, trying to shutdown a thread that has not yet been properly initialized could lead to a deadlock. This change makes wtpStartWrkr() synchronous in regard to the initialization of the newly created thread.
This issue extends an older one here: #966
=> Race condition in wtp

plugins/imuxsock/imuxsock.c
When imjournal and imuxsock modules are loaded, $OmitLocalLogging is on and the rsyslog service is being stopped, imuxsock wants to close socket on index 0 which leads to segfault in rsyslog and the service stopping ends with failure.
=> Imuxsock segfault when stopping rsyslog service

tests/diag.sh
most importantly, include line numbers, so that rsyslog startup
error messages can be traced to the right line. Due to the framework,
the line number info is otherwise not visible.
=> testbench: ease testbench debugging by outputting generated conf

runtime/module-template.h
If an om,mm module has no parameters, a macro function parameter is
unused and triggers compile warning (and thus error on -Werror).
closes https://github.com/rsyslog/rsyslog/issues/1293
=> core: fix bug in module-template macros

.travis.yml
As suggested by Travis CI support, we fall back to the previous
images until the issue is resolved.
=> travis: work-around travis failures due to new travis images

plugins/omelasticsearch/omelasticsearch.c
The _bulk index endpoint on ElasticSearch 5.0 no longer
ignores the ?replication=async query parameter. It was deprecated
since 1.5 and silently ignored in 2.x but passing it to a 5.x
instance breaks omeleastisearch with a 400 response.
closes https://github.com/rsyslog/rsyslog/issues/1250
=> omelasticsearch: remove "asyncrepl" config parameter

.travis.yml
We tried to disable this to prevent unnecessary Travis runs after
merging changes to master, however, disabling it also disabled
checking of PRs, so we cannot do this. Thus undoing this change.
=> travis: enable CI on master branch

plugins/imjournal/imjournal.c
There is a bug in rsyslog which is caused by not very atomic writes of imjournal statefile. It's hardly reproducible but there is a way. fscanf error appears only when rsyslog reads an empty statefile  which causes that imjournal is stopped so no logging from journal is performed. When the statefile contains random bytes error appears again but from journal and imjournal is stopped too.
In this patch Rsyslog writes imjournal statefile more atomically and secure. Reading the statefile is more robust and doesn't affect imjournal module so when corrupted statefile is read imjournal ignores statefile, continues with logging and it doesn't stop. Logger can be used as a test if it's logging or not.
Patch introduces a new option with both old and new config format "IgnoreNonValidStateFile" which …
=> Make state file handling in imjournal more robust

runtime/msg.c
We handle the (confusing) case of invalid system properties now so that
we do not only emit an error message but also point to the potentially
correct version in case we can guess it.
=> config parsing: improved error messages

tools/rsyslog.conf.5
Add a blurb to the rsyslog.conf man page for configurating remote servers
reachable via a specific device. Add comment for Linux with VRF support as
well.
Signed-off-by: David Ahern <dsa@cumulusnetworks.com>
=> Update the rsyslog.conf man page for device option

tools/omfile.c
If bFlushOnTXEnd is set, we need to flush on transaction end - in
any case. It is not relevant if this is using background writes
(which then become pretty slow) or not. And, similarly, no flush
happens when it is not set.
closes https://github.com/rsyslog/rsyslog/issues/1297
=> bugfix: bFlushOnTxEnd == 0 not honored when writing w/o async writer

plugins/ommongodb/clean-mongo-syslog
In the latest pymongo library, the Connection class is now called MongoClient
=> plugins/ommongodb/clean-mongo-syslog: support for MongoClient API

runtime/ratelimit.c
Fixes  #1354 . For ratelimit checking, added check for time going backwards. If time goes backwards, then ratelimit begin and done values must be set to zero
=> For ratelimit checking, added check for time going backwards.

runtime/glbl.c, runtime/glbl.h, runtime/msg.c, tests/Makefile.am, tests/prop-programname-with-slashes.sh, tests/prop-programname.sh
The new option permits to have slashes inside the programname
property. This is counter the BSD syslog defintitions, but
sometimes useful (e.g. the journal records path names, which
obviously contain slashes).
closes https://github.com/rsyslog/rsyslog/issues/1365
see also https://github.com/rsyslog/rsyslog/issues/1361
=> add option "parser.PermitSlashInProgramname"

runtime/stream.c
Rsyslog 8.23.0 loops on FreeBSD when trying to access a (now revoked) /dev/console file descriptor, as per Alexandre's original bug report [1].
The original patch fixes the problem when tryTTYRecover() sees errno 6 ENXIO.
Running FreeBSD 10-stable here and getting errno 5 EIO, same as Xavier gets in his 2016 bug report [2].
New patch [3] includes errno 5 to tryTTYRecover() in runtime/stream.c and fixes the problem for me, on multiple machines.
[1] https://github.com/rsyslog/rsyslog/issues/371
[2] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211033
[3] https://bz-attachments.freebsd.org/attachment.cgi?id=178452
closes https://github.com/rsyslog/rsyslog/issues/1351
=> bugfix: rsyslog loops on freebsd when trying to write /dev/console

plugins/imfile/imfile.c, tests/Makefile.am, tests/diag.sh, tests/imfile-wildcards-dirs-multi.sh, tests/imfile-wildcards-dirs.sh, tests/imfile-wildcards-dirs2.sh, tests/imfile-wildcards.sh, tests/testsuites/es-bulk-errfile-popul-def-format.conf, tests/testsuites/es-bulk-errfile-popul-def-interleaved.conf, tests/testsuites/es-bulk-errfile-popul-erronly-interleaved.conf, tests/testsuites/es-bulk-errfile-popul-erronly.conf, tests/testsuites/imfile-wildcards-dirs-multi.conf, tests/testsuites/imfile-wildcards-dirs.conf, tests/testsuites/imfile-wildcards.conf
Added support for multilevel wildcards (inotify only)
imfile supports now wildcards on multiple levels.
Directories can be dynamically added and removed.
Each directory has its own inotify watch.
=> Imfile multilevelwildcard

grammar/rainerscript.c, tests/rscript_num2ipv4.sh
If str2num() receives an empty string, misadressing happens.
Under extreme conditions, this theoretically can lead to a segfault.
closes https://github.com/rsyslog/rsyslog/issues/1412
=> bugfix: str2num mishandling empty strings

plugins/imjournal/imjournal.c
This is resolving the situation when system is after reboot and boot_id
doesn't match so cursor pointing into "future". Usually sd_journal_next
jump to head of journal due to journal aproximation, but when system
time goes backwards and cursor is still invalid, rsyslog stops logging.
We use sd_journal_get_cursor to validate our cursor. When cursor is
invalid we are trying to jump to the head of journal. This problem with
time is not affecting persistent journal.
=> Fixed situation when time goes backwards

runtime/glbl.c, runtime/glbl.h, runtime/rsconf.c
This is caused by uninitialized net static structure in glbl objUse(net)
is not called after start of glbl module.
It looks like it is not possible to use objUse(net) when glbl module
starts. So we call it inside of glblDoneLoadCnf().
=> Fixed segfault in glblDoneLoadCnf()

tests/diag.sh
ps is used when waiting on startup and spams the test log if
rsyslog takes longer to start up (or fails to do so). This
makes the log hard to read.
=> testbench: do not spam testbench log with output from ps command

runtime/glbl.c, tests/Makefile.am, tests/glbl-umask.sh
This is equivalent to "$umask" and permits to convert that construct
to new-style config format.
closes https://github.com/rsyslog/rsyslog/issues/1382
=> add new global parameter "umask"

tests/tcpflood.c
closes https://github.com/rsyslog/rsyslog/issues/232
=> testbench/tcpflood: auto-apply silent option during CI runs

contrib/imczmq/imczmq.c
Commit https://github.com/rsyslog/rsyslog/commit/299f5a637f97d2ec064ad3df20fa845ef4b7c7e5 introduced 2 small regressions in the imczmq plugin that I found as we upgrade from 8.18 to 8.24.
Subscribing to every topic (via an empty string in the config) no longer works, and imczmq over a SUB socket no longer connects by default. The fixes for both are very simple.
@taotetek FYI
=> imczmq: fix 2 regressions introduced in 8.19

plugins/imdiag/imdiag.c, runtime/rsyslog.h, runtime/stream.c, tests/Makefile.am, tests/diag.sh, tests/omfile-read-only-errmsg.sh, tests/tcpflood.c, tools/iminternal.c, tools/rsyslogd.c
reissue of #1441 due to rebase problems
Those messages previously went only to the debug log, as due to design limitations inside the error message subsystem they could not be emitted at the related code locations. This has changed now, and so we can improve error reporting.
=> core/file handling: add new error messages

plugins/imdiag/imdiag.c, runtime/rsyslog.h, tests/diag.sh, tests/tcpflood.c, tools/iminternal.c, tools/rsyslogd.c
previous code could deadlock if internal messages were issued
inside queue processing code, which effectively limited
error-reporting capabilities. This change makes it possible
to call error messages from any part of the code at any time.
This comes at the price of slightly delayed message output.
=> core: enable internal messages at any time

runtime/queue.c, runtime/stream.c
with the recent change that permits us to emit error messages at
(alomost) any time, we can now provide better end-user diagnostics.
This patch generates error message which could previously only be
logged to the debug log.
=> improve queue error messages

plugins/omsnmp/omsnmp.c
When omsnmp was configured via new-config, init_snmp wasn't called.
This config doesn't work.
module(load="omsnmp")
local2.debug action( type="omsnmp"
transport="udp"
server="localhost"
port="162"
version="1"
community="public"
trapoid="ADISCON-MONITORWARE-MIB::syslogtrap"
messageoid="ADISCON-MONITORWARE-MIB::syslogMsg"
)
It prints error message:
"rsyslogd-2006: omsnmp_sendsnmp: Adding trap OID failed 'ADISCON-MONITORWARE-MIB::syslogtrap' with error 'Unknown Object Identifier'"
Config worked only without specified MIB-files.
=> Fixed omsnmp new-config issue

tests/tcpflood.c
The previous commit 73e3b7ab for issue #1426 was incomplete and missed
the librelp.h header include.
Gentoo-Bug: https://bugs.gentoo.org/614424
=> testbench: tcpflood failed to build if RELP support was disabled (2/2)

configure.ac, tests/Makefile.am, tests/tcp_forwarding_ns_tpl.sh, tests/testsuites/tcp_forwarding_ns_tpl.conf, tools/omfwd.c
Network namespaces are part of the linux kernel since v2.6.24. This
enables forwarding output into a configurable network namespace. E.g.,
action(type="omfwd" networknamespace="my_ns" target="192.168.1.23"
port="10514")
Signed-off-by: Bastian Stender <bst@pengutronix.de>
=> omfwd: add support for network namespaces

plugins/imfile/imfile.c
This should fix compile problems in issue:
https://github.com/rsyslog/rsyslog/issues/1494
=> imfile: Setting GLOB_BRACE to ZERO if not available on platform

tests/rscript_str2num_empty.sh
to check if es_str2num (in libestr) handles empty strings
correctly. Not yet in use, but will be useful later on.
=> add new test

plugins/imptcp/imptcp.c
An unnecessary debug output from development was accidentally left in a pull request.
see https://github.com/rsyslog/rsyslog/pull/1497
=> imptcp: remove debug output used for testing

tools/iminternal.c
We have seen cases where the kill() used to signal new messages
actually cases problems and the new debug message is intended to
provide a better clue to what is happening. In any case, this
is generally useful, and so should remain even after the debugging
of that special case.
=> iminteral: add addtl debug message

plugins/imptcp/imptcp.c
imptcp had very limited debug messages and also did not emit error
messages in important cases. This has been enhanced. Possibly there
is some potential for even more debug messages, but we wanted not
to overdue it...
closes https://github.com/rsyslog/rsyslog/issues/1499
=> imptcp: improve debug output and error messages

plugins/imuxsock/imuxsock.c, runtime/ratelimit.c
This is sort of addition to recently merged changes, first commit addresses real-world use-case finding that hostname and message source are better split by some formatting char (colon seems ok for this purpose) and second commit adds much better source logging for those using imuxsock which does not rely on APPNAME mesage field which is, more often than not, blank. What do you think of this @rgerhards ?
=> Rate limit proc name

tests/dynstats_prevent_premature_eviction.sh, tests/dynstats_reset-vg.sh, tests/dynstats_reset.sh, tests/testsuites/dynstats_reset.conf
dynstats_prevent_premature_eviction.sh always fails on Solaris10 sparc buildbot due to this tolerance issue (https://github.com/rsyslog/rsyslog/issues/1519).
=> Double impstats flush-interval because 1-flush-per-second is not enough tolerance on very slow machines

plugins/imtcp/imtcp.c, runtime/tcps_sess.c, runtime/tcps_sess.h, runtime/tcpsrv.c, runtime/tcpsrv.h, tests/Makefile.am, tests/imtcp-discard-truncated-msg.sh
Parameter discardTruncatedMsg makes it possible to discard the rest of the message after it has been truncated.
closes https://github.com/rsyslog/rsyslog/issues/745
=> imtcp: add new parameter discardTruncatedMsg

tools/rsyslogd.c
This leads to invalid writes to whatever file is open with file
descriptor 2. The problem only happens during shutdown.
closes https://github.com/rsyslog/rsyslog/issues/1526
=> core bugfix: stderr used on shutdown even though it is closed

runtime/net.c
In case of resolution function specific failure there is a risk of strstr() being called with NULL argument which results in undefined behavior
=> guard against calling strstr with NULL

tests/mmnormalize_processing_test1.sh, tests/mmnormalize_processing_test2.sh, tests/mmnormalize_processing_test3.sh, tests/mmnormalize_processing_test4.sh, tests/now-utc-casecmp.sh, tests/now-utc-ymd.sh, tests/now-utc.sh, tests/now_family_utc.sh, tests/timegenerated-dateordinal-invld.sh, tests/timegenerated-dateordinal.sh, tests/timegenerated-utc-legacy.sh, tests/timegenerated-utc.sh, tests/timegenerated-uxtimestamp-invld.sh, tests/timegenerated-uxtimestamp.sh, tests/timegenerated-ymd.sh
this  causes all libfaketime tests to fail, due to unset
environment variable (which is set in init).
=> testbench: invalid init sequence

runtime/msg.c, tests/Makefile.am, tests/diag.sh, tests/internal-errmsg-memleak.sh, tools/rsyslogd.c
In this case, the message object is not destructed, resulting in a memory leak. Usually, this is no problem due to the low number of internal message, but it can become an issue if a large number of messages is emitted.
closes #1548
closes #1531
=> core bugfix: memory leak when internal messages not processed internally

runtime/msg.c, tests/Makefile.am, tests/diag.sh, tests/internal-errmsg-memleak.sh, tools/rsyslogd.c
Rate-limiting is only applied to messages processed internally. While the
external logging system probably also applies rate-limiting, it would be
preferrable that rsyslog applies the same policies on internal messages,
no matter where they go. This commit implements that change.
closes #1549
=> core: correctly rate-limit internal messages

configure.ac
I was wondering about the message
```
librdkafka is missing but library present, using -lrdkafka
```
so I looked into the code and improved librdkafka detection.
=> Improve librdkafka detection

configure.ac, contrib/mmgrok/Makefile.am, contrib/omhttpfs/Makefile.am, runtime/Makefile.am
... but used it for libfastjson. This was a left-over when we
could use both json-c and libfastjson. As github user hdatma
pointed out, this was confusing to users. This has now been
changed to LIBFASTJSON. No functional changes.
=> cosmetic: build system still used JSON_C name

plugins/imkafka/imkafka.c, tests/Makefile.am, tests/travis/install.sh
add kafka komponents to travis checking
Note: omkafka already was, but seems to have been disabled by recent imkafka work. This also has been re-established.
=> Travis librdkafka

contrib/mmdblookup/mmdblookup.c, tests/Makefile.am, tests/diag.sh, tests/libmaxmindb.supp, tests/mmdb-vg.sh
There were multiple large memory leaks in mmdblookup, which made
it unusable when used more than lightly.
closes https://github.com/rsyslog/rsyslog/issues/1415
=> mmdblookup bugfix: multiple memory leaks

contrib/omhiredis/omhiredis.c
This PR fixes the build warnings on newer gcc's mentioned in https://github.com/rsyslog/rsyslog/issues/1258.
=> fix omhiredis build warnings

contrib/mmcount/mmcount.c, contrib/mmdblookup/mmdblookup.c
libfastjson returns NULL for json "null" objects, and callers need
to handle this. This is correctly handled in almost all code path
in rsyslog, and this patch fixes theoretical issues in the remaining
two places. Note, however, that a json null object can not really
occur at those places due to the rest of processing. But we
wanted to include the check anyways.
closes https://github.com/rsyslog/rsyslog/issues/600
=> bugfix: handling of json "null" objects in regard to msgGetJSONPropJSON

plugins/imfile/imfile.c
This PR is submitted for solving the problem that rsyslog will not monitor files which were moved to monitored directory.
In our case, we use `logrotate` to rotate log file. It moves `foo.log` to `foo.log.1`, then to `foo.log.2`, etc. At last , `logrotate` cleans `foo.log.9` and moves the empty file to `foo.log` (we just keep 9 log dump files), and this action causes a mistake: rsyslog does not handle inotify's `IN_MOVED_TO` event, so  `foo.log` will never be monitored.
In order to solve this problem, we update `logrotate`'s configuration to avoid moving file back. It works, but I hope rsyslog can do right thing with files which were moved to directory.
=> Fix #1588: Handle inotify event `IN_MOVED_TO` as `IN_CREATE`

plugins/imfile/imfile.c, runtime/stream.c, tests/Makefile.am, tests/imfile-endregex-timeout-with-shutdown-polling.sh, tests/imfile-endregex-timeout-with-shutdown.sh
The timeout feature for multiline reads does not correctly work for files for which a state file existed. This is usually the case for files that had been processed by a previous run and that still exist on the new start. For all other files, especially those monitored by a wildcard and newly created after the rsyslog start, timeout worked as expected.
closes https://github.com/rsyslog/rsyslog/issues/1445
=> imfile: multiline timeout does not work after rsyslog restart

contrib/imzmq3/imzmq3.c, contrib/omzmq3/omzmq3.c
This PR will fix 2 compilation errors when trying to build imzqm3 or omzmq3 module with *-Werror=format-security*:
```
omzmq3.c: In function ‘initZMQ’:
omzmq3.c:245:9: error: format not a string literal and no format arguments [-Werror=format-security]
if(-1 == zsocket_bind(pData->socket, (char*)pData->description)) {
^~
omzmq3.c:252:9: error: format not a string literal and no format arguments [-Werror=format-security]
if(-1 == zsocket_connect(pData->socket, (char*)pData->description)) {
^~
```
and
```
imzmq3.c: In function ‘createSocket’:
imzmq3.c:406:9: error: format not a string literal and no format arguments [-Werror=format-security]
rv = zsocket_connect(*sock, info->description);
^~
imzmq3.c:416:9: error: format not a string literal and no format arguments [-Werror=format-security] …
```
=> Fix format security issue in zmq3 modules

runtime/net.c
After digging trough `gethostbyname()` and `getaddrinfo()` glibc sources I found out that for some reason the condition logic was changed in a way that without working DNS, fallback functions fetching local hostname are skipped, so this commits retains this behavior on rsyslog level, thus returning to previous behavior.
=> Ignore NONAME error from getaddrinfo 

configure.ac, runtime/Makefile.am
Previously, libksi was added to all binaries when --enable-ksi-ls12
was activated.
closes https://github.com/rsyslog/rsyslog/issues/1600
=> bugfix build system: add libksi only to those binaries that need it

plugins/imfile/imfile.c, tests/Makefile.am, tests/imfile-rename.sh, tests/inputfilegen.c, tests/testsuites/imfile-wildcards-simple.conf
Added check for IN_MOVED_TO in in_handleDirEvent. Statefilename and
event cookie are saved in IN_MOVE_FROM event in a linkedlist now,
so the statefile can be renamed to a new name in IN_MOVED_TO event.
Closes https://github.com/rsyslog/rsyslog/issues/1417
=> imfile: Added test for dynamic renamed files (wildcard)

tests/imfile-error-not-repeated.sh, tests/internal-errmsg-memleak.sh
I guess they were accidently disabled.
=> testbench: enable some more tests on solaris

ChangeLog, plugins/omprog/omprog.c
One of the users of the FreeBSD rsyslog port (I'm the port maintainer) has reported problems
with the omprog module not generating any output.  He diagnosed this as due to calling 
execve(2) with a NULL second argument -- which is an error on FreeBSD and probably on
other operating systems.
To reproduce:
```
% cat rsyslog.conf
$WorkDirectory /
#$ModLoad imudp
#$ModLoad imtcp
#$ModLoad imklog
#$ModLoad imuxsock
module(load="builtin:omfile")
module(load="builtin:ompipe")
#module(load="builtin-shell")
module(load="builtin:omdiscard")
module(load="builtin:omfwd")
module(load="builtin:omusrmsg")
module(load="builtin:pmrfc5424")
module(load="builtin:pmrfc3164")
module(load="builtin:smfile")
module(load="builtin:smtradfile")
module(load="builtin:smfwd")
module(load="builtin:smtradfwd") …
```
=> Empty argv

tests/travis/install.sh
was a left-over from debugging the kafka CI system;
spams stdout and thus can even lead to premature abort on
Travis due to too-large output
=> remove very verbose CI output in librdkafka install

plugins/imfile/imfile.c
If PersistStateInterval=1, then each log line read should cause the state file to be updated, but this
was not happening because nRecords was being post-increment.
=> Fix behaviour of PersistStateInterval.  

runtime/obj.c
(Forgive the verbosity of this description. I copied it over from our internal repository as it was meant to educate those who were not very familiar with some of the workings of the underlying DA process)
During the deserialization of an object defined within a DA queue file, we will attempt to parse each property of an object [in-order based on a ruleset](https://github.com/rsyslog/rsyslog/blob/master/runtime/msg.c#L1280). Each line within the object structure represents a property that is to be applied to the `var` struct. The type and values of the property are separated by `:`s. Here's an example of an object structure:
```
<Obj:1:msg:1:
+iProtocolVersion:2:1:0:
+iSeverity:2:1:5:
+iFacility:2:2:16:
+msgFlags:2:1:0:
+ttGenTime:2:10:1497509508: …
```
=> Reset to VARTYPE_NONE

plugins/imklog/bsd.c, plugins/imklog/imklog.c, plugins/imklog/imklog.h, tests/Makefile.am, tests/imklog_permitnonkernelfacility_root.sh
permitnonkernelfacility doesn't work when the new configuration syntax
is used, e.g. 'module(load="imklog" permitnonkernelfacility="on")'.
It does work with the old syntax, e.g. '$KLogPermitNonKernelFacility
on'
This is because the old style config is stored in a static global
struct "cs", while the new style config is passed in as a pointer.
Code in imklog will put old style config entries into the new config
struct, and almost all the code in imklog uses the new config struct
like it should.  Except for a check for bPermitNonKernel in Syslog()
that continued to use the static global that only has old style
configs.
Fix this by passing pModConf down into Syslog() and using that in
place of the static global.
closes https://github.com/rsyslog/rsyslog/issues/477
=> imklog: Fix permitnonkernelfacility not working

runtime/net.c, runtime/prop.c, tests/Makefile.am, tests/hostname-getaddrinfo-fail.sh, tests/override_getaddrinfo.c, tests/override_gethostname_nonfqdn.c, tools/rsyslogd.c
rsyslog will segfault on startup if
a) the local machine's hostname is set to a non-FQDN name
b) the getaddrinfo() system call fails
This scenario is higly unlikely, but may exist especially with provisioned VMs which may not properly be able to do name queries on startup (seen for example on AWS).
This patch fixes the situation and also provides more robustness for very early startup error messages when some of the error-reporting subsystem is not yet properly initialized. Note that under these
circumstances, errors may only show up on stderr.
closes rsyslog#1573
=> core bugfix: segfault after configuration errors

configure.ac
Many tests depend on omstdout. Given the fact that omstdout
is really only useful for the testbench (at least that's the intent),
we now require --enable-omstdout if --enable-testbench is given.
The alternative would have been to disable all those tests that
need it, which would have lead to considerable less testbench
coverage.
closes https://github.com/rsyslog/rsyslog/issues/1649
=> testbench bugfix: hang in tests if omstdout is not present

plugins/impstats/impstats.c, runtime/modules.c, runtime/modules.h, tests/Makefile.am, tests/diag.sh, tests/impstats-hup.sh, tools/rsyslogd.c
If the parameter "log.file" is specified, impstats writes its own
log file. However, HUP is not handled for this file, which makes
the functionality unusable with log rotation. It is also counter-
intuitive for users.
This patch enables correct HUP processing. As a sideline, it also
introduces a generic HUP processing framework for non-action type
of loadable modules.
closes https://github.com/rsyslog/rsyslog/issues/1662
closes https://github.com/rsyslog/rsyslog/issues/1663
=> impstats bugfix: impstats does not handle HUP

runtime/netstrm.c, tools/omfwd.c
In many cases, no error message were emitted when omfwd
went into action suspension, which was confusing for end
users. This patch enables explicit error messages in all
those cases.
closes https://github.com/rsyslog/rsyslog/issues/782
=> omfwd: always give reason for suspension

tools/omfwd.c
omfwd reads compression level from config but deflateInit has hardcoded level 9
=> omfwd: Use compression level from config

plugins/imfile/imfile.c, tests/Makefile.am, tests/imfile-wildcards-dirs-multi2.sh, tests/testsuites/imfile-wildcards-dirs-multi2.conf
Wildcards mode was not properly detected when wildcards
were only used in a directory name on startup.
This caused imfile not to create a propper dynamic filewatch.
Closes: https://github.com/rsyslog/rsyslog/issues/1672
=> imfile: Fixed wildcard detection issue on path wildcards

plugins/omelasticsearch/omelasticsearch.c
For http(s), CURLOPT_NOBODY makes libcurl do a HEAD request.
this procudes a "HTTP/1.1 404 Not Found" instead of an expected
"HTTP/1.1 200 OK".
see https://curl.haxx.se/libcurl/c/CURLOPT_NOBODY.html
remove this option to produce a GET request
Fixes: issue #1546
=> omelasticsearch: avoid 404 during health check

plugins/omelasticsearch/omelasticsearch.c
ES5 is generating warnings when sending json without the proper header:
$ curl -i -H "Content-Type: text/json" -XGET 'http://elasticsearch5:9200/' -d '{}\n'
HTTP/1.1 200 OK
Warning: 299 Elasticsearch-5.4.3-eed30a8 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Wed, 26 Jul 2017 14:33:28 GMT"
no issue on previous version.
this patch correctly sets the header as application/json. It works for all versions (tested on ES2 and ES5)
we also handle the bulkmode where it should be set to application/x-ndjson
Fixes: #1642
=> omelasticsearch: avoid ES5 warnings while sending json

plugins/omelasticsearch/omelasticsearch.c
since we switched to libfastjson, the default error function is
duplicating the string from fjson_object_to_json_string in order to free
the fjson object.
we however don't free the duplicated string later.
fix that by adding a free
also add a second duplication for the second case of rendered string;
this makes the code easier to read instead of adding another condition.
Fixes: issue #1668
=> omelasticsearch: fixing leak while writing error file

plugins/imrelp/imrelp.c, plugins/omrelp/omrelp.c, runtime/debug.c, runtime/debug.h, runtime/glbl.c, runtime/glbl.h, runtime/rsyslog.h, tools/rscryutil.c
add parameters to configure debug-output to only be shown if it is generated by specific files.
=> add debug.file and debug.whitelist parameters

plugins/omuxsock/omuxsock.c
fixed a bug causing incorrect debug output. Thanks
to etainativ for the fix-suggestion.
Also removed an incorrect comment (copy-paste error).
for the bug itself, see https://github.com/rsyslog/rsyslog/issues/1708
=> omuxsock: Fix error reporting and remove incorrect comment

plugins/imptcp/imptcp.c
Remove the 'pThis->' from the second argument to STATSCOUNTER_INC macro.
This only affects architectures without atomic uint64 actions, like aarch64.
Others do not use the mut argument, and it gets compiled out.
Resolves issue #1719.  Thank you @Hoshpak for reporting.
=> correct mutex arg in imptcp

runtime/wtp.c
The testbench got some occasionally failing tests. Review of
them brought up the idea that there is a race during worker
threat termination. Further investigation showed that this
might be a long-standing issue, but so far did not really
surface as the timing was almost always correct. However,
with the new functionality to emit a message on worker
shutdown (v8.29), the timing got more complex and now this
seemed to occasionally surface.
closes #1754
=> core bugfix: race on worker thread termination

action.c
It's helpful to know the module name when suspending as well as when resuming.
=> Also report module name when suspending action

plugins/imdiag/imdiag.c, plugins/imtcp/imtcp.c, runtime/netstrm.c, runtime/netstrm.h, runtime/nsd.h, runtime/nsd_gtls.c, runtime/nsd_ptcp.c, runtime/strmsrv.c, runtime/strmsrv.h, runtime/tcpsrv.c, runtime/tcpsrv.h
Most importantly, output os error messages on API failures.
Among others, this improves error messages in imtcp.
closes https://github.com/rsyslog/rsyslog/issues/1749
=> tcpsrv subsystem: better error messages

plugins/omelasticsearch/omelasticsearch.c
my original patch attented to fix an deprecation warnings while sending
json related to content type.
I however wanted to improve my commit and support the mentioned x-ndjson
content type in case of bulk mode.
see
https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-bulk.html
However, firstly my patch was wrong, since, in bulk mode, the x-ndjson was
set even for connection checks. Secondly I discovered that ES community
kind of disagree of what is the correct behavior:
in RFC 6648 the x- prefix is already decided as "deprecated"
see https://github.com/elastic/elasticsearch/issues/25718
So I decided to put only application/json as content type; it is
supported for both simple request or bulk requests containing multiple
json. We can improve it when there is a final decision …
=> omelasticsearch: avoid ES5 warnings while sending json in bulkmode

tools/omfwd.c
when omfwd is used with the $streamdriverpermittedpeers legacy
parameter, a memory corruption can occur. This depends on the
length of the provided strings and probably the malloc subsystem.
Once config parsing succeeds, no problem can happen.
Thanks to github user bwdoll for analyzing this bug and providing
a suggested fix (which is almost what this commit includes).
closes https://github.com/rsyslog/rsyslog/issues/1474
=> core: memory corruption during configuration parsing

runtime/stream.c, tests/diag.sh
when a queue was restarted from disk file, it almost always
emitted a message claiming
"file opened for non-append write, but already contains xxx bytes"
This message was wrong and did not indicate a real error condition.
The predicate check was incorrect.
closes https://github.com/rsyslog/rsyslog/issues/170 (kind of)
=> queue bugfix: file write error message was incorrect

configure.ac, plugins/imjournal/imjournal.c
persistent journal switch.
This addresses a point raised in #1747
=> enabling falback to older systemd version without restart-less

runtime/rsyslog.h, tools/omfwd.c
When a message larger than supported by the UDP stack is to be sent,
EMSGSIZE is returned, but not specifically handled. That in turn
will lead to action suspension. However, this does not make sense
because messages over the UDP max message size simply cannot be sent.
This patch truncates the message in question and reports an error
message with the condition.
closes https://github.com/rsyslog/rsyslog/issues/1654
=> omfwd bugfix: UDP oversize message not properly handled

tools/rsyslogd.c
Note that the segfault can occur only during early startup. Once
rsyslog has started, everything works reliably.
closes https://github.com/rsyslog/rsyslog/issues/1783
=> bugfix: rsyslog aborts if errmsg is generated in early startup

tests/Makefile.am
This commit fixes a regression caused by commit 835e645b73babf1290b691ef2ef137da206f6eff
and will restore the removed if nesting necessary to run *mmnormalize* tests
only when *mmnormalize* module was actually enabled.
Bug: https://bugs.gentoo.org/631246
=> testbench: Run mmnormalize tests only when mmnormalize module was actually enabled

runtime/nsd_gtls.c, tests/tls_error_file_not_found.sh
When a certificate can not be read the error message now contains
more information about what went wrong when trying to read the file.
=> TLS errmsg more specific when file can not be read

plugins/imptcp/imptcp.c
I don't see in which case it could be useful to compare a pointer
a \0 char since we are already comparing it to NULL value just before
imptcp.c: In function ‘addInstance’:
imptcp.c:1519:35: warning: comparison between pointer and zero character constant [-Wpointer-compare]
if((pNewVal == NULL) || (pNewVal == '\0')) {
^~
imptcp.c:1519:27: note: did you mean to dereference the pointer?
if((pNewVal == NULL) || (pNewVal == '\0')) {
^
=> imptcp: simplify parsing in bind port

plugins/imptcp/imptcp.c
The port MUST be given in the legacy statement, so it makes no
sense to accept the statement without it.
see also https://github.com/rsyslog/rsyslog/pull/1799
=> imptcp: fix handling of missing port in legacy conf statement

tools/iminternal.c
There was a race in iminternalAddMsg(), where the mutex is
released and after that the passed message object is accessed.
If the mainloop iterates in between, the msg may have already
been deleted by this time, resulting in a segfault.
Most importantly, there is no need to release the mutex lock
early, as suggested by current code. Inside mainloop the mutex
is acquired when it is time to do so, so at worst we'll have a
very slight wait there (which really does not matter at all).
This only happens if a large number of internal messages are emitted.
closes https://github.com/rsyslog/rsyslog/issues/1828
=> core/ratelimit bugfix: race can lead to segfault

ChangeLog, configure.ac, runtime/glbl.c, tests/diag.sh, tests/solaris/prep-libfastjson.sh, tests/testsuites/json_var_case.conf, tests/travis/install.sh, tools/rsyslogd.c
**NOTE:** *This requires libfastjson 0.99.7, a new version. CI testing will fail as long as the new version is not yet installed on the machines in question. This will probably be the case for at least some days. It is suggested to merge this PR late and after the new libfastjson release.*
The variable system inside rsyslog is JSON based (for easy consumption
of JSON input, the prime source of structured data). In JSON, keys
("variable names") are case-sensitive. This causes constant problems
inside rsyslog configurations. A major nit is that case-insensitivity
option inside templates (even if turned on) does not work with JSON
keys because they of inner workings*1.
It is much more natural to treat keys in a case-INsensitive way (e.g.
"$!Key" and "$!key" are the same). We do not expect …
=> handle (JSON) variables in case-insensitive way

plugins/imtcp/imtcp.c
Valid value 0 was not permitted as config value.
closes https://github.com/rsyslog/rsyslog/issues/1850
=> imtcp: fix "streamdriver.mode" parameter

tests/travis/install.sh
this was needed while libfastjson 0.99.7 was not released
We just uncomment it so that the override can be easily re-enabled
the next time a similar need arises (what routinely happens)
closes https://github.com/rsyslog/rsyslog/issues/1848
=> travis: remove temporary package override

plugins/imgssapi/imgssapi.c
Commit 5c5a7a3ed509dfb39b451c806646ab67782f6eda introduced an additional parameter "oserr".
Fixes: https://github.com/rsyslog/rsyslog/issues/1838
=> imgssapi: Incooperate changes from tcpsrv subsystem

plugins/mmanon/mmanon.c
mmanon.c:454:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
if(cyc == 0) {
^
mmanon.c:458:3: note: here
default:
^~~~~~~
=> mmanon: fix fall through warning

runtime/queue.c, runtime/queue.h, runtime/rsconf.c, runtime/ruleset.c, tests/Makefile.am, tests/nested-call-shutdown.sh
when rulesets are nested a segfault can occur when shutting down
rsyslog. the reason is that rule sets are destructed in load order,
which means a "later" ruleset may still be active when an "earlier"
one was already destructed. In these cases, a "call" can invalidly
call into the earlier ruleset, which is destructed and so leads to
invalid memory access. If a segfault actually happens depends on the
OS, but it is highly probable.
The cure is to split the queue shutdown sequence. In a first step,
all worker threads are terminated and the queue set to enqOnly.
While some are terminated, it is still possible that the others
enqueue messages into the queue (which are then just placed into the
queue, not processed). After this happens, a call can no longer
be issued (as there are no more …
=> core bugfix: potential segfault when shutting down rsyslog

tests/Makefile.am, tools/omfile.c
For a while, this lead to suspension as the data error was
not detected by the rule engine. This has changed with fixes
in 8.30.0. I asked users what they prefer (and expect) and
everyone meant it should still be handled via suspension. See
github tracker below for more details.
closes https://github.com/rsyslog/rsyslog/issues/1832
=> omfile: hande file open error via SUSPEND mode

grammar/rainerscript.c, plugins/imfile/imfile.c, plugins/imrelp/imrelp.c, plugins/mmanon/mmanon.c, runtime/rsyslog.h
We add a macro to provide better cross-platform compatibility.
We also intend to do this for other attribues as well.
see also: https://github.com/rsyslog/rsyslog/pull/1798
Note that other PRs will follow to add the new macro where necessary. I just want to get the testbench env going first.
closes https://github.com/rsyslog/rsyslog/issues/1861
=> build: add macro to support new FALLTHROUGH checks in gcc7

runtime/rsyslog.h, threads.c
this in almost all cases indicates a real problem that the user
should be made aware of
=> core: emit error message on abnormal input thread termination

plugins/mmpstrucdata/mmpstrucdata.c
This was invalidly formatted as '"'. Thanks to github user
wu3396 for the error report including the patch idea.
closes https://github.com/rsyslog/rsyslog/issues/1826
=> mmpstrucdata bugfix: formatting error of ']' char

contrib/mmcount/mmcount.c
closes https://github.com/rsyslog/rsyslog/issues/1790
=> mmcount: fix compiler warning

contrib/imczmq/imczmq.c, plugins/imptcp/imptcp.c, runtime/libgcry.c, runtime/lookup.c, runtime/net.c, runtime/net.h, runtime/nsd_gtls.c, runtime/prop.h, runtime/rsyslog.h, runtime/tcpsrv.c, template.c, tests/CI/clang-analyzer-build.sh
This enables a consistent static analyzer run on the buildbot env, including the ability to obtain in-depth error report. It also fixes a couple of issues found by the analyzer.
=> CI: add script to run static analyzer

plugins/imjournal/imjournal.c
The open function was broken by commit 92ac801, resulting in
no data being ever read from the journal.
patch bases on the idea of Radovan Sroka given here:
https://github.com/rsyslog/rsyslog/issues/1895#issuecomment-339017357
but follows the current imjournal-paradigm of having the journal
handle inside a global variable.
see also https://github.com/rsyslog/rsyslog/issues/1895
closes https://github.com/rsyslog/rsyslog/issues/1897
=> imjournal bugfix: module did not work at all

plugins/imudp/imudp.c, tests/imudp_error_msg.sh
When udp listener could not be created, an error message containing the ip-address and port is put out.
closes https://github.com/rsyslog/rsyslog/issues/1899
=> imudp: add error msg when listener wasn't created

runtime/msg.c, runtime/statsobj.c, tools/omfwd.c
due to missing unlock. This could only occur if pstats was set to
CEE-format logging (very uncommon) AND if the system runs out of
memory (in which case other things go pretty bad as well).
found by Coverty scan
=> fixes for issues found by coverty scan

runtime/msg.c, runtime/stringbuf.c
Detected by Coverty scan, can only happen when we run out of
memory, in which case we have a very big problem anyhow.
Double free could happen in lower layer when a property was
freed due to realloc failure. Solution is to continue to use
old value, which also makes sense otherwise.
=> core: double free under OOM condition (extremely unlikely)

runtime/lookup.c
lookup table could loop if error in lookupDoStub() occurs
also fixes coverty scan CID 185315 (IDENTICAL_BRANCHES due to
CHKiRet() immediately followed by finalize_it)
=> lookup table bugfix:  potential infinite loop

runtime/glbl.c
This happens if there is a problem with the timezone parameters.
Affects only startup, once started, no problem exists.
Detected by Coverty scan; CID 185414
=> core: potential NULL pointer dereference in config parsing

runtime/libgcry.c
If files are encrypted via the libgcry crypto provider, file handles
with numerical values 0 obtained by the crypto provider are never
closed. This is extremely unlikely to happen, as file handle 0
is (almost) every time already persistently open when the code
in question is reached.
Detected by Coverty scan, CID 185411.
=> core: fix potential file handle leak

tools/omfwd.c
could only happen if namespaces were used
Detected by Coverty scan, CID 185442.
=> omfwd bugfix: ressource leak if namespace could not be set

plugins/omelasticsearch/omelasticsearch.c
omelasticsearch made libcurl output messages to stdout. This
commit fixes that. It also automatically enables libcurl verbose
mode during debug runs - it needs to be seen if this is smart or
not (previously, code needed to be commented in).
closes https://github.com/rsyslog/rsyslog/issues/1909
=> omelasticsearch bugfix: output from libcurl to stdout

runtime/statsobj.c
This removes what Coverity scan correctly identified as unnecessary.
However, it might have been there to prevent a clang static analyzer
false positive, so we check if this causes issues and merge only
if not. I keep this note in any case because it later might become
important info.
CID 185313
=> cosmetic: remove unnecessary cleanup detected by Coverity Scan

runtime/stream.c
this tries to fix a potential false positive in Coverity scan. If this does
not work out, we need to explicitely set it to false positive.
CID 185330
=> cosmetic: ensure strmOpenFile() has opened file when returning RS_RET_OK

plugins/omstdout/omstdout.c
The overrung occurs in code for testing an interface that currently
does not exists, so the overrun can actually never happen. We fixed
it anyhow to keep Coverity scan clean of defects.
Note also that omstdout is a testbench tool not intended for
production.
Detected by Coverity scan, CID 185325
=> omstdout: fix theoretical buffer overrun

tools/rscryutil.c
could only happen if file handle 0 was returned, what actuallyy
could not happen, as stdin is kept open by this command line tool.
Still fixing it to get rid of Coverity scan diagnostic.
Detected by Coverity scan, CID 185323
=> rscryutil: fix theroretical file handle leak

plugins/omtesting/omtesting.c
If it doesn't work out, we'll disable it via the user interface
=> omtesting: another try at silencing Coverity scan

plugins/omprog/omprog.c, runtime/msg.c
Root of variable tree is accessed prior to locking access to it.
This introduces a race that may result in various kinds of
misadressing.
Found while reviewing code, no bug report exists.
=> core/msg: potential race in variable handling

contrib/imczmq/imczmq.c
Fix a SIGSEGV in a call to
371: zcert_destroy(&serverCert) called from rcvData().
- remove serverCert as it is only used uninitialized in a call
to zcert_destroy() - this causes a core dump at rsyslogd exit.
- also initialize authActor at definition.
Signed-off-by: Nachiketa Prachanda <nachiketa.prachanda@att.com>
=> imczmq: remove unallocated and unused pointer

runtime/msg.c, tests/check-length-json-property.sh
When no variables exist and a variable with at least one variable in its path was used, then rsyslog was searching for that non existant variable
Rsyslog now aborts it when no variables exist.
closes https://github.com/rsyslog/rsyslog/issues/1920
=> Segfault when variable path consists of variables

runtime/net.c
This is a small static leak that happens during config reading. At
most one leak for each configured but invalid allowed sender.
Detectec by Coverity scan, CID 185378
=> core/net: potential memory leak when adding AllowedSenders

runtime/ruleset.c
while the issue is valid, this was not a bug but rather a
safeguard. Doing it slightly differntly this time.
CID 185393
=> ruleset: "fix" coverity scan issue

runtime/stream.c
We ensure that the previous line segment is always valid... actually this
was already done with existing code, but Coverity scan did not detect this.
Maybe we now get a control flow issue because we do what already happened
in this case...
CID 185423
=> file stream handler: ensure multiline read is kept valid

plugins/imdiag/imdiag.c, runtime/atomic.h, runtime/queue.c
This is not a real problem because imdiag intentionally does multiple
tries to validate predicate validity. However, this is reported in
clang thread sanitizer and so we need to fix it.
=> imdiag: fix cosmetic race in termination processing

runtime/tcpsrv.c
small leak, can theoretically occur during rsyslog startup; will not
grow afterwards. Prime trigger would be out of process memory, which is
fatal in any case if it already occurs on startup.
Deteced by Coverity scan, CID 185322
=> tcpsrv: fix potential memory leak on startup

plugins/imkafka/imkafka.c, plugins/omkafka/omkafka.c
CID 185720, 185719 fixed by correcting expression check for MsgFile handle.
CID 185723 fixed by removing CHKiRET
CID 185722 added additional check (stat) for MsgFile before unlink
Fixed 2 clang issues in imkafka as well
=> kafka: fixed multiple coverity scan issues

runtime/tcpsrv.c
During shutdown of a tcpsrv, a race could occur, resulting in
a hang on shutdown of rsyslog as whole.
Detected via valgrind's helgrind thread debugger.
=> core/tcpsrv: fix potential hang on shutdown

ChangeLog, runtime/queue.c
more or less cosmetic, but pollutes thread debuggers
=> core/queue: fix potential race during shutdown

contrib/mmgrok/README
Needs libfastjson, would segfault if build with json-c. Probably not updated since this changed.
=> mmgrok: fix readme

plugins/mmanon/mmanon.c
only happened if system was already out of memory.
detected by coverity scan (cid: 185735)
=> mmanon: fix potential memory leak

template.c
could happen if the config was loaded and the parameters could not
properly be processed. If so, this occured only during the startup
phase.
Detected by Coverity scan, CID 185318
=> core/template bugfis: potential NULL pointer access at config load

action.c, plugins/omelasticsearch/omelasticsearch.c, runtime/obj-types.h, tests/Makefile.am, tests/es-basic-bulk-vg.sh, tests/es-basic-ha-vg.sh, tests/es-basic-vg.sh
Depending on the state of unavailability (libcurl return code),
omelasticsearch tries to process a NULL return message, what
leads to a segfault.
This fixes the problem and introduces better error handling and
better error messages.
closes https://github.com/rsyslog/rsyslog/issues/1885
=> omelasticsearch bugfix: abort on unavailable ES server

plugins/imdiag/imdiag.c
data type was not correctly re-cast after atomic operation
Also added a couple of code attributes to aid compiler finding bugs.
Detected by Coverity scan, CID 185416
=> imdiag: blocking pstats did not always work correctly

tests/travis/run.sh
For historic reasons, it only processed part of the files, what no longer
is necessary (buildbot already covers everything).
closes https://github.com/rsyslog/rsyslog/issues/2005
=> travis: run clang static analyzer over ALL files

plugins/omkafka/omkafka.c
Code used a suboptimal command sequence. Refactored this and also
cleaned up things a bit.
Detected by Coverity scan, CID 185722
=> omkafka: refactor deletion of failed message file

runtime/queue.c
If the queue parameters were incorrectly given, a NULL pointer derefernce
could happen during config parsing. Once post that stage, no problem could
occur.
Detected by Coverity scan, CID 185339
=> queue subsystem: fix NULL pointer dereference during config processing

plugins/omkafka/omkafka.c
These are not even recognized when used and leads to a config startup error message:
* closeTimeout
* reopenOnHup
* resubmitOnFailure
* keepFailedMessages
* failedMsgFile
Reason was invalid use of upper case in config param block.
fixes https://github.com/rsyslog/rsyslog/issues/2052
=> omkafka bufgix: various config parameters did not work

runtime/stream.c
Detected by Coverity scan, CID 185349
=> core/file stream: do not silently ignore error condition

plugins/mmexternal/mmexternal.c
We hope to get past the false positive by pretending we store the
values for reuse (what never can happen, but that's the sole point
of this function...).
=> "fix" Coverity false positive CID 185363

runtime/net.c
... and also solve a socket leak that pre-8.31 occurred when the option
was enabled.
Special thanks to github user amg1127 who analysed the situation and
actually provided the original patch for the issue. Unfortunately, the
existing code base was really bad, and so I needed to do some refactoring
first. My patch here is modelled exactly after amg1127's patch, but
bases on the refactoring.
Full credits for the patch belong to amg1127.
see also https://github.com/rsyslog/rsyslog/pull/2049
closes https://github.com/rsyslog/rsyslog/issues/2040
=> udp socket creation: make IPFREEBIND work

runtime/msg.c
note: this is a non-fixable situation, but we now at least let the
user know
Detected by Coverity scan, CID 185366
=> msg handling: emit error message if ruleset cannot be assigned to msg

tests/tcpflood.c
When TLS certificates are specified but TLS is NOT enabled
tcpflood now exits with an error message.
This was decided as useful in https://github.com/rsyslog/rsyslog/issues/1776
=> tcpflood: add err when parameter -Ttls is missing

runtime/srutils.c
Add mutex for attempting to create parent directories of a log file. https://github.com/rsyslog/rsyslog/issues/2107
=> error during config processing: omfile: creating parent directories for file  'File exists'

tests/dynstats_prevent_premature_eviction.sh, tests/dynstats_reset-vg.sh, tests/dynstats_reset.sh, tests/testsuites/dynstats_reset.conf
Increases tolerance from 1 second to 3 seconds for eviction test (it was 2 seconds unused-ttl with 1 second delay, now its 4 second ttl with 1 second delay, so total 3 seconds of tolerance).
=> Relax time constraints for dynstats elapsed-time dependent tests

runtime/srUtils.h, runtime/srutils.c
PR #2109 provides a solution for a race in directory creation (if a file
is to be written to a new path). There is a small weakness in that patch
in that it introduces a (very unlikely) potential hang condition during
shutdown.
see also https://github.com/rsyslog/rsyslog/pull/2109
=> fix cancel cleanup handler in directory tree creation code

configure.ac
and fail if it cannot be found. This is needed to ensure that builds
for platforms that actually need it succeed.
see also https://github.com/rsyslog/rsyslog/issues/2134
=> build system: add capability to required libsystemd

plugins/imuxsock/imuxsock.c
Unless I misunderstand, the comment contains a reference to a different module than this one (perhaps a bad copy/paste/modify operation). I noticed this while reviewing the code in an attempt to better understand the purpose of the sysSock.Use and sysSock.Name parameters (rsyslog/rsyslog-doc#397).
=> Fix module name in pInputName comment

grammar/rainerscript.c, tests/Makefile.am, tests/rscript_trim-vg.sh
fix a bug causing a crash if rtrim or ltrim were called
with a string containing a blank and one single different character.
closes https://github.com/rsyslog/rsyslog/issues/2127
=> rainerscript: bugfix

plugins/imkafka/imkafka.c, tests/sndrcv_kafka-vg-rcvr.sh
When rkmessage->err was set, rkmessage was not proberly destroyed with
rd_kafka_message_destroy.
Closes https://github.com/edenhill/librdkafka/issues/1536
=> imkafka: Fixed memory leak in msgConsume

runtime/dnscache.c
Description of problem:
It looks like that a hash key which is used to find out already cached dns entry gets incorrectly computed from the whole sockaddr_storage (sockaddr_in/sockaddr_in6) structure including a sin_port (which doesn't have a static value) instead of only an address, thus creating redundant dns cache entries/consuming more space.
How reproducible:
Always.
Steps to Reproduce:
1. Build rsyslog (you have to have CFLAGS containing '-O0 -g' so the follow up gdb script works properly):
~~~
~~~
2. Add below into the /etc/rsyslog.conf:
~~~
$ModLoad imudp
$UDPServerRun 514
~~~
3. Run rsylogd:
~~~
~~~
4. Make sure you have gdb & nc utility installed (needed by the below script)
5. Save the below gdb script as rsyslog-gdb-script.txt:
~~~
#set print pretty on
set print elements 4096 …
=> cache sin_addr instead of the whole sockaddr structure

runtime/libgcry.c
Under an out-of-memory condition when memory alloc fails a NULL
pointer was accessed. Note that this only happens if the system (process)
is totally out of memory.
=> file encryption subsystem: fix potential NULL pointer access

grammar/rainerscript.c, grammar/rainerscript.h, runtime/ruleset.c, runtime/wti.c, runtime/wti.h, tests/Makefile.am, tests/rscript_script_error.sh
This permits script functions that could fail to report errors back, so
that the user can handle them if desired. We use an errno-style of
interface. That means script_error() needs to be called after functions
that supports it. It will return either 0 (all OK) or something else
(an error condition).
@mrworkman The commit also modifies the ```parse_time()``` function to use the new
interface. First of all, this is useful for users, and secondly we
needed a capability to craft a testbench test.
closes https://github.com/rsyslog/rsyslog/issues/1978
=> RainerScript: add function script_error() and error-reporting support

plugins/imudp/imudp.c
The rate-limiter inside imudp was not set to be thread safe, but was
used across multiple threads. This worked in default configuration,
but failed when RepeatedMsgReduction was set to "on".
Note that it in general is a bug to use a rate-limiter in
non-threadsafe mode across multiple threads. This also causes invalid
rate limiting counts in the default case.
closes https://github.com/rsyslog/rsyslog/issues/441
fixes https://github.com/rsyslog/rsyslog/issues/2132
=> imudp bugfix: potential segfault in ratelimiting

.travis.yml, configure.ac, tests/Makefile.am, tests/travis/run.sh
This is necessary as we hit the Travis max runtime limit per VM,
so we need to duplicate the tests. This is done via
--enable-testbench1 and --enable-testbench2 which we than use
in different VMs.
This PR also includes updates to the Travis scripts so that we
use the new capability. We have only duplicated Travis VMs where
acutally necessary -- we may need to do more of this in the future.
closes https://github.com/rsyslog/rsyslog/issues/2196
=> testbench: provide capability to split testbench

configure.ac, tests/Makefile.am, tests/imuxsock_traillf.sh, tests/imuxsock_traillf_syssock.sh
Root permissions are uncommon in the CI environmen (requires very special
setup). Test skip if run under non-root, but that pollutes the
testbench result. So the default now is not to do that. The can still be
activated via --enable-root-tests configure switch.
closes https://github.com/rsyslog/rsyslog/issues/2192
=> testbench: do not run tests that require root permissions by default

tests/diag.sh
previous timeout caused very long runtime in cases where rsyslog
segfaulted on startup, which made the testbench failure harder to
diagnose than necessary.
=> testbench: reduce startup timeout for tests

tests/Makefile.am, tests/pmrfc3164-json.sh, tools/pmrfc3164.c
headerless is indicated by whitespace followed by either '{' or '['.
This follows the trend to send JSON messages via syslog without any
header. We use default header values in this case.
This right now is a bit experimental; we may roll it back if
problems show up in practice.
closes https://github.com/rsyslog/rsyslog/issues/2030
=> pmrfc3164: try to detected headerless message

configure.ac, runtime/debug.c, runtime/debug.h
The --enable-rtinst configure switch and associated instrumentation
code dates back to the time pre-(valgrind, address sanitizer, ...).
It has not been actively used by rsyslog developers for years and is
inferior to the new debugging tools.
With this commit, we remove the --enable-rtinst option and do some
mild refactoring of the code itself. As it turned out, fully removing
the debug code requires a bit more of time, and we push this as a
follow-on activity. It's not as urgent as getting us to build
properly under all configure switches.
closes https://github.com/rsyslog/rsyslog/issues/2048
=> cleanup: remove unused runtime instrumentation code

plugins/ommongodb/ommongodb.c, tools/logctl.c
this is fixed in newer versions of libbson, but we do not
want to force using the newer ones just because of this issue.
=> work-around libbson compiler warning

tools/pmrfc3164.c
regression from yesterday's commit, deteced by Coverity Scan,
CID 186292
=> pmrfc3164: fix invalid whitespace-skip

plugins/imrelp/imrelp.c, tools/rsyslogd.c
Can be useful during debugging.
closes https://github.com/rsyslog/rsyslog/issues/2215
=> debug system: output global and imrelp (listener) max message size

plugins/imptcp/imptcp.c
CI testing seems to indicate that we sometimes do not get valid
data, but so far we could not reliably reproduce this. This commit
introduces an additional check which emits an error message in
that case. The hope is that we will see it on further occasions or
get some reports. If that really happens, we should handle it.
=> imptcp: check if we really got a remote addr on connect

configure.ac, tests/Makefile.am
Unfortunately, libfaketime becomes more and more problematic in newer
versions and causes aborts on some platforms. This provides the ability
to turn it off via --disable-libfaketime.
In the longer term, we should consider writing our own replacement.
=> testbench: add a capability to turn off libfaketime tests via configure

threads.c
This fixes a potential race that valgrind's helgrind found on some
very few occasions, and right now only on CentOS 7. However, it
looks like the variable was actually not correctly protected.
see also https://github.com/rsyslog/rsyslog/issues/2012
=> core: fix potential race

tests/Makefile.am
some tests requiring faketime were executed even when this was
disabled
=> testbench: fix new --enable-libfaketime configure option

tests/rscript_format_time.sh
FreeBSD's `cmp` program does not read from STDIN.
=> Fix test so it will run on FreeBSD.

runtime/wti.h
I consider the C99 semantics to be pretty broken. Rather than
duplicating code for the inline variant and the non-inline one,
I replace the functions in question by macros. We do not loose
much in terms of type-safety.
see also https://github.com/rsyslog/rsyslog/pull/2246
=> core: replace some inline functions by macros

plugins/mmdblookup/mmdblookup.c
Many thanks to Will Storey (github user @horgh) for mentioning this and
his phantastic help in debugging this rsyslog problem!
=> mmdblookup: replace thread-unsafe strtok() by thread-safe counterpart

runtime/syslogd-types.h
it just permitted 200 chars, with almost all systems permitting for
more. I tried to find a more portable way to find out the actual max,
but this turned out horrible. The next solution would have been to use
dynamic alloc, but that often is overkill. So I now settle to just
increasing the value to 4KiB. This is the Linux limit, and it is by
far the highest I could find. This should be good to go for quite
some while but should not put too much stressure on the stack alloc.
closes https://github.com/rsyslog/rsyslog/issues/2228
=> core bugfix: MAXFNAME was set too low

plugins/imklog/imklog.c
This is now taken from the global localHostIP setting, which is used
consistent accross all modules.
Also, the removed (2012?) directive $klogLocalIPIF has been added
again but directly marked as removed. That way, an informative error
message is generated if someone tries to use it.
closes https://github.com/rsyslog/rsyslog/issues/2276
=> imklog: local host IP was hardcoded to 127.0.0.1

runtime/glbl.c
This was still available, but had no effect (for ~10 years or so). The
plumbing is now removed. If someone tries to use the option, an
error message is generated.
closes https://github.com/rsyslog/rsyslog/issues/2280
=> core/glbl: remove long-unused option $optimizeforuniprocessor

plugins/omkafka/omkafka.c
The failed message list is improperly cleaned. This is a regression
from recent commit 4eae19e089b5a83da679fe29398c6b2c10003793, which
was introduced in 8.31.0.
This problem is more likely to happen under heavy load or bad
connectivity, when the local librdkafka queue overruns or message
delivery times out.
closes https://github.com/rsyslog/rsyslog/issues/2184
closes https://github.com/rsyslog/rsyslog/issues/2067
=> omkafka bugfix: potential misadressing

KNOWN_ISSUES
closes https://github.com/rsyslog/rsyslog/issues/2099
=> testbench: document problems with libfaketime 0.99.7

runtime/lookup.c
bsearch is not permitted to be called with NULL ptr for array.
Detectedb by LLVM UBSan.
see also https://github.com/rsyslog/rsyslog/issues/2295
=> lookup tables: fix undefined behaviour

configure.ac
as omczmq does require v4 features
closes https://github.com/rsyslog/rsyslog/issues/872
=> build system: require libczmq 4.x

runtime/lookup.c, runtime/lookup.h
* uint32 underflow fixed in array-table
* lookup on empty table fixed for array and sparse-array tables
* some trailing whitespaces deleted
=> Fix lookup-table unsigned underflow in array-table lookup and empty-table handling across array and sparse-array tables

plugins/imptcp/imptcp.c
When notifyconnectionclose was on, a string buffer was accessed immediately
after it was freed (as part of the connection close operation). This commit
changes the order of operations to fix that.
Detected by LLVM ASAN.
=> imptcp bugfix: access to free'ed memory

tools/rsyslogd.8, tools/rsyslogd.c
Command line option -iNONE provides this capability. This utilizes the
pre-existing -i option, but uses the special name "NONE" to turn of the
pid file check feature. Turning off is useful for systems where this no
longer is needed (e.g. systemd based).
closes https://github.com/rsyslog/rsyslog/issues/2143
=> rsyslogd: add capability to specify that no pid file shall be written

ChangeLog, configure.ac
On Ubuntu 16, we do not have libczmq 4, but omczmq obviously builds
fine with 3.0.2, so this seems to be the actual requirement. If that
works, I'll settle for now as I am finally totally confused on what
happens here. I have asked for help from those in the know, but
if we do not get a definitive answer, it'll stay so that it works
for us -- after all this is a contributed module...
closes https://github.com/rsyslog/rsyslog/issues/872
=> omczmq: change minimum libczmq requirement again

tests/Makefile.am
... because we know they sometimes fail due to a confirmed bug
inside imfile. These need to be re-enabled once the bug is fixed.
see also https://github.com/rsyslog/rsyslog/issues/2271
=> testbench: TEMPORARILY disable tests to permit "normal" CI runs

action.c, action.h, runtime/wti.h
This internal state was improperly handled and most probably caused
(hard to see) issues when action instances were run on multiple worker
threads. It looks like the state variable was forgotten to move over
to worker state when action workers were introduced. This patch
fixes that.
closes https://github.com/rsyslog/rsyslog/issues/2046
=> action bugfix: bHadAutoCommit handled in thread-unsafe way

.travis.yml, tests/travis/install.sh, tests/travis/run.sh
LLVM has changed packaging structure, this fix adapts to it. So we
now have scan-build-5.0 again.
=> travis: reenable static analyzer

runtime/obj.c, runtime/obj.h, runtime/queue.c, tests/testsuites/threadingmq.conf
this helps to diagnose issue - unfortunately we need more
work to ensure that the messages always make it to the user. This
is a start and hopefully useful at least for the testbench, possibly
more.
=> core/queue: emit better status messages at rsyslog shutdown

runtime/queue.c, runtime/wti.c, runtime/wti.h, runtime/wtp.c, runtime/wtp.h
The last commit (yesterday) did not properly convey when we actually
needed to cancel a thread. This commit corrects this and also
provides better information on the actual cancel operation and
some tipps for the user on how to solve it (timeout mentioned).
=> core: improve queue status reporting on shutdown

plugins/impstats/impstats.c
some of the counters were stored in int-sized fields vs. intctr_t-sized
ones. This had undefined effects. Most often, everything worked fine
for values smaller than 2^31, sometimes we go negative values and at
least in theory this could also lead to invalid memory access. The
later however is extremely unlikely due to global memory layout. In
any case, the output could be invalid.
closes https://github.com/rsyslog/rsyslog/issues/1517
=> impstats: fix invalid counter definitions for getrusage() reporting

runtime/msg.c, runtime/stream.c, runtime/stringbuf.c, runtime/stringbuf.h, tests/diag.sh, tests/imfile-truncate-line.sh
**RIGHT NOW INCOMPLETE -- but need early access to CI system**
The currently done buffer modification (add of '\0') is bad, especially when
multiple threads access the same string. It is not really an issue that needs
to be urgently fixed, as always the same data is written. However, among others,
it will pollute the thread debugger and as such prevent more elaborate automatted
tests.
closes https://github.com/rsyslog/rsyslog/issues/1993
=> core/cstr: stringbuf.c: cstrGetSzStrNoNULL shall not modify buffer

plugins/omelasticsearch/omelasticsearch.c
At this time all jsons are writing to the error file without an eol. So it is not very continent to monitor, catch changes, observe and process this file.
=> omelasticsearch: add eol to every elastic response for error file

tools/rsyslogd.c
this is a regeresson from recent commit 159b37afc881, bug was never
released
=> core: pidfile was not deleted upon shutdown

tests/Makefile.am
this is known to fail due to known bug in imfile (which
will be worked on soon).
Thanks to whissi for mentioning this test.
see also https://github.com/rsyslog/rsyslog/issues/2325
=> testbench: temporarily disable another imfile tests

configure.ac
This is now required because 0.99.7 has a bug with pretty serious
consequences for rsyslog.
closes https://github.com/rsyslog/rsyslog/issues/1839
closes https://github.com/rsyslog/rsyslog/issues/2268
=> build system: enforce use of libfastjson 0.99.8

grammar/rainerscript.c
I was using 8.24.0 that came with RHEL 7.4 and tried to use the `ltrim()` function.  It simply returned the value `0`.  Turns out that `ltrim()` didn't exist in 8.24.0, and the warning about that is only printed with debug enabled.  This will now print messages like:
```
rsyslogd: error during parsing file /path/to/rsyslog.conf, on or before line 34: Invalid function ztrim [v8.32.0.master try http://www.rsyslog.com/e/2207 ]
```
*maintainer edit: auto-close existing issue on merge*
closes https://github.com/rsyslog/rsyslog/issues/2187
=> Report unknown function calls as parser errors

tests/diag.sh, tests/rscript_http_request-vg.sh, tests/rscript_http_request.sh
They may not be accessible because they (or parts of the
network) can be down or access is not permitted. In this
case, the affected tests skip themselves.
Special thanks to Thomas D. (Whissi) for providing the check
function.
closes https://github.com/rsyslog/rsyslog/issues/2339
=> testbench: check if external URLs can be accessed, skip if not

configure.ac
Else we get a make failure. With this patch, we bail out during
./configure time, which is easier to handle.
Note that a check for libgrok did not work and we did not want to
invest more time for this *contribute* module (aka non-official).
closes https://github.com/rsyslog/rsyslog/issues/871
=> build system: check for existance of req. header if mmgrok is enabled

plugins/im3195/im3195.c
... namely gcc 7 and clang 5. We do the most minimal change to
get to a clean build as this module AFAIK is not used by anyone
for quite some years now (RFC3195 is a total failure).
closes https://github.com/rsyslog/rsyslog/issues/2094
=> im3195: fix compile issues on modern compilers

tests/glbl_setenv.sh, tests/pmrfc3164-AtSignsInHostname.sh, tests/pmrfc3164-AtSignsInHostname_off.sh, tests/pmrfc3164-defaultTag.sh, tests/pmrfc3164-msgFirstSpace.sh, tests/pmrfc3164-tagEndingByColon.sh
These tests have command line tool incompatibilities which are
easy to solve. This doesn't fix all test's issues, but at least
we get some more on board.
=> testbench: enable more tests on BSD

action.c
regression from recent commit c1a601e72f779328994c6c344ef4e7576a57e5c3
Not present in any released code.
Detected by Coverity Scan, CID 186455
=> action: fix memory leak when errorfile capability is used

runtime/glbl.c, runtime/glbl.h, tools/rsyslogd.c
It can be useful to ctl-c out of rsyslog, even if it is started via
-n, especially inside containers.  The new config setting permits
to enable this capability.
closes https://github.com/rsyslog/rsyslog/issues/533
=> add global config setting shutdown.enable.ctl-c to enable ctl-c

tools/rsyslogd.c
This also sets the basis for other container-specific config changes
and other optimizations.
closes https://github.com/rsyslog/rsyslog/issues/2371
=> core: detect if runing in container, enable ctl-c if so

configure.ac, grammar/rainerscript.c, tests/Makefile.am
Please check "\n" in *grammar/rainerscript.c* before merge.
```C
LogError(0, RS_RET_INTERNAL_ERROR,
"rainerscript: internal error: HTTP_Fetch not supported, not built with libcurl support\n");
```
This PR will fix https://github.com/rsyslog/rsyslog/issues/2374
=> Fix build without libcurl

grammar/rainerscript.c, tests/rscript_replace_complex.sh, tests/testsuites/complex_replace_input, tests/testsuites/rscript_replace_complex.conf
there is a bug. To catch it just try to use config:
```
template(name="test" type="list") {
property(name="$!all-json")
}
ruleset(name="test") {
reset $!xxx=replace($msg, "==1234567890==", "=54321=");
action(type="omfile" file="tmp/aaa" template="test")
}
*.* call test
```
do two calls 
` logger "A==1234567890=="`
`logger "A==1234567890="`
and see results into `/tmp/aaa`
So I submit a PR to resolve this bug. I have auto-replacement of trailing spaces. Also I have decreased the amount of calculations a bit. And have renamed/added a couple variables to align their names with other.
=>  doFuncReplace(): add tail of src if tail is partially similar to 'replaceWith'

plugins/mmexternal/mmexternal.c, plugins/omprog/omprog.c, tools/rsyslogd.c, tools/syslogd.c
due to old-style header names -- now using the new ones, which are also
supported on the other platforms.
=> fix build warning on Alpine Linux

grammar/Makefile.am, plugins/omelasticsearch/Makefile.am
When using --disable-libcurl, libgrammar should not be linked against
libcurl unconditionally as CURL_LIBS might be set if one of the modules
using libcurl, like elasticsearch, is enabled.
See #2378
=> build system: Don't link core against libcurl if explicitly requested

tools/rsyslogd.c
This means we run inside a container and writing pid files is unnecessary
and bad practice in this case.
=> core: do not write pid file by default if running as pid 1

configure.ac
This was used nowhere. It most probably was a forgotten left-over
from an experiment.
closes https://github.com/rsyslog/rsyslog/issues/2386
=> build system: remove spurios xOS_LINUX definition

tests/Makefile.am, tests/omprog-feedback.sh, tests/testsuites/omprog-feedback-bin.sh, tests/testsuites/omprog-feedback.conf
A simple test for the feedback feature implemented in #1753, which didn't have any test yet. This test only checks the 'confirmMessages' flag without the use of transactions.
Note: This PR is based on #1992, but in contrast to that PR, this one is ready to merge. I will rewrite PR #1992 to restrict it to the problematic transaction-related cases.
=> omprog: added test for feedback feature (without using transactions)

tests/diag.sh, tests/omprog-cleanup-vg.sh, tests/omprog-cleanup-with-outfile.sh, tests/omprog-cleanup.sh, tests/omprog-noterm-cleanup-vg.sh, tests/omprog-noterm-cleanup.sh
this might have caused sporadic failures on platform where "lsof" was
missing.
see also https://github.com/rsyslog/rsyslog/issues/2403
=> testbench: ensure we have the necessary commands to execute test

.travis.yml
We now know it does not work, and will not fix it immediately. So
running it is just a waste of ressource.
[skip ci] - no changes other than travis config
=> travis: remove experimental build from build matrix

runtime/msg.c
this can lead to misadressing when the jsonmesg property is used.
closes https://github.com/rsyslog/rsyslog/issues/2396
=> core bugfix: string not properly terminated when RFC5424 MSGID is used

grammar/lexer.l, grammar/rainerscript.c, grammar/rainerscript.h, tests/Makefile.am, tests/rscript_backticks-vg.sh
We introduce strings enclosed in backticks, which is along the lines
of what the shell does. However, we currently only support
"echo $VARNAME" -- but this may be extended later on.
closes https://github.com/rsyslog/rsyslog/issues/2416
=> config: add ability to use environment variables for config params

rsyslog.service.in
systemd does not require a pid file to track the rsyslogd process.
By not writing a pid file, the rsyslog service can be locked down even
further as it no longer needs write access to /var/run.
=> Don't write pid file when running under systemd

grammar/grammar.y, grammar/lexer.l, grammar/parserif.h, grammar/rainerscript.c, grammar/rainerscript.h, runtime/rsconf.c, runtime/ruleset.c, tests/Makefile.am, tests/include-obj-in-if-vg.sh, tests/include-obj-outside-control-flow-vg.sh, tests/include-obj-text-from-file.sh, tests/include-obj-text-vg.sh, tests/testsuites/include-std-omfile-action.conf
This permits to include files (like legacy $IncludeConfig) via a
script object. Needless to say, the script object offers more
features:
- include files can now be
- required, with rsyslog aborting when not present
- required, with rsyslog emitting an error message but otherwise
continuing when not present
- optional, which means non-present include files will be
skipped without notice
This is controlled by the "mode" parameter.
- text can be included form e.g. an environment variable
--> ex: ```include(text=`echo $ENVVAR`)```
This finally really obsoletes $IncludeConfig.
closes https://github.com/rsyslog/rsyslog/issues/2151
=> config: add include() script object

tests/Makefile.am
This test is known to fail rather frequently. We disable it until
the root cause is solved, because otherwise CI does have too many
false positive failures.
see also https://github.com/rsyslog/rsyslog/issues/2434
=> testbench: temporarily disable sndrcv_kafka-vg-rcvr.sh test

tests/travis/run-alpine.sh
... as this brought us away from the abuild environment. Most importantly,
-Os was overriden by -O2, which did make a lot of warning go away.
=> testbench: do not override default Alpine CFLAGS

devtools/devcontainer.sh
this does not properly work when the script is used in
cron jobs
=> dev tools: do not use -ti in docker run

grammar/rainerscript.c
We missed the header include in commit d9475f133e3c79875a7c4ccd92038b7123c1f155.
See: https://github.com/rsyslog/rsyslog/issues/2374
Bug: https://bugs.gentoo.org/646262
=> Fix building with --disable-libcurl

runtime/lib_ksils12.c
There was a bug in lmsig_ksils12 code which rendered the dirOwner/dirGroup configuration vlaues useless. This patch solves the problem and the respective values will be used as intended. 
fixes #2446
=> BUGFIX, Issue 2446. Fix directory creation code in lmsig_ksils12 plugin

grammar/lexer.l
This rule was never applied, actually flex even complained about it.
It should not have been there in the first place. The match is actually
done right at the top of the <EXPR> block.
=> cleanup/config: remove redundant lexer rule

runtime/errmsg.h, runtime/lib_ksils12.c
see also https://github.com/rsyslog/rsyslog/pull/2450
=> lmsig_ksils12: emit error message if chown() to sig file fails

plugins/omstdout/omstdout.c, tests/Makefile.am, tests/omstdout-basic.sh
Omstdout can now be configured in the new style
and a parameter for the template was added.
closes https://github.com/rsyslog/rsyslog/issues/2376
=> omstdout: add new configuration format

runtime/glbl.c
the config system actually does not permit "-" inside parameter
names. This has now been changed to "shutdown.enable.ctlc".
closes https://github.com/rsyslog/rsyslog/issues/2482
=> fix global parameter name shutdown.enable.ctl-c

tests/Makefile.am
This commit fixes EXTRA_DIST list which was broken via commit
87f296fd2e667e95f38991a8a7caf84c3458e7c9.
In addition, this commit adds the missing testsuites/include-std-omfile-action.conf file
to EXTRA_DIST.
Fixes: https://github.com/rsyslog/rsyslog/issues/2493
=> tests/Makefile: Fix EXTRA_DIST and add testsuites/include-std-omfile-action.conf

tests/Makefile.am
we can split the testbench into two test runs in order to make each of them complete
quicker (this currently is required for Travis, but may also be useful for other
cases). Some test are run twice in this scenario, which is obviously counter-productive.
We ensure now that at least some longer-running database tests are only executed
once in this setup.
=> testbench: do not run some DB tests twice in split test runs

grammar/rainerscript.c, grammar/rainerscript.h
calling and identifying a script function now works via
a function pointer. Going forward, this will be used when
making loadable functions in rainerscript.
=> rscript: refactor to use function pointers for script functions

ChangeLog
Fix two instances of the wrong name.
closes rsyslog/rsyslog#2521
refs rsyslog/rsyslog-doc#614
=> Changelog: Fix config.enabled parameter name

.lgtm.yml
As discussed with @rgerhards: here is a configuration file to enable C/C++ analysis of rsyslog on lgtm.com. Full disclosure: I'm part of the team behind lgtm :smile: 
The build script contains three small patches to configure.ac, tools/rsyslogd.c, and runtime/glbl.c to enable building with an older version of libfastjson-dev. This shouldn't affect the analysis. The build environment on lgtm.com will be upgraded to Ubuntu 18.04 in the next couple of months, so hopefully this small hack won't be needed for long.
Lines 2-5 can also soon be removed from this file; we're looking into why that dependency wasn't detected automatically.
In other words: hopefully these build hints won't be needed any longer in a couple of months' time!
=> Add lgtm.yml configuration for analysis on lgtm.com

tools/omfile.c
This small PR fixes two error messages in omfile that had the wrong order of arguments.
=> omfile: Fix wrong order of arguments for errmsg

tests/Makefile.am
This patch fixes the list of TESTS, broken by a line without the backslash introduced in Commit 87f296fd2e667e95f38991a8a7caf84c3458e7c9.
=> tests/Makefile: Fix broken TESTS

tests/glbl-umask.sh
This patch improves the stability of `tests/glbl-umask.sh`, which now fails when running after `tests/rawmsg-after-pri.sh`, since the glob pattern `rsyslog.o*` matches `rsyslog.out.compare`, created by `rawmsg-after-pri.sh`.
=> tests/glbl-umask.sh: Improve test stability

tests/Makefile.am, tests/omprog-transactions-failed-commits.sh, tests/omprog-transactions-failed-messages.sh, tests/omprog-transactions.sh, tests/testsuites/omprog-transactions-bin.sh, tests/testsuites/omprog-transactions-failed-commits.conf, tests/testsuites/omprog-transactions-failed-messages.conf, tests/testsuites/omprog-transactions.conf
I have added two automated tests for the feedback feature introduced in #1753. They are still incomplete; consider this as work in progress. I have submitted the PR now because I'm stuck at two issues related to some behavior of the rsyslog core that I don't fully understand.
My doubts are related to how the rsyslog core handles transactions. I have marked them with two "TODO" marks in the code.
1) It seems that deferred messages (confirmed with RS_RET_DEFER_COMMIT) in a transaction are not retried if a later message in the transaction fails (with RS_RET_SUSPENDED). Please see the TODO in "omprog-transactions-feedback.sh". Is this the expected behavior?
2) If a commit fails (endTransaction returns a RS_RET_SUSPENDED), the next transaction hangs at the second message. The debug logs show …
=> omprog: added tests for transactions with feedback

tests/Makefile.am
these test are still instable and some concerns about their
validity at all have been raised. We now disable them to make
the testbench more reliable. Root cause needs to be investigated
and tests finally fixed or removed.
see also https://github.com/rsyslog/rsyslog/issues/2403
=> testbench: disable some racy omprog tests

tests/Makefile.am
So we permit CI to work well while we work on solving the issue.
see: https://github.com/rsyslog/rsyslog/issues/2564
=> testbench: disable imjournal tests temporarily due to issues

runtime/ratelimit.c, runtime/ratelimit.h
rsyslog uses unsigned short for configuration setting
SystemLogRateLimitBurst. Being just 16 bits, unsigned short cannot
hold values bigger than 65535. On our LDAP server rsyslog misbehaved with
SystemLogRateLimitBurst being bigger than 65535. Make it unsigned int to
accept bigger values.
=> Make configuration setting SystemLogRateLimitBurst unsigned int

tests/Makefile.am
I have obviously overlooked some...
see also https://github.com/rsyslog/rsyslog/issues/2403
=> testbench: temporarily disable more racy omprog tests

tests/diag.sh
some tests use rsyslog.out.* file names, which were so far not cleaned up.
This can lead to all sorts of problems, including failure of
"make distcheck" due to leftover files. We now delete all of these files
on cleanup. This should not have any undesired side-effects.
Thanks to Kasumi Hanazuki for spotting this problem.
see also https://github.com/rsyslog/rsyslog/pull/2527
=> testbench: improve cleanup

grammar/rainerscript.c
... as it causes issues. Plan is to fix and re-enable with next release.
see also https://github.com/rsyslog/rsyslog/issues/2524
=> core: disable script optimizer warning

tests/omprog-transactions-failed-messages.sh
test consistently fails
see also https://github.com/rsyslog/rsyslog/issues/2403
=> testbench: disable omprog-transactions-failed-messages.sh on solaris

plugins/imfile/imfile.c
Coverity Scan detected a file handle leak. This was introduced in the
refactoring done in the past couple of days. Was NOT present in any
released code, so is nothing to really care about.
fixes Coverity Scan ID 188771
=> imfile: fix ressource leak in just-refactored code

tests/imfile-endregex-timeout-with-shutdown-polling.sh
test imfile-endregex-timeout-with-shutdown-polling.sh fails, most probably
due to bad timing.
=> testbench: address failure on FreeBSD

plugins/omprog/omprog.c
There was a fd leak in the feedback feature I added in v8.31.0 (PR #1753). The leak occurred when omprog was used with the `confirmMessages=on` setting and no `output` setting. One fd was leaked every time the external program was started.
I have found this when reviewing the omprog tests. A later PR I'm currently preparing will include a regression test for this case. Meanwhile, the correction should be merged ASAP.
=> omprog: corrected fd leak with confirmMessages=on

plugins/imtcp/imtcp.c
Set the right tcp keepalive settings to match the documentation and the linux sysctl original meaning.
TCPKeepAliveIntvl and TPCKeepAliveTime was switched
=> Fix tcp keepalive settings assignment

configure.ac, plugins/omkafka/omkafka.c, runtime/atomic.h, runtime/dynstats.c, tests/imfile-endregex-timeout-with-shutdown-polling.sh, tools/omfile.c
... on platforms that do not support them natively. None of them actually break building except when warning-free compile is enforced.
closes #2612
=> fix issues with atomic operations

configure.ac
This is essential and seems to be often forgotten. We enable it
in the hope that it does not break anything. If so, we need to
re-evaluate the default and situation.
see also https://github.com/rsyslog/rsyslog/issues/1459
=> build system: enable --unlimited-select by default

configure.ac
Reverts rsyslog/rsyslog#2209 - undo accidental merge :-(
=> Revert "build system: enable --unlimited-select by default"

configure.ac
closes https://github.com/rsyslog/rsyslog/issues/2613
=> fmhttps bugfix: missing configure check for libcurl

plugins/imptcp/imptcp.c
Increase the UNIX socket backlog to the same value as TCP socket.
I encountered performance issues under heavy load with a backlog set to 5.
=> imptcp: increase UNIX socket backlog for performance under heavy load

tests/rscript_http_request-vg.sh, tests/rscript_http_request.sh
this becomes necessary as the main site switches to https
=> testbench: switch external testbench URL

grammar/rainerscript.c, plugins/fmhttp/fmhttp.c, runtime/modules.c
was used while implementing function modules, but were
not removed due to oversight.
=> remove unnecessary debug output

configure.ac, grammar/rainerscript.c, plugins/imfile/imfile.c, plugins/imklog/bsd.c, plugins/omprog/omprog.c, runtime/debug.c, tools/omfwd.c
We do not know exactly why AX_COMPILER_FLAGS turns these off, but we
consider them useful and would like to have them turned on.
**Note: PR will and must fail** until we have fixed those warnings that sneaked in while the warnings were turned off. Those fixes will be done in separate PRs, then a rebase happens here.
=> QA: re-enable some compiler warnigs AX_COMPILER_FLAGS disables

configure.ac, contrib/mmkubernetes/mmkubernetes.c, contrib/mmkubernetes/sample.conf, tests/Makefile.am, tests/mmkubernetes-basic-vg.sh, tests/mmkubernetes-basic.out.json, tests/mmkubernetes-basic.sh, tests/mmkubernetes_test_server.py
Changes:
- add tests for mmkubernetes
- clean up sample mmkubernetes file
- fix indentation
- check for Kubernetes response code
- only examine filename if non-null and length is not 0
- add default kubernetesurl https://kubernetes.default.svc.cluster.local:443
- fix broken lnrule for CONTAINER_NAME
- add pkg check for lognorm >= 2.0.3 for mmkubernetes for
HAVE_LOADSAMPLESFROMSTRING
- fix lnrules
=> Several fixes for mmkubernetes

rsyslog.service.in
This is for solving situations when dealing with many files and
also to keep aligned with systemd value (because of journal
integration).
=> Increased limit of concurrent FDs.

runtime/queue.c
if a ruleset queue is in direct mode, a segfault can occur during
rsyslog shutdown.
closes #2480
=> core bugfix: segfault on queue shutdown

grammar/rainerscript.c
closes https://github.com/rsyslog/rsyslog/issues/2665
=> core: config optimizer did not handle call_indirect

plugins/imfile/imfile.c
When imfile rewrites state files, it does not truncate previous
content. If the new content is smaller than the existing one, the
existing part will not be overwritten, resulting in invalid json.
That in turn can lead to some other failures.
closes https://github.com/rsyslog/rsyslog/issues/2662
=> imfile bugfix: statefiles contain invalid JSON

grammar/rainerscript.c
When a "call" script statement was used with a non-existing ruleset AND
debug logginf was active for rainerscript.c, valgrind complained and
one debug message could potentially be incorrect (stating a queue
where non was).
This was caused by not initializing a variable which was probed in
debug mode before it was set. Non-debug mode was not affected.
see also https://github.com/rsyslog/rsyslog/issues/2399#issuecomment-384890873
=> cosmetic bugfix: valgrind complain in some error conditions

tools/rsyslogd.c
The following errors must be made in rsyslog.conf:
* no action present
* a call statement is used on an undefined ruleset
In this case, rsyslog emits an error message on the missing actions and
then segfaults. Depending on memory layout, it may also continue to run
but do nothing except accepting messages as no action is configured.
This patch make rsyslog properly terminate after the error message. It
is a change in behavior, but there really is no reason why a defunct
instance should be kept running.
closes https://github.com/rsyslog/rsyslog/issues/2399
=> bugfix: rsyslog aborts on startup when specific config errors are made

plugins/imrelp/imrelp.c, tests/Makefile.am, tests/imrelp-maxDataSize-error.sh
maxDataSize specifies the length which will still be accepted
but is larger than the global parameter maxMessageSize.
=> imrelp: maxDataSize can only be set larger than maxMessageSize

runtime/nsdsel_ptcp.c, runtime/nsdsel_ptcp.h, runtime/rsyslog.h, tests/hostname-getaddrinfo-fail.sh
**This PR is split off from a larger PR which fails for some reason.** I try to see if the individual patch works, and if so I can apply it immediately as it is pretty useful.
This removes us of problems with fds > 1024. The performance will
probably also increase in most cases.
Note this is not a replacement for the epoll drivers, but a general
stability improvement when epoll() is not available for some reason.
see also https://github.com/rsyslog/rsyslog/issues/2615
closes https://github.com/rsyslog/rsyslog/issues/1728
closes https://github.com/rsyslog/rsyslog/issues/1459
=> nsdsel_ptcp: replace select() by poll()

tests/hostname-getaddrinfo-fail.sh
The preloaded library causes some side-effect, which we so far
did not find. We try to avoid making CI always fail, and so we
skip the test on FreeBSD for now.
=> testbench: temporarily disable test failing on FreeBSD

plugins/imklog/imklog.c, plugins/imklog/imklog.h
On Linux kernel logs are ratelimited only for messages using
printk_ratelimit().  Some logs do not use this facility, so
we ratelimit kernel ourselves.
=> Enable ratelimit on imklog

plugins/imklog/imklog.c
there is a sanity check meant to catch coding bugs, but so far
it did not complain loudly enough. Now it's a user-visible message.
=> imklog: better internal bug tracking

contrib/mmgrok/mmgrok.c
The modules used strtok(), which is not thread-safe. So it will potentially
segfault when multiple instances are spawned (what e.g. happens on busy
systems).
This patch replaces strtok() with its thread-safe counterpart
strtok_r().
see also https://github.com/rsyslog/rsyslog/issues/1359
=> mmgrok: fix potential segfault

runtime/debug.c, runtime/queue.c, tests/diag.sh, tests/testsuites/threadingmqaq.conf, tests/threadingmqaq.sh
As related testing has show this test sometime fails because
the enq operation on the action queue times out. This is valid,
but causes false positives. The simple (and correct!) solution is
to increase the timeout.
=> testbench: fix race in threadingmqaq test

dirty.h, plugins/imfile/imfile.c, plugins/imrelp/imrelp.c, plugins/imudp/imudp.c, runtime/errmsg.c, runtime/errmsg.h, runtime/glbl.c, runtime/glbl.h, runtime/msg.c, runtime/msg.h, runtime/ratelimit.c, runtime/rsyslog.h, tests/Makefile.am, tests/glbl-oversizeMsg-log-vg.sh, tests/glbl-oversizeMsg-log.sh, tests/glbl-oversizeMsg-split.sh, tests/glbl-oversizeMsg-truncate-imfile.sh, tests/glbl-oversizeMsg-truncate.sh, tests/imfile-truncate-line.sh, tests/imptcp-msg-truncation-on-number.sh, tests/imptcp-msg-truncation-on-number2.sh, tests/imptcp-oversize-message-display.sh, tests/imrelp-long-msg.sh, tests/imtcp-msg-truncation-on-number.sh, tools/rsyslogd.c
In the community we frequently discuss handling of oversize messages.
David Lang rightfully suggested to create a central capability inside
rsyslog core to handle them.
We need to make a distinction between input and output messages. Also,
input messages frequently need to have some size restrictions done at
a lower layer (e.g. protocol layer) for security reasons. Nevertheless,
we should have a central capability
* for cases where it need not be handled at a lower level
* as a safeguard when a module invalidly emits it (imfile is an example,
see https://github.com/rsyslog/rsyslog/pull/2632 for a try to fix it
on the module level - we will replace that with the new capability
described here).
The central capability works on message submission, and so cannot be
circumvented. It needs to …
=> core: consistent handling of oversize input messages

plugins/fmhttp/Makefile.am, plugins/imfile/Makefile.am
Fixes https://github.com/rsyslog/rsyslog/issues/2697.
=> pass liblogging cflags when building fmhttp and imfile plugins

runtime/stringbuf.c
This can be exposed via imfile, as follows:
- use a regex to process multiline messages
- configure timeouts
- make sure imfile reads a partial message
- wait so that at least one timeout occurs
- add the message termination sequence
This leads to a misadressing, which may have no obvious effects potentially
up to a segfault.
closes https://github.com/rsyslog/rsyslog/issues/2661
=> imfile/core bugfix: potential misadressing in string copy routine

plugins/imrelp/imrelp.c
... even if librelp is current. The codition check was actually missing.
This commit adds it.
closes https://github.com/rsyslog/rsyslog/issues/2712
=> imrelp bugfix: error message "librelp too old" is always emitted

grammar/rainerscript.c
permit 4-digit file creation modes (actually 5 with the leading zero) so
that the setgid bit can also be set (and anything else on that position.
closes https://github.com/rsyslog/rsyslog/issues/1092
=> config: permit 4-digit file creation modes

tests/mmkubernetes-basic.sh, tests/mmkubernetes_test_server.py
https://github.com/rsyslog/rsyslog/issues/2721
Was not working on python3 - must use `encode()` to convert the
string to a `bytes` object.
Also run the server with python -u to make sure we get the log
output from the kubernetes test server.
=> mmkubernetes test python must encode response

.github/pull_request_template.md, CONTRIBUTING.md
while this is utter nonsense, discussion on GDPR and git
seems unfortunately be rooted in actual legal needs
=> add GDPR legal notice to contributor doc

runtime/lookup.c
@rgerhards @davidelang 
Based on discussion, I've attempted to adjust the error level to reflect that the action (reloading the lookup table) is normal/expected and not an actual error condition. No real clue what I'm doing here, so feedback/corrections are much appreciated!
related to rsyslog/rsyslog#2713
=> lookup table reload: log level from error to info

plugins/omrelp/omrelp.c
When authmode is configured, it is checked if the value is
valid, before using it.
If the value is invalid an error message is put out.
closes https://github.com/rsyslog/rsyslog/issues/2743
=> omrelp: check for correct authmode

rsyslog.service.in
systemd[1]: [/lib/systemd/system/rsyslog.service:19] Unknown lvalue 'LimitNOFILE' in section 'Install'
=> rsyslog.service.in: move LimitNOFILE to correct section

tests/Makefile.am
Found a missed file:
```
============================================================================
Testsuite summary for rsyslog 8.35.0
============================================================================
FAIL: mmkubernetes-basic.sh
===========================
------------------------------------------------------------
Test: ./mmkubernetes-basic.sh
------------------------------------------------------------
testbench: TZ env var not set, setting it to UTC
ABORT! Timeout waiting on startup (pid file)
FAIL mmkubernetes-basic.sh (exit status: 1)
$ cat tests/mmk8s_srv.log
/usr/bin/python3.6: can't open file './mmkubernetes_test_server.py': [Errno 2] No such file or directory
$ find /tmp/rsyslog-8.35.0/work/rsyslog-8.35.0/ -name 'mmkubernetes_test*'
-
```
=> testbench: Add missing mmkubernetes_test_server.py to EXTRA_DIST

runtime/ruleset.c, tests/imfile-basic-vgthread.sh, tests/imfile-basic-vgthread.supp
when writing disk queue files during shutdown, access to freed
memory can occur under these circumstances:
- action A is processing data, but could not complete it
most importantly, the current in-process batch needs not to
be totally completed. Most probable cause for this scenario
is a suspended action in retry mode.
- action A is called from a ruleset RA which
- does not have a queue assigned
- where RA is called from a ruleset RO which is bound
to the input from which the message originated
- RO must be defined before RA inside the expanded config
- Disk queues (or the disk part of a DA queue) must be utilized
by A
When re-injecting the unprocessed messages from A into the disk queue, the
name of ruleset RO is accessed (for persisting to disk). However, RO is
already destructed at …
=> core: misadressing when writing disk queue files

contrib/mmkubernetes/k8s_container_name.rulebase, contrib/mmkubernetes/k8s_filename.rulebase
We see memory leaks in liblognorm in older versions of
liblognorm unless we explicitly specify version=2
=> use version=2 in mmkubernetes rulebase files

plugins/external/INTERFACE.md, plugins/external/skeletons/python/plugin-with-feedback.py
Make the skeleton easier to understand by removing transaction support.
Also, transaction failures did not work as explained in the skeleton,
because of issue #2420. In the future, a 'plugin-with-transactions.py'
example can be added, ideally once the issue is solved.
=> omprog: simplify 'plugin-with-feedback.py' example

plugins/omelasticsearch/omelasticsearch.c, tests/Makefile.am, tests/README, tests/diag.sh, tests/es-bulk-retry.sh, tests/es-config-errs.supp, tests/es-writeoperation.sh
Add support for a 'create' write operation type in addition to
the default 'index'.  Using create allows specifying a unique id
for each record, and allows duplicate document detection.
Add support for checking each record returned in a bulk index
request response.  Allow specifying a ruleset to send each failed
record to.  Add a local variable `omes` which contains the
information in the error response, so that users can control how
to handle responses e.g. retry, or send to an error file.
Add support for response stats - count successes, duplicates, and
different types of failures.
Add testing for bulk index rejections.
=> omelasticsearch: write op types; bulk rejection retries

ChangeLog, plugins/imfile/imfile.c, tests/imfile-freshStartTail1.sh, tests/imfile-freshStartTail2.sh, tests/imfile-freshStartTail3.sh
When the option is set and a new file is created after rsyslog startup,
freshStartTail is also applied to it. That is data written quickly to it
(before rsyslog can process it) will potentially be discarded. If so,
and how much, depends on the timing between rsyslog and the logging process.
This problem is most likely to be seen in polling mode, where a relatively
long time may be required for rsyslog to find the new file.
This is changed so that now freshStartTail only applies to files that
are already-existing during rsyslog's initial processing of the file
monitors. HOWEVER, depending on the number and location (network?) of
existing files, this initial startup processing may take some time as
well. If another process creates a new file at exactly the time of
startup processing and …
=> imfile bugfix: if freshStartTail is set some initial file lines missing

runtime/nsd_gtls.c
Commit 7589f42e45888b83f5c2a0d788896d41e6a6a598 introduced support
for loading certificate chains. Unfortunatley the max number of permitted
certificates was miscalculated and so a certificate chain with more than
10 certificates could lead to a buffer overrun. This patch corrects this.
Note that the commit was merged just yesterday and there was no release
with the affected code.
=> nds_gtls: fix regression that could lead to attack (never released)

runtime/nsd_ossl.c
=> nsd_ossl: use new errmsg interface

plugins/mmnormalize/mmnormalize.c
=> mmnormalize: use new errmsg interface

plugins/imptcp/imptcp.c, tests/Makefile.am, tests/diag.sh, tests/imptcp_framing_regex-oversize.sh, tests/imptcp_framing_regex.sh, tests/testsuites/imptcp_framing_regex-oversize.testdata, tests/testsuites/imptcp_framing_regex.testdata
Add support for regex-based framing  for complex multi-line messages (XML in particular), the multiLine method does not work. We now have a capability to specify via a regex when a frame starts (and the previous thus ends).
adds imptcp input parameter "framing.delimiter.regex"
=> imptcp: experimental multiline support via regex

plugins/ommongodb/README, plugins/ommongodb/ommongodb.c
Added new configuration (not mandatory) option `allowed_error_codes`.
The directive argument MUST be in the following format (handling a maximum of 256 codes): "11000,...,17,64"
The behavior of ommongodb was for a long time to `ABORT_FINALIZE(RS_RET_SUSPENDED)` on any MongoDB insertion error; keeping this behavior, I wanted to add the possibility to ignore some error code that may be allowed in some (really rare) configuration (*ex. `11000: DuplicateKey` in case of collection containing one or more unique field(s)*).
Hugo.
=> [ommongodb] Adding possibility to ignore some insertion error code

plugins/imrelp/imrelp.c
Commit 32b71daa8aadb8f16fe0ca2945e54d593f47a824 introduced a
potential misadressing of "inst" during error processing. No
version with that commit was ever released.
Detected by Coverity Scan, CID 190327
=> imrelp: fix regression from very recent commit

plugins/imjournal/imjournal.c
-- Adds impstats counters for messages read from journal, submitted to main queue, and dropped due to rate-limiting
-- Also, adds counters for journal file rotations and disk usage
=> imjournal: journal visibility through additional impstats counters

runtime/stream.c
strmFlushInternal and especially doAsyncWriteInternal needs to be called with locked mutex as it is in the rest of code. It changes stream object and that should be done when mutex was correctly locked.
Another problem is that doAsyncWriteInternal containts pthread_cond_wait which specifically requires locked mutex.
=> Fixed race in asyncWriter

ChangeLog, action.c, tests/stats-json.sh
We now inlcude the module name (e.g. "omelasticsearch" or "builtin:omfile")
as part of the name. This is still not perfect, but hopefully a bit
easier to grasp.
see also https://github.com/rsyslog/rsyslog/issues/342
=> core: provide a somewhat better default action name

tests/Makefile.am
While older GnuTLS versions do use gcrypt, newer version no longer do.
From
https://www.gnutls.org/manual/html_node/Cryptographic-Backend.html
"
Cryptographic library layer
The Cryptographic library layer, currently supports only libnettle.
Older versions of GnuTLS used to support libgcrypt, but it was switched
with nettle mainly for performance reasons and secondary because it is
a simpler library to use. In the future other cryptographic libraries
might be supported as well.
"
=> Don't link tcpflood against -lgcrypt

Makefile.am, configure.ac, runtime/debug.h
veeeeery old testing capability, no longer functional but
causes build to fail if enabled. Replaced by ASAN/valgrind.
Issue detected while testing some other CI settings.
=> cleanup: remove no longer needed --enable-memcheck

plugins/ommail/ommail.c
When sending a message via ommail the email body was
not sent unless enable.body was specified to "on".
Now the default is "on" and it only needs to be specified
if you don't want the body part to be sent.
Closes https://github.com/rsyslog/rsyslog/issues/2789
=> ommail: enable.body parameter default set correctly

contrib/mmkubernetes/mmkubernetes.c
check for null fp before `fclose(fp)`
fixes https://github.com/rsyslog/rsyslog/issues/2804
=> check for null fp before fclose

runtime/glbl.c, tests/abort-uncleancfg-badcfg-check.sh, tests/testsuites/abort-uncleancfg-badcfg.conf, tools/rsyslogd.c
This provides a new-style alternative to $AbortOnUncleanConfig.
Note that a testbench test was changed to the new syntax. Adding
an additional test did not look useful, as the testbench still
sufficiently tests old and new method.
closes https://github.com/rsyslog/rsyslog/issues/2744
=> add global directive "abortOnUncleanConfig"

.travis.yml
We originally merged master into the PR. At that time, github did not
(reliably?) provide a merged code basis. This is now the case, so the
test is kind of unnecessary. It only did some good if master was updated
after PR submission but before Travis started the test. This is pretty
unlikely, so we remove that test - which also is a relief in regard
to Travis runtime.
see also https://github.com/rsyslog/rsyslog/issues/2800
=> travis: remove "merge master" test

action.c
Message modification modules do not work if used with a non-direct queue.
We now make this more explicit in the config parsing error message.
closes https://github.com/rsyslog/rsyslog/issues/1323
=> more explicit error msg with message modification mod on queue

contrib/mmkubernetes/Makefile.am, contrib/mmkubernetes/mmkubernetes.c
Change the default filename rules to use container_name_and_id
Include the rulebase files in the dist / source tarball
=> default rules use container_name_and_id; include rulebase files in dist

plugins/imsolaris/imsolaris.c
=> imsolaris: use new errmsg interface

plugins/impstats/impstats.c
With this config, "ruleset" is silently ignored, what probably is
not obvious to a user.
closes https://github.com/rsyslog/rsyslog/issues/2821
=> impstats: emit warning if log.syslog="off" and ruleset name given

contrib/mmgrok/mmgrok.c
causes build under gcc 7 to fail with warning
=> mmgrok bugfix: cosmetic build issue

contrib/imkmsg/imkmsg.c, contrib/imkmsg/imkmsg.h, contrib/imkmsg/kmsg.c, tests/hostname-getaddrinfo-fail.sh
nothing serious, but still breaks CI. Also, we want as-clean-as-possible code
closes https://github.com/rsyslog/rsyslog/issues/2830
=> imkmsg bugfix: build warnings on some platforms

.travis.yml, tests/Makefile.am
this has been moved to the buildbot infrastructure, where we
do not have the strong runtime limitations. We still need to
run db-related (mysql, ...) distcheck tests as this is not yet
supported in the containers we use on buildbot.
=> Travis: reduce distcheck tests

plugins/ommysql/ommysql.c
This patch is intended to fix problems when using the mysql or mariadb ___binary package___.
If use the ___mysql_real_connect___ api and specify the ___db server___ argument to ___localhost___, the ___mysql_real_connect___ api internally tries to connect using the mysql unix domain socket.
For example, an error will occur under the following conditions:
1. start mysql daemon with ___--socket=/var/run/mysqld.sock___ option.
2. Set the ommysql plugin as shown below.
```
module(load="ommysql")
action(
type="ommysql"
server="localhost"
serverport="3306"
db="Syslog"
uid="rsyslog"
pwd="blahblah*^^*secret"
template="stdSQLformat"
)
```
So, I have added the ___socket___ option to solve this problem.
Adding the ___socket___ option as shown below will not cause an error.
```
module(load="ommysql") …
```
=> support mysql unix domain socket

tests/arrayqueue.sh, tests/linkedlistqueue.sh
These tests indicated they terminate rsyslog forcefully without
drainging the queues, but then checked if they were drained (all
messages processed). That does not make sense, and I cannot
envison why I wrote this in the first place. So I assume some
copy&paste problem was the root of that.
=> testbench: fix tests that look awfully wrong

tests/diag.sh
On slow machines (ARM in CI env e.g.) the previous timeout was insufficient.
=> testbench: increase ElasticSearch start timeout

tests/CI/kill_all_kubernetes_test_server.sh, tests/diag.sh, tests/glbl-oversizeMsg-truncate-imfile.sh, tests/imrelp-manyconn.sh, tests/mmkubernetes-basic-vg.sh, tests/mmkubernetes-basic.sh
when the test is aborted it is currently not possible to recover the hanging instance, forcing all future tries on that machine to hang until either reboot or manual intervention.
=> testbench: kubernetes test cannot recover from failure

.travis.yml, configure.ac, tests/Makefile.am
This permits to control the "default tests" in testbench runs. These
are those tests that do not need a special configure option. There are
some situations where we really want to turn them of so that we can
run tests only for a specific component (e.g. ElasticSearch).
This commit also removes the --enable-testbench[12] configure switches,
which were introduced just to work-around travis runtime restrictions.
With the new CI setup and new options we could reduce the Travis runtime
dramatically and so we do not need them any longer.
=> add --enable-default-tests ./configure option

contrib/mmkubernetes/mmkubernetes.c, tests/mmkubernetes-basic-vg.sh, tests/mmkubernetes-basic.out.json, tests/mmkubernetes-basic.sh
When mmkubernetes encounters a record with a CONTAINER_NAME field,
but the value does not match the rulebase, mmkubernetes returns
an error, and mmkubernetes does not do any further processing
of any records.
The fix is to check the return value of ln_normalize to see if
it is a "hard" error or a "does not match" error.
This also adds a test for pod names with dots in them.
=> mmkubernetes: stops working with non-kubernetes container names

runtime/rsyslog.c
rsyslog creates a default scheduling policy on startup. This code
invalidly used CHKiRet (our exception handler) to check pthreads
return codes, what this macro cannot do. This lead to hard to
diagnose startup problems in cases where there were problems
setting the scheduling defaults (e.g. when rsyslog is set to run
at idle priority). Even more so, this blocked startup altogether,
which is not the right thing to do. Actually, this can be considered
a regression from commit 7742b21. That commit was 8 years ago, so
in general this cannot be a big issues ;-)
The code now emits proper error messages (to stderr, as at this point
no other output is available as it is during the initial state of
rsyslog initialization) and continues the startup.
closes …
=> core: do not abort startup on problems setting scheduling policy

plugins/imrelp/imrelp.c
This adds a new optional `address` parameter to `imrelp` inputs in order
to specify an address to bind to.
Based on support added by rsyslog/librelp@96eb5be (rsyslog/librelp#90).
=> imrelp: add support for seting address to bind to (#894)

tests/diag.sh
=> testbench: cleanup no-longer needed "nettester" command

tests/travis/install.sh
We already know they are currently unstable, so there is not point
in messing up CI result each time. The test will still be carried out
in nightly checks, so the problems won't be forgotten.
=> Travis: temporarily disable kafka tests

plugins/imjournal/imjournal.c, tests/Makefile.am, tests/imjournal-basic-vg.sh, tests/imjournal-basic.sh, tests/imjournal-statefile.sh, tests/journal_print.c
Fetching journal cursor in persistJournal could cause us to save
invalid cursor leading to duplicating messages further on, now we are
saving it on each readJournal() where we now that the state is good.
This result in simplyfing persisJournalState() a bit as well.
pollJournal() is now cleaner and faster, correctly handles INVALIDATE
status from journald and is able to continue polling after journal
flush.
=> Fetching cursor on readJournal() and simplified pollJournal()

plugins/imjournal/imjournal.c
If fputs() failed we aborted without closing opened handle
=> Fixed resource leak in persistJournalState()

tests/diag.sh
We still see hanging instances, so we for now resort to kill them.
The uxsockrcvr tool itself should timeout after a while.
=> testbench: cleanup hanging uxsocksrvr instances

tests/diag.sh
this was harmless, but generated irritating messages in test log
=> testbench: uxsockrcvr cleanup did try to kill "grep" process

plugins/omprog/omprog.c
Log some messages related to child process termination as info/warn
instead of error.
=> omprog: fix severity of some log messages in waitForChild

plugins/omelasticsearch/omelasticsearch.c, tests/Makefile.am, tests/es-bulk-retry.sh
Write all of the original request metadata fields to `$.omes` for
the retry, if present.  This may include all of the following:
_index, _type, _id, _parent, pipeline
This is in addition to the fields from the response.  If the same
field name exists in the request metadata and the response, the
field from the request will be used, in order to facilitate
retrying the exact same request.
=> write all header metadata to omes for retries

plugins/imfile/imfile.c
Coverity seems not to understand realpath() API, but we nevertheless
want to have a clean Coverity report. So we hope this silences it.
CID 1911977
=> imfile: try to "fix" Coverity false positive

tests/Makefile.am, tests/daqueue-dirty-shutdown.sh, tests/diag.sh, tests/hostname-with-slash-dflt-invld.sh, tests/imjournal-basic-vg.sh, tests/imjournal-basic.sh, tests/mmkubernetes-basic-vg.sh, tests/mmkubernetes-basic.sh, tests/testsuites/gethostname.conf
required for parallel test execution
=> testbench: support dynamic pidfile naming

devtools/check-codestyle.sh
The codestyle script will now put out an error message
when the codestyle is incorrect, explaining what went wrong
and providing a link to the documentation.
=> codestyle: give error message when codestyle is incorrect

plugins/omprog/omprog.c
When sending logs to the program, in case of a partial write to the pipe, invalid data was sent, or an invalid memory access could occur. (A partial write can occur if the syscall is interrupted or the pipe is full.)
I have incidentally found this bug through code inspection (I have not reproduced it). It affects all versions to date.
Ideally there should be a test case for this, but I'm not sure how it could be implemented functionally (?).
Note: the changes from "int" to "ssize_t" are not related to the bug. Just a minor refactor.
=> omprog: fix invalid memory access on partial writes to pipe

plugins/imtcp/imtcp.c, plugins/imudp/imudp.c, runtime/msg.c, runtime/msg.h, runtime/net.c, runtime/tcpsrv.c, runtime/tcpsrv.h
When imudp is used for input, the FROMHOST value is all lowered:
`FROMHOST: 'myclient.example.lab', fromhost-ip: '192.168.122.111', HOSTNAME: 'myCLIENT', ...`
while the case is preserved if it is imtcp:
`FROMHOST: 'myCLIENT.example.lab', fromhost-ip: '192.168.122.111', HOSTNAME: 'myCLIENT', ...`
where the host name is defined as "myCLIENT.example.lab myCLIENT" in /etc/hosts.
These 2 behaviours are preferably matched.
My concern is resolveDNS is a common helper function in runtime/msg.c, which is being called not just from getRcvFrom but multiple places.  The rest may expect all lowercase localName.
=> [WIP] "fromhost" property's case is lowered when using UDP

plugins/imfile/imfile.c
There was a garbage byte left before which could cause errors down the
road.
=> Fixed parent name when processing symlinks

plugins/imfile/Makefile.am, plugins/imfile/imfile.c, plugins/imfile/siphash.c, tests/Makefile.am, tests/diag.sh, tests/imfile-growing-file-id.sh, tests/imfile-persist-state-1.sh
This ensures that files with the same inodes are not accidently treated
as equal, at least within the limits of the file id hash (see doc for
details).
closes https://github.com/rsyslog/rsyslog/issues/2530
=> omfile: implement file-id, used in state file

plugins/omkafka/omkafka.c, tests/Makefile.am, tests/diag.sh, tests/sndrcv_kafka-vg-rcvr.sh, tests/sndrcv_kafka-vg-sender.sh, tests/sndrcv_kafka.sh, tests/sndrcv_kafka_fail.sh, tests/sndrcv_kafka_failresume.sh, tests/sndrcv_kafka_multi.sh, tests/sndrcv_kafka_multi_topics.sh, tests/testsuites/kafka-server.dep_wrk1.properties, tests/testsuites/kafka-server.dep_wrk2.properties, tests/testsuites/kafka-server.dep_wrk3.properties, tests/testsuites/kafka-server.properties
Fixed test configurations (socket timeouts, settings and so on)
Switched testbench to newer kafka/zookeeper versions.
Added new test for multiple imkafka instances.
Renabled sndrcv_kafka_fail.sh testcase.
=> testbench: use new kafka/zookeeper versions, fixed/added tests.

tests/uxsock_simple.sh, tests/uxsockrcvr.c
The program times out after some time.
Default is 60 seconds and can be changed with the parameter -t.
closes https://github.com/rsyslog/rsyslog/issues/2905
=> uxsockrcvr: add timeout

tests/Makefile.am, tests/test_id.c
The new program test_id puts out the system time
up to microseconds.
=> testbench: add program to get system time

configure.ac, tests/Makefile.am
They have very special requirements, so it does not make sense to have
them run by default. Also note that as of now, they have a pretty high
rate of false positives due to bugs in the journal.
see also https://github.com/rsyslog/rsyslog/issues/2931#issuecomment-416914707
=> testbench: disable journal tests by default

plugins/imdiag/imdiag.c, plugins/imptcp/imptcp.c, runtime/netstrm.c, runtime/netstrm.h, runtime/nsd.h, runtime/nsd_gtls.c, runtime/nsd_ossl.c, runtime/nsd_ptcp.c, runtime/strmsrv.c, runtime/tcpsrv.c, runtime/tcpsrv.h
This parameter is used to specify a file in which the port
being used by imptcp is written.
=> imptcp: add parameter ListenPortFileName

action.c, grammar/lexer.l, plugins/imuxsock/imuxsock.c, plugins/mmexternal/mmexternal.c, runtime/modules.c, runtime/net.c, runtime/nsd_ptcp.c, runtime/rsyslog.h, runtime/srutils.c, runtime/tcpclt.c, tests/tcpflood.c, tools/omfile.c, tools/omfwd.c, tools/ompipe.c, tools/omusrmsg.c, tools/rsyslogd.c
The default stack size on some platforms is insufficient, so we
need to explicitely set it.
=> tcpflood: fix segfauls on some platforms (e.g. AIX)

plugins/imgssapi/imgssapi.c, plugins/imtcp/imtcp.c, runtime/tcpsrv.c
Until now when port 0 was specified in imtcp, imgssapi or imdiag,
it was automatically changed to 514 in tcpsrv.
Imtcp and imgssapi accept port 0, but only if parameter listenPortFileName
(imgssapi: inputgsslistenportfilename) is specified. Otherwise it will
still change the port.
Imdiag accepts 0 as a port and will create a socket with a random
port.
=> imdiag: port 0 is now accepted

tests/Makefile.am, tests/diag.sh, tests/es-writeoperation.sh, tests/omprog-restart-terminated-outfile.sh, tests/sndrcv_gzip.sh, tests/test_id.c
The RSYSLOG_DYNNAME used to make test file unique was very long,
which potentially causes issues with some test scenarios.
see also: https://github.com/rsyslog/rsyslog/pull/2945#issuecomment-417078768
Also, the dynamic port determination method we currently use
is not 100% reliable. That port number was used inside the DYNNAME
and thus was not necessarily unique. This has now changed to the
current time in microseconds plus a hash of the test file name. This
should be sufficiently unique. If still not, we can now simply
extend the test_id program (e.g. read /dev/urandom).
=> testbench: short test id and make more reliable

plugins/external/INTERFACE.md, plugins/external/skeletons/python/plugin-with-feedback.py, plugins/omprog/omprog.c, tests/Makefile.am, tests/diag.sh, tests/omprog-close-unresponsive-noterm.sh, tests/omprog-close-unresponsive-vg.sh, tests/omprog-close-unresponsive.sh, tests/omprog-defaults.sh, tests/omprog-feedback-vg.sh, tests/omprog-feedback.sh, tests/omprog-output-capture-mt.sh, tests/omprog-output-capture-vg.sh, tests/omprog-output-capture.sh, tests/omprog-restart-terminated-outfile.sh, tests/omprog-restart-terminated-vg.sh, tests/omprog-restart-terminated.sh, tests/omprog-transactions-failed-commits.sh, tests/omprog-transactions-failed-messages.sh, tests/omprog-transactions-vg.sh, tests/omprog-transactions.sh, tests/testsuites/omprog-feedback-bin.sh, tests/testsuites/omprog-output-capture-bin.sh, tests/testsuites/omprog-output-capture-mt-bin.py, tests/testsuites/omprog-restart-terminated-bin.sh
Capture program output using a pipe shared with all child processes,
and write to the file using a dedicated thread. Ensures lines emitted
by the child processes will not be intermingled in the output file if
the lines are less than PIPE_BUF chars long and are written in line-
buffered mode.
Reopen output file on HUP, to support external rotation of the file.
New setting 'fileCreateMode' as in omfile.
With these improvements the 'output' setting should now be usable for
production (it was originally intended only for debugging).
Redirect stdout/stderr of child process to /dev/null when not captured.
Closes #2787
Minor: simplify some test code: 'wait-startup' not needed after
'startup', 'wait-queueempty' not needed before 'shutdown_when_empty'.
=> omprog: improve child process output capture/redirection

plugins/omprog/omprog.c
Fix bug introduced in #2945: output file write lock was not released if
an error occurred writing the file.
=> omprog: fix output file write lock not always released

plugins/imptcp/imptcp.c, runtime/nsd_ptcp.c
Until now it was tried to write to the file even
if it couldn't be opened. Now the process is aborted.
=> lstnPortFileName: abort when file can't be opened

contrib/omfile-hardened/omfile-hardened.c, tools/omfile.c, tools/omfwd.c
Per issue [2975](https://github.com/rsyslog/rsyslog/issues/2975)
Compiled successfully under Ubuntu 16.04, but that's about it.
Dirt simple changes. Not much to see here.
I can't even say with 100% certainty I got everything, as I'm not that familiar with rsyslog... but I did do a search and these were the ones I found. Clearly there are other instances of *dynfile* that aren't malicious. I tried to err on the side of changing as little as possible.
=> WiP: Fix errant error message when dynafile param needed

tools/omfwd.c
The config plumbing itself provides an error message. The one given here
was also totally wrong ;-)
Thanks to Frank Bicknell for spotting this message and making me alert.
=> omfwd: remove invalid error message

plugins/external/INTERFACE.md, plugins/omprog/omprog.c, tests/Makefile.am, tests/omprog-feedback-mt.sh, tests/omprog-feedback-timeout.sh, tests/omprog-feedback-vg.sh, tests/testsuites/omprog-feedback-bin.sh, tests/testsuites/omprog-feedback-mt-bin.sh, tests/testsuites/omprog-feedback-timeout-bin.sh
Restart the program if it does not respond within timeout.
New setting 'confirmTimeout' (default 10 seconds).
Allow the program to provide keep-alive feedback when a
message requires long-running processing.
Improve efficiency when reading feedback line (use buffer).
Retry interrupted writes/reads to/from pipe.
New setting 'reportFailures' for reporting error messages
from the program.
Report child termination when writing to pipe.
Minor refactor: renamed writePipe function to sendMessage,
renamed readPipe to readStatus.
=> omprog: add feedback timeout and keep-alive feature

runtime/cfsysline.c, tests/conf-directive-gone-away.sh
closes https://github.com/rsyslog/rsyslog/issues/2880
=> provide better error information if gone-away config directive is used

plugins/imkafka/imkafka.c, plugins/omkafka/omkafka.c, tests/Makefile.am, tests/diag.sh, tests/imkafka.sh, tests/omkafka.sh, tests/sndrcv_kafka-vg-rcvr.sh, tests/sndrcv_kafka-vg-sender.sh, tests/sndrcv_kafka.sh, tests/sndrcv_kafka_fail.sh, tests/sndrcv_kafka_failresume.sh, tests/sndrcv_kafka_multi.sh, tests/sndrcv_kafka_multi_topics.sh, tests/testsuites/kafka-server.dep_wrk1.properties, tests/testsuites/kafka-server.dep_wrk2.properties, tests/testsuites/kafka-server.dep_wrk3.properties, tests/testsuites/kafka-server.properties, tests/testsuites/zoo.dep_wrk1.cfg, tests/testsuites/zoo.dep_wrk2.cfg, tests/testsuites/zoo.dep_wrk3.cfg, tests/travis/install.sh
Omkafka: 
- Fixed minor issue in omkafka producing wrong kafka timestamps when msgTimestamp was NULL. 
- Setting RD_KAFKA_V_KEY(NULL, 0) in rd_kafka_producev now when KEY is not configured. 
- Fixed minor issue when rsyslog is compiled with --enable-debug and librdkafka is to old. 
Testbench: 
- Using latest kafka server version again.
- Fixed server configuration issues holding the kafka tests back from working. 
- Fixed some config issues in all sndrcv kafka tests. 
- Generating dynamically kafka topics now for each kafka test.
- Testmessages back to 100000 working stable now with log.retention.hours=5000.
- Renabled kafka_multi test which runs a test on 3 kafka/zookeeper instances.
=> testbench: Added new kafka tests using kafkacat for better debugging.

plugins/imfile/imfile.c, runtime/ratelimit.c
The new input parameter delay.message has been added. It specifies a delay in microseconds after each line read.
closes https://github.com/rsyslog/rsyslog/issues/2960
=> imfile: experimental input throtteling feature

tests/sndrcv_relp.sh, tests/sndrcv_relp_dflt_pt.sh, tests/sndrcv_relp_rebind.sh, tests/sndrcv_relp_tls.sh, tests/sndrcv_relp_tls_prio.sh
imtcp was primarily used for historical reasons and is actually
to inferior method of injection messages for such cases
=> testbench: make imrelp tests faster and avoid imtcp

plugins/imkafka/imkafka.c
Fix imkafka can't parse hostname.
Add a option named "ParseHostName"(default is off) in imkafka, to maintain compatibility.
When ParseHostName = "on", a correct $hostname would be parsed.
=> fix imkafka can't parse hostname

plugins/imptcp/imptcp.c
=> imptcp: fixed pointers for session counting

runtime/queue.c
When having a disk-assisted queue without permission
to write to the specified queue file an error will
be put out.
closes https://github.com/rsyslog/rsyslog/issues/323
=> queue.c: add error if queue file can't be accessed

plugins/pmnormalize/pmnormalize.c, runtime/msg.c, tests/pmnormalize-rule-vg.sh
While parsing the message the reference count of the
json objects is incremented but was never decremented.
=> pmnormalize: fix memory leak

plugins/omrelp/omrelp.c, tests/Makefile.am, tests/omrelp_wrong_authmode.sh, tests/sndrcv_relp_tls_certvalid.sh
The new authmode certvalid for relp is now permitted in omrelp.
Test was also added.
=> omrelp: permit new authmode certvalid

configure.ac, plugins/imrelp/imrelp.c
closes https://github.com/rsyslog/rsyslog/issues/2938
=> imrelp: do not fail build if librelp does not have relpSrvSetLstnAddr

.codecov.yml, tests/CI/gcov.supp, tests/Makefile.am, tests/diag.sh
=> CI: add valgrind suppressions for -coverage gcc option

runtime/rsyslog.h, runtime/stream.c, runtime/stream.h, tests/Makefile.am, tests/imfile-truncate-multiple.sh
previously, truncation was only detected at end of file. Especially with
busy files that could cause loss of data and possibly also stall imfile
reading. The new code now also checks during each read. Obviously, there
is some additional overhead associated with that, but this is unavoidable.
It still is highly recommended NOT to turn on "reopenOnTruncate" in imfile.
Note that there are also inherant reliability issues. There is no way to
"fix" these, as they are caused by races between the process(es) who truncate
and rsyslog reading the file. But with the new code, the "problem window"
should be much smaller and, more importantly, imfile should not stall.
see also https://github.com/rsyslog/rsyslog/issues/1605
possibly replaces #3011
=> imfile: improve truncation detection

tests/Makefile.am, tests/ommail_errmsg_no_params.sh
not a very good test at the moment, but still better than none at all.
=> testbench: add very basic ommail test

tests/CI/buildbot_cleanup.sh
=> CI: clean hanging kafka and zookeeper instances on test startup

plugins/external/INTERFACE.md
The rsyslog module interface was not designed to support modules that
can act both as transactional and non-transactional according to
a configuration parameter. The old transaction interface (incidentally)
supports this, but it is not supported by the new transaction interface.
Therefore a future change is envisaged regarding this feature, that will
likely break backwards compatibility.
=> omprog: document 'useTransactions' flag as experimental

tests/sndrcv_kafka.sh
=> testbench: skip sndrcv_kafka.sh as it fails quite frequently

tests/Makefile.am, tests/omsnmp_errmsg_no_params.sh
currently only checks if module is loaded and checks for
required parameters correctly
=> testbench: add simple omsnmp test

tests/imfile-endmsg.regex-with-example.sh, tests/imfile-endregex-timeout-with-shutdown-polling.sh, tests/imfile-endregex-timeout-with-shutdown.sh, tests/imfile-endregex-timeout.sh, tests/imfile-freshStartTail2.sh, tests/imfile-rename.sh, tests/imfile-symlink.sh, tests/imfile-wildcards-dirs-multi.sh, tests/imfile-wildcards-dirs-multi2.sh, tests/imfile-wildcards-dirs-multi3.sh, tests/imfile-wildcards-dirs-multi4.sh, tests/imfile-wildcards-dirs-multi5-polling.sh, tests/imfile-wildcards-dirs-multi5.sh, tests/imfile-wildcards-dirs.sh, tests/imfile-wildcards-dirs2.sh, tests/imfile-wildcards.sh
- Fixed timing issues in some imfile wildcard/regex tests
- Added touch command in imfile wildcard tests to make sure directories exist before files are created in it if IO is under stress. 
- changed content checking in some tests to use "content_check_with_count" with check timeouts instead of using fixed sleeptimes.
=> testbench: fixed imfile parallel issues

tests/Makefile.am, tests/sndrcv_relp_dflt_pt.sh
Test was originally only executed when root tests were enabled,
which routinely was not the case. There was not even a hard reason
to handle it that way. Also, the test had a couple of defects which
have also been fixed.
closes https://github.com/rsyslog/rsyslog/issues/3064
=> testbench: re-enable test sndrcv_relp_dflt_pt.sh

tests/diag.sh
=> testbench: remove useless "cat" command (cosmetic)

tests/diag.sh
=> cleanup: replace legacy bash backticks by current $() syntax

.codecov.yml
.. as they are not testable under CI runs.
see also https://github.com/rsyslog/rsyslog/issues/3073
=> exclude KSI components from CodeCov

tests/Makefile.am, tests/queue-encryption-disk_keyfile.sh
=> QA: add test for queue.cry.keyfile parameter

tests/Makefile.am, tests/queue-encryption-disk_keyprog.sh
=> QA: add test for queue.cry.keyprogram parameter

tests/imjournal-basic-vg.sh, tests/imjournal-statefile.sh, tests/imkafka-vg.sh, tests/imkafka.sh, tests/imkafka_multi_many.sh, tests/imkafka_multi_single.sh, tests/sndrcv_kafka_fail.sh, tests/sndrcv_kafka_failresume.sh, tests/sndrcv_kafka_multi.sh
more or less cosmetic here, but anyhow...
detected by shellcheck
=> fix useless use of cat

runtime/queue.c, runtime/wtp.c, tests/diag.sh
The root cause was a deadlock during worker startup. This could
happen for example when a DA queue needed to persist data during
shutdown.
Fail condition:
* startup request for a new worker
* initialization of that worker
* immediate detection that the worker can or must shutdown
* main thread waiting for worker running state, which it skips,
and so the main thread hangs inside a loop
closes https://github.com/rsyslog/rsyslog/issues/3094
=> bugfix core: potential hang on rsyslog termination

tests/Makefile.am, tests/mmutf8fix_no_error.sh
closes https://github.com/rsyslog/rsyslog/issues/3070
=> mmutf8fix: add test for no error

runtime/libgcry.c, runtime/queue.c
If a crypto key is specified directly via the key="" parameter,
the storage for that key is not freed, causing a small memleak.
Note that the problem occurs only once per context, so this
should not cause real issues. Even more so, as specifying a
key directly is meant only for testing purposes and is strongly
discouraged for production use.
Detected by internal testing, no actual fail case known.
=> gcry crypto driver: small memleak

plugins/imrelp/imrelp.c, tests/Makefile.am, tests/imrelp-basic-oldstyle.sh
imrelp: Fixed issue with oldstyle configuration caused by commit:
https://github.com/rsyslog/rsyslog/commit/32b71daa8aadb8f16fe0ca2945e54d593f47a824
Fixed by setting bEnableLstn in addInstance().
Closes https://github.com/rsyslog/rsyslog/issues/3106
=> imrelp: Fixed issue with oldstyle configuration caused by commit:

tests/mangle_qi.c
=> cosmetic fix: mangle_qi test tool did not check mandatory arg

tests/diag.sh
If testbench test fails, a remote count call will be called using wget. 
The data is collected for stats monitoring in order to see which tests fail the most.
=> testbench: Added stats counter call for failed tests

runtime/errmsg.c
detected by codacy, instead added error message if vsnprintf fails.
=> errmsg: remove unnecessary if clause

tests/Makefile.am, tests/msleep_usage_output.sh
see also https://github.com/rsyslog/rsyslog/issues/3072
=> add test for msleep usage message

runtime/lib_ksils12.c
KSI LS12 module skips signing the last block in the file in some conditions
closes #3105
=> Bugfix: issue 3105, lmsig-ksils12 

runtime/queue.c
=> fix invalid assert location and improve error checking

runtime/queue.c
Also improve error checking. Detected by Codacy/cppcheck.
=> queue: fix invalid assert location

tests/Makefile.am, tests/tcpflood_wrong_option_output.sh
see also https://github.com/rsyslog/rsyslog/issues/3072
=> testbench: add test for tcpflood usage message

grammar/rainerscript.c
=> rainerscript: fix parentheses in if clause

plugins/mmsnmptrapd/mmsnmptrapd.c, plugins/omjournal/omjournal.c, runtime/msg.c, runtime/msg.h, tests/Makefile.am, tests/msg-deadlock-headerless-noappname.sh, tools/smfile.c, tools/smfwd.c, tools/smtradfile.c, tools/smtradfwd.c
can happen e.g. with headerless messages when app-name
property is used
closes https://github.com/rsyslog/rsyslog/issues/3135
=> bugfix core msg: potential deadlock (and rsyslog hang)

runtime/queue.c, runtime/wtp.c, runtime/wtp.h
=> shutdown: fix race in thread termination

.travis.yml, tests/diag.sh
**NOTE: before merging this, the buildbot config MUST be updated.** Otherwise, we disable stats reporting.
The newly introduced test status reporting now always tries to connect
to our stats server. This can be considered a privacy invasion and
also can wreck our stats. so make this optional and only happen when
an explicit URL is given. This can than be set in our CI environment.
request by setting stats reporting url env var RSYSLOG_STATSURL
closes https://github.com/rsyslog/rsyslog/issues/3144
=> testbench: do test error reporting only if requested

tools/strippedsymbols.exp
unfortunately, AIX does not export all public symbols (or I
consistently fail in trying to convince it...)
=> AIX portability: add missing symbol to export file

tests/imptcp_uds.sh
=> testbench: remove useless cat

runtime/queue.c, runtime/stream.c, runtime/stream.h, tests/diag.sh, tests/diskqueue.sh
due to some old regression (commit not exactly identified, but for
sure a regression, 9 years ago it was correct) an error message
is emitted when no .qi file exists on startup of the queue, which
is a normal condition.
Actually, the code should not have tried to open the .qi file in
the first place because it detected that it did not exist. That
(necessary) shortcut had been removed a while ago.
=> queue bugfix: invalid error message on queue startup

tests/diag.sh, tests/omkafka.sh
The test often misses messages. One idea is that rsyslog is actually
terminated too early, and thus messages are missing. To proove that idea,
we now explicitely wait for all messages to be processed.
If this does not work out, we should try to run kafkacat inside the
loop - maybe the librdkafka output port of omkafka is too slow.
=> testbench: try to make omkafka test more stable

autogen.sh
=> fix nit detected by shellcheck

tests/imfile-wildcards-dirs.sh, tests/imfile-wildcards-dirs2.sh, tests/timegenerated-dateordinal-invld.sh
=> testbench: cleanup bash codestyle

tools/rsyslogd.c
This happens only during auto-backgrouding, where we cannot any longer
access stderr. Whatever is opened with fd2 receives some debug messages.
Note that the specific feature is usually turned on only in CI runs.
=> core/debug: data written to random fd 2 under some debug settings

tests/Makefile.am, tests/diag.sh, tests/omkafka.sh
zookeeper startup was not actually checked, it was just hoped
that it started within 2 seconds (sleep). On busy systems, this
may be too short, thus results in an improper start and thus can
result in follow-on problems during the test.
We have now corrected it so that we wait until we see a pid. It's
still questionable if this is sufficient to conclude zookeeper is
really ready for processing. But let's take one step after the
other.
=> testbench: improve kafka test stability

tests/diag.sh, tests/omkafka.sh
This permits to flag some tests as being unreliable. If done so, CI
can treat them specially. This is meant to get rid of time-consuming
issues with known problematic tests, but still retain the ability to
gather trouble-shooting information. Later commits may extend the
functionality.
=> testbench: introduce concept of "unreliable" tests

tests/Makefile.am, tests/diag.sh, tests/tcpflood.c, tests/tcpflood_wrong_option_output.sh
tool may abort when TLS transport is specified by mandatory parameters
are not specified
closes https://github.com/rsyslog/rsyslog/issues/3176
=> bugfix tcpflood testing tool: improper parameter validation

tests/tcpflood.c
It is unlikley that this has caused a real issue, as long as pointers
are all of the same size (what is highly probable).
detected by cppcheck via Codacy.com
=> bugfix tcpflood: invalid type in calloc (openssl mode)

tests/CI/buildbot_cleanup.sh, tests/Makefile.am, tests/diag.sh, tests/imkafka-backgrounded.sh, tests/imkafka-config-err-param.sh, tests/imkafka-config-err-ruleset.sh, tests/imkafka-vg.sh, tests/imkafka.sh, tests/imkafka_multi_single.sh, tests/omkafka-vg.sh, tests/omkafka.sh, tests/sndrcv_kafka.sh
=> testbench: keep kafka/zookeeper running between tests

.codecov.yml
=> CodeCov: permit slight drop of coverage but still go "OK"

tests/diag.sh, tests/imptcp_large.sh
... and also fix some issue in test setup. This means the test has been
rewritten and now also support current script syntax. Bufferred i/o was
probably only used because of where it was copied from, and it was used
in a way that does not seem correct (iotimeout was set, but background
writing not activated).
=> testbench: stabilize imptcp_large test

tests/diag.sh
=> testbench: ensure failure stats error reporting always happens

tests/imjournal-basic-vg.sh
... it looks like it was accidently kept in "skip" state
=> testbench: re-enable journal test

tests/Makefile.am, tests/kafka-selftest.sh
We can now check if kafka's own tools also fail.
=> testbench: add self-test for kafka subsystem

tests/diag.sh
=> testbench: grep fails with option error in some tests

tests/Makefile.am, tests/mysqld-start.sh, tests/mysqld-stop.sh
This is required to run mysql/mariadb tests inside containers.
closes https://github.com/rsyslog/rsyslog/issues/3223
=> testbench: support auto-start/-stop of mysqld

configure.ac, plugins/imklog/Makefile.am, plugins/immark/Makefile.am, plugins/imtcp/Makefile.am, plugins/imudp/Makefile.am, plugins/imuxsock/Makefile.am, plugins/mmexternal/Makefile.am, plugins/omtesting/Makefile.am, runtime/Makefile.am, tools/Makefile.am
When liblogging-stdlog was available but configure option "--disable-liblogging-stdlog"
was set, rsyslog was still linking against liblogging-stdlog.
This commit will ensure that rsyslog will only link against liblogging-stdlog when
"--enable-liblogging-stdlog" was set.
Bug: https://bugs.gentoo.org/667836
=> build system: don't link liblogging-stdlog when available but not enabled

grammar/lexer.l, tests/Makefile.am, tests/diag.sh, tests/rscript_backticks_empty_envvar-vg.sh
checking that echo on non-exist env var does not abort rsyslog
see also https://github.com/rsyslog/rsyslog/issues/3006
=> testbench: add test for backticks parameters

grammar/lexer.l
The bug was introduced in commit abe0434 (config: enhance backticks "echo"
capability). The getenv() result passed to strlen() and es_addBuf() may be
NULL if the environment variable does not exist, resulting in a segfault.
This commit fixes Github issue #3006.
=> config: fix segfault in backticks "echo" expansion of undefined variables

runtime/wtp.c
while the leak is small, it looks like it points to a problem with
thread startup/shutdown synchronization
see also https://github.com/rsyslog/rsyslog/issues/2902
=> testbench: add debug support for hunting small memleak on shutdown

tests/diag.sh, tests/imfile-logrotate.sh, tests/imfile-rename.sh, tests/imfile-truncate-multiple.sh, tests/imkafka.sh, tests/imkafka_multi_single.sh, tests/imptcp_large.sh, tests/omkafka.sh, tests/sndrcv_udp_nonstdpt.sh
=> testbench: modernize "wait-file-lines" functionality

tests/diag.sh, tests/imjournal-basic.sh
working on removing potential race between journal forward latency
and rsyslog shutdown. Also adding additional debug information to
improve understanding of potentially upcoming new test failures.
see also https://github.com/rsyslog/rsyslog/issues/2564
=> testbench: try to make journal tests more reliable

plugins/imsolaris/imsolaris.c
On Solaris messages don't have their time directly in the raw body but in a separate *log_ctl* structure which is currently not used.
When message is logged and processed, rsyslogd gives it current time because it ignores the actual one. That means that old messages (e.g. from system reboot) get timestamp of processing instead of the reboot itself (it is not a problem for live logging where *now* is used anyway).
=> Fix message timestamps on Solaris

tests/Makefile.am, tests/mmjsonparse_extra_data-vg.sh
ensure that this case works well
closes https://github.com/rsyslog/rsyslog/issues/313
=> testbench: add test for mmjsonparse w/ unparsable data

tests/Makefile.am, tests/diag.sh, tests/urlencode.py
=> testbench: ensure error reporting params are urlencoded

tests/diag.sh, tests/sndrcv_kafka_multi_topics.sh
better we skip the test than create false positives due to kafka failure.
Also improve broken Broker check with additional possibilites.
This commit introduces the functionality to a subset of tests. Follow-up
commits may extend it to all kafka tests.
see also https://github.com/rsyslog/rsyslog/issues/3088
=> testbench: detected kafka failure during test run and SKIP if so

tests/diag.sh
otherwise, one may be puzzled why no report is generated. I just
experienced this on a misconfigured buildbot builder... ;-)
=> testbench: let user know if test failure reporting is not enabled

runtime/debug.c
first change of  #3227 trying to nail down why that one is failing.
=> fix small issue detected by cppcheck

tests/diag.sh, tests/libdbi-asyn.sh
=> testbench: make libdbi test more reliable

tests/tcpflood.c
=> bugfix tcpflood: remove-left over debug output

tests/diag.sh
Error reporting did not work as we still used the wrong path to our new
urlencode utility. Being a python app, it remains in $srcdir.
=> fix testbench error reporting under distcheck

runtime/wti.c
Seen while testing other things: the worker thread hard cancellation
handler may cause a hang when the to-be-cancled threat is not inside
a cancellable section. We now do an extra wakeup to avoid this.
=> core/wti: prevent potential hang in hard cancelation handler

runtime/wtp.c, tests/known_issues.supp, tests/mmpstrucdata-invalid-vg.sh
valgrind sometimes reports a leak on shutdown and we are still not sure
if this is a rsyslog bug or something in (some versions of) pthreads lib,
which simply should be suppressed. This adds additional debug info, to be
shown in CI runs, to hopefully help clarify the issue.
see also https://github.com/rsyslog/rsyslog/issues/2902
This also adds some other small testbench improvements.
=> try to solve shutdown memory leak

runtime/stream.c
This occurs always if and only if
- reopenOnTruncate="on" is set
- file grows over 2GiB in size
Then, the data is continously re-sent until the file becomes smaller
2GiB (due to truncation) or is deleted.
It is a regression introduced by 2d15cbc8221e385c5aa821e4a851d7498ed81850
closes https://github.com/rsyslog/rsyslog/issues/3249
=> bugfix imfile: rsyslog re-sends data for files larger 2GiB

tests/CI/gather_all_logs.sh
previously, it also picked test output files if they were left over. For
some test this meant very verbose data could be sent to buildbot master.
We have seen cases with over 20million lines, which made the log view
impossible. This has now been corrected.
=> buildbot: gather script shall not pickup $RSYSLOG_DYNNAME*.log files

tests/diag.sh, tests/imfile-basic-2GB-file.sh, tests/imfile-endregex-vg.sh, tests/imfile-readmode2-vg.sh, tests/imfile-truncate-2GB-file.sh
They did not work on FreeBSD because of an imfile bug which is
now fixed.
=> testbench: modernize some imfile tests, re-enable on FreeBSD

tests/diag.sh
This is primarily a cosmetic fix, as multiple core files should never
exist. The only exception might be parallel builds, but in this case
the whole concept does not work correctly (we may probably see into
that when we finally support parallel builds, which we do not yet).
detected by shellcheck
=> testbench: fix core file handling when multiple core files exist

tests/Makefile.am, tests/minitcpsrv_usage_output.sh
see also https://github.com/rsyslog/rsyslog/issues/3072
=> testbench: add test for minitcpsrv usage

tests/diag.sh, tests/omprog-restart-terminated-outfile.sh, tests/omprog-restart-terminated.sh, tests/uxsock_simple.sh
this does not work with parallel builds; replaced by
timing haning uxsockrcvr instances out.
=> testbench: do not cancel uxsockrcvr on test init

template.c
inside debug logging, the date property options were not all
properly converted into strings. Some of the newer ones were
invalidly flagged as "UNKNOWN". This is primarily a cosmetic
problem and has no effect other than puzzling folks looking at
the debug log.
=> bugfix debug output: date property options output wrongly

runtime/wti.c
hard cancellation occurs when an action does not terminate within
timeout; possible reasons are e.g. retry loop or hanging in lib call.
This most probably is a regression from recently introduce thread worker join code.
=> bugfix: rsyslog may hang during hard cancellation on shutdown

contrib/omhttp/omhttp.c
at least on CentOS 6 package build we see errors:
https://build.opensuse.org/package/live_build_log/home:jgerhards:branches:home:rgerhards/rsyslog/CentOS_6/i586
see also https://github.com/rsyslog/rsyslog/issues/3302
=> bugfix omhttp: does not compile on all platforms

plugins/imfile/imfile.c
The file/directory node-object alignment now ignores symlinks.
Previously it reported error on each directory symlink spamming
user error logs.
This may also allow for some more complicated use-cases, for example where symlink to dir is replaced with actual dir without rsyslog restart and similar operations.
closes #3291
=> disable file vs directory error on symlinks

tests/imfile-truncate.sh
see also https://github.com/rsyslog/rsyslog/issues/3232
=> testbench: instrument flaky imfile-truncate test to find flake cause

tests/omprog-output-capture-mt.sh, tests/omprog-output-capture-vg.sh, tests/omprog-output-capture.sh
=> testbench: harden omprog tests against CI timing

tests/Makefile.am
closes https://github.com/rsyslog/rsyslog/issues/3228
=> testbench: do not execute libgcrypt tests if disabled

plugins/omelasticsearch/omelasticsearch.c
=> elasticsearch: remove unnecessary if clause for free

tests/Makefile.am, tests/diag.sh, tests/tabescape_on.sh
changing one test from legacy style to current; still retain related
test in legacy style albeit not strictly ncessary.
see also https://github.com/rsyslog/rsyslog/issues/552
=> testbench: add tests for parser.EscapeControlCharacterTab global option

runtime/nsd_gtls.c, runtime/nsd_gtls.h, runtime/nsd_ossl.c, runtime/nsd_ossl.h, runtime/nsd_ptcp.c, runtime/nsdsel_ossl.c, runtime/queue.c, tests/es-basic-abort.sh, tests/es-basic-vgthread.sh, tests/es-execOnlyWhenPreviousSuspended.sh, tests/imptcp_large.sh, tests/imptcp_nonProcessingPoller.sh, tests/imptcp_veryLargeOctateCountedMessages.sh, tests/sndrcv.sh, tests/sndrcv_drvr_noexit.sh, tests/sndrcv_failover.sh, tests/sndrcv_gzip.sh, tests/sndrcv_omudpspoof.sh, tests/sndrcv_omudpspoof_nonstdpt.sh, tests/sndrcv_relp_rebind.sh, tests/sndrcv_tls_anon_hostname.sh, tests/sndrcv_tls_anon_ipv4.sh, tests/sndrcv_tls_anon_ipv6.sh, tests/sndrcv_tls_anon_rebind.sh, tests/sndrcv_tls_ossl_anon_ipv4.sh, tests/sndrcv_tls_ossl_anon_ipv6.sh, tests/sndrcv_tls_priorityString.sh, tests/sndrcv_udp.sh, tests/sndrcv_udp_nonstdpt_v6.sh, tools/omfwd.c
=> testbench: make tests more robust against races

tests/diag.sh, tests/wr_large_async.sh, tests/wr_large_sync.sh
also fix an issue with tests that use non-standard plumbing
=> testbench: make some more test more robust against slow CI machines

runtime/wtp.c
only when instructed to do so, rsyslog may emit a "final worker thread shutdown"
messages. This is usually only enabled in CI and/or other testing. If enabled,
the code has a race on the pWti object which can lead to segfault or abort.
Only system which explicitly enable this CI aid are affected (running in debug
mode alone is NOT sufficient).
=> fix a potential race in CI debug mode which can lead to segfault

runtime/nsd_ossl.c, tests/sndrcv_tls_anon_ipv4.sh, tests/sndrcv_tls_anon_ipv6.sh, tests/sndrcv_tls_anon_rebind.sh, tests/sndrcv_tls_ossl_anon_ipv4.sh, tests/sndrcv_tls_ossl_anon_ipv6.sh, tests/sndrcv_tls_ossl_anon_rebind.sh
OpenSSL Driver: Fixed authentication mode anon
Authmode and peer settings were set afer new TLS Session initialized.
This caused all sessions to be handeled with certvalid mode instead
of the configired authmode.
Changed verify_callback to only log certificate errors into debug
log now when anon authmode is configured.
Fixed sndrcv ossl tests by using mixed certificates now.
closes: #3037
=> OpenSSL Driver: bugfix authentication mode anon

tests/diag.sh, tests/es-basic-bulk.sh, tests/es-bulk-errfile-empty.sh
=> testbench: make some elasticsearch tests more robust f/ slow machines

tests/omprog-output-capture-mt.sh
=> testbench nitfix: remove unused imtcp module

runtime/stream.c
while in theory, the fd should immediately be rewritten, in practice
we sometimes see some errors "bad file descriptor" that we cannot
explain. So we clean this up to remove a potential trouble cause.
=> core/stream: always invalidate fd on file close

contrib/mmgrok/mmgrok.c
replaced questionable sprintf() by simpler method
=> mmgrok fix: build error w/ gcc-8 due to questionable code construct

configure.ac, tests/Makefile.am
we add configure switch --enable-helgrind. We need to turn helgrind off
when we use clang coverage instrumentation. The instrumentation injects
mt-unsafe counter updates which we seem to be unable to suppress.
Note: for gcc this was possible, because they all occured in a utility
function. For clang, they are inlined so we get many -and changing- violations.
see also https://github.com/rsyslog/rsyslog/issues/3361#issuecomment-450502569
=> build system: add capability to turn off helgrind tests

plugins/mmexternal/mmexternal.c, plugins/omprog/omprog.c, runtime/glbl.c, runtime/glbl.h, runtime/srutils.c, tests/omprog-restart-terminated-outfile.sh, tests/omprog-restart-terminated-vg.sh, tests/omprog-restart-terminated.sh, tests/testsuites/omprog-restart-terminated-bin.sh, tools/rsyslogd.c
Add new global setting 'reportChildProcessExits' with possible values
'none|errors|all' (default 'errors'), and new global function
'glblReportChildProcessExit' to report the exit status of a child
process according to the setting.
Invoke the report function whenever rsyslog reaps a child, namely in:
- rsyslogd.c (SIGCHLD signal handler)
- omprog
- mmexternal
- srutils.c (execProg function, invoked from stream.c and omshell)
Remove redundant "reaped by main loop" info log in omprog.
Promote debug message in mmexternal indicating that the child has
terminated prematurely to a warning log, like in omprog.
Closes #3281
=> report child process exit status according to config parameter

tools/omusrmsg.c
Since commit 56ace5e418d149af27586c7c1264fccfbc6badf1, omusrmsg was broken
because "memcpy()" is not a suitable substitute for "strncat()" in this
context, it is actually replacing the previous added content.
Bug: https://bugs.gentoo.org/673004
Closes: https://github.com/rsyslog/rsyslog/issues/3346
=> omusrmsg: don't overwrite previous set _PATH_DEV value

tests/Makefile.am, tests/imrelp-manyconn-vg.sh
We see this test segfault on Solaris and want some more insight
into why. This is probably also useful in the future.
=> testbench: add imrelp valgrind test

tests/clickhouse-start.sh
that way we at least know when someting goes wrong
=> testbench: check for clickhouse start success and complain on fail

tests/clickhouse-errorfile.sh, tests/clickhouse-wrong-insert-syntax.sh
some tests had "http:" included in their expected response, and thus
failed on TLS-secured systems. This has been fixed.
Note that the tests still depend on english language clickhouse error
messages. We could probably improve here as well.
=> testbench: remove some clickhouse test dependency against non-TLS

tests/clickhouse-basic.sh, tests/clickhouse-bulk-load.sh, tests/clickhouse-bulk.sh, tests/clickhouse-limited-batch.sh, tests/clickhouse-load.sh, tests/clickhouse-retry-error.sh, tests/clickhouse-select.sh, tests/clickhouse-wrong-insert-syntax.sh, tests/clickhouse-wrong-template-option.sh
Input source for clickhouse tests was changed to injectmsg
where it is possible. This will result in a shorter and easier
to read debug files and the tests won't fail duo to port problems
on the testbench.
=> changed input source for clickhouse tests

tests/imfile-wildcards-dirs-multi.sh, tests/imfile-wildcards-dirs-multi2.sh, tests/imfile-wildcards-dirs-multi3.sh, tests/imfile-wildcards-dirs-multi5.sh, tests/imfile-wildcards-dirs2.sh, tests/omfile-read-only.sh
=> testbench: fix minor nits in bash scripting

tests/imfile-logrotate.sh, tests/imfile-wildcards-dirs-multi.sh, tests/imfile-wildcards-dirs-multi2.sh, tests/imfile-wildcards-dirs-multi3.sh, tests/imfile-wildcards-dirs-multi4.sh, tests/imfile-wildcards-dirs-multi5-polling.sh, tests/imfile-wildcards-dirs-multi5.sh, tests/imfile-wildcards-dirs2.sh, tests/loop.sh, tests/mysql-actq-mt-withpause-extended.sh, tests/omprog-output-capture-mt.sh, tests/omprog-single-instance-outfile.sh, tests/omprog-single-instance.sh, tests/omprog-transactions-failed-commits.sh, tests/omprog-transactions-failed-messages.sh, tests/omprog-transactions.sh
=> testbench nitfixes: modernize arithmetic expressions

tests/diag.sh
=> testbench: increase main queue enq timeout (for slow machines)

tests/Makefile.am, tests/imfile-logrotate-copytruncate.sh, tests/imfile-logrotate-nocopytruncate.sh
Testing copytruncate and nocopytruncate options with logrotate.
copytruncate option need imfile "reopenOnTruncate" to be enabled!
closes https://github.com/rsyslog/rsyslog/issues/3053
=> testbench: Added new tests for imfile and logrotate

action.c, action.h
This parameter permits to set an upper limit on the growth of the
retry interval. This is most useful when a target has extended
outage, in which case retries can happen very infrequently.
closes https://github.com/rsyslog/rsyslog/issues/3401
=> action: add "action.resumeIntervalMax" parameter

runtime/queue.c
The previous default of 0 gave action queues no real chance to
shutdown - at the time they were applied, they were usually already
expired (computing the absolute timeout took a small amount of time).
So we change this now to 10ms, which still is very quick but gives
the queue at least a chance to shutdown itself. That in turn
smoothens the whole shutdown process.
If a very large number of action queues is used this may lead
to a very slightly longer shutdown time, albeit this is very
improbable.
=> change queue.timeoutshutdown default to 10 for action queues
