rsyslog/rsyslog

- .travis.yml
This PR will add basic Travis CI support.
> Initial Travis CI support added.

- runtime/glbl.c
- runtime/glbl.h
- runtime/nsd_gtls.c
enables GnuTLS indepth debugging
closes https://github.com/rsyslog/rsyslog/issues/219
> add global parameter "debug.gnutls"

- tests/Makefile.am
- tests/asynwr_deadlock_2.sh
- tests/testsuites/asynwr_deadlock_2.conf
Copy of the test deadlock with other parameters
> testbench: new test deadlock_2

- tests/Makefile.am
- tests/abort-uncleancfg-goodcfg.sh
- tests/testsuites/abort-uncleancfg-goodcfg.conf
test update Abort-uncleancfg-goodcfg
> Testbench: add test for $AbortOnUncleanConfig  (good case)

- plugins/mmjsonparse/mmjsonparse.c
Not sure if this is the correct way to go about this or not.  I have applications sending data to rsyslog which doesn't contain a syslog header.  Thanks!
> adding ability to use rawmsg for mmjsonparse

- plugins/imrelp/imrelp.c
- plugins/omruleset/omruleset.c
- plugins/omuxsock/omuxsock.c
- runtime/cfsysline.c
- runtime/errmsg.c
- runtime/errmsg.h
- runtime/queue.c
- runtime/rsconf.c
- runtime/rsyslog.h
- template.c
- tools/omdiscard.c
- tools/omfile.c
- tools/omfwd.c
- tools/ompipe.c
- tools/omusrmsg.c
- tools/rsyslogd.c
This is the main patch set to properly check for unclean configs. Some other modules need review as well, but this does not justify holding the merge into today's release.
> make "abort on unclean config" option work properly

- plugins/omkafka/omkafka.c
librdkafka provides an automatic partitioning function that will evenly split the produced messages into all partitions configured for that topic.
To use, set partitions.auto="on" in your omkafka action config. This is instead of specifying the number of partitions on the producer side, where it would be easier to change the kafka configuration on the cluster for number of partitions/topic vs on every machine talking to Kafka via rsyslog.
> omkafka: Add automatic partitioning

- runtime/glbl.c
closes https://github.com/rsyslog/rsyslog/issues/255
> non-void function setMaxLine does not return anything

- plugins/imjournal/imjournal.c
Looks like this got mixed up in 1ac20ff.
> imjournal: fix default message priority

- tests/threadingmq.sh
closes https://github.com/rsyslog/rsyslog/issues/229
> testbench: try to solve race by giving more time to settle

- plugins/imdiag/imdiag.c
- plugins/imgssapi/imgssapi.c
- plugins/imtcp/imtcp.c
- tcpsrv.c
- tcpsrv.h
added 'address' attribute for address based ip bind to imtcp module
> added 'address' attribute for IP based bind to imtcp module

- contrib/imczmq/README
- contrib/imczmq/imczmq.c
- contrib/omczmq/README
- contrib/omczmq/omczmq.c
* fixes for omczmq and imczmq
* fixes for documentation to track config parameter changes for omczmq and imczmq
* note, these are still experimental - needs better bad parameter handling and a little clean up around edge cases before they should be considered production - I'll get those ready for 8.10
> omczmq / imczmq fixes

- ChangeLog
- plugins/imuxsock/imuxsock.c
- plugins/pmciscoios/pmciscoios.c
- runtime/datetime.c
- runtime/datetime.h
- tools/pmrfc3164.c
Some specific to Aruba Networks equipment.
> pmrfc3164 upgrades

- runtime/cfsysline.c
- tools/rsyslogd.c
> Clear two small memleaks

- configure.ac
- runtime/msg.c
- runtime/rsyslog.h
- runtime/typedefs.h
This is a proposal for issue #304.  I'm guessing you don't want to pollute the system properties with those format settings, but thought I would take a shot anyway.  Thanks!
> Adding JSON output format options

- plugins/imfile/imfile.c
- plugins/imptcp/imptcp.c
- plugins/imrelp/imrelp.c
- plugins/imtcp/imtcp.c
- plugins/imudp/imudp.c
- plugins/pmciscoios/pmciscoios.c
- runtime/cfsysline.c
- runtime/librsgt_read.c
- runtime/rsconf.h
- runtime/rsyslog.h
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772490
> typo fix: paramter → parameter

- action.c
closes closes https://github.com/rsyslog/rsyslog/issues/395
> impstats: Readded failed statscounter incrementation in Action Queue

- plugins/imfile/imfile.c
- plugins/mmexternal/mmexternal.c
- plugins/omprog/omprog.c
- tests/diagtalker.c
- tests/minitcpsrvr.c
- tests/msleep.c
- tests/uxsockrcvr.c
Also fixed headers for Freebsd in test tools.
> FreeBSD: Fixed mulitple compile issues in plugins.

- plugins/imfile/imfile.c
When monitoring single files in inotify mode, a corruption of the
configuration filetable happened when the file was deleted.
The Active and Configuration table are sharing the same Listener
object when monitoring a single file. We check if the listener
object is present in the configured filetable before we delete it now.
closes https://github.com/rsyslog/rsyslog/issues/392
> imfile: Fixed file table corruption when monitoring single files

- runtime/srutils.c
- tools/omfile.c
The detection code actually never worked. This fixes the detection and an additional segfault mainly triggered by the race condition.
> Couple fixes for race condition detection in dynafiles

- plugins/omkafka/omkafka.c
This fixes a bug which allowed omkafka to get into a state where it wouldn't accept any new messages for publishing.
It also fixes a bug which whould manifest only when using dyntopic and when producer is in i-won't-accept-new-messages state, and caller tries to produce a new message. The dyn-topic-lock wouldn't be unlocked (because of premature fail-jump).
If you know librdkafka at a high level and are interested in details, here is a more detailed explaination:
So 'rk' tries to bound number of objects in flight by maintaining a counter, the max-value of which defaults to 100k. When a new message comes in, it rejects it if it already is at max-messages-in-flight. Now this counter is decremented (and in-flight-msg memory is freed) in callback-poll (which picks things from reply-queue, …
> fixes 2 bugs in omkafka

- tests/abort-uncleancfg-goodcfg.sh
- tests/diag.sh
> Several corrections to the testbench

- runtime/msg.c
see also https://github.com/rsyslog/rsyslog/issues/475
> fix potential race in variable access

- tools/omfwd.c
Add config options for client side keep-alives for tcp connections.
> Tcp client side keep alives

- runtime/nsdsel_gtls.c
Potential solution to issue described in [issue 318](https://github.com/rsyslog/rsyslog/issues/318)
> Potential fix for imtcp/TLS hangs on dropped packets

- contrib/omczmq/omczmq.c
As the titles says, this PR enables omczmq to publish to specific topics.
There is actually a bug, where the "" topic is not set, so whatever the first string is, it will be used by the pub socket as the topic.
> omczmq: implement topics for pub socket

- contrib/omhiredis/omhiredis.c
* This fixes a bug in config parsing when in template mode
> redis - fix template mode config switch

- plugins/external/solr/README.md
Added pretty much a complete guide on how to connect rsyslog with Solr (in an efficient way).
> Make usage clearer

- .gitignore
- runtime/lookup.c
- tests/Makefile.am
- tests/diag.sh
- tests/lookup_table.sh
- tests/testsuites/lookup_table.conf
- tests/testsuites/xlate.lkp_tbl
- tests/testsuites/xlate_more.lkp_tbl
It wasn't picking up new table-length.
> Fixed lookup-table reload bug

- README.md
I fixed a simple spelling mistake
> Fixing a spelling mistake

- plugins/imfile/imfile.c
Added bugfix from issue #534 regarding add/del file problem
Closes https://github.com/rsyslog/rsyslog/issues/534
Closes https://github.com/rsyslog/rsyslog/issues/532
> imfile: Added bugfix from issue #534 regarding add/del file problem

- tests/imfile-endregex.sh
- tests/imfile-readmode2-with-persists-data-during-stop.sh
- tests/imfile-readmode2-with-persists.sh
- tests/imfile-readmode2.sh
Only affects the tests using inotify, tests will be skipped when no
inotify is available.
> testsuite: Added detection script for inotify in imfile tests

- runtime/librsksi_read.c
Some minor changes:
* Fixed a typo
* Using KSI_getErrorMessage to debugging messages.
> Debug messages

- configure.ac
- runtime/librsksi.c
- runtime/librsksi.h
- runtime/librsksi_read.c
The latest libksi release has some compatibility breaking changes.
> libksi 3.4.0.1

- Makefile.am
- configure.ac
- contrib/mmgrok/Makefile.am
- contrib/mmgrok/README
- contrib/mmgrok/mmgrok.c
usecase metioned in https://github.com/rsyslog/liblognorm/issues/154
> new mmgrok plugin

- tests/imtcp_conndrop_tls-vg.sh
- tests/imtcp_conndrop_tls.sh
- tests/tcpflood.c
- tests/testsuites/imtcp_conndrop_tls.conf
imtcp TLS tests are now actually using TLS ;).
> Imtcp tlstests fix

- runtime/librsgt.c
- runtime/librsgt_common.h
- runtime/librsgt_read.c
- runtime/librsksi.c
- runtime/librsksi_read.c
Fixed multiple issues found using scan-build (clang)
> libksi/libgt: multiple memory leaks and clang issues fixed

- runtime/librsgt_read.c
- runtime/librsksi_read.c
Fixed other issues in ksi code found with clang.
> Ksi clang fixes again

- contrib/omczmq/omczmq.c
* sendtimeout now works properly on conjunction with suspend / resume
> omczmq: make sendtimeout not required with reasonable default

- .travis.yml
- ChangeLog
- configure.ac
- runtime/librsgt.h
- runtime/librsgt_read.c
- runtime/librsksi.c
- runtime/librsksi.h
- runtime/librsksi_read.c
- tools/rsgtutil.c
- tools/rsgtutil.rst
Multiple changes and fixed needed for new libksi version.
> Ksi libupdate

- .travis.yml
- Makefile.am
- configure.ac
- contrib/mmgrok/Makefile.am
- contrib/mmgrok/README
- contrib/mmgrok/mmgrok.c
- plugins/imjournal/imjournal.c
- template.c
includes some fixes to the build system as well as fixes to mmgrok itself.
Includes https://github.com/rsyslog/rsyslog/pull/681
DO NOT MERGE IF TRAVIS FAILS. We are trying to solve an issue with the build process.
> make mmgrok build under travis

- plugins/omkafka/omkafka.c
bases on problem identification done by Tait Clarridge
> omkafka: fix potentially negative partition number

- tests/Makefile.am
- tests/exec_tpl-concurrency.sh
- tests/testsuites/exec_tpl-concurrency.conf
... under concurrency conditions. Just to make sure we don't
we got all looking right.
> testbench: add test for exec_template

- .travis.yml
- ChangeLog
- tests/Makefile.am
includes https://github.com/rsyslog/rsyslog/pull/707 because we tested the new method with that PR
> Travis distcheck with testbench

- runtime/obj.c
- runtime/stream.c
- runtime/stringbuf.c
- runtime/stringbuf.h
closes https://github.com/rsyslog/rsyslog/issues/393
> Fix rsCStrGetSzStr

- .travis.yml
- plugins/imdiag/imdiag.c
- plugins/imklog/imklog.c
- plugins/imptcp/imptcp.c
- plugins/imudp/imudp.c
- plugins/imuxsock/imuxsock.c
- runtime/datetime.c
- runtime/datetime.h
- runtime/msg.c
- runtime/syslogd-types.h
- runtime/tcps_sess.c
- runtime/typedefs.h
- tests/Makefile.am
- tests/now_family_utc.sh
- tests/testsuites/now_family_utc.conf
closes https://github.com/rsyslog/rsyslog/issues/729
> Add system time properties in UTC

- plugins/imfile/imfile.c
Fixes # 718.
We also clean up whitespace in a separate commit so that `git diff --check` is helpful in the future.
> Remove bad use of inotify_event structure

- plugins/imfile/imfile.c
> Fix crash in frequently rotate

- ChangeLog
- plugins/imfile/imfile.c
This is a PR of my manual merges of #719, #720, #735 and some minor others (which are already integrated into master). This adds nothing new except ChangeLog entries. The main aim of this PR is to run the manual merge through travis before merging into master-candidate.
> Consolidated merges to imfile

- contrib/imczmq/imczmq.c
- runtime/lmcry_gcry.c
> imzmq: fix memory leak

- runtime/librsgt_common.h
- runtime/librsksi.c
- runtime/librsksi.h
- runtime/librsksi_read.c
- tools/rsgtutil.c
- tools/rsgtutil.rst
Closes https://github.com/rsyslog/rsyslog/issues/561
> Ksi extract tool

- .travis.yml
- ChangeLog
- plugins/mmutf8fix/mmutf8fix.c
- plugins/omelasticsearch/omelasticsearch.c
- plugins/pmciscoios/pmciscoios.c
includes some fixes, including https://github.com/rsyslog/rsyslog/pull/749
> Travis add elasticsearch

- plugins/omelasticsearch/omelasticsearch.c
- runtime/lmcry_gcry.c
- runtime/modules.c
- runtime/modules.h
- runtime/rsconf.c
- tools/rscryutil.c
new version of clang static analyzer seems to find some new issues...
> Fix statan findings

- plugins/imptcp/imptcp.c
- runtime/dynstats.c
- runtime/dynstats.h
- runtime/glbl.c
- runtime/glbl.h
- runtime/rsyslog.h
- runtime/statsobj.c
- runtime/statsobj.h
- runtime/tcps_sess.c
- tests/tcpflood.c
- tools/rsyslogd.c
doc still needs a brush-up; some tests wouldn't hurt, but maybe that requires framework changes (aka "maybe postpone tests")
This is for TCP only; support for UDP is under consideration.
closes https://github.com/rsyslog/rsyslog/issues/751
> add sender statistics and [dis]appearance warnings

- plugins/imuxsock/imuxsock.c
- tests/Makefile.am
- tests/imuxsock_logger_ruleset.sh
- tests/testsuites/imuxsock_logger_ruleset.conf
ruleset parameter is added at listener level
implements https://github.com/rsyslog/rsyslog/issues/765
> imuxsock: add support for rulesets

- runtime/libgcry.c
The static analyzer correctly complains about "garbagge
value being used", but this is exactly what we want. The
code in question is a fallback when we cannot obtain any
other source of randomness for cryptography needs.
> prevent a clang static analyzer warning

- .travis.yml
Added support to run mysql tests in travis.
> testbench: activated mysql tests for travis

- .travis.yml
extends https://github.com/rsyslog/rsyslog/pull/775
> travis: enable mysql tests

- plugins/imfile/imfile.c
We have use cases where people are using imfile to read in pure JSON files.  This pr adds an "addceetag" option to imfile that will prepend each line from a pure json log file with "@cee:" so that the contents can be used with mmjsonparse, etc.
> adds addceetag option to imfile

- plugins/omjournal/omjournal.c
As per #769 I wanted to transform log lines before they were sent to the journal. 
I've hacked about a bit, and have something that works, based on the ommongodb module. Each entry in the OMSR_TPL_AS_JSON is dumped into the journal. The caveat is that if you don't include a MESSAGE field, then you don't see anything useful.
```
template(name="journaljson" type="list"){
property(name="$!@message" outname="MESSAGE") 
property(name="$!@fields!levelname" outname="LEVEL") 
property(name="$!@fields!funcName" outname="CODE_FUNC")
property(name="$!@fields!lineno" outname="CODE_LINE")
property(name="$!@fields!filename" outname="CODE_FILE")
property(name="syslogtag" outname="SYSLOG_IDENTIFIER")
}
action(type="omjournal" template="journaljson")
```
If you don't provide a template, then the module …
> Adds simple templating to omjournal

- runtime/lookup.c
- runtime/lookup.h
- tests/Makefile.am
- tests/lookup_table_no_hup_reload-vg.sh
- tests/lookup_table_no_hup_reload.sh
- tests/testsuites/lookup_table_no_hup_reload.conf
It was somehow missed while implementing the proposal.
This PR adds impl and tests for it.
> added reloadOnHUP property to lookup-table object

- plugins/imfile/imfile.c
- runtime/stream.c
- runtime/stream.h
This is a merge of PR #664, which fast-forwards. Also, this way we run it through the updated travis testbench.
> Merge PR #664

- ChangeLog
- plugins/imfile/imfile.c
- runtime/rsyslog.h
see changelog patch for more details
> fix race bug in imfile

- plugins/ommongodb/ommongodb.c
We found it useful to provided a way to write real dates to mongo. For this case mongo has a extended json format https://docs.mongodb.org/v3.0/reference/mongodb-extended-json/#data_date
With this pull request we implement the extended date format handling in ommongodb plugin.
It would be great if you accept this pull request.
Best
Florian
> implemented extended json format for dates in ommongodb

- grammar/lexer.l
- outchannel.c
- runtime/msg.c
- template.c
- template.h
- tests/Makefile.am
- tests/json_var_case.sh
- tests/testsuites/json_var_case.conf
- tests/testsuites/variable_leading_underscore.conf
- tests/variable_leading_underscore.sh
main intent is to run PR #622 through updated travis testbench. Includes some fixes for merge conflicts occurred since PR was created.
> Merge PR #622

- plugins/imuxsock/imuxsock.c
- tests/Makefile.am
- tests/imuxsock_logger_ruleset_ratelimit.sh
- tests/testsuites/imuxsock_logger_ruleset_ratelimit.conf
fix regression (post 8.16.0) in imuxsock
> Bugfix imuxsock

- runtime/hashtable.c
- runtime/hashtable.h
closes https://github.com/rsyslog/rsyslog/issues/763
> slight improvement to hashtable handling

- runtime/dynstats.c
- runtime/dynstats.h
- tests/diag.sh
- tests/dynstats_overflow-vg.sh
- tests/dynstats_overflow.sh
- tests/testsuites/dynstats_overflow.conf
towards: https://github.com/rsyslog/rsyslog/issues/786
> improve resilience of dynstats_overflow-vg.sh

- .travis.yml
- Makefile.am
- configure.ac
- contrib/omamqp1/Makefile.am
- contrib/omamqp1/README.md
- contrib/omamqp1/omamqp1.c
Hello,
I'd like to contribute an output module I have written for use with AMQP 1.0 brokers.  I've tested this against the QPID broker, and the QPID Dispatch Router.
Thanks,
> Output Module for AMQP 1.0-compliant brokers

- README.md
Fix H3 & H4 headers formatting for proper github rendering.
> doc: fix H3 & H4 headers formatting

- threads.c
This is just a quick attempt to code-up some changes that I saw reviewing the thread termination handling.  I have to spend some more time thinking about this, but the gist of the changes is to work the non-cancel termination under a predicate loop over `bIsActive` to avoid spurious wakeups, only allowing the thread itself to change the state of `bIsActive`.
This passed all Travis checks in my tree, for what its worth (https://travis-ci.org/portante/rsyslog).
> EXPERIMENT: join always, except already exited, proper predicate loop

- ChangeLog
- runtime/datetime.c
- tests/Makefile.am
- tests/timegenerated-uxtimestamp-invld.sh
- tests/timegenerated-uxtimestamp.sh
- tests/timegenerated-ymd.sh
fixes https://github.com/rsyslog/rsyslog/issues/830
> fix leap year "unixtimestamp" computation

- runtime/datetime.c
- tests/Makefile.am
- tests/timegenerated-dateordinal-invld.sh
- tests/timegenerated-dateordinal.sh
> Testbench check date-ordinal format

- ChangeLog
- runtime/glbl.c
- runtime/glbl.h
- runtime/modules.c
- tests/Makefile.am
- tests/glbl-invld-param.sh
- tests/glbl-unloadmodules.sh
> Module unload param

- ChangeLog
- runtime/librsgt_read.c
- runtime/librsksi_read.c
- tools/rsgtutil.c
Fixes multiple KSI issues in rsgtutil
> Ksi extract update

- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/848
> improve json variable performance

- .travis.yml
- action.c
- runtime/librsgt.c
* move to clang-3.6, to get less false positives in static analyzer (unfortunatley, this does not work as well as we hoped)
* improve compiler warnings in compile-only stage
* some fixes for issues found
> improvements to travis CI

- tests/Makefile.am
- tests/faketime_common.sh
- tests/now-utc-casecmp.sh
- tests/now-utc-ymd.sh
- tests/now-utc.sh
- tests/now_family_utc.sh
- tests/timegenerated-dateordinal-invld.sh
- tests/timegenerated-dateordinal.sh
- tests/timegenerated-uxtimestamp-invld.sh
- tests/timegenerated-uxtimestamp.sh
- tests/timegenerated-ymd.sh
Proposal for https://github.com/rsyslog/rsyslog/issues/873
> Run year-2038 tests only on systems which supports those dates

- tests/travis/run.sh
... and do not abort before displaying it.
closes https://github.com/rsyslog/rsyslog/issues/887
> travis: emit make check error log on failure

- runtime/msg.c
- template.c
- template.h
- tests/Makefile.am
- tests/compresssp-stringtpl.sh
- tests/compresssp.sh
closes https://github.com/rsyslog/rsyslog/issues/861
> templates: add new option "compressspace"

- plugins/omkafka/omkafka.c
As of now, omkafka kills and re-creates kafka-producer on HUP. This is not always desirable. This change introduces an action param (reopenOnHup="on|off") which allows user to control re-cycling of kafka-producer. 
It defaults to on (for backward compatibility). Off allows user to ignore HUP as far as kafka-producer is concerned.
omkafka error-log-file is still re-opened on HUP (regardless of the value of this flag).
> omkafka: makes kafka-producer on-HUP restart optional

- runtime/glbl.c
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/rsyslog.h
- tests/Makefile.am
- tests/privdropgroup.sh
- tests/privdropgroupid.sh
- tests/privdropuser.sh
- tests/privdropuserid.sh
Note: this test fails as long as #892 is not merged (it tries to find what is fixed there). After merge, it should run smooth or something is wrong with either #892 or this patch.
> add testbench tests for $privdroptogroup

- tests/Makefile.am
- tests/sndrcv_relp_tls.sh
- tests/testsuites/sndrcv_relp_tls_rcvr.conf
- tests/testsuites/sndrcv_relp_tls_sender.conf
see also https://github.com/rsyslog/rsyslog/issues/907
> testbench: add basic test for RELP with TLS

- ChangeLog
- runtime/tcps_sess.c
- runtime/tcps_sess.h
- tests/Makefile.am
- tests/imtcp_incomplete_frame_at_end.sh
Add testbench test for https://github.com/rsyslog/rsyslog/pull/851
note: #851 is also included in this PR (to test the test ;))
> Testbench imtcp lastmsg

- contrib/omhttpfs/omhttpfs.c
* fix C++ style comments
* remove commented-out code
closes https://github.com/rsyslog/rsyslog/issues/677
> omhttpfs: code cleanup

- runtime/obj.c
- runtime/queue.c
- tests/Makefile.am
- tests/daqueue-invld-qi.sh
- tests/diag.sh
- tests/mangle_qi.c
see commit comments for details
> make queue subsystem somewhat more robust

- tests/Makefile.am
- tests/sndrcv_tls_anon.sh
> testbench re-enable some tests

- grammar/rainerscript.h
closes https://github.com/rsyslog/rsyslog/issues/937
> fix missing include file

- ChangeLog
- plugins/omjournal/omjournal.c
- plugins/ommongodb/ommongodb.c
- runtime/msg.c
@portante can you please have a look at the last commit (a21ff7e)
> omjournal cleanup

- runtime/net.h
closes https://github.com/rsyslog/rsyslog/issues/952
> fix macros which were improperly guarded against side-effects

- tests/Makefile.am
- tests/diag.sh
- tests/mmjsonparse-w-o-cookie-multi-spaces.sh
- tests/mmjsonparse-w-o-cookie.sh
see also https://github.com/rsyslog/rsyslog/issues/940
> testbench/mmjsonparse: test empty cookie

- tests/.gitignore
- tests/execonlywhenprevsuspended_multiwrkr.sh
> Fix testbench test

- tests/CI/README
- tests/CI/clang-check-sanitizer.sh
- tests/CI/try_merge.sh
this guards against integration problems across different
patches
> CI: add support for a try to merge with master

- .travis.yml
- tests/CI/try_merge.sh
- tests/travis/run.sh
this guards against cross-PR regressions and also ensures that our
newest travis settings are used
> travis: do a special run which merges with master

- plugins/imdiag/imdiag.c
Previously, we just did three checks with some longer waits in between.
This was insufficient to avoid races, as we saw in practice. Now we
have slightly changed that approach and require 10 times in a row
an empty queue to deduce it atcually is empty.
closes https://github.com/rsyslog/rsyslog/issues/688
> imdiag: avoid races in detecting queue empty status

- runtime/dynstats.c
- runtime/rsyslog.c
- runtime/statsobj.c
- runtime/tcpsrv.c
- runtime/wti.h
- runtime/wtp.h
- tools/omfile.c
This "leak" happes only immediately before shutdown, so it is not
a real leak. But it can get in our way when working with memory
debuggers.
> fix cosmetic memory leaks

- grammar/lexer.l
- grammar/rainerscript.c
- runtime/Makefile.am
- runtime/debug.c
- runtime/lookup.c
- runtime/queue.c
- tests/tcpflood.c
closes https://github.com/rsyslog/rsyslog/issues/987
> build system: fix missing RSRT_FLAGS assignment

- tests/diag.sh
shutdown detection was based on pid file, we should check the
actual pid. We can't use wait, because we want to be able to
timeout. This patch should fairly portable handle the situation.
closes https://github.com/rsyslog/rsyslog/issues/1005
> testbench: sometimes an instance hangs at end of test

- ChangeLog
- tests/faketime_common.sh
some final checks ;) and rebased to current master, which means we get the latest CI additions in the test run.
> Merge #995

- configure.ac
see also https://github.com/rsyslog/rsyslog/issues/1009
> configure can't find gss_acquire_cred on Solaris

- plugins/imdiag/imdiag.c
- runtime/srUtils.h
- runtime/srutils.c
Let us not merge this just yet. Have created this PR so I can see it build on fedora 23 (slowenv)
> more diagnostics around coordinating with stats-flush (in response to it still failing on very slow env)

- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/1017
> write pid file atomically

- runtime/stream.c
- tests/Makefile.am
- tests/imfile-endregex-save-lf.sh
Both patches together should give a clean CI run.
> Consolidated merge of 1021 and 1027

- runtime/stream.c
> imfile: append newline marker before the next line in a multiline message

- tests/Makefile.am
- tests/imfile-endregex-save-lf.sh
LF is placed incorrectly and missing after first line.
see also https://github.com/rsyslog/rsyslog/issues/843
Note: CI will fail, as the code is currently buggy (needs #1021)
> testbench: add test to check LF placement in imfile processing

- tests/travis/run.sh
Note: the testbench can currently not be run in parallel
> travis: speed up build via parallel build (make -j) where possible

- tests/diag.sh
this was introduced as a debug aid and is no longer needed
> testbench: cleanup verboseness

- runtime/parser.c
- runtime/parser.h
- tests/CI/buildbot_cleanup.sh
- tests/CI/gather_all_logs.sh
- tests/Makefile.am
- tests/diag.sh
- tests/imptcp-NUL-rawmsg.sh
- tests/imptcp-NUL.sh
- tests/imtcp-NUL-rawmsg.sh
- tests/imtcp-NUL.sh
- tests/imtcp-basic.sh
> Testbench: add tests for NUL byte handling

- contrib/imczmq/README
- contrib/imczmq/imczmq.c
- contrib/omczmq/README
- contrib/omczmq/omczmq.c
Work in progress PR for contrib/imczmq and contrib/omczmq for 8.19 release. Highlights:
* moved imczmq off of deprecated zloop api to zpoller
* support for new zeromq socket types when built against recent zeromq
* moved authentication setup to module level parameters as conflicting options in action level parameters would cause issues
> WIP! czmq: updates for imczmq and omczmq plugins

- runtime/stringbuf.c
- runtime/stringbuf.h
- tests/imfile-endregex-save-lf-persist.sh
includes PR https://github.com/rsyslog/rsyslog/pull/1029 to show the original cause is fixed. Replaces #1026.
> refactoring of stringbuf.c

- tests/Makefile.am
- tests/imfile-endregex-save-lf-persist.sh
- tests/imfile-endregex-save-lf.sh
This adds a test to reproduce the issue described in #874. Note that CI will fail, as we do not yet have a final fix for that case. This PR shall be merged only after that fix is available and together with it (to ensure good master branch builds including testbench).
> Reproduce imfile multiline message corruption.

- contrib/omhttpfs/omhttpfs.c
fix a more or less cosmetic complaint
> omhttpfs: solve clang static analyzer issue

- plugins/omelasticsearch/omelasticsearch.c
This adds plumbing as suggested by Joerg Heinemann and Radu Gheorghe,
but is otherwise untested. Chances are good it works. If you use it,
please let us know your experience and most importantly any bug
reports you may have.
closes https://github.com/rsyslog/rsyslog/issues/89
> omelasticsearch: add option to permit unsigned certs (experimentally)

- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/gzipwr_flushInterval.sh
- tests/gzipwr_flushOnTXEnd.sh
- tests/gzipwr_rscript.sh
see also https://github.com/rsyslog/rsyslog/issues/1054
> fix omfile async writing flush functionality

- grammar/lexer.l
- tests/Makefile.am
- tests/invalid_nested_include.sh
> check for invalid recursive inputs

- action.c
- runtime/rsyslog.h
- runtime/stream.c
- tests/Makefile.am
- tests/arrayqueue.sh
- tests/chkseq.c
- tests/diag.sh
- tests/minitcpsrvr.c
- tests/omfile-read-only.sh
- tests/tcp_forwarding_dflt_tpl.sh
- tests/tcp_forwarding_retries.sh
- tests/tcp_forwarding_tpl.sh
- tools/omfile.c
- tools/omfwd.c
This also includes testbench enhancements.
see #500, #974 for more details
> fix issues in action commitTransaction processing

- ChangeLog
- configure.ac
- plugins/omrelp/omrelp.c
tries to merge #1023, including some adaptions necessary
> Merge PR #1023

- tests/Makefile.am
- tests/empty-prop-comparison.sh
We had a forum post that this might be problematic, so we
did give it a try. As it turned out, everything works ok.
see also http://kb.monitorware.com/viewtopic.php?p=26755
> testbench: add test for comparison with empty string

- tests/Makefile.am
- tests/diag.sh
- tests/hostname-with-slash-dflt-invld.sh
- tests/hostname-with-slash-dflt-slash-valid.sh
- tests/hostname-with-slash-pmrfc3164.sh
- tests/hostname-with-slash-pmrfc5424.sh
- tools/pmrfc3164.c
pmrfc3164: add support for slashes in hostname
added parameter "permit.slashesinhostname" to support this
> Permit slash in hostname

- .travis.yml
- runtime/obj.c
- runtime/queue.c
- runtime/queue.h
- runtime/rsyslog.h
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/daqueue-dirty-shutdown.sh
- tests/diag.sh
- tests/travis/install.sh
This PR (when completed) contains both additional code as well as new testbench tests. It is submitted early in order to be able to use the buildbot test farm.
> improve disk queue reliability on dirty shutdown

- runtime/nsd_gtls.c
especially in the common case that a certificat file is not present.
The GnuTLS provided error messages is pretty misleading, so we now
check this ourselves.
Note that further improvements to TLS error reporting are desirable,
this fixes just one annoying case that frequently causes confusion.
> TLS forwarding: slightly improved error message

- configure.ac
- plugins/ompgsql/ompgsql.c
- tests/Makefile.am
- tests/pgsql-basic.sh
- tests/pgsql-template.sh
- tests/testsuites/pgsql-basic.conf
- tests/testsuites/pgsql-select-msg.sql
- tests/testsuites/pgsql-select-syslogtag.sql
- tests/testsuites/pgsql-template.conf
- tests/testsuites/pgsql-truncate.sql
> try to  merge #1087 to current code base

- README.md
Fix capitalization of some words, remove & add blank lines, improve style.
> Improve formatting in README.md.

- ChangeLog
new PR to merge #1109 with new buildbot testbench settings & updates
> Merge 1109

- contrib/omhiredis/omhiredis.c
* We check for the connection state when receiving replies
so that we don't try to free(NULL)
* We now close the redis connection if we fail to send logs, which
causes us to reconnect in tryResume
* Cleaned up the freeReply code in endTransaction and dropped the
replies array since it isn't actually used.
> WiP: Omhiredis now reconnects to redis after failure

- contrib/pmaixforwardedfrom/pmaixforwardedfrom.c
PR to run #1152 through the testbench with updated defs.
> Merge 1152

- contrib/pmaixforwardedfrom/pmaixforwardedfrom.c
if syslog in AIX started with "-s" option, AIX syslog adds only "From " instead of "Message
forwarded from "
> patch to handle "From " in AIX forwarded messages.

- plugins/imfile/imfile.c
- runtime/datetime.c
- runtime/datetime.h
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-endregex-timeout-none-polling.sh
- tests/imfile-endregex-timeout-none.sh
- tests/imfile-endregex-timeout-polling.sh
- tests/imfile-endregex-timeout.sh
> Imfile: add timeout feature

- runtime/stream.c
This runs #1161 through the full testbench, which required updates from master.
> Merge PR #1161

- runtime/srUtils.h
- runtime/srutils.c
- runtime/stream.c
- runtime/stream.h
see #1074 for more details
closes #1074
> Partial Merge of #1074

- runtime/stream.c
> imfile: abort in stream handler

- template.c
- tests/Makefile.am
- tests/template-json.sh
merge #1216, adding testbench test
> Merge #1216

- ChangeLog
- tests/Makefile.am
- tests/imfile-persist-state-1.sh
- tests/inputfilegen.c
see also https://github.com/rsyslog/rsyslog/issues/1239
> testbench: add test for object persisting

- runtime/net.c
- tests/Makefile.am
- tests/diag.sh
- tests/empty-hostname.sh
- tests/faketime_common.sh
- tests/override_gethostname.c
doing this via separate branches to get full testbench coverage as we evolve things in parallel.
> merge fixe for #1040 including new testbench

- runtime/librsksi.c
- runtime/lmsig_ksi.c
> merge #1236 with some extra functionality

- runtime/net.c
- tests/empty-hostname.sh
see also https://github.com/rsyslog/rsyslog/issues/1268
> doc: add description of what empty-hostname.sh test actually does

- tools/pmrfc3164.c
> Honor parseHostnameAndTag

- plugins/imudp/imudp.c
closes https://github.com/rsyslog/rsyslog/issues/1146
> imudp: limit rcvbufsize parameter to 1GiB

- Makefile.am
- configure.ac
- plugins/pmnull/Makefile.am
- plugins/pmnull/pmnull.c
- tests/Makefile.am
- tests/mmrm1stspace-basic.sh
- tests/pmnull-basic.sh
- tests/pmnull-withparams.sh
closes https://github.com/rsyslog/rsyslog/issues/1275
> pmnull: add null parser module

- grammar/grammar.y
- grammar/lexer.l
- grammar/rainerscript.c
- grammar/rainerscript.h
- runtime/ruleset.c
- tests/Makefile.am
- tests/rscript_ruleset_call_indirect-basic.sh
- tests/rscript_ruleset_call_indirect-invld.sh
- tests/rscript_ruleset_call_indirect-var.sh
- tests/testsuites/lookup_table_reload.conf
closes https://github.com/rsyslog/rsyslog/issues/1318
> rainerscript: implement new "call_indirect" statement

- contrib/imzmq3/README
- contrib/omczmq/README
- contrib/omczmq/omczmq.c
- contrib/omzmq3/README
WIP - DO NOT MERGE if this message is still  here :)
* support for publishing logs on multiple topics created via template using dynaKey option
* code cleanup
> new omczmq features

- tests/daqueue-persist.sh
see https://github.com/rsyslog/rsyslog/issues/1308
> testbench: temporarily disable daqueue-persist.sh test

- runtime/nspoll.c
closes https://github.com/rsyslog/rsyslog/issues/1343
> debug build: fix invalid assertion

- grammar/rainerscript.c
- plugins/imtcp/imtcp.c
- tests/Makefile.am
- tests/rscript_set_memleak-vg.sh
- tests/rscript_set_unset_invalid_var.sh
> fix issues with set/unset statements

- plugins/imuxsock/imuxsock.c
- runtime/msg.c
- runtime/obj.c
- runtime/queue.c
- runtime/stream.c
This is useful for tracking queue corruption.
> core: add additional debug output

- runtime/errmsg.c
- runtime/errmsg.h
- runtime/rsyslog.h
- runtime/srutils.c
create error message if chown fails on dir
> Errmsg on dir own chg err

- ChangeLog
- runtime/msg.c
> core: fix sequence error in msg object deserializer

- tests/Makefile.am
- tests/diskq-rfc5424.sh
DO NOT MERGE before #1404 bugfix is applied to master. Until then, it will always fail (by intent).
closes https://github.com/rsyslog/rsyslog/issues/1404
closes https://github.com/rsyslog/rsyslog/issues/1401
> testbench: add test for rfc5424 format and disk queue

- plugins/imfile/imfile.c
The check does not print warnings anymore if wildcards are used
in directory names.
> imfile: Fixed checkInstance when using wildcards in directorynames.

- ChangeLog
- runtime/glbl.c
- runtime/glbl.h
- runtime/msg.c
- tests/Makefile.am
- tests/imrelp-oversize-cc.sh
- tests/tcpflood.c
limit message length in core msg object
> Sanitizer longmsg fix2

- tests/tcpflood.c
closes https://github.com/rsyslog/rsyslog/issues/1426
> testbench: tcpflood failed to build if RELP support was disabled

- tools/rsyslogd.c
> added chdir call after successful chroot

- tests/Makefile.am
- tests/pmrfc3164-AtSignsInHostname.sh
- tests/pmrfc3164-AtSignsInHostname_off.sh
- tests/pmrfc3164-defaultTag.sh
- tests/pmrfc3164-msgFirstSpace.sh
- tests/pmrfc3164-tagEndingByColon.sh
- tools/pmrfc3164.c
> pmrfc3164: add tests

- action.c
... plus it will most probably not work at all if someone
comes along and uses it. So better to remove it.
closes https://github.com/rsyslog/rsyslog/issues/865
> remove ARRAY_PASSING mode, which is no longer used

- runtime/ratelimit.c
> added logging name of source of rate-limited messages

- plugins/imrelp/imrelp.c
> Honor imrelp input name if provided when submitting to impstats

- runtime/srutils.c
closes https://github.com/rsyslog/rsyslog/issues/1485
> fix build problem on MacOS

- runtime/rsyslog.h
- tests/Makefile.am
- tests/omfile_both_files_set.sh
- tools/omfile.c
also adds a test.
closes https://github.com/rsyslog/rsyslog/issues/1346
> omfile: add error if both file and dynafile are set

- plugins/imptcp/imptcp.c
- tests/imptcp_uds.sh
- tests/testsuites/imptcp_uds.conf
Adds similar functionality to `omfile` for setting file ownership and access permissions
> Add ability to set owner/group/access perms for imptcp uds

- grammar/rainerscript.c
- tests/rscript_num2ipv4.sh
> reverted str2num() bSuccess return to be consistent with past behavior

- runtime/glbl.c
not a solution but connected to #1491, and is nice to fix
> fixed MainqObj destruction

- plugins/omkafka/omkafka.c
> Add 'origin' field to 'omkafka' plugin stats output

- tools/rsyslog.conf.5
> updated manpage discard section

- plugins/imptcp/imptcp.c
- tests/Makefile.am
- tests/imptcp-connection-msg-disabled.sh
- tests/imptcp-connection-msg-received.sh
closes https://github.com/rsyslog/rsyslog/issues/1488
> imptcp: add optional connection tracking message

- runtime/net.c
replaces #1518
@rgerhards  I cloned it into my repo and will continue on it to find out why it hangs in some environments, I will close the original PR (from your repo)
> replaced gethostbyname() with getaddrinfo() call

- plugins/imtcp/imtcp.c
- runtime/tcps_sess.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/imtcp-maxFrameSize.sh
- tests/imtcp-msg-truncation-on-number.sh
- tests/imtcp-msg-truncation-on-number2.sh
add new parameter maxFrameSize
fix Problem with Segmentation Fault when iOctetsRemain is too big
add tests
> imtcp: add parameter maxFrameSize

- plugins/imfile/imfile.c
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-file-not-found-error.sh
- tests/imfile-fileNotFoundError-parameter.sh
As default imfile returns an error if file is not found, but if the parameter is set off then no error is returned.
Closes https://github.com/rsyslog/rsyslog/issues/1535
> imfile: add error message when file not found and parameter to disable the message

- plugins/imptcp/imptcp.c
closes https://github.com/rsyslog/rsyslog/issues/1266
> imptcp: add new parameter flowControl

- ChangeLog
> Fixed a typo in Changelog

- configure.ac
- plugins/imrelp/imrelp.c
depeds on https://github.com/rsyslog/librelp/pull/63
> Expose configuration for max data size in librelp

- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/165
> rsyslogd: delete unused command line options

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
This is a PR just for the sake of merging #1621 to current master, so that we get proper CI run. I didn't want to rebase the original contributor branch. Once this here goes through, #1621 will automatically be merged (so @allanpark please do **not** close it).
> mergePR for #1621

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
Fixed the tree height calculation in two places.
> Fixing issue #1621: fixing ksi ls12 tree height calculation

- runtime/tcpclt.c
- runtime/tcpclt.h
- tools/omfwd.c
closes https://github.com/rsyslog/rsyslog/issues/1602
> omfwd: add parameter "tcp_frameDelimiter"

- grammar/rainerscript.c
- plugins/imfile/imfile.c
- runtime/stringbuf.c
- template.c
see also: https://github.com/rsyslog/rsyslog/issues/1102
> multile modules: add better error messages when regcomp is failing

- plugins/omkafka/omkafka.c
Bug was found using new tests.
> omkafka: Adding messages to failed list while doAction is in retry mode

- runtime/msg.c
- tests/Makefile.am
- tests/msgdup.sh
> fix message garbling problem #1658

- plugins/imudp/imudp.c
- plugins/omudpspoof/omudpspoof.c
- runtime/net.c
- runtime/net.h
- tools/omfwd.c
overall improvement, including fix for #1665 -- see individual commits for details
> omfwd: fixes and enhancements in udp forwarding

- runtime/glbl.c
- runtime/glbl.h
- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/1670
> core: make rsyslog internal message rate-limiter configurable

- plugins/impstats/impstats.c
closes https://github.com/rsyslog/rsyslog/issues/1661
> impstats: add new ressoure counter "openfiles"

- plugins/imptcp/imptcp.c
closes https://github.com/rsyslog/rsyslog/issues/1664
> imptcp: framing/size errmsgs contain remote peer

- runtime/tcps_sess.c
closes https://github.com/rsyslog/rsyslog/issues/1676
> imtcp: framing/size errmsgs contain remote peer

- Makefile.am
- configure.ac
- plugins/pmnormalize/Makefile.am
- plugins/pmnormalize/pmnormalize.c
- runtime/msg.c
- runtime/msg.h
- runtime/rsyslog.h
- tests/Makefile.am
- tests/pmnormalize-basic.sh
- tests/pmnormalize-rule-vg.sh
- tests/pmnormalize-rule.sh
- tests/testsuites/pmnormalize-rule-vg.conf
- tests/testsuites/pmnormalize_basic.rulebase
Parser module that uses liblognorm to parse incoming messages.
> pmnormalize: new parser module

- runtime/rsyslog.c
- runtime/rsyslog.h
- runtime/wtp.c
This provides better insight into operational state of rsyslog and is useful
in monitoring system health.
> queue: provide informational messges on thread startup and shutdown

- plugins/imtcp/imtcp.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/sndrcv_tls_priorityString.sh
- tests/testsuites/sndrcv_tls_priorityString_rcvr.conf
- tests/testsuites/sndrcv_tls_priorityString_sender.conf
- tools/omfwd.c
closes https://github.com/rsyslog/rsyslog/issues/1093
> omfwd, imtcp: add possibility to use priority string

- plugins/external/skeletons/python/plugin.py
Minor typo correction in comments
> Typo correction

- plugins/mmanon/mmanon.c
- tests/Makefile.am
- tests/mmanon_random_32_ipv4.sh
- tests/mmanon_random_cons_32_ipv4.sh
- tests/mmanon_recognize_ipv4.sh
- tests/mmanon_simple_12_ipv4.sh
- tests/mmanon_simple_33_ipv4.sh
- tests/mmanon_simple_8_ipv4.sh
- tests/mmanon_zero_12_ipv4.sh
- tests/mmanon_zero_33_ipv4.sh
- tests/mmanon_zero_8_ipv4.sh
for more information, see https://github.com/rsyslog/rsyslog/issues/1723
closes https://github.com/rsyslog/rsyslog/issues/1717
closes https://github.com/rsyslog/rsyslog/issues/1720
> mmanon: rewrite ipv4-anonymization

- runtime/glbl.c
closes https://github.com/rsyslog/rsyslog/issues/1736
> core bugfix: cosmetic memory leak

- plugins/omelasticsearch/omelasticsearch.c
> Fix Elasticsearch response handling

- plugins/mmanon/mmanon.c
- tests/Makefile.am
- tests/mmanon_both_modes_compatible.sh
- tests/mmanon_random_128_ipv6.sh
- tests/mmanon_random_32_ipv4.sh
- tests/mmanon_random_cons_128_ipv6.sh
- tests/mmanon_random_cons_32_ipv4.sh
- tests/mmanon_recognize_ipv4.sh
- tests/mmanon_recognize_ipv6.sh
- tests/mmanon_simple_12_ipv4.sh
- tests/mmanon_simple_33_ipv4.sh
- tests/mmanon_simple_8_ipv4.sh
- tests/mmanon_zero_128_ipv6.sh
- tests/mmanon_zero_12_ipv4.sh
- tests/mmanon_zero_33_ipv4.sh
- tests/mmanon_zero_50_ipv6.sh
- tests/mmanon_zero_64_ipv6.sh
- tests/mmanon_zero_8_ipv4.sh
- tests/mmanon_zero_96_ipv6.sh
> mmanon: add support for ipv6 

- plugins/imptcp/imptcp.c
- runtime/tcps_sess.c
- tests/imptcp-oversize-message-display.sh
closes https://github.com/rsyslog/rsyslog/issues/1718
> imptcp/imtcp: include module name in error msg

- runtime/netstrms.c
- runtime/netstrms.h
- runtime/nsd_gtls.c
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- tests/sndrcv_tls_priorityString.sh
- tests/testsuites/sndrcv_tls_priorityString_sender.conf
fixes https://github.com/rsyslog/rsyslog/issues/1722
> imtcp: fix usage of priorityString

- configure.ac
- plugins/imjournal/imjournal.c
bumped corresponding systemd version dependency
> switching to persistent journal possible without rsyslog restart, 

- plugins/imjournal/imjournal.c
> Fixed possible segfault. 

- plugins/mmanon/mmanon.c
closes https://github.com/rsyslog/rsyslog/issues/1756
> mmanon: us a better rand function for randomization

- tests/diag.sh
- tests/sndrcv_kafka.sh
Fixes a problem of random kafka test failures in travis.
> Kafka dump failedtests

- plugins/imfile/imfile.c
- plugins/omkafka/omkafka.c
- runtime/msg.c
- runtime/msg.h
- runtime/stream.c
- runtime/stream.h
- tests/diag.sh
- tests/imfile-wildcards.sh
- tests/testsuites/imfile-wildcards.conf
This builds on #1633 but provides the fileoffset as start of message, not end of message.
Note: this includes PR #1633. Do **NOT** close #1633, it will automatically be merged and closed when this PR here is merged.
> implement fileoffset metadata

- plugins/omrelp/omrelp.c
- tests/Makefile.am
- tests/sndrcv_relp_rebind.sh
- tests/testsuites/sndrcv_relp_rebind_rcvr.conf
- tests/testsuites/sndrcv_relp_rebind_sender.conf
> omrelp: fix segfault when rebindinterval parameter is used

- plugins/ommysql/ommysql.c
- tools/omfwd.c
closes https://github.com/rsyslog/rsyslog/issues/1819
> ommysql: return error code on data failure

- plugins/ommysql/ommysql.c
- tools/omfwd.c
provides higher performance and better reliability;
module currently uses old-style interface with new-style emulation.
closes https://github.com/rsyslog/rsyslog/issues/1817
> ommysql: update to v8 transactional interface

- template.c
closes https://github.com/rsyslog/rsyslog/issues/1811
> template/bugfix: invalid template option conflict detection

- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/1794
> core bugfix: informational messages was logged with error severity

- plugins/ommysql/ommysql.c
> ommysql fixes

- action.c
- runtime/glbl.c
- runtime/ratelimit.c
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/wti.h
- tests/Makefile.am
- tests/action-tx-single-processing.sh
- tests/chkseq.c
- tools/rsyslogd.c
restores some recovery functionality we lost in a couple of 8.x builds.
closes #974
> Improvements / fixes to rsyslog core

- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/1866
> add debugging message showing end of startup

- plugins/imfile/imfile.c
- plugins/mmjsonparse/mmjsonparse.c
- runtime/rsyslog.h
- runtime/statsobj.c
Merging the remaining 2 relevant commits from PR #961 (see there for more details)
> imfile improvements

- runtime/queue.c
closes https://github.com/rsyslog/rsyslog/issues/1876
> queue: enhance error message

- plugins/imrelp/imrelp.c
- plugins/omrelp/omrelp.c
- runtime/tcpsrv.c
- tests/Makefile.am
- tests/relp_tls_certificate_not_found.sh
Fix Segmentation Fault when certificate is NULL
closes https://github.com/rsyslog/rsyslog/issues/1869
> omrelp/imrelp: fix certificate check

- tests/Makefile.am
- tests/imjournal-basic.sh
- tests/journal_print.c
this ensures that the module is at least loading and doing
part of its work.
see also https://github.com/rsyslog/rsyslog/issues/1895
closes https://github.com/rsyslog/rsyslog/issues/164
> testbench: implement basic test for imjournal

- grammar/rainerscript.c
- plugins/mmexternal/mmexternal.c
- plugins/omjournal/omjournal.c
- runtime/libgcry_common.c
- runtime/statsobj.c
- runtime/stream.c
- template.c
removed first commit from branch coverity-7 - let's see if it now runs through CI.
> coverity scan fixes, minus one which seems problematic

- plugins/omtesting/omtesting.c
> omtesting: flag use of rand() function as intentional (for Coverity)

- plugins/mmanon/mmanon.c
detected by coverity scan, CID 185418
> mmanon: fix potential NULL-pointer exception

- tests/CI/try_merge.sh
also fix issue with user name/email not set on merge
> testbench: make sure try_merge does not fail because of git settings

- runtime/msg.c
- runtime/rsyslog.h
refactored the method so that it consistent in all functions and easier
to follow. Most importantly, now an as simple as possible locking paradigm
of lock ... unlock within the function. Hopefully easier to understand
both for humans and static code analyzers.
> core/msg: refactor locking for json variable access

- grammar/rainerscript.c
Also fixes Coverity Scan CID 185357.
> improve error messages in case of failing to obtain group info

- runtime/wtp.c
- tests/diag.sh
- threads.c
improve debug information so that developer can easily find core dumps during CI runs
> improve core dumps during testbench runs

- tests/diag.sh
make sure we are not puzzled when things go wrong.
> testbench: detect and report error download kafka dependency

- runtime/statsobj.c
Detected by Coverity scan, CID 185395
> remove unnecessary code

- runtime/msg.c
- tests/Makefile.am
- tests/mmexternal-SegFault-empty-jroot-vg.sh
- tests/mmexternal-SegFault-vg.sh
- tests/testsuites/mmexternal-SegFault-mm-python.py
... which most importantly was triggerred by mmexternal (but could potentially be triggered by other uses as well)
closes https://github.com/rsyslog/rsyslog/issues/1822
probably replaces https://github.com/rsyslog/rsyslog/pull/2008 and https://github.com/rsyslog/rsyslog/pull/1837
> core/msg: fix segfault in MsgSetPropsViaJSON

- tests/mmanon_both_modes_compatible.sh
- tests/mmanon_random_128_ipv6.sh
- tests/mmanon_random_32_ipv4.sh
- tests/mmanon_random_cons_128_ipembedded.sh
- tests/mmanon_random_cons_128_ipv6.sh
- tests/mmanon_random_cons_32_ipv4.sh
- tests/mmanon_recognize_ipembedded.sh
- tests/mmanon_recognize_ipv4.sh
- tests/mmanon_recognize_ipv6.sh
- tests/mmanon_simple_12_ipv4.sh
- tests/mmanon_simple_33_ipv4.sh
- tests/mmanon_simple_8_ipv4.sh
- tests/mmanon_zero_128_ipv6.sh
- tests/mmanon_zero_12_ipv4.sh
- tests/mmanon_zero_33_ipv4.sh
- tests/mmanon_zero_50_ipv6.sh
- tests/mmanon_zero_64_ipv6.sh
- tests/mmanon_zero_8_ipv4.sh
- tests/mmanon_zero_96_ipv6.sh
closes https://github.com/rsyslog/rsyslog/issues/2017
> mmanon: enable tests on FreeBSD

- plugins/omprog/omprog.c
- runtime/lmcry_gcry.c
- runtime/netstrms.c
- runtime/statsobj.c
plus some truely cosmetic-only changes to silence Coverity scan.
> gcry crypto provider: improve error reporting

- plugins/omkafka/omkafka.c
omkafka does not release a mutex under some error conditions (most
notably out of memory on specific alloc calls). This leads to a hang
during actively processing messages or during shutdown (at latest).
This can only happen if dynamic topics are configured.
Detected by Coverity Scan, CID  185781 (originally 185721, detected
as a different issue by Coverity after code refactoring done in regard
to 185721 -- then the problem became more obvious).
> omkafka: fix potential hang condition

- runtime/modules.c
- runtime/modules.h
- tools/rscryutil.c
Detectec by Coverity scan, CID 185340
> rscryutil bugfix: decryption error potentially undetected

- plugins/omrelp/omrelp.c
>  omrelp: incorrect error handling 

- runtime/lookup.c
- runtime/ruleset.c
- tests/diag.sh
Trying to understand CID 185407, which looks like a false positive. On
the way to this, add attributation which could increase correctness of
compiler code unerstanding and trigger different set of error messages.
> lookup: improve code in regard to err detection at compile time

- plugins/omelasticsearch/omelasticsearch.c
Authentication credentials were not applied during health check,
permission to use unsigned CERTS was not applied to regular data
post.
Also done a bit refactoring to unify curl setup as much as possible.
fixes https://github.com/rsyslog/rsyslog/issues/1949
> omelasticsearch bugfix: some config params not consistenly applied

- plugins/omkafka/omkafka.c
> omkafka: make maxoutqsize resettable

- plugins/imkafka/imkafka.c
- plugins/omkafka/omkafka.c
- tests/sndrcv_kafka.sh
> omkafka: multiple fixes, among others big memory leak

- runtime/cfsysline.c
Detected by Coverity scan, CID 185387
> remove dead code

- plugins/imjournal/imjournal.c
Remove "time of check time of use" Coverity scan warning by refactoring
the code to directly try out things prior to just checking if we could.
Ultimately, we need to handle the same error (and already did so), so
there was little point in doing a check first.
Coverity scan CID 185500
> imjournal: refactor journal state file load

- runtime/net.c
Function used very old style and was hard to read. Now also supports
strucutred handling of exceptions.
see also https://github.com/rsyslog/rsyslog/pull/2049
see also https://github.com/rsyslog/rsyslog/issues/2040
> refactor create_udp_socket

- plugins/imkafka/imkafka.c
Getting the code more into rsyslog style, fixing up TODOs,
improving error reporting
> imkafka: better error reporting and code cleanup

- plugins/mmdblookup/mmdblookup.c
see also https://github.com/rsyslog/rsyslog/issues/1885#issuecomment-344882616
> mmdblookup: guard against potential libmaxminddb thread unsafeness

- configure.ac
- tests/Makefile.am
- tests/diag.sh
- tests/es-basic-abort.sh
- tests/es-basic-es6.0.sh
- tests/es-basic-vg.sh
- tests/es-basic.sh
- tests/testsuites/es-basic.conf
- tests/testsuites/es.yml
> testbench: improvements in elasticsearch testing

- plugins/omelasticsearch/omelasticsearch.c
closes https://github.com/rsyslog/rsyslog/issues/2023
> omelasticsearch cleanup: remove debugging helpers

- runtime/srutils.c
random() is known to be weak. Therefore, using /dev/urandom
is better, but only available on Linux.
closes https://github.com/rsyslog/rsyslog/issues/1937
> srutils: use better random function

- configure.ac
Please see the individual commits for details.
> Multiple Autoconf fixes

- plugins/external/messagemod/anon_cc_nbrs/anon_cc_nbrs.py
- plugins/external/messagemod/fac-sever-rewrite/fac-sever-rewrite.py
- plugins/external/skeletons/python/mm-python.py
- plugins/external/skeletons/python/plugin.py
- plugins/external/solr/rsyslog_solr.py
- plugins/external/spm/rsyslog_spm_custom_metrics.py
- tests/testsuites/mmexternal-SegFault-mm-python.py
Normalize Python shebang and improve portability.
> Normalize Python shebang and improve portability

- tests/rscript_parse_time_get-ts.py
> Fix to work on systems where Python 3.x is the default.

- runtime/lib_ksils12.c
BUGFIX: fixing regression bugs introduced by PR 2117 (reported by coverity)
> BUGFIX: fixing regression bugs introduced by PR 2117

- .travis.yml
- contrib/mmgrok/mmgrok.c
- contrib/omamqp1/omamqp1.c
- contrib/omtcl/omtcl.c
- grammar/lexer.l
- plugins/mmsnmptrapd/mmsnmptrapd.c
- plugins/pmnormalize/pmnormalize.c
- runtime/debug.h
- tests/travis/install.sh
- tests/travis/run-osx.sh
- tests/travis/run.sh
Not yet finished, but need access to full Buildbot slaves, thus the early PR!
> ensure gcc-7 can be used without problems for building rsyslog

- tools/rsyslogd.c
minor enhancement useful when troubleshooting libsystemd-related issues.
> add info if compiled with libsystemd to rsyslogd -v output

- CONTRIBUTING.md
- tests/hostname-with-slash-pmrfc3164.sh
- tests/imfile-endregex-timeout-none-polling.sh
- tests/imklog_permitnonkernelfacility_root.sh
- tests/imtcp-discard-truncated-msg.sh
- tests/mmnormalize_processing_test1.sh
- tests/pmnormalize-basic.sh
- tests/pmnormalize-rule-vg.sh
- tests/pmnull-basic.sh
- tests/pmnull-withparams.sh
- tests/pmrfc3164-AtSignsInHostname_off.sh
- tests/rscript_ipv42num.sh
- tests/rscript_num2ipv4.sh
- tests/rscript_str2num_empty.sh
- tests/rscript_trim.sh
- tests/template-json.sh
- tests/timegenerated-dateordinal-invld.sh
- tests/timegenerated-dateordinal.sh
- tests/timegenerated-utc.sh
- tests/timegenerated-uxtimestamp-invld.sh
- tests/timegenerated-uxtimestamp.sh
- tests/timereported-utc-legacy.sh
- tests/timereported-utc-vg.sh
- tests/timereported-utc.sh
... by fixing command lines that are not valid under BSD.
> testbench: enable more tests on BSD

- plugins/imuxsock/imuxsock.c
... of course only if this capability is used on systemd systems.
> imuxsock: report system socket name received from systemd

- contrib/mmcount/mmcount.c
- contrib/mmrfc5424addhmac/mmrfc5424addhmac.c
- contrib/mmsequence/mmsequence.c
- contrib/omamqp1/omamqp1.c
- contrib/omhiredis/omhiredis.c
- contrib/omrabbitmq/omrabbitmq.c
- contrib/omzmq3/omzmq3.c
- plugins/mmanon/mmanon.c
- plugins/mmdblookup/mmdblookup.c
- plugins/mmexternal/mmexternal.c
- plugins/mmfields/mmfields.c
- plugins/mmrm1stspace/mmrm1stspace.c
- plugins/mmutf8fix/mmutf8fix.c
- plugins/omkafka/omkafka.c
- plugins/ommongodb/ommongodb.c
Detected by Coverity scan, CID 185415
> omkafka: remove invalid duplicate code

- plugins/omtesting/omtesting.c
- runtime/libgcry.c
- tools/rscryutil.c
this is a step forward, but not everything yet done. Nevertheless
useful in itself.
> refactor core to unify random number generation

- plugins/mmexternal/mmexternal.c
regression from 8.31.0
fixes https://github.com/rsyslog/rsyslog/issues/2164
> mmextrenal: fix double-free

- plugins/omprog/omprog.c
When using the omprog plugin with a binary without arguments, argv[0] (the
name of the binary) is not set, causing binaries that depend on this value
being set to crash or misbehave.
This patch also mildly refactors omprog argv[] creations, albeit some more
refactoring would be useful.
fixes https://github.com/rsyslog/rsyslog/issues/1858
> omprog plugin: argv[0] not set when using binary without arguments

- runtime/srutils.c
streamline code, also fix Coverity scan ID 185877
> core: refactor parent directory creation function

- .travis.yml
- plugins/ompgsql/ompgsql.c
- runtime/msg.c
- runtime/msg.h
- runtime/rsconf.c
- tests/Makefile.am
- tests/pgsql-actq-mt-withpause-vg.sh
- tests/pgsql-actq-mt-withpause.sh
- tests/pgsql-basic-cnf6-vg.sh
- tests/pgsql-basic-cnf6.sh
- tests/pgsql-basic-threads-cnf6.sh
- tests/pgsql-basic-vg.sh
- tests/pgsql-template-cnf6-vg.sh
- tests/pgsql-template-cnf6.sh
- tests/pgsql-template-threads-cnf6.sh
- tests/pgsql-template-vg.sh
- tests/testsuites/pgsql-basic.conf
- tests/testsuites/pgsql-basic.sql
- tests/testsuites/pgsql-select-msg.sql
- tests/testsuites/pgsql-template.conf
- tests/testsuites/pgsql-truncate.sql
- tests/travis/run.sh
Fixes issue #1824, invalidates #1800, implements #895, #648, #818
> update postgres output module

- runtime/lib_ksils12.c
fixes https://github.com/rsyslog/rsyslog/issues/2218
> Issue $2218: lmsig_ksils12: fixing coverity issue 185331

- contrib/omzmq3/omzmq3.c
> omzmq3: use new errmsg interface

- tools/omfile.c
this permits to enable SUSPENDing dynafile actions. Traditionally,
SUSPEND mode was never entered for dynafiles as it would have blocked
overall processing flow. Default is not to suspend (and thus block).
closes https://github.com/rsyslog/rsyslog/issues/2236
> omfile: add module-global option "dynafile.donotsuspend"

- plugins/mmanon/mmanon.c
closes https://github.com/rsyslog/rsyslog/issues/2232
> mmanon: fix undefined behaviour

- contrib/mmsequence/mmsequence.c
> mmsequence: use new errmsg interface

- configure.ac
- grammar/rainerscript.c
currently, this disables the http_request() script function
see also https://github.com/rsyslog/rsyslog/pull/2146#issuecomment-352412933
see also https://github.com/rsyslog/rsyslog/pull/2146#issuecomment-352413248
> build: permit to disable libcurl for rsyslog core

- grammar/rainerscript.c
- tests/Makefile.am
- tests/rscript_str2num_negative.sh
Thanks to Stephen Workman for providing a very detailled hint of the
problem and root cause. This patch bases on his recommendation for a
fix.
closes https://github.com/rsyslog/rsyslog/issues/2255
> script engine: improper string-to-number conversion for negative numbers

- grammar/lexer.l
- plugins/impstats/impstats.c
- plugins/imptcp/imptcp.c
- plugins/imuxsock/imuxsock.c
- plugins/mmexternal/mmexternal.c
- plugins/omkafka/omkafka.c
- runtime/lookup.c
- runtime/nsd_ptcp.c
- tools/rsyslogd.c
- tools/syslogd.c
> import BSD project and Solaris patches

- plugins/imfile/imfile.c
Code often used old-style interface where the caller needed to decode
errno. This is no longer necessary and has been cleaned up.
> imfile: directly provide errno to LogError where possible

- plugins/omkafka/omkafka.c
closes https://github.com/rsyslog/rsyslog/issues/2168
> omkafka bugfix: build fails with older versions of librdkafka

- plugins/imptcp/imptcp.c
- runtime/nsd_ptcp.c
see also https://github.com/rsyslog/rsyslog/issues/352#issuecomment-352667294
> replace SOL_TCP by portable equivalent IPPROTO_TCP

- plugins/omgssapi/omgssapi.c
closes https://github.com/rsyslog/rsyslog/issues/2097
> omgssapi: fix build problems

- contrib/omhttpfs/omhttpfs.c
see also https://github.com/rsyslog/rsyslog/pull/2259
> omhttpfs: use new errmsg interface

- plugins/imfile/imfile.c
> imfile: fix minor issues

- runtime/glbl.c
The way the default was set could lead to a race if e.g. two internal
messages were emitted at startup when the property was not yet set. This
has been seen to happen in practice. It had no bad effect except a very
small stationary memory leak, but made using thread analyzers unreliable
(as it was rightfully detected as a problem).
closes https://github.com/rsyslog/rsyslog/issues/2012
> core bugfix: race on LocalHostIP property during startup

- contrib/mmrfc5424addhmac/mmrfc5424addhmac.c
see also: https://github.com/rsyslog/rsyslog/issues/1684
> mmrfc5424addhmac: use new errmsg interface

- .github/ISSUE_TEMPLATE.md
Provide an issue template that helps getting all necessary information together in one shot. Should be an aid to both users and developers.
> github: add issue template to project

- plugins/mmanon/mmanon.c
closes https://github.com/rsyslog/rsyslog/issues/2243
> mmanon: fix undefined behavior

- plugins/imfile/imfile.c
> imfile: use new errmsg interface

- runtime/rsconf.c
> rsconf: use new errmsg interface

- plugins/imfile/imfile.c
Note: CI may fail as we have discovered at least one bug in imfile https://github.com/rsyslog/rsyslog/issues/2271 -- this is not a reason not to merge.
> imfile: some improvements

- runtime/lookup.c
Fixes unsigned-underflow part of #2295
> Fix lookup-table unsigned underflow lookup-table comparators

- runtime/lookup.c
> lookup: use new errmsg interface

- plugins/imfile/imfile.c
this is just the beginning of a needed larger refactoring/bug fixing
effort. It's useful in it's own and should be run trough testing.
> imfile: some basic refactoring plus some TODO items added

- .travis.yml
- plugins/imuxsock/imuxsock.c
- runtime/hashtable.c
... plus a couple of fixes to solve issues UBSan detected.
> Add UBSan to CI runs

- configure.ac
commit ad8bdb06f0079cc78e5028641f8d780a056d0f69 did the
wrong thing, fixing it here.
> build system: fix libczmq requirement

- contrib/omrabbitmq/omrabbitmq.c
> omrabbitmq: use new errmsg interface

- plugins/imkafka/imkafka.c
if rdkafka handle cannot fully populated, cleanup is added. Previously, we
could leak a handle if e.g. no brokers were avaiable. Note that this was
a cosmetic leak, as proper processing is not possible in any case and the
leak is once per listener, so not growing. But we now also ensure that
proper error reporting and handling is done in any case. Previously, we
may have some misleading error messages if the defunct kafka handle was
used.
closes https://github.com/rsyslog/rsyslog/issues/2084
> imkafka: fix potential small ressource leak

- runtime/tcpsrv.c
> tcpsrv: use new errmsg interface

- contrib/omhiredis/omhiredis.c
if userpush is on, RPUSH will be use instead of LPUSH
closes https://github.com/rsyslog/rsyslog/issues/1625
> omhiredis: add option to use RPUSH instead of LPUSH

- plugins/omkafka/omkafka.c
- tests/diag.sh
- tests/sndrcv_kafka.sh
- tests/testsuites/sndrcv_kafka_sender.conf
among others, fixes https://github.com/rsyslog/rsyslog/issues/2313
Note: PR will most probably ammended by additional commits. Need early access to CI system.
> omkafka: refactor and fixes

- runtime/gss-misc.c
> gss-misc: use new errmsg interface

- plugins/omkafka/omkafka.c
omkafka emits many useful operational status messages only to the debug
log. After careful review, we have exposed many of these as user error
and warning message (ex: librdkafka queue full, so user knows why we
suspend the plugin temporarily). This may have made the module too
chatty. If so, one can always filter out messages via configuration. And
if we really went overboard, we can undo those parts with the next
release. So IMHO it's better to give a bit more than less, as this
definitely eases troubleshooting for users.
closes https://github.com/rsyslog/rsyslog/issues/2314
> omkafka: expose operational status to user where useful

- runtime/cfsysline.c
> cfsysline: se new errmsg interface

- plugins/imfile/imfile.c
if set, files will be input in a sorted order
closes https://github.com/rsyslog/rsyslog/issues/1489
> imfile: add sortfiles parameter

- grammar/lexer.l
- grammar/rainerscript.c
- runtime/msg.c
- tests/Makefile.am
- tests/rscript_bare_var_root-empty.sh
- tests/rscript_bare_var_root.sh
closes https://github.com/rsyslog/rsyslog/issues/326
> config processing: bare variable root access not permitted

- action.c
Triggering condition:
* output module using the legacy transaction interface
(e.g. omelasticsearch, omlibdbi)
* output module needs to suspend itself
In these cases, rsyslog enters a busy loop trying to resolve the
suspend condition. The bug is rooted in rsyslog core action code.
This patch fixes it by inserting a 1-second sleep during calls
to the resume handler.
Note: we cannot sleep exactly as long as tryResume needs. This
would require larger refactoring, which probably is not worth for
the legacy interface. The current solution is almost as good, as
the one second sleep has very little overhead on a real system.
Thus we have choosen that approach.
This patch now also ensures that failed messages are properly
handled and do not cause eternal hang.
closes …
> core/action bugfix: 100% CPU utilization on suspension of output module

- runtime/conf.c
> conf: use new errmsg interface

- configure.ac
- tests/msleep.c
closes https://github.com/rsyslog/rsyslog/issues/2365
> build system: fix build of testbench tools under Alpine Linux

- plugins/mmpstrucdata/mmpstrucdata.c
- tests/mmpstrucdata-case.sh
- tests/testsuites/mmpstrucdata-case.conf
This makes the functionality provided by #2181 optional and thus makes us able to merge it.
> Merge PR #2181

- plugins/mmpstrucdata/mmpstrucdata.c
- tests/Makefile.am
- tests/mmpstrucdata-case.sh
- tests/testsuites/mmpstrucdata-case.conf
please also see Adiscon [36205--786c48a]
> case preservation for RFC5424 SD-PARAMs

- runtime/modules.c
> modules: use new errmsg interface

- runtime/tcps_sess.c
> tcps_sess: use new ermsg interface

- runtime/lookup.c
Detected by Coverity scan, CID 185407
> lookup: fix dead code (caused no harm)

- runtime/dnscache.c
> dnscache: use new errmsg interface

- runtime/datetime.c
> datetime: use new errmsg interface

- runtime/srutils.c
- tests/Makefile.am
- tests/omprog-multiparam-vg.sh
> fix issues in external command line parser

- runtime/rsyslog.h
- tests/diag.sh
- tests/omfwd-keepalive.sh
- tools/rsyslogd.c
In theory, TZ should be set by the OS. Unfortuantely, this seems
to be not the case any longer on many Linux distros. We now check
it and set it appropriate if not already given.
closes https://github.com/rsyslog/rsyslog/issues/2054
> core: set TZ on startup if not already set

- runtime/ruleset.c
> ruleset: use new errmsg interface

- runtime/obj.c
see aso https://github.com/rsyslog/rsyslog/issues/1684
> obj: use new errmsg interface

- runtime/lmcry_gcry.c
> lmcry_gcry: use new errmsg interface

- grammar/lexer.l
detected by Coverity Scan, CID 187116
> config: fix file handle leak in backtick parameters

- grammar/rainerscript.c
- grammar/rainerscript.h
- runtime/ruleset.c
> config: optimize-out totally empty "if" statements

- runtime/nsd_gtls.c
> nsd_gtls: use new errmsg interface

- .travis.yml
- tests/Makefile.am
re-enable macOS builds, temporarily disable a test
> Travis: "tactical" modifications

- runtime/dynstats.c
> dynstats: use new errmsg interface

- runtime/glbl.c
> glbl: use new errmsg interface

- plugins/imjournal/imjournal.c
WIP: psuedo code for fix to reloading journal after journald rotates its internal journal files.
> Fix to reloading journal

- runtime/stream.c
> stream: use new errmsg interface

- runtime/statsobj.c
> statsobj: use new errmsg interface

- tools/rsyslogd.8
unless it's a mnemonic to remember "-N"
> Fix typo rsyslogd.8

- runtime/nsdpoll_ptcp.c
> nsdpoll_ptcp: use new errmsg interface

- template.c
- tests/Makefile.am
- tests/template-const-jsonf.sh
Testbench test and doc is missing; early state uploaded to gain full testbench access.
closes https://github.com/rsyslog/rsyslog/issues/2348
> core/template: add format jsonf to constant template entries

- compat/strndup.c
- template.c
- template.h
- tests/Makefile.am
- tests/diag.sh
- tests/template-pure-json.sh
This enables easy JSON generation via template.
closes https://github.com/rsyslog/rsyslog/issues/2347
> template: add option to generate json "container"

- runtime/parser.c
> parser: use new ermsg interface

- grammar/rainerscript.c
this is to estabilsh a common interface for all rainerscript functions
to enable calling them via function pointer (to be done
at a later stage).
> rscript: refactor all functions

- runtime/stream.c
- tests/Makefile.am
- tests/imfile-readmode0-vg.sh
see also https://github.com/rsyslog/rsyslog/issues/2421
> fix memory leak in imfile readmode 0

- tests/testsuites/sndrcv_relp_sender.conf
now also given action a name for easier debug log check
> nitfix: test included invalid parameter

- plugins/omelasticsearch/omelasticsearch.c
This allows omelasticsearch to perform client cert based authentication
to Elasticsearch.
Add the following parameters:
`tls.cacert` - Full path and filename of the file containing the CA cert
for the CA that issued the Elasticsearch server(s) cert(s)
`tls.mycert` - Full path and filename of the file containing the client
cert used to authenticate to Elasticsearch
`tls.myprivkey` - Full path and filename of the file containing the client
key used to authenticate to Elasticsearch
> omelasticsearch - add support for CA cert, client cert auth

- Makefile.am
- configure.ac
- grammar/rainerscript.c
- grammar/rainerscript.h
- plugins/fmhttp/Makefile.am
- plugins/fmhttp/fmhttp.c
- runtime/module-template.h
- runtime/modules.c
- runtime/modules.h
- tests/Makefile.am
- tests/rscript_http_request-vg.sh
- tests/rscript_http_request.sh
- tests/rscript_num2ipv4.sh
- tests/rscript_re_match.sh
function modules add functions to rainerscript dynamically,
change http_request into such a module (enabled by default).
This module can be used as a sample for future function modules.
> rscript: make function modules loadable

- configure.ac
- tests/travis/travis-run-compile-tests.sh
> CI: test build of all components without atomic operations

- plugins/imfile/imfile.c
- runtime/stream.c
- runtime/stream.h
- tests/imfile-endregex-timeout-with-shutdown-polling.sh
- tests/imfile-readmode2-with-persists-data-during-stop.sh
We change it to json and also change the way it is stored and loaded.
This sets base to additional improvements in imfile.
closes https://github.com/rsyslog/rsyslog/issues/2529
> imfile: refactor state file format

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/imfile-old-state-file.sh
- tests/testsuites/imfile-old-state-file_imfile-state_.-rsyslog.input
see also https://github.com/rsyslog/rsyslog/issues/2231#issuecomment-376862280
> imfile: re-enable support for readind old-style state files

- tests/imjournal-basic-vg.sh
- tests/imjournal-basic.sh
For some unknown reason, the check if data really was forwarded from
the journal was missing.
> testbench bugfix: journal tests did not actually check for success

- Makefile.am
- configure.ac
- contrib/omfile-hardened/Makefile.am
- contrib/omfile-hardened/omfile-hardened.c
- runtime/rsyslog.h
> merge #2490 as experimental module

- plugins/imuxsock/imuxsock.c
gcc would (rightly) complain that the cred and ts pointers
would cause alignment problems, so they were converted to structs
and the necessary data was memcpy()'ed to them.
the aux[] buffer was also potentially misaligned, so making a union
out of it and struct cmsghdr insured it was properly aligned.
The problems were especially visible on alpha and ia64 machines:
```
[6143331.481422] ia64_handle_unaligned: 2 callbacks suppressed
[6143331.481463] in:imuxsock(31387): unaligned access to 0x2000000000e2e554, ip=0x20000000008594c0
[6143331.481519] in:imuxsock(31387): unaligned access to 0x2000000000e2e55c, ip=0x20000000008594e0
```
> Fix data alignment problems in plugins/imuxsock/imuxsock.c

- tests/Makefile.am
- tests/omfile-null-filename.sh
- tests/omfile-whitespace-filename.sh
- tools/omfile.c
closes https://github.com/rsyslog/rsyslog/issues/2417
> omfile bugfix: segfault when empty filename is given

- runtime/lmsig_ksi-ls12.c
> lmsig_ksi-ls12: use new errmsg interface

- devtools/check-codestyle.sh
files which have the correct style are checked so that no
style errors are created with new pull requests.
> codestyle: check files that have correct codestyle

- runtime/nsdsel_gtls.c
> nsdsel_gtls: use new errmsg interface

- tools/omusrmsg.c
> omusrmsg: use new errmsg interface

- runtime/lib_ksi_queue.c
- runtime/lib_ksils12.c
> lmsig_ksils12: fixing issues 2517 and 2621

- tools/rsyslogd.c
> rsyslogd: use new errmsg interface

- plugins/impstats/impstats.c
- plugins/mmjsonparse/mmjsonparse.c
- runtime/nsdsel_gtls.c
- tests/Makefile.am
- tests/mmjsonparse-invalid-containerName.sh
- tests/mmjsonparse_cim2.sh
- tests/mmjsonparse_localvar.sh
see also https://github.com/rsyslog/rsyslog/issues/2584
> add test for invalid container name in mmjsonparse

- tools/omshell.c
> omshell: use new errmsg interface

- tools/omfwd.c
To allow the same source address to be used regardless of the egress
interface taken, an option is added for an address to bind the datagram
socket to. Similarly to imudp, it is necessary to add an ipfreebind
option which is set by default, so as to avoid an excess of errors at
startup before the network interface has come up. This enhancement
allows a usecase on networking devices, by which a source interface
that is typically a loopback is specified, on which an address to bind
to is configured. This is so that the same source address is used for
all packets from rsyslog. Support for the TCP case can be added later.
Signed-off-by: Mike Manning <mmanning@att.com>
> omfwd: add support for bind-to-address for UDP

- tests/Makefile.am
- tests/wtpShutdownAll-assertionFailure.sh
> add test for issue https://github.com/rsyslog/rsyslog/issues/2480

- tools/omfwd.c
This is a regression from
https://github.com/rsyslog/rsyslog/commit/2bd0fb282df92962a9817b
PR https://github.com/rsyslog/rsyslog/pull/2651 introduced that commit.
Note: that commit was merged 17 days ago and is not part of any offically
released version.
Detected by Coverity Scan, CID 190071, 190072.
> omfwd: fix memory leak in never-released code

- plugins/imuxsock/imuxsock.c
re-try of early merge of this PR
While extremely unlikely, imuxsock could abort if a file descriptor
> 1024 was received during the startup phase (never occured in
practice, but theoretically could if imfile monitored a large number
of files and were loaded before imuxsock - and maybe other
strange cases).
see also https://github.com/rsyslog/rsyslog/issues/2615
> imuxsock: replace select() call by poll()

- plugins/imudp/imudp.c
imudp introduced it's own (feature-limited) rate-limiting capability for
message on disallowed senders before we had central rate-limiters
inside rsyslog. Also, that code evolved from running on a single
thread to running on multiple threads, which introduced data races
and so made unreliable.
Now we removed the old rate-limiting capability and depend on the
system rate limiter for internal rsyslog messages.
closes https://github.com/rsyslog/rsyslog/issues/2467
> imudp: use rsyslog message rate-limiter instead of home-grown one

- tools/ompipe.c
> ompipe: use new errmsg interface

- plugins/imjournal/imjournal.c
following statistics counter are now supported by imjournal
- submitted = total number of messages submitted for processing
closes https://github.com/rsyslog/rsyslog/issues/2549
> add statistics counter to imjournal

- contrib/fmhash/fmhash.c
> Wrong Copyright year in fmhash

- plugins/imdiag/imdiag.c
> imdiag: use new errmsg interface

- rsyslog.service.in
This is to fix directive misplaced in #2657, thanks @mbiebl for the pointer.
> moved FD limit setting to correct section of unit file

- plugins/imrelp/imrelp.c
- tests/diag.sh
- tests/imrelp-missing-privkey.sh
closes https://github.com/rsyslog/rsyslog/issues/2747
> imrelp: segfault on startup when cert without priv key is configured

- plugins/imfile/imfile.c
> imfile bugfix: double-free on module shutdown

- plugins/imkafka/imkafka.c
> imkafka: use new errmsg interface

- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
this is necessary for certificate chains
closes https://github.com/rsyslog/rsyslog/issues/2762
> gnutls driver: support intermediate certificates

- runtime/nsd_ossl.c
Minor coverty issue "190592" fixed
> openssl: fixed coverty issues

- plugins/omelasticsearch/omelasticsearch.c
- tests/Makefile.am
> fix some build issues on CentOS 6

- contrib/omrabbitmq/omrabbitmq.c
A different pthread mutex is created for each connection (action) instead of a single one shared by all connections.
This will improve performance when using multiple concurrent connections to a single (or multiple) RabbitMQ instance(s) (e.g. for load balancing)
> omrabbitmq: one pthread mutex per connection

- grammar/lexer.l
This is now more along the lines of what bash does. We now support
multiple environment variable expansions as well as constant text
between them.
example:
env SOMEPATH is set to "/var/log/custompath"
config is: param=`echo $SOMEPATH/myfile`
param than is expaned to "/var/log/custompath/myfile"
among others, this is also needed inside the testbench to properly
support "make distcheck".
Note: testbench tests follows via separate commit. There will be
no special test, as the testbench itself requires the functionality
at several places, so the coverage will be very good even without
a dedicated test.
> config: enhance backticks "echo" capability

- plugins/imudp/imudp.c
- runtime/nsd_ptcp.c
- tests/hostname-getaddrinfo-fail.sh
This set of patches replaces select() by poll() ... plus a bit more of things that got in our way. The core idea is to get rid of the issues associated with select().
see also https://github.com/rsyslog/rsyslog/issues/2615
> replace select() by poll()

- plugins/mmdblookup/mmdblookup.c
> mmdblookup: use new errmsg interface

- runtime/msg.c
- tests/parsertest-parse1-udp.sh
- tests/parsertest-parse1.sh
We had problems rebasing on https://github.com/rsyslog/rsyslog/pull/2768. To not further complicate things, I create this new PR on top of current master. I'll also apply fixes here for tests that need it.
> Merge PR #2768

- contrib/omhttpfs/omhttpfs.c
- runtime/dynstats.c
- runtime/lookup.c
- runtime/msg.c
- runtime/obj.h
- runtime/queue.c
- runtime/rsyslog.h
- runtime/wti.c
- runtime/wtp.c
> gcc 8 strict support, including some fixes

- grammar/rainerscript.c
- plugins/ommysql/ommysql.c
- runtime/lookup.c
- runtime/nsdsel_ossl.c
- tools/omusrmsg.c
solves a couple of things (see commits for details)
closes https://github.com/rsyslog/rsyslog/issues/2842
> fix a couple of issues with and detected by gcc 8

- plugins/mmpstrucdata/mmpstrucdata.c
see also https://github.com/rsyslog/rsyslog/issues/1262#issuecomment-404773495
> mmpstrucdata: better error message, support $! in var names

- contrib/mmkubernetes/mmkubernetes.c
- grammar/rainerscript.c
- plugins/imptcp/imptcp.c
- plugins/ompgsql/ompgsql.c
- plugins/omsnmp/omsnmp.c
- runtime/debug.c
- runtime/queue.c
- runtime/ruleset.c
> more gcc-8 induced corrections

- tests/chkseq.c
- tests/diag.sh
> testbench: do not unnecessarily persist test data to disk

- tests/stop-localvar.sh
- tests/stop-msgvar.sh
- tests/stop.sh
- tests/stop_when_array_has_element.sh
- tests/tcp_forwarding_dflt_tpl.sh
- tests/tcp_forwarding_ns_tpl.sh
- tests/tcp_forwarding_tpl.sh
- tests/threadingmq.sh
- tests/threadingmqaq.sh
- tests/uxsock_simple.sh
- tests/wr_large.sh
> Test refactor part 1

- runtime/datetime.c
- runtime/lib_ksils12.c
Look like general 32 bit issues, though.
> fix build issues on armhf systems

- tests/diag.sh
- tests/omtcl.sh
- tests/uxsock_simple.sh
> testbench: make port for imdiag dynamic

- tests/imfile-readmode2-with-persists-data-during-stop.sh
- tests/imptcp_uds_unlink.sh
> Test refactor part 7 - multi configs

- tests/diag.sh
- tests/sndrcv_relp.sh
> testbench: prototype of sndrcv test in modern style

- contrib/imzmq3/imzmq3.c
- contrib/mmgrok/mmgrok.c
- contrib/omamqp1/omamqp1.c
- contrib/omhttpfs/omhttpfs.c
- contrib/omzmq3/omzmq3.c
- contrib/pmpanngfw/pmpanngfw.c
- tests/journal_print.c
We did not totally fix all that we would like to see changed, but we
fixed it so that it permits us to finally run the style checker on all
files.
Needs some little manual fixup PR to follow.
> codestyle fix - rough way

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/diag.sh
- tests/imfile-symlink-multi.sh
- tests/imfile-symlink.sh
this introduces symlink detection and following as well
as monitoring changes on them.
> Symlink support for imfile

- tests/Makefile.am
- tests/diag.sh
- tests/known_issues.supp
see also https://github.com/rsyslog/rsyslog/issues/2902
> testbench: suppress known issue

- README.md
0 alerts on LGTM.com is something to show off, just like the associated A+ code quality grade :slightly_smiling_face:!
> Add LGTM.com code quality badges

- tests/sndrcv_kafka-vg-rcvr.sh
- tests/sndrcv_kafka-vg-sender.sh
- tests/sndrcv_kafka.sh
- tests/sndrcv_kafka_fail.sh
- tests/sndrcv_kafka_failresume.sh
- tests/sndrcv_kafka_multi.sh
> Test refactoring part 8

- plugins/imfile/imfile.c
Now watching target directory as well to properly catch rotation
of files monitored via symlink.
Also fixed a bug in file move handling, previously state file could be deleted when `node` had more than one `edge`.
> Enhanced symlink rotation support

- tests/CI/get_all_check_logs.sh
- tests/Makefile.am
- tests/diag.sh
- tests/diskqueue-full.sh
- tests/imjournal-basic-vg.sh
- tests/imjournal-basic.sh
> testbench: force sequence of execution for some tests

- configure.ac
- tests/Makefile.am
- tests/chkseq.c
- tests/diag.sh
- tests/empty-hostname.sh
- tests/hostname-getaddrinfo-fail.sh
- tests/inputfilegen.c
- tests/prop-programname.sh
- tests/syslog_caller.c
- tests/uxsockrcvr.c
- tools/Makefile.am
- tools/strippedsymbols.exp
> AIX portability fixes

- tools/Makefile.am
regression form 9c0f2d4066b7d5a393f2f5acd080caa4dc4c1144
> fix build error e.g. on FreeBSD

- runtime/modules.c
> core: improve error message on module load fail

- tests/array_lookup_table-vg.sh
- tests/array_lookup_table.sh
- tests/array_lookup_table_misuse-vg.sh
- tests/diag.sh
- tests/dynstats_nometric.sh
- tests/dynstats_overflow-vg.sh
- tests/dynstats_overflow.sh
- tests/impstats-hup.sh
- tests/json_nonarray_looping.sh
- tests/json_object_looping-vg.sh
- tests/json_object_looping.sh
- tests/json_object_suicide_in_loop-vg.sh
- tests/lookup_table-vg.sh
- tests/lookup_table.sh
- tests/lookup_table_bad_configs-vg.sh
- tests/lookup_table_bad_configs.sh
- tests/lookup_table_no_hup_reload-vg.sh
- tests/lookup_table_no_hup_reload.sh
- tests/lookup_table_rscript_reload-vg.sh
- tests/lookup_table_rscript_reload.sh
- tests/lookup_table_rscript_reload_without_stub-vg.sh
- tests/lookup_table_rscript_reload_without_stub.sh
- tests/mmnormalize_regex_defaulted.sh
- tests/mmnormalize_regex_disabled.sh
- tests/multiple_lookup_tables-vg.sh
- tests/multiple_lookup_tables.sh
- tests/omprog-output-capture-mt.sh
- tests/sparse_array_lookup_table-vg.sh
- tests/sparse_array_lookup_table.sh
- tests/stop_when_array_has_element.sh
> testbench: modernize, next part

- tests/diag.sh
- tests/dynstats_nometric.sh
- tests/dynstats_overflow-vg.sh
- tests/dynstats_overflow.sh
- tests/dynstats_reset-vg.sh
- tests/dynstats_reset.sh
- tests/rcvr_fail_restore.sh
- tests/sndrcv_tls_anon_rebind.sh
- tests/stats-json-es.sh
- tests/stats-json-vg.sh
- tests/stats-json.sh
> testbench: some more modernization

- plugins/imdiag/imdiag.c
This is required for tests with longer-running outputs.
> imdiag: add capability to specify input flow control mode

- plugins/imdiag/imdiag.c
- tests/CI/buildbot_cleanup.sh
- tests/Makefile.am
- tests/diag.sh
- tests/imkafka.sh
- tests/omkafka.sh
- tests/sndrcv_kafka-vg-rcvr.sh
- tests/sndrcv_kafka-vg-sender.sh
- tests/sndrcv_kafka.sh
- tests/sndrcv_kafka_fail.sh
- tests/sndrcv_kafka_failresume.sh
- tests/sndrcv_kafka_multi.sh
- tests/sndrcv_kafka_multi_topics.sh
> testbench: improve plumbing, especially in kafka tests

- plugins/imfile/imfile.c
- plugins/imptcp/imptcp.c
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-endmsg.regex-vg.sh
- tests/imfile-endmsg.regex-with-example-vg.sh
- tests/imfile-endmsg.regex-with-example.sh
- tests/imfile-endmsg.regex.crio.rulebase
- tests/imfile-endmsg.regex.json.rulebase
- tests/imfile-endmsg.regex.sh
This adds support for endmsg.regex.  It is similar to
startmsg.regex except that it matches the line that denotes
the end of the message, rather than the start of the next message.
This is primarily for container log file use cases such as this:
date stdout P start of message
date stdout P  middle of message
date stdout F  end of message
The `F` means this is the line which contains the final part of
the message.  The fully assembled message should be
`start of message middle of message end of message`.
`endmsg.regex="^[^ ]+ stdout F "` will match.
> imfile: support for endmsg.regex

- .gitignore
- plugins/omprog/omprog.c
- tests/Makefile.am
- tests/omprog-defaults-vg.sh
- tests/omprog-single-instance-outfile.sh
- tests/omprog-single-instance-vg.sh
- tests/omprog-single-instance.sh
- tests/testsuites/omprog-single-instance-bin.sh
> omprog: fix forceSingleInstance flag

- plugins/imkafka/imkafka.c
- tests/Makefile.am
- tests/imkafka_multi_many.sh
- tests/imkafka_multi_single.sh
Imkafka now creates a worker thread for each configured kafka input. 
Added two tests with 4 and 8 imkafka input sources.
> Imkafka: Added multithreaded support for kafka consumers

- tests/Makefile.am
- tests/diag.sh
- tests/imkafka-vg.sh
- tests/imkafka_multi_many.sh
- tests/imkafka_multi_single.sh
- tests/omkafka-vg.sh
- tests/omkafka.sh
- tests/sndrcv_kafka_fail.sh
- tests/sndrcv_kafka_failresume.sh
- tests/sndrcv_kafka_multi.sh
- tests/sndrcv_kafka_multi_topics.sh
- Removed all sleeps where possible.
- Moved all kafka start/stop/download logic into functions.
- Moved kafka/zookeeper stop into error_exit and exit_test.
- Kafka/Zookeeper cleanup only done on success now.
- Kafka/Zookeeper logfiles automatically dumped on error_exit only now.
- Added cleanup for Kafka/Zookeeper instances into CI/buildbot_cleanup.sh
> testbench: Kafka plumbing [squashed commits]

- tests/omprog-output-capture-mt.sh
- tests/testsuites/omprog-output-capture-mt-bin.py
> testbench: fix incompatibility of one omprog test with Python3

- .codecov.yml
Initial customization, to be changed as we begin to really use the tool.
> CI: customize CodeCov settings

- tools/iminternal.c
- tools/iminternal.h
> cleanup: remove no longer needed code

- tests/diag.sh
- tests/sndrcv_kafka_multi_topics.sh
see also https://github.com/rsyslog/rsyslog/issues/3045
> testbench: small test refactor; add pluming to find test bug

- plugins/external/skeletons/python/mm-python.py
- plugins/external/skeletons/python/plugin.py
- plugins/external/solr/rsyslog_solr.py
- plugins/external/spm/rsyslog_spm_custom_metrics.py
- plugins/impstats/statslog-analyzer.py
- plugins/impstats/statslog-graph.py
- plugins/impstats/statslog_regex.py
- tests/elasticsearch-error-format-check.py
- tests/rscript_parse_time_get-ts.py
- tests/testsuites/mmexternal-SegFault-mm-python.py
> fix trailing whitespace in Python files

- tests/diag.sh
Topic creation was racy: it can happen that the brokers have not
been synced.  This causes follow-on errors and ultimately causes
the test to hang in rsyslog shutdown.
This PR introduces a method to ensure the brokers are acutally
up and running before the rest of the test is carried out. I
assume this fixes the problems we have seen. However, only
practice will show if this really is the case because the
problem happened relatively infrequently (so a couple of good
tests do not necessarily indicate "problem solved").
As such, we close the issue with this commit, but may need
to re-open it if the issue is seen again.
closes https://github.com/rsyslog/rsyslog/issues/3045
> bugfix testbench: kafka test startup was racy

- tests/diag.sh
kafka tests are plagued by brokers failing to start, which then causes
(false positive) test failures.
We now to detect missing brokers, and do a kafka/zookeepr shutdown and
restart in this case. If that fails again, let's skip the test instead
of failing it - after all, it's not the issue of the to-be-checked code.
> testbench: restart kafka if brokers do not come up

- plugins/imfile/imfile.c
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-logrotate.sh
- tests/imfile-wildcards-dirs-multi5-polling.sh
A change in the inode was not detected under all circumstances, most importantly not in some logrotate cases.
closes https://github.com/rsyslog/rsyslog/issues/1605
> bugfix imfile: file change was not reliably detected

- runtime/Makefile.am
- runtime/libgcry.c
- runtime/queue.c
- tests/Makefile.am
- tests/daqueue-dirty-shutdown.sh
- tests/daqueue-invld-qi.sh
- tests/daqueue-persist-drvr.sh
- tests/diag.sh
- tests/imudp_thread_hang.sh
- tests/internal-errmsg-memleak-vg.sh
- tests/nested-call-shutdown.sh
- tests/queue-encryption-da.sh
- tests/queue-encryption-disk.sh
- tests/queue-persist-drvr.sh
- tests/sndrcv_relp_tls_certvalid.sh
This commit fixes the bug and adds a new test to check the functionality.
closes https://github.com/rsyslog/rsyslog/issues/3066
closes https://github.com/rsyslog/rsyslog/issues/2575
> bugfix queue subsystem: DA queue did ignore encryption settings

- tests/diag.sh
> cleanup: useless use of cat (cosmetic)

- tests/diag.sh
- tests/omkafka-vg.sh
- tests/omkafka.sh
- tests/sndrcv_kafka.sh
Nothing out code has to do with the failure...
see also https://github.com/rsyslog/rsyslog/issues/3088
> testbench: detect kafka broker failure and skip test if so

- tests/omkafka.sh
as the kafka tests failed so frequently, I overlooked that I
actually broken one...
> fix bug in my previous commit

- plugins/imdiag/imdiag.c
- tests/diag.sh
> testbench: improve shutdown timeout diagnostics

- tests/diag.sh
- tests/testsuites/kafka-server.dep_wrk1.properties
- tests/testsuites/kafka-server.dep_wrk2.properties
- tests/testsuites/kafka-server.dep_wrk3.properties
- tests/testsuites/kafka-server.properties
Also adjusted some kafka server settings related to log retention.
> testbench: Hardened Kafka / Zookeeper shutdown functions 

- tests/es-bulk-retry.sh
> cosmetic: replace useless use of cat

- tests/es-bulk-retry.sh
- tests/imkafka.sh
> cosmetic: remove useless use of cat

- tests/es-writeoperation.sh
- tests/imkafka-vg.sh
- tests/imkafka_multi_many.sh
- tests/imkafka_multi_single.sh
- tests/mmkubernetes-basic-vg.sh
- tests/mmkubernetes-basic.sh
> remove several unneded cat commands

- plugins/imdiag/imdiag.c
> mostly cosmetic: improve function def, remove unnecessary NULL check

- contrib/fmhash/fmhash.c
Fixing https://github.com/rsyslog/rsyslog/issues/3025
> removing result var from context

- tests/omprog-restart-terminated-outfile.sh
- tests/omprog-restart-terminated-vg.sh
- tests/omprog-restart-terminated.sh
also first test for CodeFactor CI integration
> some more cosmetic fixes (previously overlooked)

- plugins/ommysql/ommysql.c
> ommysql: fix minor printf error

- .shellcheck.yaml
> update shellcheck rules for CodeFactor.io

- .travis.yml
- plugins/imkafka/imkafka.c
- tests/Makefile.am
- tests/diag.sh
- tests/imkafka-hang-on-no-kafka.sh
see also https://github.com/rsyslog/rsyslog/issues/3154
> fix imkafka hang on unavailable kafaka server

- runtime/libgcry.c
- tests/Makefile.am
- tests/queue-encryption-disk_keyfile-vg.sh
> fix potential misadressing in encryption subsystem

- tests/es-bulk-retry.sh
also change test to emit error-message more CI-user friendly (bottom of log);
update a bit up to testbench standards
> testbench: try to stabilize es-bulk-retry test

- tests/sndrcv_udp_nonstdpt.sh
replace fixed-time sleep with better method
> testbench: make test more reliable

- devtools/check-codestyle.sh
- runtime/nsd_ossl.h
- runtime/var.h
> some cleanup

- tests/imfile-wildcards-dirs-multi4.sh
> testbench: fix shellcheck issue

- plugins/imkafka/imkafka.c
- tests/Makefile.am
- tests/diag.sh
- tests/imkafka-backgrounded.sh
- tests/imkafka-config-err-param.sh
- tests/imkafka-config-err-ruleset.sh
- tests/imkafka-hang-other-action-on-no-kafka.sh
- tools/rsyslogd.c
closes https://github.com/rsyslog/rsyslog/issues/3180
> fix issues when imkafka is backgrounded

- tests/diag.sh
- tests/imkafka-backgrounded.sh
- tests/imkafka-config-err-param.sh
- tests/imkafka-config-err-ruleset.sh
- tests/imkafka-vg.sh
- tests/imkafka.sh
- tests/imkafka_multi_single.sh
> testbench: improve imkafka tests and testbench framework

- .lgtm.yml
As requested on Twitter: https://twitter.com/rgerhards/status/1055495248376401925
> Enable query results for commented-out code

- action.h
- contrib/omhttp/omhttp.c
- contrib/pmpanngfw/pmpanngfw.c
- plugins/imptcp/imptcp.c
- plugins/mmaudit/mmaudit.c
- plugins/omsnmp/omsnmp.c
- runtime/modules.c
- runtime/nsd_ossl.c
- runtime/nsdpoll_ptcp.c
- runtime/nsdsel_ossl.c
- runtime/rsyslog.h
- runtime/statsobj.h
- runtime/tcps_sess.c
- template.h
- tools/rsyslogd.c
thanks to lgtm.com for the ability to detect commented out code!
> cleanup: remove commented-out code

- tests/imfile-truncate-multiple.sh
> testbench: make imfile check more reliable by better wait predicate

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
- runtime/lmsig_ksi-ls12.c
Improve module debug logging, added conf parameter for specifing file name for libksi debug output and improved error reporting
closes #3191
> Issue 3191, lmsig_ksils12: improve module debug logging

- runtime/lib_ksils12.c
Disable unsafe hash algorithm SHA1
closes #3190
> Issue 3190 lmsig_ksils12: disable unsafe hash algorithm SHA1

- runtime/net.c
also clean up duplicated code
detected by cppcheck via Codacy.com
> fix preprocessor stmt inside macro

- tests/Makefile.am
- tests/test_id_usage_output.sh
see also https://github.com/rsyslog/rsyslog/issues/3072
> testbench: add test for test_id

- grammar/rainerscript.c
- plugins/imfile/imfile.c
- plugins/imkafka/imkafka.c
- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
- runtime/obj.c
- template.c
commented-out code detected by lgtm.com
> cleanup: remove commented-out code, simplify a bit

- plugins/imjournal/imjournal.c
This is workaround for possible imjournal interaction with systemd
where journal invalidate fix is not present. The code tries to
detect SD_JOURNAL_INVALIDATE loop and not reload after each call.
> Fix journald excessive reloading behavior

- plugins/imfile/imfile.c
- runtime/obj.c
- runtime/obj.h
> remove no longer used code

- runtime/queue.c
- runtime/srUtils.h
> simplify code

- Makefile.am
see also https://github.com/rsyslog/rsyslog/issues/3223
> make distcheck did not honor "--enable-mysql-tests"

- tests/daqueue-invld-qi.sh
- tests/daqueue-persist-drvr.sh
- tests/diag.sh
- tests/queue-persist-drvr.sh
- tests/queue-persist.sh
duplicate diag.sh init call was not detected due to typo
issues found be shellcheck
> improve bash coding style and fix a small bug in testbench

- tests/diag.sh
- tests/faketime_common.sh
- tests/rscript_parse_json-vg.sh
- tests/rscript_parse_json.sh
- tests/rscript_script_error.sh
based on issues detected by shellcheck
> testbench: improve code style, reduce duplication

- tools/rsyslogd.c
albeit not necessarily correct - see code comment
> AIX: handle forking in a defined way

- tests/es-bulk-retry.sh
Fix es-bulk-retry.sh script and add additional information
when the test fails.
https://github.com/rsyslog/rsyslog/issues/3104
> try to debug es-bulk-retry failures

- tests/tcpflood.c
> fix printf format error

- tests/diag.sh
based on issues detected by shellchek
> testbench: nitfixes and cleanup

- tests/sndrcv_tls_ossl_anon_rebind.sh
trying to get insight into occasional failure
see also https://github.com/rsyslog/rsyslog/issues/3256
> testbench: debug instrument sndrcv_tls_ossl_anon_rebind

- tests/diag.sh
- tests/es-basic-abort.sh
- tests/es-basic-bulk-vg.sh
- tests/es-basic-bulk.sh
- tests/es-basic-errfile-empty.sh
- tests/es-basic-es6.0.sh
- tests/es-basic-ha-vg.sh
- tests/es-basic-ha.sh
- tests/es-basic-server.sh
- tests/es-basic-vg.sh
- tests/es-basic-vgthread.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-empty.sh
- tests/es-bulk-retry.sh
- tests/es-maxbytes-bulk.sh
- tests/es-writeoperation.sh
- tests/es_response_get_msgnum.py
> testbench: modernize elasticsearch tests

- tests/diag.sh
- tests/es-basic-abort.sh
- tests/es-basic-bulk-vg.sh
- tests/es-basic-bulk.sh
- tests/es-basic-errfile-empty.sh
- tests/es-basic-errfile-popul.sh
- tests/es-basic-es6.0.sh
- tests/es-basic-ha-vg.sh
- tests/es-basic-ha.sh
- tests/es-basic-server.sh
- tests/es-basic-vgthread.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-empty.sh
- tests/es-bulk-errfile-popul-def-format.sh
- tests/es-bulk-errfile-popul-def-interleaved.sh
- tests/es-bulk-errfile-popul-erronly-interleaved.sh
- tests/es-bulk-errfile-popul-erronly.sh
- tests/es-bulk-errfile-popul.sh
- tests/es-bulk-retry.sh
- tests/es-maxbytes-bulk.sh
- tests/es-writeoperation.sh
- tests/mmkubernetes-basic-vg.sh
- tests/mmkubernetes-basic.sh
> improvements to elasticsearch tests and framework

- runtime/stream.c
Rotation detection seeks backwards, what caused issues as least in one isolated
case. We try to work around this by only doing positive seeks. We also have
added diagnostic information to the warning messages rsyslog emits on
rotation detection.
see also https://github.com/rsyslog/rsyslog/issues/3249
> imfile: improved rotation detection messages, slightly different mode

- tests/diag.sh
> testbench improvements, kafka test reliability improvement

- autogen.sh
- devtools/run-static-analyzer.sh
- tests/CI/interactive_exec_test_hook.sh
- tests/CI/try_merge.sh
> cleanup legacy shell code

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/diag.sh
- tests/imfile-basic-legacy.sh
- tests/imfile-basic-vg.sh
- tests/imfile-basic-vgthread.sh
- tests/imfile-basic.sh
> fix imfile default operations mode and testbench imrpovements

- runtime/stream.c
- tests/Makefile.am
- tests/diag.sh
- tests/imfile-basic-2GB-file.sh
- tests/imfile-truncate-2GB-file.sh
- tests/inputfilegen.c
complements #3274 
see also https://github.com/rsyslog/rsyslog/issues/3249
> imfile/stream: fixes and improvements

- tests/diag.sh
- tests/es-bulk-retry.sh
> minor testbench improvements

- tests/action-tx-errfile.sh
> testbench: harden test against slow machines

- tests/diag.sh
> testbench: some cleanup and improvements

- tests/travis/install.sh
> travis: more error message to diagnose travis issue

- plugins/omrelp/omrelp.c
- tests/Makefile.am
- tests/omrelp_errmsg_no_connect.sh
- tests/sndrcv_relp.sh
The module did not emit error messages. Actually, it would have done
if librelp would emit them (callback is in place), but librelp does
not do. We expect to fix this at the librelp level as well. But to
make this work with all versions of librelp, we have added basic
error messages to omrelp. They may not be totally easy to understand,
but at least provide the librelp error code (that's the best we can
do in this situation).
see also https://github.com/rsyslog/librelp/issues/130
closes https://github.com/rsyslog/rsyslog/issues/3294
> bugfix omrelp: emit error messages on suspension

- tests/timegenerated-uxtimestamp.sh
> testbench: modernize test

- README.AIX
- README.AIX.IBM
> add some info on rsyslog on AIX

- contrib/mmkubernetes/mmkubernetes.c
This adds support for a new bool parameter `sslpartialchain`
If `"on"`, this will set the OpenSSL certificate store flag
`X509_V_FLAG_PARTIAL_CHAIN`.   This will allow you to verify the Kubernetes API
server cert with only an intermediate CA cert in your local trust store, rather
than having to have the entire intermediate CA + root CA chain in your local
trust store.  See also `man s_client` - the `-partial_chain` flag.
This option is only available if rsyslog was built with support for OpenSSL and
only if the `X509_V_FLAG_PARTIAL_CHAIN` flag is available.  If you attempt to
set this parameter on other platforms, you will get an `INFO` level log
message.  This was done so that you could use the same configuration on
different platforms.
> mmkubernetes: add support for sslpartialchain for openssl

- tests/mysql-actq-mt.sh
> testbench: make mysql-actq-mt.sh more robust against slow machines

- tests/complex1.sh
- tests/diag.sh
> testbench: make complex1 test more robust on slow test machines

- Makefile.am
- configure.ac
- devtools/prepare_clickhouse.sh
- plugins/omclickhouse/Makefile.am
- plugins/omclickhouse/omclickhouse.c
- runtime/rsconf.c
- tests/Makefile.am
- tests/clickhouse-basic-vg.sh
- tests/clickhouse-basic.sh
- tests/clickhouse-bulk-load-vg.sh
- tests/clickhouse-bulk-load.sh
- tests/clickhouse-bulk-vg.sh
- tests/clickhouse-bulk.sh
- tests/clickhouse-errorfile.sh
- tests/clickhouse-limited-batch.sh
- tests/clickhouse-load-vg.sh
- tests/clickhouse-load.sh
- tests/clickhouse-select.sh
- tests/clickhouse-start.sh
- tests/clickhouse-stop.sh
- tests/clickhouse-wrong-insert-syntax.sh
- tests/clickhouse-wrong-quotation-marks.sh
- tests/clickhouse-wrong-template-option.sh
This output module adds the posibility to send
INSERT querys to a Clickhouse database.
The messages are sent via a REST interface.
This commit also adds support of the testbench
for clickhouse tests, as well as  various tests.
Closes https://github.com/rsyslog/rsyslog/issues/2272
> new output module for DBMS Clickhouse

- devtools/prepare_clickhouse.sh
- tests/Makefile.am
some serialization rules did not work correctly
Note: parallel testing is still experimental and not fully
supported.
> testbench: fix issues with parallel test run

- configure.ac
- tools/rsyslogd.c
> introduce new versioning scheme for rsyslog

- .travis.yml
- plugins/imdiag/imdiag.c
- runtime/cfsysline.c
- tests/diag.sh
- tests/es-basic-bulk.sh
- tests/es-basic-errfile-empty.sh
- tests/es-basic-errfile-popul.sh
- tests/es-basic-es6.0.sh
- tests/es-basic-server.sh
- tests/es-basic-vgthread.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-empty.sh
- tests/es-maxbytes-bulk.sh
- tests/imptcp_conndrop-vg.sh
- tests/omprog-output-capture-mt.sh
- tests/privdropuser.sh
- tests/sndrcv_gzip.sh
- tests/travis/run.sh
a couple of enhancements (and even a fix) to make CI work more robust against (very) slow machines.
See commit(s) for details.
> testbench: improve slow machine robstness

- contrib/pmpanngfw/pmpanngfw.c
> Issue #3343: signed and unsigned comparison

- autogen.sh
- plugins/impstats/statslog-analyzer.py
- plugins/impstats/statslog-graph.py
- tests/elasticsearch-error-format-check.py
- tests/testsuites/mmexternal-SegFault-mm-python.py
> fix some nits found by analyzers

- runtime/stream.c
This works-around an issue we can reproduce e.g. via the
imtcp-tls-ossl-x509fingerprint.sh test. Here, omfile gets a write
error with reason EBADF. So far, I was not able to see an actual
coding error. However I traced this down to a multithreaded race
on open and close calls. I am very surprised to see this type
of issue, as I think the kernel guarantees that it does not happen.
Here is what I see in strace -f:
openssl accepts a socket:
[pid 66386] accept(4, {sa_family=AF_INET, sin_port=htons(59054), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 10
then, it works a bit with that socket, detects a failure and shuts it down. Sometimes, at the very same instant omfile on another thread tries to open on output file. Then the following happens:
[pid 66386] close(10)                   = 0 …
> omfile: work-around for "Bad file descriptor" errors

- plugins/omkafka/omkafka.c
- tests/omkafka-dynatopic.sh
- tests/omkafka-statistics.sh
Also fixed two minor debug output seqfaults when dynatopic was used on shutdown (CODESTARTfreeInstance)
closes: https://github.com/rsyslog/rsyslog/issues/3410
> testbench: Added new omkafka tests for more coverage.

- tests/diag.sh
- tests/imuxsock_ccmiddle.sh
- tests/imuxsock_ccmiddle_syssock.sh
- tests/imuxsock_logger.sh
- tests/imuxsock_logger_err.sh
- tests/imuxsock_logger_parserchain.sh
- tests/imuxsock_logger_ruleset.sh
- tests/imuxsock_logger_ruleset_ratelimit.sh
- tests/imuxsock_logger_syssock.sh
- tests/imuxsock_traillf.sh
- tests/imuxsock_traillf_syssock.sh
- tests/msgdup.sh
> fix some bash nits

- grammar/rainerscript.h
> clarify that commented-out code is intentional (as an example)

- runtime/queue.c
- runtime/queue.h
- runtime/wti.c
- runtime/wti.h
- tests/Makefile.am
- tests/diag.sh
- tests/queue-minbatch-queuefull.sh
- tests/queue-minbatch.sh
closes https://github.com/rsyslog/rsyslog/issues/495
> queue: add support for minimum batch sizes

- tests/Makefile.am
- tests/diag.sh
- tests/imjournal-statefile-vg.sh
- tests/imjournal-statefile.sh
- tests/imrelp-manyconn-vg.sh
see also https://github.com/rsyslog/rsyslog/issues/3433
> testbench: fix imjournal tests; add imjournal valgrind test

- plugins/imjournal/imjournal.c
> Added missing free of received journal cursor

- tests/omfile-read-only.sh
> fix legacy format

- tests/timestamp-3339-udp.sh
> testbench: modernize test and hopefully make more robust on slow CI

- action.c
- grammar/lexer.l
- grammar/rainerscript.c
- plugins/imfile/imfile.c
- plugins/imptcp/imptcp.c
- plugins/imrelp/imrelp.c
- plugins/imuxsock/imuxsock.c
- plugins/ommongodb/ommongodb.c
- plugins/omrelp/omrelp.c
- runtime/lookup.c
- runtime/net.c
- runtime/nsd_ptcp.c
- runtime/rsyslog.h
- runtime/srutils.c
- runtime/tcpsrv.c
- runtime/wti.c
- runtime/wtp.c
- template.c
> cleanup: use less verbose C11 method to use pragmas

- tests/imfile-symlink.sh
We hope this solves the pretty frequent false positives this test
generates.
> testbench: refactor imfile-symlink test for robustness and simplicity

- grammar/lexer.l
> lexer.l: change to PRAGMA macros

- tests/diag.sh
The old method via startup timeout was less reliable. We now use time-based
runtime method. This PR fixes all startups, but leaves some shutdown
scenarios in previous state.
> testbench: bind startup timeout to general runtime timeout

- tests/daqueue-dirty-shutdown.sh
This test occasionally failed with left-over spool files. As far as we
have analyzed, this is due to the use of an invalid shutdown timeout
(very short) in the second phase of the test. It looks like this is
actually a copy&paste error from phase one. Behaviour of rsyslog was
correct, but the test itself created a false positive.
We have corrected the timeout now and also modernized the test
a bit.
closes https://github.com/rsyslog/rsyslog/issues/2122
> testbench: fix daqueue-dirty-shutdown test

- tests/imptcp_conndrop-vg.sh
- tests/imptcp_conndrop.sh
while doing so, alos modernize tests
> testbench: harden long-running tests against slow CI environment

- tests/es-bulk-errfile-popul-erronly.sh
> testbench: nitfix

- tests/da-mainmsg-q.sh
- tests/mmexternal-SegFault-vg.sh
> testbench improvements

- tests/CI/PR_validation.sh
- tests/CI/check_commit_text.py
> CI: improve error messages in PR validation

- contrib/omamqp1/omamqp1.c
They occur on some, newer, platforms.
> omamqp: fix build errors

- runtime/nsd_ossl.c
- tests/tcpflood.c
Handling of SSL_ERROR_SYSCALL has been hardened.
Also fixed SSL Shutdown handling in tcpflood (openssl code).
If SSL_Shutdown returns error, we call SSL_read as described in
the documentation to do a bidirectional shutdown.
Closes https://github.com/rsyslog/rsyslog/issues/3561
> openssl: Added better error handling in osslRecordRecv

- plugins/imjournal/imjournal.c
The sd_journal_get_cursor() got called regradless of previous
retcodes from other jorunal calls which flooded logs with journald
errors. Now skipping the call in case of previous journal call
non-zero result.
Also, making WorkAroundJournalBug true by default, as there were no
confirmed performance regressions for a quite long time.
> Fetching journal cursor only for valid journal

- .lgtm.yml
> lgtm: reduce change of merge conflic on .lgtm.yml

- ChangeLog
- runtime/msg.c
- runtime/msg.h
closes https://github.com/rsyslog/rsyslog/issues/3570
> try to fix regression from 1255a67fdec2fc44cd49b6ea8c463f4319910812

- .lgtm.yml
- ChangeLog
- Makefile.am
- configure.ac
- contrib/pmdb2diag/Makefile.am
- contrib/pmdb2diag/pmdb2diag.c
- tests/Makefile.am
- tests/pmdb2diag_parse.sh
This module parse special DB2 Logs to extract data to rsyslog's message structure. It requires that message flags NEEDS_PARSING to be raised by input module. "imfile" propose this enhancement in PR #3471
> Contrib_pmdb2diag

- tests/diag.sh
> testbench: better info if core file is found during test

- runtime/nsd_ossl.c
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
> openssl driver: clean up a bit

- tests/diag.sh
- tests/omhttp_server.py
Fixes: https://github.com/rsyslog/rsyslog/issues/3599
> tests: omhttp: add Python 3 compatibility

- tests/mmkubernetes-cache-expire.sh
https://github.com/rsyslog/rsyslog/issues/3626
> mmkubernetes - fix cache test python indentation

- tools/rsyslogd.c
While in theory this is a leak, in practice it's extremely unlikely
and irrelevant. Nevertheless, let's fix it ;-)
> fix cosmetic coverity leak report (CID 207601)

- Makefile.am
- tests/Makefile.am
see also https://github.com/rsyslog/rsyslog/issues/3684
> testbench: some modules were excluded in "make distcheck"

- tests/pmrfc3164-AtSignsInHostname.sh
> testbench: update a test to current testbench best practice

- runtime/glbl.h
- tools/omfile.c
see also https://github.com/rsyslog/rsyslog/issues/3686
> debug: add instrumentation to investigate 8.1905.0 regression

- tests/Makefile.am
- tests/diag.sh
- tests/gzipwr_hup-vg.sh
- tests/gzipwr_hup.sh
- tests/omfile_hup-vg.sh
- tests/omfile_hup.sh
see also https://github.com/rsyslog/rsyslog/issues/3686
> testbench: add omfile tests based on real-world issue

- README.md
see also https://github.com/rsyslog/rsyslog/issues/3712
> doc fix: outdated link in README

- tests/Makefile.am
- tests/msgdup_props.sh
**wait for https://github.com/rsyslog/rsyslog/pull/3723** before merging
see also https://github.com/rsyslog/rsyslog/issues/3716
> testbench: check MsgDup() properly duplicates all properties

- runtime/net.c
While it works well on current platforms, alignment issues may turn into real issues in future platforms. So we try to fix them if possible. As not only a side-effect this resolves compiler warnings even on current platforms.
This fix has some regression potential.
see also https://github.com/rsyslog/rsyslog/issues/2608
> core: fix alignment issue

- ChangeLog
- plugins/mmaudit/mmaudit.c
- runtime/msg.c
- runtime/rsyslog.h
> cleanup any libee mentions and clarify state in ChangeLog

- plugins/imjournal/imjournal.c
The new option makes possible to force physical write of stateFile
to persistent storage, ensuring we do not lose/duplicate messages
in case of hard crash or power loss.
> Add "fsync" option for imjournal

- tests/Makefile.am
- tests/diag.sh
- tests/imptcp-basic-hup.sh
- tests/imrelp-basic-hup.sh
- tests/imtcp-basic-hup.sh
see also https://github.com/rsyslog/rsyslog/issues/3760
**Note: this initially MUST fail.** This will be corrected one the patch for #3760 is in place. **Do not merge before the patch is in place.**
> testbench: add test for imrelp HUP handling

- tests/Makefile.am
- tests/omfile-outchannel.sh
> testbench: add test for outchannel functionality

- runtime/srutils.c
> provide some more error information on execProg failure

- runtime/atomic.h
- runtime/rsconf.c
- tools/iminternal.c
- tools/rsyslogd.c
> iminternal bugfix: race on termination

- runtime/nsd_ossl.c
- tests/tsan.supp
important step to get us started - in the future we will try to reduce
blacklisted parts
> testbench: add thread analyzer blacklist

- tests/Makefile.am
- tests/omusrmsg-errmsg-no-params.sh
- tests/omusrmsg-noabort-legacy.sh
- tests/omusrmsg-noabort.sh
> testbench: add basic tests for omusrmsg

- tests/Makefile.am
- tests/diag.sh
- tests/gzipwr_hup_multi_file.sh
- tests/gzipwr_hup_single_file.sh
see also https://github.com/rsyslog/rsyslog/issues/3772
> testbench: add multithreading tests with omfile async io/zip writing

- plugins/imptcp/imptcp.c
> imptcp: simplify error message code

- tests/diag.sh
- tests/gzipwr_large.sh
We have added new capabilities to the testbench plumbing to automatically
deal with gzip-compressed files. This also permits to use the wait_seq_check
function to work for gzip tests as well. The known-timing-sensitive
gzipwr_large test now makes use of the new capabilities.
> testbench: make gzipwr_large test more reliable and improve plumbing

- tests/mmpstrucdata-case.sh
> testbench: modernize mmpstrucdata-case test

- tests/asynwr_simple.sh
- tests/asynwr_simple_2.sh
- tests/diag.sh
> testbench: modernize tests and make them more reliable

- plugins/imdiag/imdiag.c
- plugins/imgssapi/imgssapi.c
- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/diag.sh
- tests/imtcp-listen-port-file-2.sh
- tests/sndrcv.sh
- tests/suspend-omfwd-via-file.sh
>  imtcp bugfix: multiple listnerPortFile parameter did not work

- configure.ac
- tests/Makefile.am
- tests/asynwr_deadlock.sh
- tests/asynwr_deadlock2.sh
- tests/asynwr_deadlock_2.sh
- tests/asynwr_small.sh
- tests/asynwr_timeout.sh
- tests/asynwr_timeout_2.sh
- tests/asynwr_tinybuf.sh
- tests/diag.sh
- tests/es-bulk-errfile-popul-def-format.sh
- tests/es-bulk-errfile-popul-def-interleaved.sh
- tests/es-bulk-errfile-popul-erronly-interleaved.sh
- tests/es-bulk-errfile-popul-erronly.sh
- tests/exec_tpl-concurrency.sh
- tests/gzipwr_flushInterval.sh
- tests/gzipwr_hup_multi_file.sh
- tests/queue-minbatch.sh
> testbench: modernize and stabilize some tests

- tests/Makefile.am
- tests/allowed-sender-tcp-hostname-fail.sh
- tests/allowed-sender-tcp-hostname-ok.sh
> testbench: add more tests for $allowedSender directive

- tests/Makefile.am
- tests/immark.sh
> testbench: add basic test for immark

- contrib/pmdb2diag/pmdb2diag.c
Add a new sanity check after determining the level len.
> pmdb2diag : Out of bounds issue

- runtime/nsd_ossl.c
SSL_CONF_cmd is used to set openssl options by gnutlsPriorityString
However older OpenSSL version do not support this API and a LogMsg will
now inform the user about it.
> openssl tls: Changed logerror to logmsg for SSL_CONF_cmd warning

- tests/diag.sh
- tests/dynstats-json-vg.sh
- tests/dynstats-vg.sh
- tests/dynstats.sh
- tests/dynstats_ctr_reset.sh
- tests/dynstats_nometric.sh
- tests/dynstats_overflow-vg.sh
- tests/dynstats_overflow.sh
- tests/dynstats_prevent_premature_eviction-vg.sh
- tests/dynstats_prevent_premature_eviction.sh
- tests/dynstats_reset-vg.sh
- tests/dynstats_reset.sh
- tests/dynstats_reset_without_pstats_reset.sh
> testbench: improve dynstats tests and make them more protable

- plugins/imjournal/imjournal.c
commit 78976a9bc059 introduced a regression that caused writing
the journal state file to fail. This happens when the state file
is given as relative file name and the working directory is also
a relative path. This situation is very uncommon. So most deployments
will never experience it. We discovered the issue during CI runs
where the trigger condition is given. Note that it also takes
multiple times of loading the journal to actually see the bug.
see also https://github.com/rsyslog/rsyslog/pull/3878
> imjournal: fix regression

- tests/elasticsearch-error-format-check.py
- tests/es_response_get_msgnum.py
- tests/mmexternal-SegFault-vg.sh
- tests/testsuites/mmexternal-SegFault-mm-python.py
- tests/urlencode.py
> testbench bugfix: make python scripts use print python 2/3 compatible

- runtime/stream.c
The stream class does not close re-opened file descriptors.
This lead to leaking file handles and ultimately to the inability
to open any files/sockets/etc as rsyslog ran out of handles.
The bug was depending on timing. This involed different OS
thread scheduler timing as well as workload. The bug was more
common under the following conditions:
- async writing of files
- dynafiles
- not commiting file data at end of transaction
However it could be triggerred under other conditions as well.
The refactoring done in 8.1908 increased the likelyhood of
experienceing this bug. But it was not a real regression, the new
code was valid, but changed the timing so that the race was more
likely.
Thanks to Michael Biebl for reporting this bug and helping to
analyze it.
closes …
> omfile bugfix: file handle leak

- runtime/queue.c
- runtime/stream.c
- runtime/wti.c
- tests/Makefile.am
- tests/cee_diskqueue.sh
- tests/diag.sh
- tests/diskq-rfc5424.sh
- tests/diskqueue-multithread-es.sh
Provide ability for disk queues to run on multiple threads.
see also https://github.com/rsyslog/rsyslog/issues/3543
closes https://github.com/rsyslog/rsyslog/issues/3833
> enhancement: multithread disk queue

- plugins/imrelp/imrelp.c
- runtime/queue.c
- runtime/queue.h
- runtime/rsyslog.h
This PR introduces new expert configuration options for both imrelp and the queue subsystem. They provide finer control over how these components work together. Most importantly, it is possible to make imrelp and all queues used in relp message processing flow to become blocking when over `queue.fullDelayMark`.
**Warning:** using these options can cause rsyslog to become unresponsive because of blocking operation. This behaviour is the intent of the new configuration parameters. This is **not** what almost all users want. So use the options with extreme care.
closes #3941
> permit finer-grained control over imrelp/queue processing flow

- plugins/mmutf8fix/mmutf8fix.c
- tests/mmutf8fix_no_error.sh
1. Invalid utf8 detection didn't handle 3 and 4-byte overlong encodings (2 byte overlong econdings were handled explicitly by rejection E0 and E1 start bytes). Unified checks for overlong encodings.
2. Surrogates U+D800..U+DFFF are not valid codepoints (Unicode Standard, D92)
3. Replacement of characters in invalid 3 or 4-bytes encodings was too eager. It must not replace bytes which are valid UTF-8 sequences. For example, in [0xE0 0xC2 0xA7] sequence the 0xC2 is invalid as a continuation byte, but it starts a valid UTF8 symbol [0xC2 0xA7]. That is, with current
code processing the sequence will result in "???" but the correct result is "?§" (provided that the replacement character is "?").
4. Various tests for UTF-8 invalid/valid sequences.
> Enhance mmutf8fix handling of incorrect UTF-8 sequences

- .travis.yml
- tests/travis/install.sh
This also removes all remaining references to LLVM repos, as such
closes https://github.com/rsyslog/rsyslog/issues/2380
> travis: remove no longer needed Trusty install scripts

- configure.ac
- tests/Makefile.am
- tests/diag.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-popul-def-format.sh
- tests/es-bulk-errfile-popul-def-interleaved.sh
- tests/es-bulk-errfile-popul-erronly-interleaved.sh
- tests/es-bulk-errfile-popul-erronly.sh
- tests/es-bulk-retry.sh
- tests/es-writeoperation.sh
- tests/mmkubernetes-basic-vg.sh
- tests/mmkubernetes-basic.sh
- tests/mmkubernetes-cache-expire.sh
- tests/omamqp1-basic.sh
- tests/rscript_parse_time.sh
- tests/set-envvars.in
see also https://github.com/rsyslog/rsyslog/issues/3853
> testbench: obtain python binary path via AM_PATH_PYTHON

- devtools/prep-mysql-db.sh
- tests/Makefile.am
- tests/action-tx-errfile.sh
- tests/action-tx-single-processing.sh
- tests/clickhouse-stop.sh
- tests/diag.sh
- tests/libdbi-asyn.sh
- tests/libdbi-basic-vg.sh
- tests/libdbi-basic.sh
- tests/mysql-actq-mt-withpause-extended.sh
- tests/mysql-actq-mt-withpause-vg.sh
- tests/mysql-actq-mt-withpause.sh
- tests/mysql-actq-mt.sh
- tests/mysql-asyn-vg.sh
- tests/mysql-asyn.sh
- tests/mysql-basic-cnf6.sh
- tests/mysql-basic-vg.sh
- tests/mysql-basic.sh
This is an initial try to make mysql tests able to run in parallel,
which also hardens them against some timing problems.
> testbench: improve mysql test framework plumbing

- tests/urlencode.py
> testbench: improve python3 support

- tests/improg_simple_multi.sh
- tests/mmexternal-SegFault-vg.sh
- tests/omprog-output-capture-mt.sh
see also https://github.com/rsyslog/rsyslog/issues/3853
> testbench: fix some python env-induced issues

- tests/diag.sh
see also https://github.com/rsyslog/rsyslog/issues/3853
> testbench: fix some issue finding correct python interpreter

- plugins/ommongodb/ommongodb.c
This replaces PR #3432 ommongodb part.
All credits goes to @KGuillemot.
> OMMONGODB :: Add other supported formats for 'time' and 'date' fields

- plugins/imfile/imfile.c
Now checking if file-id changes and reanming - cleaning state file
accordingly and always checking and cleaning old inode-only style
state files.
closes #3960
closes #3646
closes #3646
> Thorougher state-file renaming and cleaning

- plugins/imjournal/imjournal.c
this is followup to #4000, hopefully it will be easier for future readers
> Make handleRotation() function bit easier to read

- runtime/dnscache.c
> fix indention

- contrib/imdocker/imdocker.c
- contrib/mmkubernetes/mmkubernetes.c
- contrib/omrabbitmq/omrabbitmq.c
- grammar/rainerscript.c
- plugins/imgssapi/imgssapi.c
- plugins/imkafka/imkafka.c
- plugins/omgssapi/omgssapi.c
- plugins/omkafka/omkafka.c
- plugins/omlibdbi/omlibdbi.c
- plugins/omudpspoof/omudpspoof.c
- plugins/pmnormalize/pmnormalize.c
- runtime/modules.c
- runtime/queue.c
- tools/rscryutil.c
> bugfixes: small issues detected by clang static analyzer 9

- tests/diag.sh
> testbench: cleanup no longer needed debug instrumentation

- contrib/omhiredis/omhiredis.c
- new mode 'set' to send SET/SETEX commands
- new parameter 'expiration' to send SETEX instead of SET commands (only applicable to 'set' mode)
- fixes to missing frees
> OMHIREDIS:: ADD 'SET' MODE

- plugins/omclickhouse/omclickhouse.c
> omclickhouse: set maximum time for sending data to ClickHouse

- contrib/imdocker/imdocker.c
- devtools/default_dev_container
- devtools/run-static-analyzer.sh
- tests/travis/travis-run-compile-tests.sh
> new default development container and update Travis to new compilers

- action.c
- plugins/imfile/imfile.c
- plugins/imptcp/imptcp.c
- runtime/nsd_ptcp.c
- runtime/rsyslog.h
So far, this worked everywhere (for years). But it may still have
caused issues on some platforms.
closes https://github.com/rsyslog/rsyslog/issues/2608
closes https://github.com/rsyslog/rsyslog/pull/3707 (this was just a test PR)
> fix some alignment issues

- plugins/omelasticsearch/omelasticsearch.c
The curl reply buffer (pWrkrData->reply) was allocated, realloced and freed with
each request. This has now been reduced to once per module, slightly increasing
overall performance.
closes https://github.com/rsyslog/rsyslog/issues/1964
> omelasticsearch: improve curl reply buffer handling

- tests/Makefile.am
- tests/diag.sh
- tests/diskqueue-multithread-es.sh
- tests/elasticsearch-stop.sh
- tests/es-basic-abort.sh
- tests/es-basic-bulk.sh
- tests/es-basic-errfile-empty.sh
- tests/es-basic-errfile-popul.sh
- tests/es-basic-es6.0.sh
- tests/es-basic-ha-vg.sh
- tests/es-basic-ha.sh
- tests/es-basic-server.sh
- tests/es-basic-vgthread.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-empty.sh
- tests/es-bulk-errfile-popul-def-format.sh
- tests/es-bulk-errfile-popul-def-interleaved.sh
- tests/es-bulk-errfile-popul-erronly-interleaved.sh
- tests/es-bulk-errfile-popul-erronly.sh
- tests/es-bulk-errfile-popul.sh
- tests/es-bulk-retry.sh
- tests/es-execOnlyWhenPreviousSuspended.sh
- tests/es-maxbytes-bulk.sh
- tests/es-writeoperation.sh
we avoid unnecessary ElasticSearch restarts now. This also helps with flakes
on slow CI machines.
> testbench: improve speed of elasticsearch tests

- tests/action-tx-errfile.sh
- tests/action-tx-single-processing.sh
slow test machines are now better handled
> testbench: modernize some tests and make more robust

- tests/diag.sh
> testbench: use local kafka download cache if present

- tests/imtcp-tls-basic.sh
- tests/imtcp-tls-ossl-basic-tlscommands.sh
- tests/sndrcv_tls_gtls_servercert_gtls_clientanon.sh
> testbench: modernize tests

- tests/sndrcv_gzip.sh
also make more robust against slow testbench machines
> testbench: modernize some tests

- runtime/net.c
TSAN correctly detects a race during socket initialization, but this
is harmless as at most it leads to "a bit" of extra code execution.
Usually, it does not happen. This commit works-around the issue so
that TSAN notices we know what we are doing.
For details see actual patch.
> core/network: fix cosmetic race during socket initialization

- tests/diag.sh
- tests/rscript_set_memleak-vg.sh
> testbench: make tests more robust against slow machines

- runtime/tcpsrv.c
> tcpsrv bugfix: build problem regression

- tests/asynwr_deadlock4.sh
- tests/diag.sh
- tests/inputname-imtcp.sh
- tests/omrelp_wrong_authmode.sh
- tests/sndrcv_tls_gtls_serveranon_gtls_clientanon.sh
> testbench: further improvements

- plugins/imfile/imfile.c
The timeout feature was soley based on timeouts of the poll()
system call. On a very busy system, this would probably happen
very seldomly.  Moreover, the timeout could occur later than
expected on any system with high load.
The issue was not reported from practice but discovered during
CI system improvements.
> imfile bugfix: timeout did not work on very busy system

- runtime/ratelimit.c
In theory, rsyslog should call parsers on the queue worker threads whenever
possible. This enables the parsers to be executed in parallel. There are
some cases where parsers needs to be called earlier, namely when parsed
data is needed for rate-limiting.
The logic to do this previously did not work correctly and was fixed six
years ago (!) by b51dd22. Unfortunately, b51dd22 was overly agressive:
it actually makes the early parser call now mandatory, effectively moving
parsing to the input side where there is no to little concurrency.
We still do not need to call the parser when all messages, regardless of
severity, need to be rate-limited. This is the default and very frequent
case. This patch introduces support for this and as such makes parsers
able to run in parallel in the frequent …
> core bugfix: too early parsing of incoming messages

- plugins/imfile/imfile.c
Add MaxBytesPerMinute and MaxLinesPerMinute options.
These take integer values and, respectively, limit the number
of bytes or lines that may be sent in a minute.
This can be used to put a limit on the count or volume of logs
that may be sent for an imfile.
I have run into problems in production where developers ship changes that vastly increase the quantity of logs sent. I would like to be able to set rate limits on the number of messages or bytes sent per imfile.
This change solves this problem for me.
Initially I went per second, but that was too spiky and difficult to pick a sensible value for. Per minute works well for me.
I'm interested in feedback as to whether this could be merged, before I update the docs to match it.
> Add per minute rate limiting to imfile plugin

- tests/diag.sh
those used so far are outdated, bump to newest version
> testbench tooling: update kafka components

- plugins/omprog/omprog.c
When omprog was used with the 'forceSingleInstance=on' option, and/or
the 'output' setting, "bad file descriptor" errors occurred, which
prevented the external program to be executed and/or the program output
to be correctly captured. The bug could also manifest as "resource
temporarily unavailable" errors, or other errors related to the use of
invalid/reassigned file descriptors. These errors only happened when
rsyslog ran in daemon mode (i.e. they didn't happen if rsyslogd was
run with the '-n' option).
The cause of the bug was that omprog opened the pipe fds needed by
these flags during the configuration load phase (in the 'newActInst'
module entrypoint). This is a bad place since the fork of the daemon
occurs after this phase, and all fds are closed when the daemon process
is started …
> omprog: fix bad fd errors in daemon mode

- runtime/nsd_ossl.c
Older OpenSSL Versions do not have SSL_MODE_AUTO_RETRY enabeld by default.
If the setting is set to OFF, SSL_read can return an error with
SSL_ERROR_WANT_READ when a non-application data record has been processed.
For more see: https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html
closes: https://github.com/rsyslog/rsyslog/issues/4224
> ossl: setting SSL_MODE_AUTO_RETRY on ssl objects returned by SSL_new

- grammar/rainerscript.c
This patch provides a fix for a problem reported in https://github.com/rsyslog/rsyslog/issues/4245
> rainerscript: call getgrnam_r repeatedly to get all group members

- tools/ompipe.c
Hello Rainer,
Sometimes we need to reopen a pipe after an ompipe action gets suspended. Sending an HUP signal to rsyslog does the job but requires an interaction with rsyslog. The patch adds support for a new boolean option, tryResumeReopen, for the ompipe action. It mimics what an HUP signal would do.
We have issues with ompipe in the following context:
- ompipe writes to a Nagios 4 command fifo
- Nagios gets restarted
- The rsyslog ompipe action suspends but never resumes, even with action.resumeinterval and action.resumeintervalmax set to small values, and action.resumeretrycount set to -1. I believe the select() call always returns 0.
Using this patch works for us. It adds option tryResumeReopen and keeps the current behavior by default ("off" by default). I am not sure if it is …
> ompipe: add action parameter tryResumeReopen

- configure.ac
- plugins/mmdblookup/Makefile.am
- plugins/mmdblookup/dummy.c
> build system: add option --enable-mmdblookup=optional

- configure.ac
- plugins/imkafka/Makefile.am
- plugins/imkafka/dummy.c
- plugins/omkafka/Makefile.am
- plugins/omkafka/dummy.c
> build system: add --enable-[io]mkafka=optional configure parameter

- plugins/imfile/imfile.c
EXPERIMENTAL / PROPOSAL ONLY
see also https://github.com/rsyslog/rsyslog/issues/3771#issuecomment-564916611
> imfile: add new parameter "persistStateAfterSubmission"

- .github/workflows/ci.yml.template
- .github/workflows/run_centos_7.yml
- .github/workflows/run_centos_8.yml
- .github/workflows/run_debian_10.yml
- .github/workflows/run_tumbleweed.yml
- .github/workflows/run_ubnutu_18_san.yml
- .github/workflows/run_ubnutu_18_tsan.yml
- .github/workflows/run_ubuntu_16.yml
- devtools/devcontainer.sh
> CI: add github actions

- configure.ac
- plugins/imjournal/Makefile.am
- plugins/imjournal/dummy.c
> build system: add --enable-imjournal=optional configure param

- .github/workflows/ci_compile.yml
- devtools/devcontainer.sh
> CI: use github actions for compile checks

- plugins/omelasticsearch/omelasticsearch.c
When POST'ing a document, Elasticsearch does not allow an empty pipeline
parameter value. This patch introduces boolean option skipPipelineIfEmpty
to the omelasticsearch action. When set to true, the pipeline parameter
won't be posted. Default is false so we do not modify current behavior.
> omelasticsearch: Allow to skip the pipeline parameter in POST if empty

- .github/workflows/run_kafka_codecov.yml
- .github/workflows/run_ubuntu_18_codecov.yml
> CI: do CodeCov checks via github action

- tests/diag.sh
- tests/imfile-endregex-timeout-with-shutdown.sh
> Ci imfile test debug

- tests/diag.sh
> testbench: simplify test ID generation a bit

- runtime/stream.c
- tests/Makefile.am
- tests/diag.sh
- tests/diskqueue-fail.sh
- tools/rsyslogd.c
Also added some debug output to trace the error.
closes: https://github.com/rsyslog/rsyslog/issues/4282
> Queue: add test for segfault issue 4282

- .github/workflows/run_ubuntu_20.yml
- tests/CI/ubuntu20.04.supp
- tests/Makefile.am
> CI: run testbench on ubuntu 20 with github action

- .github/workflows/ci_compile.yml
- contrib/imdocker/imdocker.c
closes https://github.com/rsyslog/rsyslog/issues/4115
> CI: add gcc-10 compile check

- contrib/mmdarwin/mmdarwin.c
- fix a use-after-free on variable during darwin uuid message extraction
- improve debug/output by logging uuid parse errors
> MMDARWIN:: FIX POTENTIAL ZERO UUID WHEN REUSING EXISTING ONE

- runtime/nsd_ossl.c
Currently the nsd_ossl module doesn't contains logs for few failure scenarios.  This commit adds those additional logs.
Also we have added the nsd_ossl tag to the logs for better identification
> Improving nsd ossl logs for better debugging

- runtime/nsdsel_gtls.c
If the tls handshake does not immediatelly finish, gnutls_handShake is called in
doRetry handler again. However the error handling was not
complete in the doRetry handler. A failed gnutls_handShake call
did not abort the connection and properly caused unexpected
problems like in issues:
https://github.com/rsyslog/rsyslog/issues/4270
https://github.com/rsyslog/rsyslog/issues/4288
> gnutls: Added handshake error handling into doRetry handler.

- tests/Makefile.am
- tests/sndrcv_relp_tls_certvalid.sh
- tests/sndrcv_relp_tls_chainedcert.sh
closes https://github.com/rsyslog/rsyslog/issues/4446
> testbench: fix missing test file

- tests/diag.sh
The kafkacat tool has an upper limit of how many messages it can send
at once. Going over that limit causes messages loss. The exact limit
seems to depend on the environment. This cases testbench false positives.
This commit fixes two related issues:
- errors during kafkacat run were not detected - this has been added
- we now have a "max messages at once" setting, after which kafkacat
is restarted for the next batch of messages. It currently is set
to 25,000 msgs per incarnation. All tests loop now to send the
required number of messages. This has been fixed at the testbench
framework level, so no need to adjust individual tests.
> testbench: fix kafkacat issues

- .github/workflows/run_journal.yml
- .github/workflows/run_ubuntu_18_codecov.yml
> QA: use github action VMs for systemd journal tests

- grammar/rainerscript.c
Fix race between key-lookup and lookup-table-reload
> Fix race between key-lookup and lookup-table-reload

- .github/workflows/run_ubuntu_20_san.yml
- .github/workflows/run_ubuntu_20_tsan.yml
- tests/asan.supp
- tests/tsan-rt.supp
- tests/tsan.supp
So we can use the more modern tools that comes with it.
> CI: switch some tests from Ubuntu 18 to 20

- .github/workflows/run_fedora_31.yml
- .github/workflows/run_fedora_33.yml
> CI add more fedora tests

- grammar/rainerscript.c
- tests/Makefile.am
- tests/rscript_re_extract_i.sh
- tests/rscript_re_match_i.sh
> add case-insensitive regex functionality

- plugins/imdiag/imdiag.c
- plugins/imgssapi/imgssapi.c
- plugins/imtcp/imtcp.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
- runtime/nsd_ptcp.h
- runtime/tcps_sess.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- runtime/typedefs.h
see also https://github.com/rsyslog/rsyslog/issues/3727
> phase 1: consolidate current imtcp input params in a single structure

- tests/Makefile.am
- tests/imrelp-tls-mixed-chainedcert.sh
- tests/imrelp-tls-mixed-chainedcert2.sh
closes: https://github.com/rsyslog/rsyslog/issues/4406
See also: https://github.com/rsyslog/librelp/issues/207
> testbench: Add testcase for librelp EINPROGRESS issue

- tests/sndrcv_tls_certvalid_expired_defaultmode.sh
make easier to understand and less verbose
> testbench: simplify test

- plugins/omkafka/omkafka.c
- For librdkafka > v1.x, utilize new api [rd_kafka_purge](https://docs.confluent.io/5.5.1/clients/librdkafka/rdkafka_8h.html#a59c28026ebf7a67df5954879ebab4707) in order to drain librdkafka queues before an instance shutdown, and save it for re-shipping. Useful in order to ensure all logs are shipped even during situations where rsyslog instance must be shut down, such as in during a HUP or restart.
- add statsname on per kafka instance basis to gain minimal visibility of `acks`, `submits`, and `failures` (for that instance).
> omkafka - use rd_kafka_purge to drain librdkafka queues during HUP and improve kafka instance visibility.

- runtime/tcpsrv.c
> fix typo in error message

- plugins/ommongodb/ommongodb.c
When Rsyslog is running with OMMongoDB and pushing logs into it, if insertion cannot be made for some reason (server down, not reachable, no primary available, etc), Rsyslog craches violently with a **Segmentation Fault** error : 
```
3504.546990792:main Q:Reg/w0  : ../action.c: actionPrepare[action-48-ommongodb]: enter
3504.546999527:main Q:Reg/w0  : ../action.c: actionDoRetry: action-48-ommongodb enter loop, iRetries=0, ResumeInRow 1
3504.547007813:main Q:Reg/w0  : ../action.c: actionDoRetry: action-48-ommongodb action->tryResume returned 0
3504.547015214:main Q:Reg/w0  : ../action.c: actionDoRetry: action-48-ommongodb had success RDY again (iRet=0)
3504.547025331:main Q:Reg/w0  : errmsg.c: Called LogMsg, msg: action 'action-48-ommongodb' resumed (module 'ommongodb')
3504.547033653:main …
```
> OMMONGODB : Fix segmentation fault when server is down

- plugins/imtcp/imtcp.c
- runtime/netstrms.c
- runtime/netstrms.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/imtcp-tls-input-2certs.sh
- tests/imtcp-tls-input-basic.sh
- tests/imtcp-tls-ossl-basic-tlscommands.sh
- tests/imtcp-tls-ossl-error-ca.sh
- tests/imtcp-tls-ossl-error-cert.sh
- tests/imtcp-tls-ossl-error-key.sh
- tests/imtcp-tls-ossl-error-key2.sh
- tests/imtcp-tls-ossl-input-2certs.sh
- tests/imtcp-tls-ossl-input-basic.sh
- tests/sndrcv_tls_anon_ipv6.sh
alternative to https://github.com/rsyslog/rsyslog/pull/4613
> imtcp: permit to use different certificate files per input/action [alternative approach]

- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- tests/Makefile.am
- tests/imtcp-tls-no-lstn-startup.sh
Test should have been added to commit 3d23c7ac8aea but was forgotten.
see also: https://github.com/rsyslog/rsyslog/pull/4627
> CI: add test for imtcp not correctly starting up

- plugins/imudp/imudp.c
Most importantly, the input name is used for stats counter names as
well. Previously, the same name was used for IPv4 and IPv6, so we had
two counters with an equal name. That left users puzzled.
Unfortunately, this change can potentially require changes to existing
analysis scripts, as the name is now slightly different.
closes https://github.com/rsyslog/rsyslog/issues/4364
> imudp: add socket type (IPv4 vs. 6) to input name

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/imfile-ignore-old-file-1.sh
- tests/imfile-ignore-old-file-2.sh
- tests/imfile-ignore-old-file-3.sh
- tests/imfile-ignore-old-file-4.sh
- tests/imfile-ignore-old-file-5.sh
- tests/imfile-ignore-old-file-6.sh
- tests/imfile-ignore-old-file-7.sh
Submit on behalf of the primary author @yanjunli76
instructs imfile not to ingest a file that has not been modified in the
specified number of seconds.
> imfile add `ignoreolderthanoption`

- runtime/nsd_ossl.c
closes: https://github.com/rsyslog/rsyslog/issues/4645
> openssl tls: Improved error message output on tls failures.

- tests/Makefile.am
- tests/diag.sh
- tests/es-basic-es7.14.sh
- tests/es-bulk-retry.sh
see also: https://github.com/rsyslog/rsyslog/pull/4566
> testbench: add basic test for ElasticSearch 7.14

- plugins/mmanon/mmanon.c
- tests/Makefile.am
- tests/mmanon_ipv6_port.sh
- tests/mmanon_zero_96_ipv6.sh
We so far tried to ensure a value is really an IPv6 address, in order
to avoid to mangle with just similar-looking information elements.
However, this lead to misdetection for unusual formats, e.g. when a
port is appended to a numerical IPv6 adress given without braces [].
This has been changed now. In a sense, we now prefer to err on the
side of privacy.
BEHAVIOR CHANGE:
Previously, a suspect value was not anonymized, and thus some other
elements (like some MAC addresses) preserved. Now the opposite is
true, and we anonymize anything that looks close enough to be an
IPv6 address. This improves anonymization.
closes https://github.com/rsyslog/rsyslog/issues/4725
> mmanon: relax IPv6 detection - improve anonymization

- README.md
> readme: remove duplicate dependent installation

- .github/workflows/run_journal.yml
remove unnecessary components - gives slightly better runtime
> CI: cleanup journal test environment

- grammar/rainerscript.c
This problem occurred when numbers were used in rsyslog.conf in
the set statement, e.g.
set $nbr = 1234;
In this case, during comparisons, the number was actually interpreted
as a string with digits. Thus numerical comparisons lead to unexpected
results. Even more so, as in other places of the code they were
treated as native numbers.
This is now fixed. We cannot outrule that this causes, in border cases,
change of behavior to existing configs. But it is unlikely and the
previous behaviour was a clear bug and very unintuitive. This in our
opinion it is justified to risk a breaking change for an expected
very minor subset of installations, if any such exists at all.
closes https://github.com/rsyslog/rsyslog/issues/4770
This is an alternative, and probably better, approach to …
> rscript: literal numbers were not compared correctly

- tests/Makefile.am
- tests/rscript_number_comparison_LE-vg.sh
- tests/rscript_number_comparison_LE.sh
- tests/rscript_number_comparison_LT.sh
- tests/rscript_number_comparison_all-vg.sh
- tests/rscript_number_comparison_all.sh
This covers failure cases from practice which were not yet covered.
see also: https://github.com/rsyslog/rsyslog/issues/4770
> testbench: test cases for rscript comparisons

- tests/solaris/prep-libfastjson.sh
- tests/solaris/prep-librelp.sh
github disabled anon access via git protocol, so we need to adjust
this to https
no functional change
> testbench: change git access protocol to cover github change

- runtime/datetime.c
- runtime/datetime.h
- runtime/msg.c
- template.c
- template.h
- tests/Makefile.am
- tests/timestamp-isoweek.sh
This addresses the issues with date-week reported in #2845
> add property options to support ISO week/year number

- tools/rsyslogd.c
there was a more or less cosmetic data race which could happen when children
processes died in quick sequence. Even then, no real harm happened, as all
children were reaped eventually.
A similar data race exists for HUP processing.
However, these races polluted TSAN test runs, and so we fixed them.
> bugfix: cosmetic data races

- plugins/imfile/imfile.c
This kind of re-opens https://github.com/rsyslog/rsyslog/pull/4445, which was closed for some (unknown) reason .
do_inotify block only once for events with timeouts. There is possible
scenario where no data is available and read() enters blocking while poll()
is released.
The change introduced here changes the racy reading to be same for the
triggered file as for the rest of the files:
current:
- Inotify is triggered
- Triggering file is read for new data
- Rest of the files are read for timer expiration
- more inotifys are processed these may be at the end of the file already as well then
new:
- Inotify is triggered
- All files are read for timer expiration, which includes the triggering file
- Triggering files is read for data, this may be at the end of the file already then
- more …
> imfile: do_inotify() use only one blocking call

- tests/testbench_test_failed_rsyslog
> cleanup: remove file accidentally added to git

- plugins/imptcp/imptcp.c
We now set the worker thread names to "imptcp/<thrd nbr>" where
<thrd nbr> is the numerical index (0, 1, ...) of the worker thread.
This enables to distinguish individual worker threads in OS tools like
htop. That is useful for performance testing and system monitoring.
The choosen name format is consistant with other similar thread
names inside rsyslog. For imptcp, worker threads were not yet
given individual names.
Note: "in:imptcp" is imptcp's "main" thread, which also is used
as a worker in some scenarios. This name was not modified.
> imptcp: set OS worker thread name

- plugins/omelasticsearch/omelasticsearch.c
I dosen´t spent time to compile it with the musl-libc.
So I added the libc to the rsyslog-docker  Alpine-Appliance  (see the rsyslog-docker  pull-request)
> Elasticsearch 8.x support (Data Stream API)

- runtime/tcps_sess.c
- runtime/tcps_sess.h
- tests/diag.sh
This patch slightly improves performance for tcpsrv-based servers.
This affects imtcp and imgssapi as well as some helpers.
No other functional change is included in this patch.
> tcpsrv/imtcp: slight performance improvements

- runtime/nsd_ossl.c
- OpenSSL error strings are loaded automatically now
- Debug Callback has changed
- See for more:
https://www.openssl.org/docs/manmaster/man7/migration_guide.html
closes: https://github.com/rsyslog/rsyslog/issues/4912
> OpenSSL: fix depreacted API issues for OpenSSL 3.x

- .github/workflows/ci_compile.yml
- .github/workflows/run_checks.yml
- .github/workflows/run_fedora_35.yml
- .github/workflows/run_ubuntu_20_codecov.yml
- .github/workflows/run_ubuntu_22.yml.DELETE_ME
remove EOL platforms and add current ones
> CI: modernize platform

- plugins/mmdblookup/mmdblookup.c
- [MMDBLOOKUP] Handle failures to read/access one mmdb file properly and suspend the module for some time instead of crashing Rsyslog with a failed assert
> MMDBLOOKUP::FIXED:: Avoid Rsyslog crashes when a mmdb file cannot be opened/read

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
Support sha256 hashes for "x509/fingerprint" for gtls and ossl
#4928
> support sha256 for StreamDriverAuthMode="x509/fingerprint"

- contrib/omrabbitmq/omrabbitmq.c
Trying to enable TLS connections for omrabbitmq module.
This code is currently working on Rocky 8.6 running rsyslog 8.2102.0
Connection is made successfully to a RabbitMQ 3.10.6 server over TLS, messages flowing.
While I finish the testing, can someone more familiar with the codebase please review the code for any mistakes I might have made?
> omrabbitmq: Add TLS support

- tests/imfile-logrotate-async.sh
- tests/inputfilegen.c
In some cases, the logrotate is not fast enough rotating the
logfile after sighub has been send to inputfilegen process. It appears
to happen more often on github CI machines, when it happens,
inputfilegen reopens the NOT yet rotated file and keeps writing
into it. However most messages written until the next sighub are lost
after the logfile finally is rotated.
In order to avoid this, I have added an extra sleep between file
CLOSE and OPEN after sighub with a default of 5ms which appears to work
very well. This should give logrotate enough time to perform the
actuzal rotate.
Also added another parameter to inputfilegen to keep the process
open after finish. Which helps syncing with the testcases.
> testbench: Adjusted timing for test imfile-logrotate-async.sh

- contrib/ffaup/ffaup.c
ffaup fix : The ffaup function fails to work properly when it is used with multiple workers.
The faup_handler_t struct is not supposed to be shared between threads.
This may cause memory corruptions and race conditions when used inside of actions.
> Fix ffaup thread safety

- .github/workflows/codeql.yml
removing invalid and not really needed stuff
> CI: fix github CodeQL settings

- runtime/msg.c
This problem can occur if a large number of threads is used and rsyslog cannot shut down all queues etc within the regular time interval. In this case, it cancels some threads. That can leave the mutex guarding libuuid calls locked and thus prevents other, not yet cancelled threads from progressing. Assuming pthread_mutex_lock() is not a cancellation point, this will case these other threads to hang forever and thus create a deadlock situation.
closes https://github.com/rsyslog/rsyslog/issues/5104
> core/bugfix: using $uuid msg prop can deadlock rsyslog on shutdown

- tools/rsyslogd.c
In case the process does not have any capabilities, e.g. running as regular user then we do not have to force capability dropping. The ```capng_have_capabilities()``` returns none if that's the case. Fixes #5091
> Do not try to drop capabilities when we don't have any

- tests/diag.sh
Old version is no longer available.
> CI: update zookeper download to newer version

- tests/sndrcv_tls_ossl_anon_rebind.sh
> testbench: cleanup a test and some nitfixes to it

- tests/tcpflood.c
Note: tcpflood is a testbench tool. This bug could lead to testbench false positives. No way it can affect production deployments.
The tcpflood tool did improperly assume that a TCP sendto() call would send messages of any size in a single shot. This is not the case. It has now been corrected to proper behavior.
As a side-activity, some int variables which acutally needed to be size_t have been fixed as well.
> tcpflood bugfix: TCP sending was not implemented properly

- tests/tcpflood.c
In commit 5050249a1e tcpflood was "fixed" to work properly when senden data to a TCP stream socket. Unfortunately, there was an undetected copy&past problem, which this commit corrects.
The issue did unfortunatley not surfcase with the previous commit as the situation where this can happen occurs infrequently and randomly (has to do with timing on the system in question). So the original PR went fine, but later PRs brought the issue up.
This is not a real regression, as the original fix was for the same symptom, but with different cause. Now everything should indeed be fixed.
NOTE: same day correction on a testbench tool
> tcpflood: fix today's programming error

- tests/imfile-endmsg.regex-vg.sh
- tests/imfile-endmsg.regex.sh
- tests/imfile-endregex-save-lf-persist.sh
- tests/imfile-endregex-save-lf.sh
- tests/imfile-endregex-timeout-none-polling.sh
- tests/imfile-endregex-timeout-none.sh
- tests/imfile-endregex-timeout-polling.sh
- tests/imfile-endregex-timeout-with-shutdown-polling.sh
- tests/imfile-endregex-timeout.sh
- tests/imfile-endregex-vg.sh
- tests/imfile-endregex.sh
Added state files to make tests more robust in parallel test execution. Fixed some slightly out of order setup statements. Cleaned up some noise.
> testbench: cleanup and improve some more imfile tests

- tools/rsyslogd.8
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904280
> Typo fixes

- tools/rsyslogd.c
fixes #5241 
After fork if the child process uses close_range to close open file descriptors it has no way to exempt the parentPipeFD causing a failure to signal successful startup to the parent process.  This causes failures on all systems that aren't Linux that implement close_range.  This patch removes the use of close_range and reverts to just looping over possible file descriptors on those platforms.
> Fix forking issue do to close_range call

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- tests/Makefile.am
- tests/sndrcv_tls_certvalid_expired.sh
- tests/sndrcv_tls_certvalid_revoked.sh
- tests/sndrcv_tls_client_missing_cert.sh
This provides richer and easier to process logs for error and warning cases. One goal is to enable automatic operations without the need to consolidate multiple message to a single information.
This improves one situation in gtls driver and provides a more generic approach in ossl driver for OpenSSL error reporting.
There is probably still room for improvement, however this patch is at least a good starting point for further work. Please provide feedback if you need more!
closes https://github.com/rsyslog/rsyslog/issues/5244
> TLS subsystem: add remote hostname to error reporting

- plugins/omlibdbi/omlibdbi.c
Solves #5282 considering previous PR #4763
> Solves omlibdbi+sqlite3 dirname problem without creating use-after-free problem

- plugins/imjournal/imjournal.c
The `DefaultTag` option specifies the default value for the tag field. In imjournal, this can happen when one of the following is missing:
* identifier string provided by the application (`SYSLOG_IDENTIFIER`) or
* name of the process the journal entry originates from (`_COMM`)
Under normal circumstances, at least one of the previously mentioned fields is always part of the journal message. But there are some corner cases I've ran into. With this patch I would like to have the ability to alter the content of the tag field.
> imjournal: Add new input module parameter 'defaulttag'

- plugins/external/messagemod/fac-sever-rewrite/fac-sever-rewrite.py
Rewrite the plugin for Python 3, adding CLI arguments to make it useful out of the box.
I've not fully tested this yet, but I'm about to start using it myself.
Are you interested in taking this, and if so is anything else required?
> New fac-sever-rewrite.py for Python 3

- tools/omfile.c
In some use cases omfile is configured to write to /dev/null. This seems primarily be done because of statistics gathering but maybe some other scenarios. We now add conditional logic to not do any actual omfile action when the target file is /dev/null.
Note: this check only works on static file names. When /dev/null is evaluated as part of dynafile, it will be handled just in the regular case like before this patch.
> omfile: do not carry out actual action when writing to /dev/null

- tools/omusrmsg.c
omusrmsg frees a string which points to OS/system library memory. When the os/libs clean up, it frees the memory as well. This results in a double free. This bug interestingly seems to go unnoticed in many cases. But it can cause a segfault or hard-to-trace memory corruptions which could lead to other problems later on. The outcome of this bug most probably depdns on os/library versions.
closes https://github.com/rsyslog/rsyslog/issues/5294
> omusrmsg bugfix: potential double free, which can cause segfault

- contrib/mmkubernetes/mmkubernetes.c
- plugins/imfile/imfile.c
correctly handle time_t values which can be 64bit on 32bit architectures.
> time_t related fixes

- runtime/nsd_ossl.c
closes: https://github.com/rsyslog/rsyslog/issues/5427
> openssl: Add remoteclient to LogMsg where possible

- plugins/imptcp/imptcp.c
> imptcp: improve error messages

- runtime/nsd_ptcp.c
If we try to connect via TCP and the connections fails, we now tell inside the error message how long the connection attempt took. This is useful to find out if targets connect very slowly.
> network subsystem: improve connection failure error message

- plugins/imjournal/imjournal.c
Previously, upon detecting a journal rotation, the pointer did not correctly advance to the next log entry, causing the first new message to be missed. This update ensures that the cursor is advanced correctly, allowing all entries to be read without skipping the first message after rotation.
There were two calls to `sd_journal_next()` — one in `handleRotation` and another in `doRun` caused the first message after rotation to be skipped." This is because sd_journal_next advances the read pointer into the journal by one entry. I deleted the call from `handleRotation()`.
```
#!/bin/bash
for i in {1..15}; do
logger "test$i"
done
exit 0
```
```
MaxRetentionSec=10s
MaxFileSec=10s
Audit=false
```
Run `systemctl restart systemd-journald; sleep 11; ./writer.sh` and observe that some logs will not …
> imjournal: Fix first message loss after journal rotation

- plugins/omazureeventhubs/omazureeventhubs.c
Sometimes Primary key or Secondary key will be generated with invalid URL characters like '/'. azure_key and azure_key_name are now checked and replaced before building the amqps:// URL internally.
closes: https://github.com/rsyslog/rsyslog/issues/5464
> omazureeventhubs: Handle invalid URL characters in config parameters

- .github/workflows/ci_compile.yml
- runtime/cfsysline.c
- runtime/linkedlist.c
- runtime/linkedlist.h
- runtime/obj-types.h
- runtime/obj.c
- runtime/obj.h
- runtime/queue.c
- runtime/rsconf.c
- runtime/rsyslog.h
- runtime/ruleset.c
- tests/sndrcv_tls_anon_rebind.sh
- tests/sndrcv_tls_client_missing_cert.sh
- threads.c
- tools/iminternal.c
possibly replaces https://github.com/rsyslog/rsyslog/pull/5510
> Gnu23 workaround

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
- runtime/nsdsel_gtls.c
- runtime/nsdsel_ossl.c
This commit cleans up the driver layer and mirrors work that is done in the broader imtcp multitasking enhancement work.
see also: #5532
> netstrm TLS driver: move TLS retry handling to main driver

- tests/tcpflood.c
Connections were originally opened sequentially. This commit adds the capability to open them via multiple threads in parallel.
This is needed at least for cases where we need to test multiple pending connection requests, which can be accept with an "accept() loop".
It can also be useful for speeding up parts of the testbench. However, the additional concurrency makes it potentially harder to debug if bugs are detected. So tests may use multiple threads for connect during regular operations but should also offer the option (by editing) to revert to a single thread for easier debugging.
closes https://github.com/rsyslog/rsyslog/issues/5535
> tcpflood test tool: enable multi threaded connection open

- ChangeLog
Fix the date errors in the Changelog.
> Maintain ChangeLog

- tests/tcpflood.c
closes: https://github.com/rsyslog/rsyslog/issues/5542
> testbench: Fix OpenSSL 3.x depreceated warnings in tcpflood

- tools/rsyslog.conf.5
- tools/rsyslogd.8
A small man page update to signal that man pages are up to date. Some users might misinterpret it if there are still old dates and versions.
> Update man page dates

- plugins/imgssapi/imgssapi.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
> netstrm: optimized interface for passing connection err info

- plugins/imudp/imudp.c
closes https://github.com/rsyslog/rsyslog/issues/5646
> imudp: Output errno after recvmmsg call

- Makefile.am
- configure.ac
- plugins/omsendertrack/Makefile.am
- plugins/omsendertrack/omsendertrack.c
- runtime/rsyslog.h
- tests/Makefile.am
- tests/omsendertrack-basic-vg.sh
- tests/omsendertrack-basic.sh
- tests/tcpflood.c
implements https://github.com/rsyslog/rsyslog/issues/5599
> Omsendertrack

- plugins/omazureeventhubs/omazureeventhubs.c
> fix mime type typo

- devtools/check-codestyle.sh
- devtools/rsyslog_stylecheck.py
- plugins/imdtls/imdtls.c
- plugins/imklog/bsd.c
- plugins/mmaudit/mmaudit.c
- plugins/mmpstrucdata/mmpstrucdata.c
- plugins/omdtls/omdtls.c
- plugins/omjournal/omjournal.c
- plugins/ommail/ommail.c
- plugins/ommysql/ommysql.c
Easier to maintain than the off-project C source. The checks are pretty trivial.
This also fixes some nits that the old checker did not detect.
closes https://github.com/rsyslog/rsyslog/issues/5631
> CI: new python-based codestyle checker

- AGENTS.md
- grammar/rainerscript.h
> doc: improve description of config parameter block handling

- runtime/cfsysline.c
- runtime/conf.c
- runtime/datetime.c
- runtime/glbl.c
- runtime/janitor.c
- runtime/lib_ksils12.c
- runtime/libcry_common.c
- runtime/libgcry.c
- runtime/libossl.c
- runtime/netstrm.h
- runtime/netstrms.c
- runtime/nsd.h
- runtime/nsd_ptcp.c
- runtime/obj.c
- runtime/rsconf.h
> cleanup: fix some TODOs and remove outdated ones

- runtime/tcpsrv.c
This fix prevents polluting the message log and solves a long-standing testbench issue where it can occur during high test concurrency due to sluggish timing.
> tcpsrv: fail to remove already-removed epoll fd is no error

- doc/source/configuration/modules/omsendertrack.rst
> doc: first omsendertrack reference manual entry

- AGENTS.md
- tests/diag.sh
Testbench tools like tcpflood are now auto-generated at test startup if missing, reducing errors and confusion during local test runs.
Updated AGENTS.md with precise instructions for running tests in both human and AI agent contexts, improving onboarding for new developers and AI-based workflows.
> CI: auto-generate testbench tools and refine AI agent instructions

- ai/README.md
Establish a new top-level directory, `ai/`, to serve as a consistent location for future Artificial Intelligence and Machine Learning tools that will work alongside rsyslog.
These tools are intended to run as separate processes, external to the rsyslog daemon, to ensure the core remains stable and performant.
This commit contains only the empty directory and a README.md file describing the vision and purpose.
> AI tools: Add directory for future AI/ML tooling

- devtools/fix-spaces.py
- runtime/cfsysline.c
- runtime/conf.c
- runtime/dynstats.c
- runtime/dynstats.h
- runtime/linkedlist.c
- runtime/module-template.h
- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
- runtime/obj-types.h
- runtime/obj.c
- runtime/objomsr.c
- runtime/strgen.c
- runtime/stringbuf.c
- runtime/tcpclt.c
- runtime/wtp.c
- tests/getline.c
- tests/mangle_qi.c
- tests/rscript.c
- tests/tcpflood.c
- tools/logsigner.c
This may be an interim solution, but definitely a useful one to address style inconsistencies.
Style inconsistencies are problematic as they tend to pollute git history by causing pseudo-changes.
This commit also contains a set of fixes to existing files, so that we get to a clean state.
> tooling: new developer tool to fix trailing spaces

- .github/ISSUE_TEMPLATE/1_support_question.md
- runtime/queue.c
- runtime/queue.h
> dev doc: add design notes to queue subsystem files

- packaging/docker/README.md
also fixes https://github.com/rsyslog/rsyslog/issues/5743
> docker: reflect new state of repo

- doc/source/configuration/properties.rst
- doc/source/tutorials/tls_cert_ca.rst
> docs: Fix minor typos

- doc/source/faq/common-config-mistakes.rst
- doc/source/faq/index.rst
"& stop" is right on top of the misunderstandings
> doc: add FAQ with commonly misunderstood config sequences

- action.c
Resubmitting PR #5121 because I need to apply new CI and am no longer able in the original PR. Original PR will be merged if this one runs OK.
> TESTING: Enhance action resume interval sleep time

- action.c
- action.h
There are no functional changes in this commit.
With support from AI Agents: Codex
> core: improve inline code doc for action.[ch]

- .github/workflows/run_checks.yml
- packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
- plugins/omazureeventhubs/omazureeventhubs.c
- build in run_checks ubuntu 24.04
closes: https://github.com/rsyslog/rsyslog/issues/5895
> omazurevenethubs: fix compilerwarning

- ai/support_gpt/base_prompt-gpt5.txt
> AI: a try at further improving custom GPT correctness

- tools/omfwd.c
Inline code docs clarify when omfwd should suspend an action in pooled
TCP forwarding. This improves maintainability and reduces ambiguity for
future changes and reviews.
Impact: No user-visible behavior change; semantics documented.
Before/After: Before, a per-target flush failure could be read as
suspending the action; after, SUSPENDED is returned only when the pool
has zero active targets.
Technically, commitTransaction no longer marks the action suspended on
a single-target flush failure. We destruct the failing target, keep the
commit OK, and rely on pool stats plus `countActiveTargets()` to decide
pool-wide availability. Only when `nActiveTargets == 0` do we return
RS_RET_SUSPENDED, engaging the action engine's retry. Buffered frames
for a failed target remain with that target and …
> omfwd: document and enforce pool-level suspend semantics

- .github/copilot-instructions.md
- .github/instructions/docs.instructions.md
- .github/instructions/modules.contrib.instructions.md
- .github/instructions/modules.plugins.instructions.md
This adds repository-level instructions to guide GitHub Copilot in producing higher quality and safer pull requests. It is part of the "AI First" approach, aiming to improve contributor experience and reduce review friction.
Impact: no change to runtime or user-facing behavior.
The new files under `.github/` provide scoped rules for Copilot across documentation, plugins, and contrib modules. They emphasize alignment with AGENTS.md, developer checklists, and module maps. Guardrails cover quoting, doc structure, config conventions, and mandatory source citations. The intent is to ensure AI-assisted edits follow existing rsyslog patterns and remain minimal and test-backed.
These changes are additive only and have no effect on rsyslog code, APIs, or operational semantics. They prepare the …
> ci: add copilot support instruction files

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
We want to ensure our community is always welcoming and acts professionally.
> doc: add code of conduct

- .github/workflows/codeql.yml
Add CodeQL actions analysis to protect against workflow vulnerabilities.
---
---
```
```
into the commit message for a clean history.
> Add actions analysis

- .github/workflows/contributor-welcome.yml
This does currently not work correctly. We need to fix it, but there currently is no time to do that now.
---
---
```
```
into the commit message for a clean history.
> community: disable automatic welcome action

- runtime/rsconf.c
> core: some code cleanup

- doc/source/configuration/lookup_tables.rst
Add reference for regex lookup tables. Describe POSIX regex support, first-match semantics, performance drawbacks, and overlapping pattern caution. Include sample table and fix minor wording.
AI-Agent: ChatGPT-4o
---
---
```
```
- If key info is only in …
> doc: describe regex lookup table type

- doc/source/getting_started/beginner_tutorials/01-installation.rst
- doc/source/getting_started/beginner_tutorials/02-first-config.rst
- doc/source/getting_started/beginner_tutorials/03-default-config.rst
- doc/source/getting_started/beginner_tutorials/04-message-pipeline.rst
- doc/source/getting_started/beginner_tutorials/05-order-matters.rst
- doc/source/getting_started/beginner_tutorials/06-remote-server.rst
- doc/source/getting_started/beginner_tutorials/index.rst
- doc/source/getting_started/index.rst
We are redesigning the new user onboarding doc. This commit provides very first experience documentation. Some is duplicate content to the previous version, which we keep for now.
A cleanup will follow later. We want to gain some feedback first. Thus the early merge.
> doc: new beginner tutorials

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
Context
- Issue: https://github.com/rsyslog/rsyslog/issues/5627
- Servers can send TLS 1.3 KeyUpdate post-handshake. The client must read to update keys; otherwise, writes can stall.
- During Send(), when the TLS lib requests READ (WANT_READ/READ direction), rsyslog must drive a read to process pending TLS records.
What changed
- runtime/nsd_ossl.c:
- Send(): If SSL_write() returns SSL_ERROR_WANT_READ, call osslRecordRecv() (buffered) to process TLS records (e.g., KeyUpdate), then retry write.
- Send(): Treat SSL_ERROR_ZERO_RETURN as RS_RET_CLOSED (peer sent close_notify).
- runtime/nsd_gtls.c:
- Send(): If gnutls_record_send() returns E_AGAIN/E_INTERRUPTED and direction is READ, call gtlsRecordRecv() (buffered), then retry write.
Why this is safe
- Backward-compatible: extra receive only …
> PR Summary: Handle TLS 1.3 KeyUpdate during send in ossl/gtls

- doc/BUILDS_README.md
- doc/README.md
- doc/tools/build-doc-linux.sh
- doc/tools/build-doc-windows.ps1
This PR introduces cross-platform helper scripts to streamline the rsyslog documentation build process and updates build instructions for better contributor experience. The changes address the documentation build issues reported in [#6143](https://github.com/rsyslog/rsyslog/issues/6143) where building docs from git leads to broken HTML output.
Issue [#6143](https://github.com/rsyslog/rsyslog/issues/6143) reported that building documentation from git results in broken HTML output, even when the build process completes without warnings. This suggests that the current manual setup process may not be creating the proper environment for consistent documentation builds.
- **`doc/tools/build-doc-linux.sh`**: Linux helper script with comprehensive virtual environment management
- …
> doc: Improve Documentation Build Process with Cross-Platform Helper Scripts

- Makefile.am
- configure.ac
- doc/source/configuration/modules/mmleefparse.rst
- packaging/docker/dev_env/debian/base/sid/Dockerfile
- packaging/docker/dev_env/ubuntu/base/22.04/Dockerfile
- packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
- plugins/mmleefparse/Makefile.am
- plugins/mmleefparse/mmleefparse.c
- tests/Makefile.am
- tests/mmleefparse_basic.sh
This parses the LEEF message (if it is) and creates a JSON subtree. The current implementation is PoC and will be provided to gather early review.
Changes, including breaking changes, may happen in future versions of this module.
> mmleefparse: new message modification module for LEEF format

- .github/workflows/run_kafka_distcheck.yml
We more precisely specify when and how exactly kafka tests need to be carried out.
> CI: optimize kafka test execution time a bit

- tests/diag.sh
- tests/imptcp-msg-truncation-on-number.sh
- tests/imptcp-msg-truncation-on-number2.sh
- tests/manytcp.sh
- tests/sndrcv_kafka_multi_topics.sh
This PR adds comprehensive macOS CI support and significantly improves test diagnostics across all platforms, particularly for macOS-specific issues.
- **Improved startup handling**:
- Separate timeout handling for valgrind vs normal runs
- Immediate crash detection during rsyslog startup
- More frequent process health checks
- **Comprehensive core dump analysis**:
- Platform-specific debugger support (lldb for macOS, gdb for Linux)
- Multi-location core dump search and analysis
- Enhanced stack trace collection
- **macOS-specific improvements**:
- System information gathering and crash reporter analysis
- Core dump pattern and settings reporting
- **Better error reporting**:
- Disk space monitoring and warnings
- Enhanced log collection
- **Skip failing TCP tests on Darwin** due to TCP …
> ci: macOS improve test diagnostics

- doc/source/configuration/modules/imjournal.rst
see also: https://github.com/rsyslog/rsyslog/issues/6178
closes: https://github.com/rsyslog/rsyslog/issues/6179
> doc: update imjournal journald warning

- runtime/AGENTS.md
- tests/AGENTS.md
The last commit which I made were missing these files. Now adding them.
> AI: add missing AGENTS.md files

- doc/source/concepts/index.rst
- doc/source/concepts/log_pipeline/design_patterns.rst
- doc/source/concepts/log_pipeline/example_json_transform.rst
- doc/source/concepts/log_pipeline/index.rst
- doc/source/concepts/log_pipeline/stages.rst
- doc/source/concepts/log_pipeline/troubleshooting.rst
- doc/source/getting_started/beginner_tutorials/04-message-pipeline.rst
Using better to understand term "Log Pipeline" vs. "Message Pipeline" and adding an in-depth concepts part including a sample config.
> doc: im prove log pipeline documentation
