- action.c
- runtime/modules.c
- runtime/tcpsrv.c
- template.c
> cleanup: remove commented-out code

- plugins/omkafka/omkafka.c
Use statsFile to specify statistics output file; also requires setting statistics.interval.ms confparam to a non-zero value.
> omkafka: Add ability to dump librdkafka statistics to a file

- tests/imtcp-tls-basic.sh
- tests/imtcp_conndrop_tls-vg.sh
- tests/imtcp_conndrop_tls.sh
- tests/tcpflood.c
when tcpflood detected a certificate error, it reported an
error message but did not abort. This could make errors undetectable
during CI runs.
> tcpflood bugfix: tool did not terminate on certificate error

- contrib/omhttp/omhttp.c
> omhttp: "fix" LGTM false positive regarding commented out code

- tests/imuxsock_traillf.sh
> fix deprecated bash expression

- configure.ac
$enable_libcurl was removed in commit dc95ef09bdb07cfb7b7df4ce87df629fc2c94f8f.
However, it wasn't removed from status overview.
This commit will remove $enable_libcurl from status overview.
> configure: remove orphaned enable_libcurl status from overview

- tests/mmdb-multilevel-vg.sh
- tests/mmdb-vg.sh
> testbench: mmdb valgrind tests failed is srcdir env was not set

- tests/imuxsock_traillf_syssock.sh
> fix legacy shell command

- tests/imfile-error-not-repeated.sh
> fix legacy shell expression

- configure.ac
- plugins/imrelp/imrelp.c
- plugins/omrelp/omrelp.c
- tests/Makefile.am
- tests/diag.sh
- tests/have_relpEngineSetTLSLibByName.c
- tests/imrelp-basic-vg.sh
- tests/imrelp-basic.sh
- tests/imrelp-invld-tlslib.sh
- tests/omrelp-invld-tlslib.sh
- tests/omrelp_wrong_authmode.sh
see also https://github.com/rsyslog/rsyslog/issues/3451
> omrelp: add capability to specify tlslib for librelp

- tests/Makefile.am
- tests/imrelp-tls.sh
- tests/tcpflood.c
Tcpflood can now send messages via relp with tls support.
A test was added aswell.
closes https://github.com/rsyslog/rsyslog/issues/3448
> tcpflood: add new transport option relp-tls

- plugins/omclickhouse/omclickhouse.c
> omclickhouse: work-around failed error detection

- action.c
- plugins/imuxsock/imuxsock.c
- runtime/rsyslog.h
> portability: hide (some) pragmas in macros

- plugins/imdiag/imdiag.c
- tests/queue-encryption-disk_keyfile-vg.sh
> testbench: increase timeout for test + better to exp reporting

- runtime/rsconf.c
STDSQL option added to the default template used in output module of clickhouse
> clickhouse default template fix

- tests/Makefile.am
- tests/clickhouse-dflt-tpl.sh
> testbench: add test for omclickhouse with default template

- tests/complex1.sh
- tests/libdbi-asyn.sh
- tests/mysql-asyn-vg.sh
- tests/mysql-asyn.sh
- tests/threadingmqaq.sh
> testbench: increase explicit enqueue timeout for slow CI systems

- tests/minitcpsrvr.c
We need this in order to help debug cases where minitcpsrvr seem to
have force-terminated before it was finished (on slow machines).
> testbench tool minitcpsrvr: inform of regular shutdown

- action.c
> cleanup: remove no longer needed include

- contrib/imczmq/imczmq.c
Make the 0MQ frame pointer local to the receive loop and destroy the
frame as soon as the contents have been copied. This avoids:
o a memory leak should the receive loop execute more than once
o referencing an un-initialised value during cleanup (finalize_it)
> Release zframe following read from socket

- runtime/lib_ksils12.c
> ksi component: update deprecated definitions

- tests/diag.sh
some tests need an extra bit, and we go as high as sounds safe in
regard to CI integration.
> testbench: increase TB_TEST_MAX_RUNTIME

- tests/diag.sh
- tests/imrelp-manyconn.sh
- tests/queue-encryption-disk_keyfile.sh
- tests/queue-minbatch-queuefull.sh
we bind the shutdown timeout to the general MAX RUN timeout
also modernize testbench a bit more
> testbench: make shutdown more reliable

- tests/queue-minbatch.sh
most probably an issue with atomic ops - disabling on Solaris for now
> testbench: queue_minbatch does not work on solaris

- tests/imfile-basic-2GB-file.sh
- tests/imfile-truncate-2GB-file.sh
closes https://github.com/rsyslog/rsyslog/issues/3493
> testbench bugfix: long-running tests had too low runtime allowance

- runtime/msg.c
- runtime/msg.h
using a large enough (dozens of kBs) structured message
it is possible to overflow the signed short type which leads
to rsyslog crash.
This is possible because with setting higher maxMessageSize  one can overflow the small signed type which the core dumps during additional message processing.
> Enlarged msg offset types for bigger structured messages

- configure.ac
- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
- runtime/lmsig_ksi-ls12.c
Libksi version 3.18 supports high availability mode of operation. In HA mode multiple server endpoints can be configured and requests are sent to all them simultaneously while the first valid response is always used. This improves the availability of the service and reduces response latency.
> Issue 3338: lmsig_ksils12: Add high avalability mode supported by libksi 3.18

- contrib/omhttp/omhttp.c
Allows spaces in `headervalue`s for the `omhttp` module
> Allow header values to have spaces

- tests/CI/PR_validation.sh
This adds the check script. It is up to CI to use it or not.
> CI: add PR validation in regard to commit structure

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/diag.sh
- tests/imfile-logrotate-multiple.sh
- tests/imfile-persist-state-1.sh
- tests/imfile-statefile-no-file_id-TO-file_id.sh
- tests/imfile-statefile-no-file_id.sh
State file handling was invalid. When a file was moved and re-created rsyslog could use the file_id if the new file to write the old files' state file. This could make the file reader stuck until it reached the previous offset. Depending on file sizes this could never happen AND would cause large message loss. This situation was timing dependent (a race) and most frequently occurred under log rotation. In polling mode the bug was less likely, but could also occur.
closes: https://github.com/rsyslog/rsyslog/issues/3465
closes: https://github.com/rsyslog/rsyslog/issues/3468
> imfile bugfix: file reader could get stuck

- plugins/omkafka/omkafka.c
- tests/Makefile.am
- tests/omkafkadynakey.sh
Hi,
we needed a way to force the kafka partition based on the data being pushed. Pretty much the subject of #1421. Here is a patch that allows to use a template to provide the partitioning key.
A new configuration property "dynaKey" is added that, when "on", changes the value of property "key" to a template names instead of a constant value. This is similar in approach to the DynaTopic implementation.  
Our system uses mmjsonparse to extract from the message the property we use as a key. The config we are using  (the relevant part) :
```
module(load="omkafka")
module(load="mmjsonparse")
template(name="json_log" type="list") {
constant(value="{")
constant(value="\"@timestamp\":\"")  property(name="timereported" dateFormat="rfc3339")
constant(value="\",\"tags\":[\"") property(name=".tag") …
```
> omkafka: add support for dynamic keys

- CONTRIBUTING.md
> update contributor doc to current state; add some more background info

- plugins/imjournal/imjournal.c
In one case there was possibility of free()'d value of journal
cursor not being reset, causing double-free and crash later on.
> Added missing reset of journal cursor

- tests/imrelp-manyconn.sh
- tests/manytcp.sh
- tests/tcpflood.c
It looks like the soft limit became defunct when tcpflood was enhanced to request more open file handles from OS.
closes https://github.com/rsyslog/rsyslog/issues/1108
> tcpflood bugfix: make soft connection limit work again

- runtime/msg.c
- runtime/obj-types.h
- runtime/obj.c
- runtime/stringbuf.c
this now handles optional developer debug statements via preprocessor define
> fix commented out-code

- runtime/stream.c
> usability: specify file name in error message (was only fd)

- plugins/omkafka/omkafka.c
fails depending on platform and settings; was somehow undetected by CI
> omkafka bugfix: build failure due to inconsistent type

- tests/diag.sh
old version is no longer available; in general it is best to test with current one
> testbench: bump kafka version

- contrib/mmkubernetes/mmkubernetes.c
- contrib/omhttp/omhttp.c
- plugins/omclickhouse/omclickhouse.c
- plugins/omelasticsearch/omelasticsearch.c
Add ability to specify the libcurl CURLOPT_SSL_VERIFYHOST
option to skip verification of the hostname in the peer cert.
WARNING: This option is insecure, and should only be used
for testing. The default value is off, meaning, the hostname
will be verified by default.
> add support for skipverifyhost

- tests/pipeaction.sh
> testbench: enable ompipe test on Solaris again and modernize it

- plugins/omelasticsearch/omelasticsearch.c
- tests/es-basic.sh
Adds support for a new parameter `rebindinterval`
This parameter tells omelasticsearch to close the connection and
reconnect to Elasticsearch after this many operations have been
submitted.  The default value `-1` means that omelasticsearch will
not reconnect.  A value greater than `-1` tells omelasticsearch,
after this many operations have been submitted to Elasticsearch,
to drop the connection and establish a new connection.  This is
useful when rsyslog connects to multiple Elasticsearch nodes
through a router or load balancer, and you need to periodically drop
and reestablish connections to help the router balance the
connections.  Use the counter `rebinds` to monitor the
number of times this has happened.
> omelasticsearch: add support for rebindinterval

- contrib/mmkubernetes/mmkubernetes.c
- runtime/atomic.h
- runtime/statsobj.h
- tests/Makefile.am
- tests/mmkubernetes-basic-vg.sh
- tests/mmkubernetes-basic.sh
- tests/mmkubernetes-cache-expire-vg.sh
- tests/mmkubernetes-cache-expire.out.expected
- tests/mmkubernetes-cache-expire.sh
New parameters for mmkubernetes (module and action):
* `cacheexpireinterval`
If `cacheexpireinterval` is -1, then do not check for cache expiration.
If `cacheexpireinterval` is 0, then check for cache expiration.
If `cacheexpireinterval` is greater than 0, check for cache expiration
if the last time we checked was more than this many seconds ago.
* `cacheentryttl` - maximum age in seconds for cache entries
New statistics counters:
* `podcachenumentries` - the number of entries in the pod metadata cache.
* `namespacecachenumentries` - the number of entries in the namespace
metadata cache.
* `podcachehits` - the number of times a requested entry was found in the
pod metadata cache.
* `namespacecachehits` - the number of times a requested entry was found
in the namespace metadata cache.
* …
> mmkubernetes - support for metadata cache expiration

- tests/diag.sh
The version used so far is no longer available.
> testbench: bump zookeeper version

- runtime/nsd_ptcp.c
do a check with larger buffer and reset on >= 0 bytes read .
> WiP: rsyslog doesn't respond to TLS close_notify 

- runtime/nsd_ptcp.c
Reverts rsyslog/rsyslog#3535
This actually caused a lot of problems, including https://github.com/rsyslog/rsyslog/issues/3587
The main issue is that the errno check seems actually be disabled. This might look like it worked, because it will frequently close connection. This "fixes" the original problem because we get lots and lots of new connections.
fixes #3587
> Revert "WiP: rsyslog doesn't respond to TLS close_notify "

- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
errno is printed with LogMsg if SSLErr is SSL_ERROR_SYSCALL (As recommended by OpenSSL doc) which enhances troubleshooting.
> openssl nsd driver: Enhanced error output for SSL_ERROR_SYSCALL

- tests/Makefile.am
- tests/imdocker-unittests.sh
It also causes unrelated testbench failures.
see also https://github.com/rsyslog/rsyslog/issues/3596
> testbench: disable imdocker-unittests because it does not work

- tests/imfile-symlink.sh
This test frequently fails. We suspect real problem. New instrumentation
hopefully helps narrowing down the case when the problem re-occurs.
The test was also slightly improved by removing an unnecessary duplicate
check.
see also https://github.com/rsyslog/rsyslog/issues/3550
> testbench: better instrumenation for imfile-symlink test

- plugins/omelasticsearch/omelasticsearch.c
- tests/es-bulk-retry.sh
https://github.com/rsyslog/rsyslog/issues/3573
Previously, when constructing the message to submit for a retry
for an original request, if the original request did not contain
the field `message`, the system property `rawmsg` was set to
the entire metadata + data from the original request.  This was
causing problems with Elasticsearch.  This patch changes
the code so that the `rawmsg` will be set to only the data part
of the original request if there is no `message` field.
> omelasticsearch - retry: set rawmsg to data from original request

- tests/Makefile.am
Looks like nobody tried to run tests since last release against release tarball :-0
> testbench: Add missing omhttp tests to EXTRA_DIST

- Makefile.am
see also https://github.com/rsyslog/rsyslog/pull/3598
Note: this PR must initially fail and only be merged when EXTRA_DIST has been fixed (via #3598).
> build system bugfix: omhttp was ignored during "make distcheck"

- .codecov.yml
> CodeCov: split off contrib modules from main project

- plugins/pmnormalize/pmnormalize.c
- tests/Makefile.am
- tests/pmnormalize-basic-vg.sh
- tests/pmnormalize-basic.sh
- tests/pmnormalize-invld-rulebase-vg.sh
- tests/pmnormalize-invld-rulebase.sh
- tests/pmnormalize-neither_rule_rulebase-vg.sh
- tests/pmnormalize-neither_rule_rulebase.sh
- tests/pmnormalize-rule.sh
- tests/pmnormalize-rule_and_rulebase-vg.sh
- tests/pmnormalize-rule_and_rulebase.sh
- tests/pmnormalize-rule_invld-data-vg.sh
- tests/pmnormalize-rule_invld-data.sh
This patch fixes a set of problems plus provides more and enhanced
tests for the module.
Most important problem was a memory leak that occured when a message
could not be passed at all. For each message that could not be parsed
memory of at least the size the message is leaked. Depending on
traffic pattern this can quickly lead to OOM. Note, however, that
this leak was never reported - it was discovered as part of code
review.
closes https://github.com/rsyslog/rsyslog/issues/2007
> pmnormalize: fix memory leak, improve tests

- plugins/imfile/imfile.c
- runtime/rsyslog.h
- tests/imfile-basic.sh
When the work directory has not been set or is invalid, state files
are created in the root of the file system. This is neither expected
nor desirable. We now complain loudly about this fact. For backwards
compatibility reasons, we still need to support running imfile in
this case.
closes https://github.com/rsyslog/rsyslog/issues/1296
> imfile: emit error on startup if no working directory is set

- tests/diag.sh
> testbench plumbing: remove left-over debug output

- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- tests/Makefile.am
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
We are using the gnutlsPriorityString setting variable, to pass configuration commands to openssl.
The format is one command per line, command and value separated by equal sign (=).
See this sample:
gnutlsPriorityString="command=value
secondcommand=value"
Also added a test that disables certain TLS/SSL protocols through this parameter. This 
causes the handshake to fail within the test due not matching common tls version between client and server. This error is checked and if found the test will pass.
closes: https://github.com/rsyslog/rsyslog/issues/3605
> openssl network driver: Added support setting openssl config commands

- tests/Makefile.am
- tests/mmnormalize_parsesuccess-vg.sh
- tests/mmnormalize_parsesuccess.sh
see also https://github.com/rsyslog/rsyslog/issues/2462
> mmnormalize: add test for proper $parsesuccess support

- tests/imfile-symlink.sh
see also https://github.com/rsyslog/rsyslog/issues/3550
> testbench: add even more debug info to imfile-symlink test

- action.c
- action.h
- tests/Makefile.am
- tests/diag.sh
- tests/externalstate-failed-rcvr.sh
- tests/suspend-via-file.sh
It has been reported that some TCP receivers exists that accept syslog tcp
messages at any rate, even if they do not manage to actually process them.
Instead, they silently drop the message. This behavior is not configurable.
All in all, it can lead to considerate message loss.
To support such use cases, we need to provide an ability to externally
trigger actions suspension and resumption.
We do this via a configured file which contains the status of the action.
Rsyslog periodically reads the file and if it contains "SUSPEND", it
suspend the action (and likewise for resume).
closes https://github.com/rsyslog/rsyslog/issues/2924
> core/action: implement capability to resume/suspend via external file

- runtime/dnscache.c
- runtime/dnscache.h
- runtime/glbl.c
- tests/Makefile.am
- tests/dnscache-TTL-0-vg.sh
- tests/dnscache-TTL-0.sh
closes https://github.com/rsyslog/rsyslog/issues/49
> dnscache: add global parameter dnscache.default.ttl

- tests/Makefile.am
- tests/smtradfile-vg.sh
- tests/smtradfile.sh
This had so far no dynamic tests.
> testbench: add test for smtradfile string generator

- .codecov.yml
- tests/Makefile.am
- tests/omudpspoof_errmsg_no_params.sh
this now also ensure at least minimal check when CI does not contain a system running with root permissions.
> testbench: add base test for omudpspoof

- runtime/dnscache.c
- runtime/dnscache.h
- runtime/glbl.c
- tests/diag.sh
- tests/dnscache-TTL-0.sh
- tests/imtcp-tls-ossl-basic-tlscommands.sh
**Last minute fix for 8.1904.0** detected by coverity scan, which unfortunately can only run nightly after merge.
This leads to a refactoring of the looking code; issue was caused
by new TTL cache expiration code which placed not semantics on the
cache. These were not properly handled under all circumstances.
> dnscache: fix looking issue detected by Coverity Scan

- runtime/dnscache.c
This fixes a memory leak that can only occur under OOM conditions.
Detected by Coverity Scan, CID 203717
> dnscache: fix very unlikely memory leak

- runtime/queue.c
- tests/Makefile.am
- tests/queue_errmsg-oversize.sh
We see error reports from users who have configured excessively large queues
and receive an OOM condition or other problems.
With that patcjh we generate a warnomg message if a queue is configured very
large. "Very large" is defined to be in excess of 500000 messages.
see also https://github.com/rsyslog/rsyslog/issues/3314
closes https://github.com/rsyslog/rsyslog/issues/3334
> core: emit a warning message for ultra-large queue size definitions

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/imfile-basic.sh
- tests/imfile-statefile-directory.sh
This permits to write state files to a location other than the rsyslog
working directory. This may be desirable for some use cases.
closes https://github.com/rsyslog/rsyslog/issues/2558
> imfile: new module parameter "statefile.directory"

- grammar/lexer.l
- grammar/parserif.h
- grammar/rainerscript.h
- tests/Makefile.am
- tests/config_output-o-option.sh
- tests/include-obj-in-if-vg.sh
- tools/rsyslogd.8
- tools/rsyslogd.c
Introduces the capability to create an output config file that explodes
all "includes" into a single file. This provides a much better overview
of how exactly the configuration is crafted. That could often be a great
troubleshooting aid.
This commit also contains some slight not-really-related cleanup.
closes https://github.com/rsyslog/rsyslog/issues/3634
> add capability to write full config file w/ includes (-o cmdline option)

- runtime/stream.c
- tools/omfile.c
The flush was only done to the last dynafile in use at end of
transactions. Dynafiles that were also modified during the
transaction were not flushed.
Special thanks to Duy Nguyen for pointing us to the bug and
suggesting a solution.
This commit also contains a bit of cosmetic cleanup inside
the file stream class.
closes https://github.com/rsyslog/rsyslog/issues/2502
> omfile bugfix: FlushOnTXEnd does not work reliably with dynafiles

- runtime/tcps_sess.c
- tests/imtcp-discard-truncated-msg.sh
The actual problem is in the tcpserver component. However, the prime user
is imtcp and so users will likely experience this as imtcp problem.
When a too-long message is truncated, the byte after the truncation
position becomes the first byte of the next message. This will garble
the next messages and in almost all cases render it is syslog-incompliant.
The same problem does NOT occur when the message is split.
This commit fixes the issue. It also includes a testbench fix.
Unfortunately the test for exactly this feature was not properly
crafted and so could not detect the problem.
closes https://github.com/rsyslog/rsyslog/issues/3580
> imtcp bugfix: oversize message truncation causes log to be garbled

- runtime/queue.c
New semantic: if lightDelayMark is 0, it is set to the max queue
size, effectively disabling the "light delay" functionality.
Thanks to Yury Bushmelev to mentioning issues related to light
delay mark and propsing the solution (which actually is what
this commit does).
closes https://github.com/rsyslog/rsyslog/issues/1778
> queue subsystem: permit to disable "light delay mark"

- runtime/queue.c
- runtime/queue.h
- runtime/rsconf.c
- runtime/rsyslog.h
- tests/Makefile.am
- tests/diskqueue-non-unique-prefix.sh
If the same name is specified for multiple queues, the queue files
will become corrupted. This commit adds a check during config parsing.
If duplicate names are detected the config parser errors out and the
related object is not created.
Note: this may look to a change-of-behaviour to some users. However,
this never worked and it was pure luck that these users did not run
into big problems (e.g. DA queues were never going to disk at the
same time). So it is acceptable to error out in this hard error case.
closes https://github.com/rsyslog/rsyslog/issues/1385
> config processing: check disk queue file is unique

- plugins/imfile/imfile.c
very unlikely; detected by Coverity Scan, CID 193442
> imfile: fix file handle leak under OOM condition

- runtime/Makefile.am
The `'\'` should have been removed when the line below was deleted
with commit 8cbeb6305c504cf6138e8c5614497689c494edcb.
> Fixing build of lmcry_gcry.so.

- tests/diag.sh
- tests/imfile-symlink.sh
This test sometimes failed. It used a symlinkl to a hardcoded name
rsyslog-link.*.log. This symlink was created but then disappears.
The reason is that upon (every!) test exit, rsyslog-link.*.log is
deleted. So a parallel test running the exit procedure just at the
"right" time can removed that file.
The bug is that the file name should be created using the tests's
dynamic name. This is done now.
closes https://github.com/rsyslog/rsyslog/issues/3550
> testbench bugfix: imfile-symlink failed w/ parallel test run

- runtime/glbl.c
- runtime/glbl.h
- tools/rsyslogd.c
permits to specify a severity filter for internal message. Only
messages with this severity level or more severe are logged.
Orignally this was done in rsyslog.conf as usual: you can filter
rsyslog messages on severity, just like any other. But with systemd,
we now emit primarily to the journal, and this is outside of rsyslog's
rule engine and so regular filters do not apply (at least in regard
to the journal). Logging to journal is good, because finally
folks begin to see the messages (traditional distro configs discard
them, for whatever is the reason).
This commit implements a global setting for a severity-based filter
for internal messages, before submitted to journal. So it's not 100%
of what rsyslog can do, but at least some way to customize.
see also …
> new global config parameter "internalmsg.severity"

- runtime/lookup.c
- tests/Makefile.am
- tests/glbl-internalmsg_severity-info-shown.sh
closes https://github.com/rsyslog/rsyslog/issues/3639
> emit info-level success message on lookup table load (startup)

- tests/glbl-internalmsg_severity-info-shown.sh
- tools/rsyslogd.c
root cause seems to be that SIGTERM is delivered differently under
FreeBSD. This causes the main thread to not be awaken, and so it
takes until the next janitor interval to come back to life - which
can be far too long. Fixed this bug explicitley awaking the main
thread.
also
* re-enable test that did not work because of this
* fix invalid message on SIGTERM in debug log
> core: harden shutdown processing on FreeBSD

- runtime/glbl.c
- tests/Makefile.am
- tests/glbl-internalmsg_severity-debug-not_shown.sh
- tests/glbl-internalmsg_severity-debug-shown.sh
- tools/rsyslogd.c
also fix a problem in handling this parameter when rsyslog processed
internal messages itself (it did not work). As the parameter was
introduced today, we do not flag this follow-up commit as "bugfix".
The issue was noticed when we added the additional tests.
see also https://github.com/rsyslog/rsyslog/issues/3650
see also https://github.com/rsyslog/rsyslog/issues/3639
**This must not be merged before full doc for new feature "internalmsg.severity" is added.**
> change default of internalmsg.severity global parameter, add tests

- runtime/queue.c
- tests/Makefile.am
- tests/da-queue-persist.sh
The queue subsystem now provides additional information messages which
may help a regular user to maintain system healt. Most importantly,
DA queues now output when they persist queue data at end of run and
when they restart the queue based on persisted data.
> queue subsystem: provide better user status messages

- runtime/glbl.c
- runtime/queue.c
- runtime/queue.h
- tests/Makefile.am
- tests/glbl-ruleset-queue-defaults.sh
specifically:
* default.ruleset.queue.timeoutshutdown
* default.ruleset.queue.timeoutactioncompletion
* default.ruleset.queue.timeoutenqueue
* default.ruleset.queue.timeoutworkerthreadshutdown
closes https://github.com/rsyslog/rsyslog/issues/3656
> global config: new parameters for ruleset queue defaults

- tests/hostname-getaddrinfo-fail.sh
root problem cause was fixed by recent comment, so now we can
use it again on these platforms.
closes https://github.com/rsyslog/rsyslog/issues/2833
> testbench: renable test hostname-getaddrinfo-fail.sh

- tests/diag.sh
- tests/imtcp-tls-ossl-basic-tlscommands.sh
When first parameter is check_only, the tcpflood funtion shall not
abort the test itself (The fail is intended if this option is set).
closes issue https://github.com/rsyslog/rsyslog/issues/3625
> testsuite: Fixed wrong parameter check in diag.sh (tcpflood())

- grammar/rainerscript.c
- tests/Makefile.am
- tests/config_enabled-off.sh
Using config.enabled="off" could lead to error messages on
"parameter xxx not known", which were invalid. They occured
because the config handler expected them to be used, which
was not the case due to being disabled.
This commit fixes that issue.
closes https://github.com/rsyslog/rsyslog/issues/2520
> bugfix: error messages if config.enabled="off" is used

- runtime/msg.c
- template.c
- template.h
- tests/Makefile.am
- tests/json-nonstring.sh
The new "datatype" template option permits to generate non-string
data rather easily. It works together with jsonf formatting, which
is what people should use nowadays.
closes https://github.com/rsyslog/rsyslog/issues/2827
> template: add datatype template option for JSON generation

- tools/pmrfc5424.c
Fixes #3667 - Leading space is lost on message when using RFC5424, SD is set and message starts with space
> Fixes #3667 - Leading space is lost on message when using RFC5424, SD is set and message starts with space 

- plugins/imjournal/imjournal.c
This fixes situation when journal was preloaded from previously
saved cursor but was not advanced to next entry so reading begun
from last message which was therefore duplicated.
> Advance cursor after reloading journal

- runtime/rsconf.c
- tests/Makefile.am
- tests/mainq_actq_DA.sh
rsyslog will segfault on startup when a main queue file name has
been set and at least on other queue contains a file name. This
was cased by too-early freeing config error-detection data
structures. It is a regression caused by commit e22fb205a3.
Thanks to Wade Simmons for reporting this issue and providing
detailled analysis. That greatly helps fixing it quickly.
closes https://github.com/rsyslog/rsyslog/issues/3681
> core bugfix: segfault on startup depending on queue file names

- tests/mmkubernetes-cache-expire.sh
This was likely a left-over from previous manual testing. Removed
the lines in question as they normally should come from diag.sh.
The generated file also caused a "make distcheck" failure.
see also https://github.com/rsyslog/rsyslog/pull/3685
> testbench: remove debug settings from kubernetes test

- runtime/queue.c
- tests/Makefile.am
- tests/queue_warnmsg-oversize.sh
The warning message was emitted as an error message, which is misleading
and may also break some automatted procedures.
> queue subsystem bugfix: oversize queue warning message shown as error

- CONTRIBUTING.md
https://github.com/rsyslog/rsyslog/issues/3673
Changed the link to point to https://github.com/rsyslog/rsyslog-doc
> Fix for: CONTRIBUTING.md broken link #3673

- runtime/stream.c
This was originally added as aid to solve potential regressions.
But now it looks good for a while and we remove some of it as
it really is overdone.
Note: some other debug messages had already be removed, so this
closes https://github.com/rsyslog/rsyslog/issues/3046
> imfile: remove no longe needed debug info

- tests/omamqp1-basic.sh
> testbench: check that valgrind runs start up correctly

- tests/array_lookup_table.sh
- tests/array_lookup_table_misuse-vg.sh
- tests/diag.sh
- tests/dynstats_nometric.sh
- tests/dynstats_overflow-vg.sh
- tests/dynstats_overflow.sh
- tests/lookup_table.sh
- tests/lookup_table_bad_configs.sh
- tests/lookup_table_no_hup_reload.sh
- tests/multiple_lookup_tables.sh
- tests/sparse_array_lookup_table.sh
- tools/rsyslogd.c
... at least not on FreeBSD. The problem was that HUP did not awake
the main loop. We now interrupt it explicitly.
> platform bugfix: HUP did not work reliably on some platforms 

- tests/omrabbitmq_error_server0.sh
- tests/omrabbitmq_error_server1.sh
- tests/omrabbitmq_error_server2.sh
- tests/omrabbitmq_error_server3.sh
- tests/omrabbitmq_raw.sh
commit 8791323c92039 fixed invalid handling of first space in MSG.
This broke some test, but was not detected at the time of its merge.
This is now fixed with this follow-up commit.
> testbench: fix tests affected by commit 8791323c92039

- tools/omfile.c
when omfile was HUPed it did not sufficiently clear all dynafile
cache maintenance data structures. This usually lead to misadressing
and could result in various issues, including a hang of rsyslog
processing or segfaults. It could also have "no effect" by pure
luck of not hitting anything important. This actually seems to
have been the most frequent case.
This seems to be a long-standing bug, but the likelyhood of its
appearance seems to have been increased by commit 62fbef7
introduced in 8.1905. Note: the commit itself has no regression,
just increases the likelyhood to trigger the pre-existing bug.
special thanks to Alexandre Guédon for his help in analyzing
the issue - without him, we would probably still not know
what actually went wrong.
closes …
> omfile: fix potential hang/segfault on HUP of dynafile action

- tests/diag.sh
The framework now first checks if "ip" is available and falls back
to "ifconfig" only if this is not the case.
Thanks to Michael Biebl for the suggestion.
closes https://github.com/rsyslog/rsyslog/issues/3682
> testbench framework: use ip tool instead of outdated ifconfig

- runtime/msg.c
MsgDup() placed timereported into timegenerated property, resulting
in invalid property values. Orignal timegenerated was lost. This
occured always when a message needed to be duplicated. Most
importantly this is the case when queues are used.
closes https://github.com/rsyslog/rsyslog/issues/3716
> core bugfix: message duplication copied incorrect timestamp

- tests/clickhouse-errorfile.sh
message checked was depending on clickhouse version; newer versions
emit differnet message. We are still dependent on clickhouse, but
hopefully now on a much more stable part of the message.
> testbench: fix clickhouse test

- plugins/omclickhouse/omclickhouse.c
omclickhouse use ` strchr(strstr(message,"VALUES ") ` when building the batch sql. But the message may not contains `VALUES`, then it segfault.  
This commit fix that . It will continue build the batch sql, and then report errors by clickhouse's return message.
> omclickhouse: fix segfault on omclickhouse batchmode

- tests/Makefile.am
- tests/diag.sh
- tests/omrabbitmq_error_server0.sh
- tests/omrabbitmq_error_server1.sh
- tests/omrabbitmq_error_server2.sh
- tests/omrabbitmq_error_server3.sh
- tests/omrabbitmq_raw.sh
- tests/rfc5424parser-sp_at_msg_start.sh
see also https://github.com/rsyslog/rsyslog/pull/3671
see also https://github.com/rsyslog/rsyslog/pull/3667
> testbench: test for leading space issue in RFC 5424 parser

- tools/rsyslogd.c
see also https://github.com/rsyslog/rsyslog/issues/2979
> fix leading double space in rsyslog startup messages

- grammar/rainerscript.c
- tests/rscript_ipv42num.sh
To fix the issue but keep compatible with existing deployments
both function names are now supported.
closes https://github.com/rsyslog/rsyslog/issues/3676
> function bugfix: "ipv42num" misspelled as "ip42mum" (without "v")

- plugins/imuxsock/imuxsock.c
FreeBSD 12 uses RFC5424 on the system log socket by default. This
format is not supported by the special parser used in imuxsock.
Thus for FreeBSD the default needs to be changed to use the
regular parser chain by default. That is all this commit does.
Note: the code was merged untested, as we currently do not have
a matching CI environment. If it does not work, please report.
closes https://github.com/rsyslog/rsyslog/issues/3694
> imuxsock: support FreeBSD 12 out of the box

- action.c
- tests/suspend-omfwd-via-file.sh
when an action was already disabled while the action was tried to be
committed, no error file was written. Note that this state is highly
unlikely to happen. Most probably, it can only happen if parameter
action.externalstate.file is used.
> core/action: no error file written if act suspended on TX commit

- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
- tests/diag.sh
- tests/imtcp-basic.sh
this parameter was added, but it had no effect as it was not
passed down to the driver layer. This has been fixed. That also
now enables us to use dynamically-assigned port, which are
very useful for further testbench stabilization. Quite some
false positives occurred because the pre-selected port was
already in use again when rsyslog started.
> imtcp: enable listenPortFileName parameter

- action.c
- tests/Makefile.am
- tests/suspend-omfwd-via-file.sh
- tests/suspend-via-file.sh
We try to reduce potential problems during transaction commit be ensuring
that the action is only tried to be suspended at begin of transaction.
This also simplifies the code a bit and also reduces performance
impact of that "suspension via external state file" feature.
> core/action: special handling for suspending action via ext file

- tools/iminternal.c
If there is a burst of log messages during a time when rsyslog is unable
to output (either during log rotation, an out-of-space condition, or
some other similar condition), rsyslog can SEGFAULT due to a mutex
double-unlock.
> iminternal: suppress mutex double-unlock

- plugins/imjournal/imjournal.c
> added mising modpdescr for fsync

- plugins/imrelp/imrelp.c
- runtime/glbl.c
- runtime/glbl.h
termination condition was not properly checked; this lead to
premature termination after patch 1c8712415b9 was applied.
It is open to debate if patch 1c8712415b9 changed the module
interface. Actually it looks like this was previously not
well thought out.
closes https://github.com/rsyslog/rsyslog/issues/3760
> imrelp bugfix: hang after HUP

- runtime/stream.c
This seems to be a long-standing bug, introduced around 7 years ago.
It became more visible by properly closing files during HUP, which
was done in 8.1905.0 (and was another bugfix).
closes https://github.com/rsyslog/rsyslog/issues/3772
> omfile bugfix: race file when async writing is enabled

- tools/omfile.c
When the janitor cleans out timed-out files, it does not
properly indicate the entry is gone. Especially when running
in async mode this can lead to use-after-free and thus
memory corruption or segfault.
see also https://github.com/rsyslog/rsyslog/issues/3756
> core/janitor bugfix: properly maintain dynafile cache

- tests/Makefile.am
- tests/omfile-module-params.sh
in this case "template" param is checked
> testbench: add test for omfile module parameters

- tests/Makefile.am
In actual case if --enable-impstats was not given some other tests failed.
> testbench bugfix: some tests were executed when req module was missing

- contrib/omhttp/omhttp.c
- tests/omhttp-retry.sh
omhttp, 'checkpath' option, was not configurable in the past.
- add 'checkpath' to the cnfparamdescr table.
- fix issue with checkpath passing extra garbage characters in string.
- add 'checkpath' into unit test - omhttp-retry.sh
> Enable checkpath option in omhttp

- plugins/imrelp/imrelp.c
- runtime/glbl.c
- runtime/glbl.h
It is extremely unlikly that the race could have caused harm, except
during test runs with thread sanitizer (TSAN) enabled.
> imrelp: fix cosmetic race in recently-added code

- tests/Makefile.am
- tests/imkafka_multi_group.sh
Both rsyslog instances share the same consumergroup. 
Test will only be successfull if each instances processes at least 25% of all messages. 
First results showed that both instances get approx the same amount of messages (+-1%), so the load
is balanced properly through consumers in the consumergroup "rsysloggroup". 
closes: https://github.com/rsyslog/rsyslog/issues/3765
> testbench: Added imkafka test with two rsyslog instances same consumergroup

- tests/travis/install.sh
there seem to be packaging changes in ubuntu or some other repos
we use on travis. This should fix the issue.
> travis: libmongoc-dev does not install all needed

- plugins/imptcp/imptcp.c
- tests/tsan.supp
imptcp counts the number of bytes received. However, receives
happen on different worker thread. The access to the counter
was not synchronized, which can cause loss of updates. Also,
thread debuggers validly flag this as an error, which creates
problems under CI.
This commit fixes the situation via atomic operations and
falls back to mutex calls if they are not available.
Detected by LLVM thread sanitizer.
closes https://github.com/rsyslog/rsyslog/issues/3798
> imptcp bugfix: received bytes counter improperly maintained

- plugins/imjournal/imjournal.c
There was a bug in location of fsync code, this commit corrects it and ensures we close FD only after everything else in completed.
> Fix state-file closing with fsync option

- plugins/omelasticsearch/omelasticsearch.c
- force to close connection by setting CURLOPT_FORBID_REUSE to 1 when the count of operation reaches rebindinterval.
> omelasticsearch - rebindinterval

- plugins/imptcp/imptcp.c
also LogError also does DBGPRINTF, so we remove the duplicate one
> imptcp: cleanup error message generation

- plugins/imptcp/imptcp.c
- tests/imptcp-basic-hup.sh
when multiple interfaces and/or protocols could be bound, each of
them used a different listener ports were assigned. While this is
basically correct, it makes things unusable, especially as
listenPortFileName will only contain the port number used for
the latest listener.
This patch now follows the model of nsd_ptcp.c to assign only
the first port randomly and then use that port consistently.
> imptcp bugfix: port="0" parameter did not work as expected

- tests/manytcp-too-few-tls-vg.sh
this test often failed "unexpectedly" when the CI system is very
busy - assuming it just had insufficient time.
> testbench: increase runtime for know-problematic test

- plugins/omelasticsearch/omelasticsearch.c
omelasticsearch does some "interesting tricks" for an output module.
This causes a segfault if the retryRuleset is now known.
The action module interface currently expects that all config errors
be detected during instance creation. Instead omelasticsearch defers
the retry ruleset check to a later state. The reason is that it wants
to support the use the same rulesetname it is defined in - and this
is not yet available at action parsing.
We fix this by ensuring that any deleted instance is properly unlinked
from the instance list. One may argue the module interface should get
upgrade for such cases, but this is a longer-term approach.
replaces https://github.com/rsyslog/rsyslog/pull/3796
closes https://github.com/rsyslog/rsyslog/pull/3796
> omelasticsearch bugfix: segfault on unknown retryRuleset

- tests/diag.sh
- tests/sndrcv.sh
this makes the test more reliable in regard to port use. This is also
a model-commit which can be used to update other tests and base new
tests on it.
> testbench: update sndrcv test to newest standard

- tests/diag.sh
the kafka tests generate a wealth of usually-unneeded output which
clutters the CI logs and makes them almost unusable.
> testbench: remove debug output; lessen kafaka tests output

- tests/imptcp-buffer-overflow.sh
- tests/imptcp-connection-msg-disabled.sh
- tests/imptcp-connection-msg-received.sh
- tests/imptcp-custom-delimiter.sh
- tests/imptcp-discard-truncated-msg.sh
- tests/imptcp_framing_regex-oversize.sh
- tests/imptcp_framing_regex.sh
- tests/imptcp_large.sh
> testbench imptcp: make port use more reliable

- tests/Makefile.am
- tests/imuxsock_legacy.sh
This was never tested. Ensures we don't accidently break existing
configurations.
> testbench: add test for imuxsock legacy format

- tests/Makefile.am
- tests/es-duplicated-ruleset-vg.sh
- tests/es-duplicated-ruleset.sh
These test test errors described in
https://github.com/rsyslog/rsyslog/pull/3796
> testbench: add tests for omelasticsearch error configs

- action.c
- tests/suspend-via-file.sh
remove trailing whitespace before checking the status string. This is
most important as a line usually ends with \n, which is considered
trailing whitespace. Accepting this increases usability.
> core/action: guard action.externalstate.file content against whitspace

- tests/asynwr_deadlock4.sh
The test frequently failed in a way that suggests rsyslog terminated too
early. We try if we can improve the situation by prolonging the empty
check. While there are better solutions for this special case, there are
some cases where we do no have them. So it is good to know if this
method works.
> testbench: experimentally increase queue empty check period

- tests/Makefile.am
- tests/allowed-sender-tcp-fail.sh
- tests/allowed-sender-tcp-ok.sh
while this is deprecated, it is still used in practice. So far no
test guarded this functionality.
> testbench: add tests for $AllowedSender functionality

- runtime/tcpsrv.c
- threads.c
if the tcpsrv component is started and quickly terminated, it may hang
for a short period of time. Also a very small amout of memory is leaked
immediately before shutdown. While this leak is irrelevant in practice
(the OS clean up the process anyways), it leads to CI failures. The hang,
however, can lead to longer than expected shutdown times for rsyslog.
The problem can be experienced via imtcp, imgssapi and imdiag (users
of affected core component).
> core/tcpsrv: potential race on startup/shutdown

- runtime/glbl.c
> core: do not unnecessarily set hostname on each HUP

- configure.ac
rsyslog fails to cross build from source, because it uses mysql_config
and mysql_config is unfixably broken for cross compilation. It would be
better to use pkg-config. The attached patch makes rsyslog try
pkg-config first and fall back to mysql_config.
> build system: support cross-platform build for mysql/mariadb

- plugins/imtcp/imtcp.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/netstrms.c
- runtime/netstrms.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tools/omfwd.c
This commit adds to new flags which can be set to allow
1) checking of extendedKeyUsage certificate field
2) stricter checking of certificate name/adresses
> Stricter GnuTLS operation

- contrib/pmaixforwardedfrom/pmaixforwardedfrom.c
> pmaixforwardedfrom bugfix: potential misadressing

- contrib/pmcisconames/pmcisconames.c
> pmcisconames bugfix: potential misadressing

- runtime/ratelimit.c
this could help users to find out exactly how is ratelimiter set
when inspecting logs so then can easier adjust configuration
> print also ratelimiter parameters

- contrib/imczmq/imczmq.c
- runtime/rsconf.c
- runtime/wti.c
A Null-pointer was passed to printf instead of the module name.
On some platforms this may lead to a segfault. On most platforms
printf check's for NULL pointers and uses the string "(null)"
instead.
In any case, the module name is missing from the error message.
> core bugfix: incorrect error message on duplicate module load

- tests/Makefile.am
- tests/mmpstrucdata-escaping.sh
> testbench: add test for mmpstrucdata with RFC5424 escape sequences

- runtime/queue.c
- runtime/wtp.c
The action name is stored in modified form for the debug header and
some messages. If it is extremely long, a buffer can be overrun,
resulting in misadressing and potential segfault for rsyslog. This
can also happen if the action is NOT named, but a custom path to
the output module is given and that path is very long. This triggers
the same issue because by default the module load path is included
in the action name.
This patch corrects the problem and trunctates overly long names
when being used for name generation.
The problem was detected during testbench work. We did never receive
a bug report from practice.
> core bugfix: potential abort on very long action name

- plugins/imjournal/imjournal.c
Decomposed ReadJournal() a bit, also now coupling journald
variables in one struct, added few warning messages and debug
prints to help with bug hunts in future, also got rid of two
needless journald calls. WorkAroundJournalBug now deprecated.
Added option to pull journald records from outside local machine.
> plugin code restructuring, added remote option

- runtime/stream.c
- tests/diag.sh
Rsyslog may leave some dangling disk queue files under the following
conditions:
- batch sizes and/or messages are large
- queue files are comparatively small
- a batch spans more than two queue files (from n to n+m with m>1)
In this case, queue files n+1 to (n+m-1) are not deleted. This can
lead to problems when the queue is re-opened again. In extreme cases
this can also lead to stalled processing when the max disk space is
used up by such left-over queue files.
Using defaults this scenario is very unlikely, but it can happen,
especially when large messages are being processed.
> core queue bugfix: handle multi-queue-file delete correctly

- contrib/mmkubernetes/mmkubernetes.c
can cause problems under extreme memory shortage - very unlikely
credits to LGTM.COM for detecting this
> mmkubernetes bugfix: improper use of calloc()

- configure.ac
Thank to Michael Biebl for pointing this out.
closes https://github.com/rsyslog/rsyslog/issues/3904
> build system bugfix: incorrect default in ./configure help text

- plugins/imuxsock/imuxsock.c
can cause problems under extreme memory shortage - very unlikely
credits to LGTM.COM for detecting this
> imuxsock  bugfix: improper use of calloc()

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
can cause problems under extreme memory shortage - very unlikely
credits to LGTM.COM for detecting this
> TLS driver bugfix: improper use of calloc()

- plugins/imfile/imfile.c
could cause problems under extreme memory shortage - very unlikely
credits to LGTM.COM for detecting this
> imfile bugfix: improper use of calloc()

- contrib/improg/improg.c
- tests/Makefile.am
- tests/improg-multiline-test.py
- tests/improg_simple_multi.sh
miscellaneous bug fixes in improg:
- properly truncate string after an input event is submitted
- set msg offset to 0.
- tests added to check above fixes
> bug fix: allow improg to handle multi-line inputs

- plugins/imjournal/imjournal.c
When data is read from the journal using sd_journal_get_data it may be
truncated to a certain threshold (64K by default).
If the rsyslog MaxMessageSize is larger than the threshold, there's a
chance rsyslog will receive incomplete messages from the journal.
Empirically, this appears to happen reliably when XZ compression is
used by journald. Systems where journald uses LZ4 compression do not
appear to suffer this issue reliably--if at all.
This change sets the threshold to the MaxMessageSize when the
journal is opened.
> #3784: set the journal data threshold to MaxMessageSize

- contrib/mmdarwin/mmdarwin.c
- contrib/mmdarwin/protocol.h
#Optimisations
- use permanent worker-dependent buffers to avoid malloc/free for each entry
- move socket structures to worker data, remove global mutex
- add log lines for parameters and general workflow
- don't send body if empty/incomplete (see new parameters)
- don't close/reopen socket every time -> let session open or create new every X entry (see new parameters)
- clean up code
#New parameters
- added 'send_partial', to let mmdarwin send body if not all fields were retrieved, or not
default false = only send complete bodies
- added 'socket_max_use' to open new session every X packet, useful for some versions of Darwin (prior to 1.1)
default is 0 = do not open new session/keep only one
#Update to protocol
- added 'evt_id' to the darwin header (Darwin v1+ compatibility)
> MMDARWIN:: Optimisations, new parameters, update to protocol header

- runtime/nsd_ossl.c
- tests/imtcp-tls-ossl-basic-tlscommands.sh
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
- tests/tcpflood.c
Fixed OpenSSL Version check in:
- SetGnutlsPriorityString function in nsd_ossl.c
- initTLS() function tcpflood.c
See https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_VERSION_NUMBER.html
for more.
closes https://github.com/rsyslog/rsyslog/issues/3939
> ossl driver: fix wrong OpenSSL Version check (OPENSSL_VERSION_NUMBER)

- plugins/imrelp/imrelp.c
dbgprintf, which is not signal safe, was called from a signal handler
to get better understanding during debugging. While this usually works,
it can occasionally (5%) lead to a hang during shutdown. We have now
removed that debug info as it is no longer vital.
Note: this could only happen during debug runs. Production mode was
not affected. As such, this fix is only revelevant to developers.
However, it caused some confusion in the following issue tracker.
see also https://github.com/rsyslog/rsyslog/issues/3941
> imrelp: remove unsafe debug instrumentation

- runtime/queue.c
This was added for a specific debug effort and obviously forgotten
to cleanup.
Thanks to github user eshadesu for alerting us.
closes https://github.com/rsyslog/rsyslog/issues/3955
> queue cleanup: remove no longer needed debug output

- plugins/imfile/imfile.c
Leaving reporting access for directories in DEBUG only as rsyslog
goes all the way to root and paths higher in filesystem are
usually blocked by selinux policy rules.
> Report access error only on files

- contrib/imtuxedoulog/imtuxedoulog.c
- plugins/imfile/imfile.c
- plugins/omkafka/omkafka.c
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-escapelf.replacement-empty.sh
- tests/imfile-escapelf.replacement.sh
The new parameter permits to specify a replacement to be configured
when "escapeLF" is set to "on". Previously, a fixed replacement string
was used ("#012"/"\n") depending on circumstances. If the parameter is
set to an empty string, the LF is simply discarded.
closes https://github.com/rsyslog/rsyslog/issues/3889
> imfile: add new input parameter escapeLF.replacement

- plugins/imjournal/imjournal.c
When trying to recover journal errors, imjournal waited a hardcoded
period of 10s between tries. This was pretty long and could lead to
loss of journal data.
This commit adjust it to 100ms, which should still be fully sufficient
to prevent the journal from "hammering" the CPU.
It may be worth considering to make this setting configurable - but
let's first see if there is real demand to actually do that.
closes https://github.com/rsyslog/rsyslog/issues/3969
> imjournal bugfix: do not wait too long on recovery try

- runtime/queue.c
- tests/Makefile.am
- tests/queue-direct-with-no-params.sh
- tests/queue-direct-with-params-given.sh
Direct queues do not apply queue parameters because they are actually
no physical queue. As such, any parameter set is ignored. This can
lead to unintentional results.
The new code detects this case and warns the user.
closes https://github.com/rsyslog/rsyslog/issues/77
> core queue: emit warning if parameters are set for direct queue

- tests/Makefile.am
> build system: remove ./tests/*.log during "make clean"

- plugins/omkafka/Makefile.am
- plugins/omkafka/omkafka.c
librdkafka needs it, and it seems not to be present inside compiled
binary. This is a try to integrate it via omkafka.
Note: I need to merge this in order to use the regular package build
process. If it does not work out, I will undo it via another commit.
> omkafka: ensure math lib is bound to executable

- tests/diag.sh
- tests/mysql-basic.sh
- tests/mysqld-start.sh
We have a long-standing issue with the mysql tests. We can't find the
root cause with special test runs. This commit now adds some debug
info. The idea is to merge this and run it in all upcoming tests, so
that we can hopefully get a sufficiently large sample that we can
address the problem.
> testbench: add some debugging instrumentation

- plugins/omprog/omprog.c
- tests/Makefile.am
- tests/omprog-if-error.sh
The spec for the omprog interaction with the program it calls specifies
that the program receives one message via one line. In other words:
it must be a string terminated by LF.
However, omprog does currently rely on a proper template to fulfill this
requirement, If the template does not provide for the LF, it is never
written. For the called program, this looks like it does not receive any
input at all. Even if it finally reads data (e.g. due to full buffer),
it will not properly be able to discern the messages.
This handling is improved with this commit.
We cannot just check the template, because at the end of the template
may by a non-constant value. As such, we do not know at config load
time if there is this problem or not.
So the correct approach is to, during runtime, check if each …
> omprog: detect violation of interface protocol

- contrib/omhttp/omhttp.c
- tests/Makefile.am
- tests/diag.sh
- tests/omhttp-batch-lokirest-retry-vg.sh
- tests/omhttp-batch-lokirest-retry.sh
- tests/omhttp-batch-lokirest.sh
Loki is a new message indexer and querier from Grafana Labs. See
https://github.com/grafana/loki for details on Loki.
This change provides the initial message structure to send bulk message
payloads to the Loki Rest endpoint. omhttp, recieved a new bulk message
format called lokirest. Additionally, the plugin relies on the user to
provide the correct "stream" read message format.
A loki template must be json compatible and include a "stream" key of
key value tags, and a values key of an array of 2 element arrays, where
each 2 element array is the unix epoch in nanoseconds followed by an
unstrectured message.
An example:
template(name="array_loki" type="string" string="{\"stream\":{\"host\":\"%HOSTNAME%\",\"facility\":\"%syslogfacility-text%\",\"priority\":\"%syslogpriority-text%\",\"syslog …
> omhttp: add basic support for Loki Rest

- action.c
fixes failpath on actionTryRemoveHardErrorsFromBatch happens only when
actionCommit ()
-> actionTryCommit => FAIL
-> actionCommit somewhat unhappy
-> actionTryRemoveHardErrorsFromBatch() // contains memcpy which did work with non allocated area and non-element size alligned copy
-> actionCommit unhappy, has still uncommited messages.
-> actionTryCommit // would pass the rogue memory range to module
> fix transactional on remove HardErrors

- tests/sndrcv_tls_anon_rebind.sh
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
This commit makes them use the reliable method to obtain a
dynamic port. The previous method lead to unreliability (flakes)
especially on busy machines.
> testbench: make some tls/ossl tests more robust

- runtime/nsd_ossl.c
Full error details will now printed out in all error cases.
See also: https://github.com/rsyslog/rsyslog/issues/3945
> openssl: Fixed Error output (logmsg).

- configure.ac
This is the recommended method and we use pkg_config in any
case. With the old method, postgres server-development packages
needed to be installed just to build the client, which was
neither intuitive nor clean.
> build system: make postgres module use pkg_config

- plugins/imjournal/imjournal.c
The journal API will sometimes issue an SD_JOURNAL_INVALIDATE
which results in a repositioning of the cursor. From the man page:
Programs only interested in a strictly sequential stream
of log data may treat SD_JOURNAL_INVALIDATE the same way as
SD_JOURNAL_APPEND, thus ignoring any changes to the log view
earlier than the old end of the log stream.
If we have configured IgnorePreviousMessages, we want to treat the
invalidate event as an append, and wind to the end of the message
stream.
> Handle journal invalidate

- contrib/omhttp/omhttp.c
- plugins/imjournal/imjournal.c
- plugins/imklog/imklog.c
- plugins/imptcp/imptcp.c
- plugins/imtcp/imtcp.c
- plugins/imudp/imudp.c
- plugins/imuxsock/imuxsock.c
- plugins/omelasticsearch/omelasticsearch.c
- runtime/ratelimit.c
- runtime/ratelimit.h
- runtime/tcpsrv.c
- runtime/tcpsrv.h
The burst parameter in the ratelimit was increased to an unsigned int
but the interval was as an unsigned short. While it may be unusual,
there is possibly a chance to need to represent an interval longer than
about 3/4 of a day.
While here, go through and normalize all the various incarnations of
rate limiting to be explicitly unsigned int for the burst and interval.
> ratelimit: increase rate limit interval parameter

- plugins/imdiag/imdiag.c
- template.c
While this is a false positiv, we actually restructure the code to
"solve" the issue. As it is only-config related code, the performance
is not affected. As such the "fix" is acceptable.
> core/config: "fix" valgrind false positive

- plugins/omsnmp/omsnmp.c
SNMP_TRAP_ENTERPRISESPECIFIC (6) was inorrectly handeled as invalid
traptype.
closes https://github.com/rsyslog/rsyslog/issues/3973
> omsnmp: Fix "traptype" variable checking.

- Makefile.am
- configure.ac
- plugins/omsnmp/omsnmp.c
- tests/Makefile.am
- tests/diag.sh
- tests/sndrcv_omsnmpv1_udp.sh
- tests/sndrcv_omsnmpv1_udp_dynsource.sh
- tests/sndrcv_omsnmpv1_udp_invalidoid.sh
- tests/snmptrapreceiver.py
If set, the source field from SNMPv1 trap can be overwritten
with a template, default is "%fromhost-ip%". The content should be a
valid IPv4 Address that can be passed to inet_addr(). If the content
is not a valid IPv4 Address, the source will not be set.
> omsnmp: Add support for new option "snmpv1dynsource"

- grammar/rainerscript.c
- tests/Makefile.am
- tests/config_enabled-on.sh
When the 'config.enabled="on"' config parameter an invalid error message was emitted that this parameter is not supported. However, it was still applied properly. This commit removes the invalid error message.
Also improve testbench in this regard.
closes https://github.com/rsyslog/rsyslog/issues/4011
> core/config bugfix: do not emit false error when config.enabled="on" is used

- template.c
> fix misleading/invalid indention

- action.c
under some circumstances (not entirely clear right now), memory
was freed but later re-used as state-tracking structures were not
properly maintained. Github issue mentioned below has full details.
Thanks to github user snaix for analysing this issue and providing
a patch. I am committing as myself as snaix did not disclose his or
her identity.
closes https://github.com/rsyslog/rsyslog/issues/3019
closes https://github.com/rsyslog/rsyslog/issues/4040
> bugfix core: potential segfault in template engine

- configure.ac
- plugins/imrelp/imrelp.c
- plugins/omrelp/omrelp.c
- tests/Makefile.am
- tests/diag.sh
- tests/have_relpSrvSetTlsConfigCmd.c
- tests/imrelp-tls-cfgcmd.sh
- tests/sndrcv_relp_tls-cfgcmd.sh
- tests/tcpflood.c
Add new configuration parameter tls.tlscfgcmd to omrelp and imrelp.
(Using relpSrvSetTlsConfigCmd and relpCltSetTlsConfigCmd)
OpenSSL Version 1.0.2 or higher is required for this feature.
A list of possible commands and their valid values can be found in the
documentation: https://www.openssl.org/docs/man1.0.2/man3/SSL_CONF_cmd.html
The setting can be single or multiline, each configuration command is
separated by linefeed (n). Command and value are separated by
equal sign (=). Here are a few samples:
tls.tlscfgcmd="Protocol=ALL,-SSLv2,-SSLv3,-TLSv1,-TLSv1.2"
tls.tlscfgcmd="Protocol=ALL,-SSLv2,-SSLv3,-TLSv1
MinProtocol=TLSv1.2"
Add to new testcases for librelp and tlscfgcmd.
> relp: Add support setting openssl configuration commands.

- tests/imtcp-basic.sh
- tests/imtcp_addtlframedelim.sh
so far, only the legacy style equivalent was tested. We have changed this
to current style. Legacy is no longer tested to keep CI runtime low.
The new test also has been made more reliable than the previous one.
> testbench: test imtcp "addtlFrameDelimiter" module param

- contrib/omhiredis/omhiredis.c
This can only happen when the system is totally out of memory. The issue
was detected by clang static analyzer. We never had a report from practice
and do not assume that the issue can cause real problems.
> omhiredis: fix potential NULL pointer use (very unlikely)

- tests/timegenerated-utc-legacy.sh
> testbench: modernize test and make more robust in regard to timing

- tests/imtcp-tls-gtls-x509fingerprint.sh
- tests/imtcp-tls-gtls-x509name.sh
- tests/imtcp-tls-ossl-basic.sh
- tests/imtcp-tls-ossl-x509fingerprint.sh
- tests/imtcp-tls-ossl-x509name.sh
- tests/imtcp-tls-ossl-x509valid.sh
> testbench: harden tests against port-assignment races

- runtime/srUtils.h
- runtime/srutils.c
- tools/rsyslogd.c
This patch updates prepareBackground() in tools/rsyslogd.c to reopen any file
descriptors used for random number generation in the child process. This fixes
an issue on Linux systems where the file descriptor obtained for /dev/urandom
by seedRandomNumber() in runtime/srutils.c was left closed after the fork. This
could be observed in procfs, where /proc/fd/ would show no open descriptors to
/dev/urandom in the forked process. /dev/urandom is reopened as the child may be
be operating in a jail, and so should not continue to use file descriptors from
outside the jail (i.e. inherited from the parent process).
I found that this issue led to rsyslog intermittently hanging during seedIV()
in runtime/libgcry.c. After the fork, the closed file descriptor number tended
to get re-assigned. …
> Reopen /dev/urandom file descriptor after fork on Linux systems

- runtime/msg.c
- tests/Makefile.am
- tests/empty-app-name.sh
RFC 5424 specifies that an empty APP-NAME needs to be indicated by
"-". Instead, the field could become empty under certain conditions.
If so, outgoing 5424 messages were invalidly formatted.
This happened under quite unusual conditions, but could be seen
in practice.
This commit also does some very light non-related code improvement
and also includes the testbench test to check the fixed error condition.
closes https://github.com/rsyslog/rsyslog/issues/4043
> core bugfix: APP-NAME fields could become empty

- runtime/rsconf.c
In defaut settings, rsyslog tries to continue to run, but some data
structures are not properly initialized due to the config parsing error.
This causes a segfault.
In the following tracker, this is the root cause of the abort:
see also https://github.com/rsyslog/rsyslog/issues/2869
> core bugfix: rsyslog aborts when config parse error is detected

- grammar/lexer.l
- tests/Makefile.am
- tests/rscript_re_match-dbl_quotes.sh
- tests/rscript_re_match.sh
closes https://github.com/rsyslog/rsyslog/issues/2869
> config system: emit proper error message on $ in double-quoted string

- tests/clickhouse-dflt-tpl.sh
not a real fix, but to get us going: clickhouse test had hardcoded
year; needs to be removed soon. Right now, just pusing it to 2020.
> testbench: rough fix for clickhouse 2019 test data problem

- tests/mysqld-start.sh
mysqld-start script always did an SKIP, so that we could check it's outcome.
This is a left-over from previous debugging. Thus removing it.
> testbench cleanup: remove debug info

- tests/imdocker-basic.sh
- tests/imdocker-multi-line.sh
some have problems on heavily loaded (CI) machines. This commit solves
that problem.
> testbench: make imdocker tests more robust in regard to timing

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
This is to be conssitent with rsyslog's prior behavior where
expired certs were automatically rejected.
This behavior changed with fixing #3364
> Changed default for permitExpiredCerts to "off"

- plugins/omprog/omprog.c
breaks compilation e.g. on Solaris 10 with gcc
> omprog bugfix: unclean data type conversions

- tests/diag.sh
the omhttp test server hangs indefinitely if tests requiring
it fail. This is relevant if the environment ist not destructed
after CI run (the buildbot CI system does not do this on VMs).
To guard against this, we have added a timeout of 30 minutes to
ensure the tool is terminated.
> testbench: do not create hanging tool instances

- tests/imtcp_conndrop_tls-vg.sh
- tests/imtcp_conndrop_tls.sh
> testbench: harden two tests against slow testbench machines

- plugins/imtcp/imtcp.c
- tests/asynwr_deadlock2.sh
- tests/diag.sh
This is added for testbench use - we need it to harden tests that
need to test legacy syntax.
The new directive is NOT intended for users. Thus it is intentionally
NOT DOCUMENTED.
> imtcp: add legacy directive $inputtcpserverlistenportfile

- tests/diag.sh
this is necessary for very slow test environments
> testbench: increase main msg queue default shutdown timeout

- plugins/imtcp/imtcp.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/netstrms.c
- runtime/netstrms.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/imtcp-tls-basic-verifydepth.sh
- tests/imtcp-tls-ossl-basic-verifydepth.sh
- tests/imtcp-tls-ossl-invalid-verifydepth.sh
- tools/omfwd.c
Support added in omfwd as instance parameter:
streamdriver.TlsVerifyDepth
Support added in imtcp as module parameter:
streamdriver.TlsVerifyDepth
Can be 2 or higher.
Support added into ossl driver
Parameter
streamdriver.TlsVerifyDepth
closes: https://github.com/rsyslog/rsyslog/issues/4035
> ossl tls: Added support to configure certificate verify depth

- tests/imtcp-tls-basic-verifydepth.sh
- tests/imtcp-tls-ossl-basic-verifydepth.sh
- tests/imtcp-tls-ossl-invalid-verifydepth.sh
these were introduced with commit fcffb063e just recently
> testbench: fix races in old-style tests

- devtools/devcontainer.sh
- devtools/run-ci.sh
- devtools/run-configure.sh
- tests/clickhouse-start.sh
The core ID is to use this script together with pretty generic
buildbot workers. This provides a simple way to load-balance
across the worker pool.
> CI: add script to do a full CI run

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
Bugfix: KSI module + dynafile in asynchronous mode fixed. KSI module kept just 1 signature file in focus and some of files were not closed. There was possibility that multiple KSI signatures of separate log files were stored in a single signature file. Also the block timeout was measured for one log file.
> Dynafile + async KSI module bugfix

- tools/omfile.h
Porting advice for gcc 10:
A common mistake in C is omitting <code>extern</code> when declaring a global
variable in a header file.  If the header is included by several files it
results in multiple definitions of the same variable.  In previous GCC versions
this error is ignored.  GCC 10 defaults to <code>-fno-common</code>, which
means a linker error will now be reported. To fix this, use <code>extern</code>
in header files when declaring global variables, and ensure each global is
defined in exactly one C file. As a workaround, legacy C code can be compiled
with -fcommon.
> satisfy-gcc-flag-fno-common

- tests/Makefile.am
- tests/omfwd-tls-invalid-permitExpiredCerts.sh
- tools/omfwd.c
This commit
- fixes the issue
- adds tests to ensure the parameter is understood
- refactors the code a bit to do the check at the upper layer
closes https://github.com/rsyslog/rsyslog/issues/4098
> omfwd: parameter streamdriver.permitexpiredcerts did not work

- runtime/msg.c
Rsyslogd aborts when writing to disk queue from multiple workers simultaneously.
It is assumed that libfastjson is not thread-safe.
Resolve libfastjson race condition when writing to disk queue.
see also https://github.com/rsyslog/rsyslog/issues/4041
> Fix race condition related to libfastjson when using DA queue

- devtools/run-ci.sh
this makes reviewing failures easier, especially if there are many SKIPped
tests involved
> CI: emit failed test info to file failed-tests.log

- devtools/devcontainer.sh
- devtools/run-ci.sh
> tooling: pass additional environment vars to dev container

- runtime/tcpsrv.c
- tools/rsyslogd.c
I have created patches to fix a few issues that can occur when shutting down rsyslog. These issues include:
- A race condition that can cause rsyslogd to block for the full janitor interval (10 minutes) before responding to a signal such as SIGTERM or SIGHUP.
- A race condition that can cause tcpsrv to segfault when shutting down
- Cleaning up tcpsrv properly if its thread is cancelled
See the commit messages for more details. Each commit represents a logical code change, with a detailed explanation in the commit message.
----
I created these changes in the course of my employment at Ciena Corporation (https://www.ciena.com/), and am submitting them to the rsyslog project with permission and on behalf of Ciena. These changes are provided to rsyslog under the terms of the GNU General …
> Various bug fixes relating to shutdown handling

- tools/rsyslogd.c
> core bugfix: misadressing in pselect()

- plugins/imfile/imfile.c
Commit 3f72e8c introduced an invalid memory allocation size. This lead to
too-short alloc and thus to overwrite of non-owned memory. That in turn
could lead to segfaults or other hard to find problems.
The issue was detected by our upgraded CI system. We did not receive
any problem reports in practice. Nevertheless, the problem is real and
people should update affected versions to patched ones.
see also: https://github.com/rsyslog/rsyslog/issues/4120
> imfile bugfix: misadressing and potential segfault

- plugins/imfile/imfile.c
Previously we saved old file_id unconditionally, which led to not
deleting old statefiles if files changes without rsyslog running.
Now it should work correctly.
closes #4120
> Fixed saving of old file_id for statefiles

- plugins/imdiag/imdiag.c
> imdiag: reduce verbosenes in shutdown queue size reporting

- runtime/errmsg.c
The oversizie message log fd is always closed on HUP, even if it never
was opened (and thus has -1 value). This patch corrects the issue.
> oversize message log bugfix: do not close fd -1

- tests/Makefile.am
- tests/improg-multiline-test.py
- tests/mmexternal-SegFault-empty-jroot-vg.sh
- tests/mmexternal-SegFault.sh
- tests/omhttp_server.py
- tests/rscript_parse_time_get-ts.py
- tests/snmptrapreceiver.py
- tests/urlencode.py
Thanks to Michael Biebl for his help on this issue.
This patch also contains some slight test modernization and
a "name fix" for a non-valgrind test.
closes https://github.com/rsyslog/rsyslog/issues/3853
> testbench: fix final issues for python 3 transition

- devtools/run-ci.sh
It looks like in some cases the codecov script generates execessive
output, which then causes buildbot to abort. This patch limits it
to a maximum of 3000 lines.
> devtools: limit output codecov can generate

- plugins/mmdblookup/mmdblookup.c
Check found_entry attribute to avoid wrong output when entry is not in database
> MMDBLOOKUP : Fix no entry found in database

- tests/Makefile.am
- tests/action-tx-errfile.sh
- tests/action-tx-single-processing.sh
- tests/chkseq.c
- tests/loadbalance.sh
This is a useful use case which was so far not covered by any tests.
Also contains: chkseq testbench tool bugfix: -i option did not work for values > 1
This bug was previously not discovered because values > 1 were not used so far. This bug is on a testbench tool, so no user is affected.
> testbench: new test for loadbalancing via global variables

- Makefile.am
- configure.ac
- tests/Makefile.am
This enables us to build GNUtls support but not necessarily
test it in CI. This is useful for some specialised subcomponent
test.
> build system: add option --enable-gnutls-tests

- devtools/gather-check-logs.sh
the current tooling also picked up non-test logs
> dev tooling: gather log files only for actual test logs

- tests/known_issues.supp
we are pretty sure this is a false positive
see also https://github.com/rsyslog/rsyslog/issues/4143
> testbench: add suppression for pselect() valgrind false positive

- Makefile.am
- configure.ac
- devtools/gather-check-logs.sh
- tests/Makefile.am
- tests/imfile-basic-vgthread.sh
This was accidentally set to "no". Test for imfile should by
default run when imfile is enabled.
see also https://github.com/rsyslog/rsyslog/issues/4120
> build system: change --enable-imfile-tests default to "yes"

- tests/diag.sh
- tests/imfile-endregex-timeout-with-shutdown.sh
We use the test_id to generate unique files during parallel
runs. So far we used a combination of ms-based timestamp and
hash test name. Practice shows that under some circumstances
the generated ids are not unique and thus test get file conflicts
and false positives.
This is now changed so that the test_id we add 4 bytes of random
data to the test ID. This is hopefully sufficient to make the IDs
of test runing in parallel unique.
> testbench: create random test_id

- grammar/rainerscript.c
- grammar/rainerscript.h
- runtime/rsconf.c
Previously the directive was processed way too late which caused
false errors whenever it was set to 'off' and sometimes directive not
working at all.
closes #4033
> Fixed processing of 'cofig.enabled' directive

- tests/Makefile.am
- tests/imrelp-bigmessage.sh
- tests/tcpflood.c
testbench: increased max extra data length in tcpflood from 256 to 512KB
Added a imrelp test for big messages (256KB).
closes: https://github.com/rsyslog/rsyslog/issues/4158
> testbench: increased max extra data length in tcpflood from 256 to 512KB

- tests/omkafkadynakey.sh
- topic check was done on wrong (hardcoded topic)
- rsyslog_out_log was overwritten by kafkacat check which caused the
seq_check to fail at the end.
closes: https://github.com/rsyslog/rsyslog/issues/4134
> testbench: Fixed two minor issues in omkafkadynakey.sh test.

- runtime/nsd_ossl.c
- tests/tcpflood.c
Switched from SSL_CTX_use_certificate_file to SSL_CTX_use_certificate_chain_file
API for loading the certificate into the certificate store.
According to the openssl doc, the SSL_CTX_use_certificate_chain_file API has the
advantage that it can load the main certificate (First in the PEM) and many chain
certificates after that automatically.
See notes section for more:
https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_use_certificate_chain_file.html
closes: https://github.com/rsyslog/rsyslog/issues/4170
> openssl nsd driver: Switch to SSL_CTX_use_certificate_chain_file API

- tests/es_response_get_msgnum.py
python3 does not like mixing spaces and tabs for indentation, so we get rid of the tab before print().
> testbench: modify es_response_get_msgnum.py for python3

- runtime/cfsysline.c
- runtime/glbl.c
- runtime/glbl.h
- runtime/rsconf.c
- runtime/rsconf.h
This parameter controls whether or not rsyslog aborts when a name ID
lookup fails (for user and group names). This is necessary as a security
measure, as otherwise the wrong permissions can be assigned or privileges
are not dropped.
CHANGE OF BEHAVIOR
The default for this parameter is "on". In previous versions, the default
was "off" (by virtue) of this parameter not existing. As such, existing
configurations may now error out.
We have decided to accept this change of behavior because of the potential
security implications.
closes https://github.com/rsyslog/rsyslog/issues/4164
> core: add global parameter "security.abortOnIDResolutionFail"

- grammar/lexer.l
> fix -o which produces missing space between call and rulename

- plugins/imudp/imudp.c
Depending on circumstances, this could also break compilation.
Detected while working on a related PR.
see also https://github.com/rsyslog/rsyslog/pull/4195
> imudp: remove no longer needed variable

- plugins/imudp/imudp.c
fix the following compiler errors with 4.19 kernel:
imudp.c:1216:2: error: implicit declaration of function 'prctl'
[-Werror=implicit-function-declaration]
if(prctl(PR_SET_NAME, thrdName, 0, 0, 0) != 0) {
^
Signed-off-by: Wen Yang <wenyang@linux.alibaba.com>
> imudp: fix compiler errors

- tests/diag.sh
We have some false positives with imfile checks and this commit
both improves the testbench framework slightly and adds debug
info.
The debug info should be remove when we finally find the cause
of the issue, but it does not hurt if it stays for a quite a
while. Thus we can analyze the false positives over an extended
period of time - what is what it looks like we need to do to
find the root cause.
> testbench: add some diagnostic info to analyze false positives

- tests/complex1.sh
Timeouts were too short to take care of slow CI environments.
> testbench: adjust queue enqueue timeouts to current standards

- runtime/queue.c
closes https://github.com/rsyslog/rsyslog/issues/4192
> queue subsystem: cap max queue size to 2^31-1

- runtime/nsd_ossl.c
- tests/imtcp-tls-ossl-basic-tlscommands.sh
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
- tests/tcpflood.c
Disable use of "@SECLEVEL" in default cipher string and
avoid SSL_CONF_CTX_set_flags() API when LIBRESSL is used.
This means tlscommands will not work.
closes: https://github.com/rsyslog/rsyslog/issues/4210
> openssl: add check for LIBRESSL

- .travis.yml
This is not a proper solution, but keeps rsyslog CI erroring out on
every run due to Travis issue. We didn't change anything, but somehow
Travis now runs only a subset of tests and fails on some others. This
needs to be investigated.
> Travis: something is wrong with Travis, this just makes it non-fail

- runtime/stream.c
- tests/Makefile.am
- tests/omfile-outchannel-many.sh
The check was done in strmPhysWrite before which caused syslog
messages to split in the middle if the syslog message batch exceeded
the default IO Buffer size.
closes: https://github.com/rsyslog/rsyslog/issues/4233
> stream.c: Moved doSizeLimitProcessing check to strmWrite

- runtime/stream.c
- if cstrLen(pThis->prevMsgSegment) > maxMsgSize then len calculation
become negative if cstrLen(thisLine) < cstrLen(pThis->prevMsgSegment)
This causes illegal access to memory location and thus causing segfault.
- assigning len = 0 if cstrLen(pThis->prevMsgSegment) > maxMsgSize so that
it access the correct memory location.
> stream: Fix for segfault on imfile read

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
When signer thread is created in rsksiInitModule thread successful
initialization is verified before returning the function. This will
prevent adding records to not initialized module and in case of an
error signature files opened will contain only magic bytes.
Thread flags replaced with thread state.
When init module fails, module is disabled.
> ksi bugfix: Signer thread initialization is verified before usage.

- runtime/lib_ksils12.c
- runtime/lmsig_ksi-ls12.c
KSI_getHashAlgorithmByName("default").
Function rsksiSetHashFunction and SetCnfParam updated.
> Hardcoded default hash algorithm KSI_HASHALG_SHA2_256 replaced with

- runtime/lib_ksils12.c
correctly. All pending signature requests are closed immediately and
unsigned block marker is attached with message about sudden closure.
Similar approach is used for blocks that already contain some records.
Empty blocks are just closed without any metadata.
> When KSI module in async. mode is suddenly closed, files are finalized

- plugins/omprog/omprog.c
- tests/omprog-output-capture-mt.sh
If the 'output' setting of omprog was used and rsyslog received a HUP
signal just after starting (and before the omprog action received the
first log to process), an internal assertion could fail, causing
rsyslog to terminate. The failure message was "rsyslogd: omprog.c:660:
closeOutputFile: Assertion `pCtx->bIsRunning' failed."
The failure could also occur if rsyslog received a HUP signal during
the shutdown sequence.
This bug was introduced in v8.2004 by PR #4255.
Although a test already existed that checked the interaction of HUPs
with the 'output' setting, it didn't always fail in this particular case
due to timing conditions. The test has been improved to cover this case
more reliably.
> omprog: fix assert failed on HUP with output flag

- tests/Makefile.am
- tests/imrelp-sessionbreak-vg.sh
For successfull test, the PR https://github.com/rsyslog/librelp/pull/184  for Issue https://github.com/rsyslog/librelp/issues/183 needs to merged into librelp first. 
Otherwise the test will trigger a double free inside librelp which results in a segfault in some cases.
closes: https://github.com/rsyslog/rsyslog/issues/4184
closes: https://github.com/rsyslog/rsyslog/issues/4005
> testbench: Add test for imrelp to check broken session handling.

- tests/imrelp-tls-cfgcmd.sh
- tests/sndrcv_relp_tls-cfgcmd.sh
closes https://github.com/rsyslog/rsyslog/issues/4131
> SKIP librelp tlscmd tests if librelp was build without openssl support

- .gitignore
- tests/omprog-single-instance-outfile.sh
- tests/omprog-single-instance.sh
Adapt one of the omprog tests to the latest improvements in the
testbench framework, for consistency with other similar tests. The test
behaviour has not changed.
Add some temporary files created by the testbench to gitignore file.
> omprog: adapt test to testbench improvements

- contrib/omhttp/omhttp.c
- tests/Makefile.am
- tests/omhttp-httpheaderkey.sh
- tests/omhttp-multiplehttpheaders.sh
Allows the inclusion of multiple http headers on the REST call, uses ":" as a delimiter for multiple header keys and values using the existing httpheaderkey and httpheadervalue parameters, you can specify up to 20 headers. Example:
httpheaderkey="X-Insert-Key:X-Event-Source"
httpheadervalue="key:logs"
> omhttp: Adding multiple http headers capability

- runtime/nsd_ossl.c
> openssl tls: stop leaking ctx

- tests/diag.sh
ElasticSearch can no longer be reliably downloaded, we receive error
451 - prohibited for legal reasons. This causes false positive test
failures.
We have solved this by moving the required tarballs to rsyslog.com and
download them now from there.
> CI: fix problems with ElasticSearch download

- ChangeLog
- configure.ac
Thanks to Thomas Deutschmann for pointing this out.
closes https://github.com/rsyslog/rsyslog/issues/3957
> build system: libzcmq version requirement needs to be bumped

- plugins/imjournal/imjournal.c
- tests/imjournal-statefile.sh
Hello @rgerhards -
I noticed the #2133 issue and thought I would make a run at some of them.
This change removes usage of strcat call from the imjournal plugin. I also looked for sprintf and strcpy calls while I was in there. I do not like the code here too much even though it is safer from the buffer overrun perspective. The way it could truncate the last 4 bytes of a very long state file path with a short state file name might result in a hidden file - or worse  in some other directory completely. I thought it would be better to just mention what I saw though, since it is unrelated, and another can of worms entirely. Happy to write another bug if you wanted.
I also spent some time on the test, it is more stable for me now.
> imjournal: remove strcat call

- plugins/imjournal/imjournal.c
Commit f604d5269bd31c09a661e9e4a20dd5044f4750da introduced strlen("Constant")
what we prefer not to do. This is now changed to sizeof("Constant") - 1,
what we usally use.
> imjournal: restore code style

- tools/ompipe.c
When HUP was received, the write mutex was not aquired. This could
lead to unexpected invalidation of the output file descriptor.
Thanks to Julien Thomas for alerting us on this issue.
see also https://github.com/rsyslog/rsyslog/pull/4136#issuecomment-578326278
> ompipe bugfix: race during HUP

- runtime/tcps_sess.c
- tests/Makefile.am
- tests/imtcp-bigmessage-octetcounting.sh
- tests/imtcp-bigmessage-octetstuffing.sh
When "discardTruncatedMsg" is enabled in imtcp, messages were incorrectly skipped if the last character before the truncation was the LFdelimiter.
Added also two tests for octet stuffing and framing
closes: https://github.com/rsyslog/rsyslog/issues/4281
> imtcp: fix octet framing / stuffing problem with discardTruncatedMsg on

- runtime/Makefile.am
This is no longer necessary, as we no longer use an embedded copy of
sd-daemon but the libsystemd system library.
> build: Drop update-systemd target

- devtools/default_dev_container
> bump default dev container to Ubuntu 20.04

- grammar/lexer.l
- tests/Makefile.am
- tests/include-obj-text-from-file-noexist.sh
when an `cat <filename>` consruct is used in rsyslog.conf ang <filename>
can not be accessed (does not exist, no permissions, ...), rsyslog
segfaults.
Thanks to Michael Skeffington for notifying us and providing analysis
of root cause.
closes https://github.com/rsyslog/rsyslog/issues/4290
> config system bugfix: backticks cat segfault if file cannot be opened

- configure.ac
- plugins/omlibdbi/Makefile.am
- plugins/omlibdbi/dummy.c
If set, builds a dummy module which just emits a "module not supported
on this platform" error message when loaded.
Primary use case for this system is Debian-ish builds on SUSE OBS,
where we prefer to have a single package definition for all versions
(else things get much more complicated).
> build system: add --enable-libdbi=optional functionality

- runtime/operatingstate.c
The month was printed with the range 0 (January) to 11 (December).
This commit corrects it.
closes https://github.com/rsyslog/rsyslog/issues/4292
> operatingstatefile bugfix: month was given too low

- runtime/lib_ksils12.c
KSI module initialization will not stuck in infinite loop when code is
built with optimization -O2.
> ksi bugfix: Optimized code in KSI module initialization fixed.

- rsyslog.service.in
now that rsyslog is usually only installed for real syslog servers,
we should assume that some network listening or forwarding happens
on start. As such we need to start a bit later, after the network.
This poses no problem as systemd nowadays comes with journal which
is in almost all cases configured to buffer log data while
rsyslog is not yet running.
> change systemd service file to wait for network

- runtime/nsd_ossl.c
- tests/Makefile.am
- tests/imtcp-tls-ossl-basic-brokenhandshake-vg.sh
Added testcase for ossl memory leak on failed handshake.
closes: https://github.com/rsyslog/rsyslog/issues/4319
> openssl: Fixed memory leak when tls handshake failed.

- plugins/imfile/imfile.c
If imfile is denied access to file watched trough symlink there is
unchecked condition resulting in access to not initialized memory.
> Fixing imfile segfaulting on selinux denial

- runtime/glbl.c
- runtime/glbl.h
- runtime/queue.c
This prevents message loss due to "queue full" when re-enqueueing data
under quite exotic settings.
see also https://github.com/rsyslog/rsyslog/issues/3941#issuecomment-549765813
closes https://github.com/rsyslog/rsyslog/issues/4020
> queue: permit ability to double size at shutdown

- grammar/rainerscript.c
There was wrong negation in the method so it returned 0/1 in reverse
and also it did not mark the node to not be reported as unknown at all
times which is needed after all.
> fixed ChkDisabled method to make config.enabled work

- .github/workflows/run_centos_6.yml
> CI: run centos 6 checks via github action

- runtime/nsd_gtls.c
Previously, when the server accepts a new connection, it doesn't properly set the dataTypeCheck field based on the listening socket. That results in skipping ExtendedKeyUsage (EKU) check on the client certificates.
> gnutls: Propagate CheckExtendedKeyPurpose when accepting connection

- .github/workflows/run_fedora_30.yml
- .github/workflows/run_ubuntu_18_distcheck.yml
> CI: move more checks to github actions

- Makefile.am
- platform/README
- platform/debian/rsyslog.service.10
- platform/debian/rsyslog.service.8
- platform/debian/rsyslog.service.9
- platform/redhat/centos/rsyslog.conf
- platform/redhat/centos/rsyslog.service
This file is a systemd unit file. Over the past months, we
received numerous complaints from the RH'ish community because
of the "wrong" content of this file. Thus, we changed it to
silence these complaints. Now, very similar complains come
from the Debian'ish community
(https://github.com/rsyslog/rsyslog/pull/4317#discussion_r445907950).
The root cause of these problems is that this is not really
a ryslog-related file. It is a systemd unit file, and obviously
very highly depending on distro policies. It was an excellent
idea to add this file back in the early days of systemd when
nobody knew about unit files. Nowadays, however, a single
"proposed" unit file causes more trouble than it solves.
As such, we will remove the file in rsyslog's project root.
Instead, we will provide …
> remove rsyslog.service[.in] sample file

- plugins/imudp/imudp.c
After running rsyslog with valgrind for a completely different reason, I found what I believe to be a missing free() in the imudp module
Here is the valgrind trace:
```
root@53c7502f7fc2:/rsyslog# valgrind --trace-children=yes --leak-check=full --show-leak-kinds=all --show-reachable=no rsyslogd -nf rsyslog.conf 
==14993== Memcheck, a memory error detector
==14993== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14993== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14993== Command: rsyslogd -nf rsyslog.conf
==14993== 
==14993== 
==14993== HEAP SUMMARY:
==14993==     in use at exit: 7,085 bytes in 47 blocks
==14993==   total heap usage: 35,753 allocs, 35,706 frees, 6,287,107 bytes allocated
==14993== 
==14993== 3 bytes in 1 blocks are definitely …
```
> FIX::IMUDP: add missing free during freeCnf()

- tools/omfile.c
When using obsolete legacy config format, omfile had a hard limit of
1,000 dynafile cache entries. This does not play well with very
large installation. This limit is now removed and converted into
a warning if cache size > 25,000 is specified.
Note: the problem can easily be worked-around by using modern
config format (RainerScript).
closes https://github.com/rsyslog/rsyslog/issues/4241
> omfile: do no longer limit dynafile cache size in legacy format

- tests/imfile-basic-2GB-file.sh
- tests/imfile-truncate-2GB-file.sh
Those tests can take a long time, especially on slow architectures like
armhf, so bump the test timeouts considerably.
closes https://github.com/rsyslog/rsyslog/issues/3698
> Increase timeouts in imfile-basic-2GB-file and imfile-truncate-2GB-file

- plugins/omelasticsearch/omelasticsearch.c
This is a proposal to fix github issue #4127 "omelasticsearch
failure parsing elasticsearch reply in 8.2001.0".
The issue happens when more than one server is defined on the
action. On that condition a health check is made through
checkConn() before sending the POST. The replyLen should be
set back to 0 after the health check, otherwise the response
data received from the POST gets appended to the end of the
last health check.
> omelasticsearch: Fix reply buffer reset after health check

- contrib/imdocker/imdocker.c
A wrong function to obtain the error code was used. This
could lead to invalid error messages.
Details:
At line 606 in imdocker.c, it calls curl_easy_strerror(ccode).
However, right before this it called curl_multi_add_handle()
which returns a CURLMcode enum. To get the right error message
conversion, it needs to call curl_multi_strerror() instead.
Thanks to Steve Grubb for the bug report and fix proposal.
closes https://github.com/rsyslog/rsyslog/issues/4381
> imdocker bugfix: error reporting not always correct

- plugins/imptcp/imptcp.c
- tests/Makefile.am
- tests/imptcp_maxsessions.sh
To protect the server against OOM we want to limit maxsessions
for imptcp.
The max is per-instance, not global across all instances.
There is also a bugfix where if epoll failed I think we could leave a
session linked in the list of sessions, this code unlinks it.
> Add max sessions for imptcp.c similar to imtcp.c to prevent OOM

- grammar/rainerscript.c
When there are actions configured after a STOP, a warning should be
emitted. In fact, an error message is generated. This prevents the
construct, which may have some legit uses in exotic settings. It
may also break older configs, but as the message is an error
for so long now, this should be no longer of concern.
see also https://github.com/rsyslog/rsyslog/issues/3668#issuecomment-493107691
> config bugfix: intended warning emitted as error

- plugins/imjournal/dummy.c
- plugins/imkafka/dummy.c
- plugins/omkafka/dummy.c
- plugins/omlibdbi/dummy.c
When we have optional components (like imjournal) a dummy module
is used. It's sole purpose is to emit "this module is not available".
During init, the module emitted an invalid module name into the debug
log. This has now been replaced by the generic term "dummy".
Note: it is highly unlikely that someone will ever see that message
at all, as it is unlikely for the dummy modules to be build.
see also: https://github.com/rsyslog/rsyslog/commit/84a7e3d80b80106dcc86c273ed8cf78a6c11c722#r41782830
Thanks to Thomas D. (whissi) for the patch.
> cosmetic: fix dummy module name in debug output

- .travis.yml
- Makefile.am
- configure.ac
- contrib/imhttp/Makefile.am
- contrib/imhttp/imhttp.c
- tests/Makefile.am
- tests/imhttp-getrequest-file-vg.sh
- tests/imhttp-getrequest-file.sh
- tests/imhttp-post-payload-compress-vg.sh
- tests/imhttp-post-payload-compress.sh
- tests/imhttp-post-payload-headers-vg.sh
- tests/imhttp-post-payload-headers.sh
- tests/imhttp-post-payload-large-vg.sh
- tests/imhttp-post-payload-large.sh
- tests/imhttp-post-payload-multi-lf-vg.sh
- tests/imhttp-post-payload-multi-lf.sh
- tests/imhttp-post-payload-multi-vg.sh
- tests/imhttp-post-payload-multi.sh
- tests/imhttp-post-payload-vg.sh
- tests/imhttp-post-payload.sh
- tests/testsuites/docroot/file.txt
- tests/testsuites/imhttp-large-data.txt
- tests/travis/install.sh
- tests/travis/run.sh
- uses http library to provide http input.
user would need to configure an 'endpoint' as input, along
with a ruleset, defining how the input should be routed in
rsyslog.
> http input module

- .github/workflows/run_centos_6.yml
This check is very slow because parallel builds are not supported
by the very old CentOS 6 autotools.
> CI: increase CentOS 6 github check max runtime

- runtime/nsd_ptcp.c
Due to an invalid return code check, broken TCP sessions could not
necessarily be detected "right in time". This can result is the loss
of one message.
closes https://github.com/rsyslog/rsyslog/issues/4227
**This merges commit 1 of https://github.com/rsyslog/rsyslog/issues/4227**
> imtcp bugfix: broken connection not necessariy detected

- runtime/msg.c
A data race can happen on variable iLenProgram as it is not guarded
by the message mutex at time of query. This can lead to it being
non -1 while the buffer has not yet properly set up.
Thanks to github user wsp1991 for alerting us and a related
patch proposal.
replaces https://github.com/rsyslog/rsyslog/pull/4300
> core bugfix: potential segfault on querey of PROGRAMNAME property

- runtime/net.c
Local hostname resolution uses DNS queries even if the enableDNS is set to off, and this can cause unexpected delays in the HUP signal handling if the DNS server is not responsive. This change makes sure that the resolver is not used if it has been explicitly disabled.
> core/network: obey net.enableDNS=off when querying local hostname

- runtime/nsd_gtls.c
Some TLS servers don't reply to graceful shutdown requests "for
optimization". This results in rsyslog's omfwd+gtls client to wait
forever for a reply of the TLS server which never comes, due to shutting
down the connection with gnutls_bye(GNUTLS_SHUT_RDWR).
On systemd systems, commands such as "systemctl restart rsyslog" just
hang for 1m30 and rsyslogd gets killed upon timeout by systemd.
This patch replaces call to gnutls_bye(GNUTLS_SHUT_RDWR) by calls to
gnutls_bye(GNUTLS_SHUT_WR) which is sufficient and doesn't wait for a
server reply.
A Red Hat customer reproduces the hang reliably when sending the logs to
his Kiwi Syslog server, which apparently doesn't send the TLS reply upon
connection termination request.
> Replace GNUTLS_SHUT_RDWR by GNUTLS_SHUT_WR when ending TLS connections

- runtime/msg.c
This is a proposal for Github issue rsyslog/rsyslog#4430:
accessing a non-existing key creates an empty parent object
https://github.com/rsyslog/rsyslog/issues/4430
When looking up an object property, the tree of intermediate
object containers was ceated by get and del functions. The
patch is an attempt to fix that behavior by passing 0 to the
bCreate argument of jsonPathFindParent().
There is also one case where the return value of
jsonPathFindParent() was not checked, in the recurssive call
of jsonPathFindParent() itself. This was leading to infinite
loops if bCreate was 0.
closes #4430 
closes #4436
> Do not create empty objects when accessing non-existent keys

- grammar/grammar.y
- grammar/lexer.l
- grammar/rainerscript.c
- grammar/rainerscript.h
- runtime/msg.c
- runtime/msg.h
- template.c
- tests/Makefile.am
- tests/rscript_exists-not1.sh
- tests/rscript_exists-not2.sh
- tests/rscript_exists-not3.sh
- tests/rscript_exists-not4.sh
- tests/rscript_exists-yes.sh
- tests/rscript_exists-yes2.sh
This implements a way to check if rsyslog variables (e.g. '$!path!var') is
currently set of not.
closes https://github.com/rsyslog/rsyslog/issues/4385
> add 'exists()' script function to check if variable exists

- runtime/msg.c
A segfault may occur in jsonPathFindNext() when bCreate is 1 and when the <root> container where to insert the namebuf key is not an object.
Here is simple reproducible test case:
```
// ensure we start fresh
// unnecessary if there was no previous set
unset $!;
set $! = "";
set $!event!created = 123;
```
There is also a memory leak in msgAddJSON() if jsonPathFindParent() failed because of a missing call to json_object_put(json).
> msg: Fix segfault and memory leak on set operation

- plugins/imtcp/imtcp.c
- runtime/netstrms.c
- runtime/nsd_gtls.c
- runtime/tcpsrv.c
- tests/Makefile.am
- tests/sndrcv_tls_certvalid_expired_defaultmode.sh
- tools/omfwd.c
In order to set the default PermitExpiredCerts handling (Deny),
we need to call PermitExpiredCerts with NULL parameter.
testbench: Add test to check expired handling in omfwd
closes: https://github.com/rsyslog/rsyslog/issues/4425
> tls: Allow calling PermitExpiredCerts with NULL parameter

- runtime/ratelimit.c
- runtime/ratelimit.h
- tools/omfwd.c
Adding new rate limit option to omfwd for rate limiting
syslog messages sent to the remote server
ratelimit.interval:
Specifies the rate-limiting interval in seconds.
Default value is 0, which turns off rate limiting.
ratelimit.burst
Specifies the rate-limiting burst in number of messages.
fixes #4423
https://github.com/rsyslog/rsyslog/issues/4423
> omfwd: adding new rate limit option

- runtime/msg.c
- runtime/typedefs.h
- tests/Makefile.am
- tests/now-unixtimestamp.sh
Among others, this may be used as a monotonic counter
for doing load-balancing and other things.
Thanks to Nicholas Brown for suggesting this feature.
> add new system property $now-unixtimestamp

- runtime/msg.h
There is a small typo in runtime/msg.h.
Should read `characters` rather than `charcters`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, charcters -> characters

- tools/omfwd.c
see also https://github.com/rsyslog/rsyslog/issues/3910
> re-phrase error message to help users understand better what happens

- plugins/immark/immark.c
- tests/Makefile.am
- tests/immark-inputname.sh
- tests/immark-ruleset-custom-msg.sh
- tests/immark-ruleset.sh
- mark message text can now be specified
- support for rulesets
- support for using syslog API vs. regular internal interface
- support for output template system
- ability to specify is mark message flag can be set
- minor changes and improvements
> immark: rewrite with many improvements

- tests/clickhouse-dflt-tpl.sh
A test had the year value hardcoded and as such failed whenever the
year changed. This patch corrects that.
> testbench: fix year-dependendt clickhouse test

- tests/Makefile.am
kafka tests can not run well in parallel (mostly due to ressource
constraints on CI machines). Accidentally, this was not enforced for
one of the tests. That could lead to random failures and false positives.
> testbench: fix invalid sequence of kafka tests runs

- grammar/rainerscript.c
A data race could happen when a lookup table was reloaded. We found
this while moving to newer version of TSAN, but have no matching
report from practice. However, there is a potential for this to cause
a segfault under "bad circumstances".
@janmejay  FYI
> lookup table bugfix: data race on lookup table reload

- .github/workflows/run_journal.yml
The journal test github action installs wrong extra dependency
version, which can lead to issues with some tests. We also trim
the dependency list a bit.
> CI bugfix: journal test installed wrong dependencies

- .github/workflows/run_journal.yml
commit 76e1191938 accidentally installed the wrong library (librelp).
We now install the right one (libfastjson).
> CI bugfix: journal testing setup was invalid

- tools/omfwd.c
If omfwd is configured via RainerScript config format and the "port"
parameter is not given, a segfault will most likely happen on
connection establishment for TCP connections. For UDP, this is
usually not the case.
Alternatively, in any case, errors may happen.
Note that the segfault will usually happen right on restart so this
was easy to detect.
We did not receive reports from practice. Instead, we found the bug
while conducting other work.
> omfwd bugfix: segfault or error if port not given

- action.c
The impstats module reports a bunch of counters for actions, including the resume count. However, the resume counter is never actually used and the value stays at 0 in the stats output, regardless of whether an action has been resumed or not.
This tiny change adds a counter increment in the resume path.
> Implement resume counting

- action.c
When the action error file is written (or would be written, if not enabled), increment the failure counter. Previously with omfwd (and others?) with action.resumeRetryCount > -1, after all retries were exhausted the message would be dropped but the failure count for the action remained at 0.
Perhaps the failure counter has other semantics, but it was unexpected that for omfwd, errors in the connection, or from GnuTLS or OpenSSL, don't increment the action's failure counter. With this change the action's failure counter is effectively a line count of its error file.
> Track failure statistics in actions

- tests/Makefile.am
- tests/omfwd_impstats-tcp.sh
- tests/omfwd_impstats-udp.sh
- tools/omfwd.c
> omfwd: add stats counter for sent bytes

- tools/omfwd.c
RSyslog on a plain TCP cannot guarantee the message delivery
without using RELP protocol. Besides that the logs may be
flooded with connection errors making the rest of messages
difficult to find. To alleviate the problem (see issue 3910),
this patch adds a configuration option that enables to reduce
the number of network errors logged and reported.
For example, if each 10th network error message should be logged,
the rsyslog configuration has to be updated as follows.
action(type="omfwd" Target="<IP_ADDR>" Port="<PORT>" Protocol="tcp" ConErrSkip="10")
> Add error reporting configuration option to omfwd.

- tests/diag.sh
- tests/imrelp-tls-cfgcmd.sh
- tests/sndrcv_relp_tls-cfgcmd.sh
tlscommands for the following tests have been changed:
- imrelp-tls-cfgcmd.sh
- sndrcv_relp_tls-cfgcmd.sh
This will make sure the librelp tlscommand tests run well on all librelp versions and with all OpenSSL Version. 
Newer OpenSSL Versions would run TLSv1.3 on those tests which is valid for the old tlscommand. However we can NOT disable TLSv1.3 with one tlscommand as this would break the tlsconfcmd for older OpenSSL Versions.
closes: https://github.com/rsyslog/rsyslog/issues/4534
> testbench: changed tlscommands for librelp tls tests.

- runtime/nsd_ptcp.c
- tests/imrelp-tls-cfgcmd.sh
This solves test failures on some platforms like solaris.
Also added _attribute__((unused)) into SetTlsVerifyDepth in
nsd_ptcp.c to fix compiler errors with gcc9.
closes: https://github.com/rsyslog/rsyslog/issues/4544
> testbench: Enhanced error detection in imrelp-tls-cfgcmd.sh

- tests/testsuites/mmexternal-SegFault-mm-python.py
- tests/testsuites/omprog-output-capture-mt-bin.py
py files should be run as ${PYTHON} *.py
reference issue: #3853
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>
> testbench: Remove python shebang in tests/testsuites

- plugins/external/skeletons/python/plugin.py
Make skeleton plugin append to a file instead of truncating it.
I lost 2 days looking why omprog not work, almost give up, because i was running a tail in /tmp/logfile and didn´t was seen any messages at all.
After running rsyslog in debug mode i saw omprog calling plugin.py, so i double checked it and after change to append all worked fine.
> Update plugin.py to append to a file

- tests/diag.sh
Busybox logger doesn't have the -d flag.
Skip instead of failing the tests that need -d.
Also fix typo s/-p/-d.
busybox reference:
https://busybox.net/downloads/BusyBox.html#logger
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>
> testbench: Skip tests that need logger -d for busybox

- grammar/lexer.l
- tests/Makefile.am
- tests/config_multiple_include.sh
- tests/testsuites/include-std1-omfile-action.conf
- tests/testsuites/include-std2-omfile-action.conf
The previous text seemed to cause the wrong impression that includes
were processed in the wrong order. Right the contrary is the case, as
config files are being put on a stack before they are processed.
closes https://github.com/rsyslog/rsyslog/issues/4271
> clarify some debug output in regard to config include load order

- runtime/nsd_ossl.c
when tls handshake fails, function osslLastSSLErrorMsg is called to
print the logs saved on error stack, adding the tag "nsd_ossl:" for the
better identification of these logs in such failure scenarios.
> Improving nsd ossl logs for better debugging

- Makefile.am
- configure.ac
- contrib/fmunflatten/Makefile.am
- contrib/fmunflatten/fmunflatten.c
- runtime/msg.c
- runtime/msg.h
- tests/Makefile.am
- tests/rscript_unflatten_arg1_unsuitable-vg.sh
- tests/rscript_unflatten_arg1_unsuitable.sh
- tests/rscript_unflatten_arg2_invalid-vg.sh
- tests/rscript_unflatten_arg2_invalid.sh
- tests/rscript_unflatten_conflict1-vg.sh
- tests/rscript_unflatten_conflict1.sh
- tests/rscript_unflatten_conflict2-vg.sh
- tests/rscript_unflatten_conflict2.sh
- tests/rscript_unflatten_conflict3-vg.sh
- tests/rscript_unflatten_conflict3.sh
- tests/rscript_unflatten_key_truncated-vg.sh
- tests/rscript_unflatten_key_truncated.sh
- tests/rscript_unflatten_non_object-vg.sh
- tests/rscript_unflatten_non_object.sh
- tests/rscript_unflatten_object-vg.sh
- tests/rscript_unflatten_object.sh
- tests/rscript_unflatten_object_exclamation-vg.sh
- tests/rscript_unflatten_object_exclamation.sh
This commit adds a new rainerscript function to unflatten keys in a JSON tree. It provides a way to expand dot separated fields.
`<result> = unflatten(<source-tree>, <key-separator-character>);`
It allows for instance to produce this: `{ "source": { "ip": "1.2.3.4", "port": 443 } }`
from this source data: `{ "source.ip": "1.2.3.4", "source.port": 443 }`
Here is a sample use case:
```
set $!source.ip = "1.2.3.4";
set $!source.bytes = 3258;
set $!source.geo.country_iso_code = "FR";
set $!destination.ip = "4.3.2.1";
set $.unflatten = unflatten($!, ".");
if (script_error() == 0) then {
unset $!;
set $! = $.unflatten;
unset $.unflatten;
}
```
An output of $! would give this, in pretty-print
```
{
"source": {
"ip": "1.2.3.4",
"bytes": 3258,
"geo": {
"country_iso_code": "FR"
}
},
"destination": …
```
> fmunflatten: rscript function to unflatten keys in a JSON object

- plugins/imjournal/imjournal.c
Flush the FILE* buffer before rename & fsync in order
to not end up syncing an empty file.
Also, close WorkDir on fsync in order to prevent
file descriptor leakage.
Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Signed-off-by: Venu Busireddy <venu.busireddy@oracle.com>
> imjournal: flush buffer before fsync

- plugins/mmdblookup/mmdblookup.c
- tests/libmaxmindb.supp
Current version of mmdblookup doesn't handle the mmdb file(s) safely, this improvement allows safe reloading of mmdb files after changing them, without having to restart Rsyslog
> MMDBLOOKUP::Improvement:: allow mmdb to be reloaded on HUP signal

- runtime/ruleset.c
There is a problem in Rsyslog with the foreach() function:
When running a foreach() loop inside a ruleset, if the json array/object iterated over is empty but valid, the foreach will make the message processing in the ruleset abort operation, no following operation (such as actions) will be executed after this.
This is the environment I used to track and correct the bug.
I used the **v8.2012.0** version, then based the work on the current master (051815873).
```
module(load="imtcp")
module(load="mmjsonparse")
module(load="builtin:omfile")
input(type="imtcp"
Address="127.0.0.1" Port="1001"
RuleSet="ruleset_test")
template(name="alljson" type="string" string="%$!%\n")
ruleset(name="ruleset_test") {
action(type="mmjsonparse" cookie="")
if $parsesuccess=="OK" then {
set $.test = 1;
foreach ( …
```
> RainerScript::FIX:: handle foreach with empty arrays/objects

- plugins/imdiag/imdiag.c
- plugins/imgssapi/imgssapi.c
- plugins/imtcp/imtcp.c
- runtime/nsdpoll_ptcp.c
- runtime/tcps_sess.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/imtcp-multiport.sh
Some further stream-lining and cleanup of paramter passing. This
levels ground for more substantial changes to the imtcp/tcpsrv
interaction.
see also https://github.com/rsyslog/rsyslog/issues/3727#issuecomment-525705318
> further refactoring of tcpsrv parameter passing

- runtime/tcpsrv.c
tcpsrv is used by multiple other modules (imtcp, imdiag, imgssapi, and,
in theory, also others - even ones we do not know about). However, the
internal synchornization did not properly take multiple tcpsrv users
in consideration.
As such, a single user could hang under some circumstances. This was
caused by improperly awaking all users from a pthread condition wait.
That in turn could lead to some sluggish behaviour and, in rare cases,
a hang at shutdown.
Note: it was highly unlikely to experience real problems with the
officially provided modules.
This patch corrects the situation.
> tcpsrv bugfix: potential sluggishnes and hang on shutdown

- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
another try at supporting inputs with different stream drivers as well as getting code cleaner
This commit also refactors imtcp in support of potentially multiple different communications modes, but perserves and fixes problems with the global worker pool.
see also #3727
> imtcp refactoring w/ global worker pool

- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
- tests/Makefile.am
- tests/imtcp-drvr-in-input-basic.sh
- tests/imtcp-multi-drvr-basic-parallel.sh
- tests/imtcp-multi-drvr-basic-ptcp_gtls_ossl.sh
- tests/imtcp-multi-drvr-basic.sh
This permits to have different inputs use different stream drivers
and stream driver parameters.
closes https://github.com/rsyslog/rsyslog/issues/3727
> imtcp: add stream driver parameter to input() configuration

- plugins/imtcp/imtcp.c
- tests/Makefile.am
- tests/imtcp-connection-msg-recieved.sh
- tests/imtcp_addtlframedelim_on_input.sh
> imtcp: add more override config params to input()

- runtime/glbl.c
- runtime/parser.c
- runtime/parser.h
This permits to turn off rsyslog's single-message compression extension
when it interferes with non-syslog message processing (the parser
subsystem expects syslog messages, not generic text)
closes https://github.com/rsyslog/rsyslog/issues/4598
> new global option "parser.supportCompressionExtension"

- runtime/statsobj.c
> bugfix: _sender_stats reports integer counter as string

- runtime/rsconf.c
This is essentially the same as RSYSLOG_SyslogProtocol23Format with
a better name and a fix to remove the unnecessary LF at the end of
the message.
The different name also enables us to fix the LF issue without
any concern about backwards compatibility.
closes https://github.com/rsyslog/rsyslog/issues/4384
> add predefined template RSYSLOG_SyslogRFC5424Format

- contrib/omhttp/omhttp.c
- tests/Makefile.am
- tests/omhttp-batch-dynrestpath.sh
- tests/omhttp-dynrestpath.sh
Modified omhttp: Fix dynrestpath param in batch mode
When batchmode was used, the templates could not be used to    
expand dynrestpath. We are now storing the restpath param 
within the batch data if we are in batch mode.
- testbench: Added tests for omhttp dynrestpath param
Testing setting the restpath by template - one with batch mode
and one without batch mode
closes: https://github.com/rsyslog/rsyslog/issues/4567
> omhttp: Fix dynrestpath param in batch mode

- plugins/imtcp/imtcp.c
- tools/omfwd.c
Memory for config parameter was not free'd on rsyslog shutdown. This had
no real consequence, but caused memleak alerts during development.
> tcp subsystem: fix cosmetic memory leak on shutdown

- contrib/mmkubernetes/mmkubernetes.c
- tests/mmkubernetes-basic-vg.sh
- tests/mmkubernetes-basic.out.json
- tests/mmkubernetes-basic.sh
- tests/mmkubernetes_test_server.py
submit on behalf of @abwaheed
- Added graceful handling of apiserver errors with unexpected responses,
i.e., anything other than 200, 404, or 429. Idea is that apiserver
transient error state will recover. We don't want mmkubernetes to miss
metadata resolution for containers that don't have cached metadata.
During these transient error states, mmkubernetes will provide basic
container file path based resolution of namespace and pod metadata for
new pods whose metadata is not yet cached. After this error state
recovers, mmkubernetes is expected to resume its metadata resolution as
expected.
- Added a unit test case for apiserver return 500 with changes to mock server
-  Fixed existing unit test that was failing due to missing expected results file
-  Added mmkubernetes unit tests to …
> mmkubernetes fix for apiserver error handling

- plugins/imdiag/imdiag.c
- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
Modules (like imtcp and imdiag) which use tcpsrv could abort or
otherwise malfunction if no listener for a specific input could
be started.
Found during implementing a new feature, no report from practice.
But could very well happen.
> tcpsrv bugfix: abort if no listener could be started

- runtime/nsd_ossl.c
Fixes a static, non-growing memory leak which existed when parameter
"GnutTLSPriorityString" was used. This was primarily a cosmetic issue,
but caused some grief during development in regard to memory leak
detectors.
Note: yes, this is for openssl -- the parameter name is history ;-)
> openssl network driver bugfix: small memory leak

- plugins/imptcp/imptcp.c
The interval was accidentally set to keep alive interval. This has been
corrected.
closes https://github.com/rsyslog/rsyslog/issues/4609
> imptcp bugfix: keep alive interval was incorrectly set

- tools/rsyslogd.c
so far, we cannot clearly see when HUP processing begins
> debug support: add indication of "being HUPed" to debug log

- plugins/imfile/imfile.c
Close file descriptor when **freshStartTail** is turned on. Introduced in https://github.com/rsyslog/rsyslog/commit/b57a65287d0c17e4b28a99cbe5d25bdb5b58f02d.
> Close file descriptor when freshStartTail is turned on

- runtime/netstrm.c
- runtime/netstrm.h
- runtime/nsd_gtls.c
- tests/Makefile.am
- tests/diag.sh
- tests/sndrcv_tls_certvalid_action_level.sh
- tests/sndrcv_tls_ossl_certvalid_action_level.sh
- tools/omfwd.c
This permits to override the global definitions for TLS certificates
at the action() level.
> omfwd: add capability for action-specific TLS certificate settings

- plugins/omelasticsearch/omelasticsearch.c
Lock the file during SIGHUPs to avoid issues with concurrent accesses by writeDataError().
Check the return value of pthread_mutex_init() in CODESTARTcreateInstance to make sure the mutex is actually usable.
> [omelasticsearch] Improve errorFile mutex handling

- tests/imuxsock_legacy.sh
- tests/imuxsock_logger.sh
- tests/imuxsock_logger_err.sh
- tests/imuxsock_logger_parserchain.sh
- tests/imuxsock_logger_root.sh
- tests/imuxsock_logger_syssock.sh
- tests/msgdup.sh
- tests/omfwd-keepalive.sh
Practice has shown that environment-induced error messages may
appear during test runs. For example, incorrect resolver settings
may cause name resolution warnings or errors. These are unrelated
to the test itself.
This patch enables tests that are otherwise unaffected by the faillures
to continue and provide "pass" test result.
see also https://github.com/rsyslog/rsyslog/issues/4619
> testbench: guard tests against unexpected warning messages

- runtime/stream.c
If imfile is ingesting log files with readMode set to 2 or 1, the resulting
messages all have a '#' character at the end. This patch corrects the behaviour.
Note: if some external script "supported" the bug of extra hash character at
the end of line, it may be necessary to update them.
closes https://github.com/rsyslog/rsyslog/issues/4491
> imfile bugfix: hash char invalidly added in readmode != 0

- plugins/imfile/imfile.c
- tests/Makefile.am
- tests/imfile-statefile-delete.sh
- tests/imfile-statefile-no-delete.sh
Fixes #4494
Fixes the `deleteStateOnFileDelete` option for imfile.
When the log file is deleted, imfile would attempt to delete the statefile but it was missing the `file_id` part of the statefile name. This means the statefiles were only removed in the log file is less than 512 characters, because for very small files the hash is not created. 
Added tests that checks that the statefile is deleted if `deleteStateOnFileDelete` is not specified, and that the statefile is not deleted if `deleteStateOnFileDelete = "off"`
> Fixing the deleteStateOnFileDelete option

- plugins/imklog/imklog.c
This is a regeression from commit 94c4a87. It introduced a free() call
using an object that was no longer valid (the main pointer to the
to-be-freed object) was already freed at time of use. This could
cause various issues, including a segfault.
Note: this bug was triggerred only during late phase of rsyslog
shutdown, so it did not affect regular operation.
Special thanks to github user wxiaoguang for analyzing the issue
and providing a draft fix proposal, on which this patch builds.
see also https://github.com/rsyslog/rsyslog/pull/4629
closes https://github.com/rsyslog/rsyslog/issues/4625
> imklog: fix invalid memory adressing, could cause abort

- grammar/rainerscript.c
- runtime/cfsysline.c
- runtime/glbl.c
- runtime/rsconf.c
- tests/Makefile.am
- tests/rscript_privdropgroup.sh
- tests/rscript_privdropgroupid.sh
- tests/rscript_privdropuser.sh
- tests/rscript_privdropuserid.sh
closes https://github.com/rsyslog/rsyslog/issues/891
> config: implement script-equavalent for $PrivDrop* statements

- runtime/nsd_gtls.c
Until now, when the server accepts new connection via ```AcceptConnReq()```, it does not initialize the ```bSANpriority``` field.
While the option does work on the client side (meaning the server cert is checked), it does not on the server side.
> gnutls: Propagate PrioritizeSAN when accepting a new connection

- plugins/imdiag/imdiag.c
- runtime/queue.c
Add NULL value handling for pDeqRoot. This caused seqfaults if
messages were discarded during dequeue.
Also fix iOverallQueueSize calculation (discarded items) in imdiag.
While building a testcase for issue #4437 , I discovered an issue with the
iOverallQueueSize counter not being substracting discarded messages. This caused
the testcase to fail with testcase timeout at the count of "discardMark" queue
setting.
closes: https://github.com/rsyslog/rsyslog/issues/4437
> queue: Add NULL check in qDeqLinkedList

- runtime/msg.c
When $wday is used inside a template, all template parts after it
are ignored. For exmaple:
template(name="json_filename" type="string" string="/var/log/%$wday%.log")
would generate something like "/var/log/0" - the ".log" part would be
missing. For the same reason, $wday can not reliably checked in script
filters.
Thannks to Alain Thivillon for reporting the bug and providing an
excellent analysis, which essentiellay was exactly this fix here.
closes https://github.com/rsyslog/rsyslog/issues/4670
> core bugfix: use of property $wday terminates string

- runtime/ratelimit.c
- tests/Makefile.am
- tests/imuxsock_logger_ratelimit.sh
This commit fixes the imuxsock's rate limiting, which does not work in the
default configuration (useSpecialParser="true" and ratelimit.severity="1")
When useSpecialParser was set to "true" all messages were treated with
severity 0 and therefore were not subjects to the rate limiting that by
default ignores messages with severity 0.
The test suite requires
./configure --enable-liblogging-stdlog
> imuxsock: fix rate limiting not working in default configuration

- tests/privdrop_common.sh
- tests/privdropgroup.sh
- tests/privdropgroupid.sh
- tests/privdropuser.sh
- tests/privdropuserid.sh
When running under root, the privdrop tests did not properly work. This
patch fixes the issue and skips test where necessary.
This also includes some modernization of the related tests.
closes https://github.com/rsyslog/rsyslog/issues/4619
> testbench: fix privdrop tests under root user

- tests/diag.sh
> testbench: bump kafka and zookeeper versions

- tests/Makefile.am
- tests/diag.sh
- tests/omfwd_fast_imuxsock.sh
Testcase omfwd_fast_imuxsock.sh uses imuxsock as input and checks
how the queue engine (linkedlist) handles discarded messages.
see also:
https://github.com/rsyslog/rsyslog/issues/4437
requires PR:
https://github.com/rsyslog/rsyslog/pull/4674
> testbench: add testcase for queue discardSeverity (linkedlist)

- configure.ac
- contrib/imhttp/Makefile.am
- contrib/imhttp/imhttp.c
- tests/Makefile.am
- tests/imhttp-post-payload-basic-auth-vg.sh
- tests/imhttp-post-payload-basic-auth.sh
- tests/imhttp-post-payload-query-params-vg.sh
- tests/imhttp-post-payload-query-params.sh
- tests/testsuites/htpasswd
- Basic Authentication support & tests
* configured via imhttp option "basicAuthFile". This option should be configured
to point to your htpasswd file generated via a standard htpasswd tool.
tests:
* imhttp-post-payload-basic-auth.sh
* imhttp-post-payload-basic-auth-vg.sh
- Query parameter ingestion capability & tests
use `addmetadata` option to inject query parameters into
metadata for imhttp input.
> imhttp updates - query parameter ingestion & basic auth support

- runtime/nsd_ossl.c
- runtime/nsd_ptcp.c
Now includes the remote client/server IP address in the log output.
closes: https://github.com/rsyslog/rsyslog/issues/4680
> openssl: extended output information on connection failure

- .github/workflows/run_ubuntu_20_distcheck.yml
- tests/Makefile.am
- tests/diag.sh
The testbench framework does not properly wait until ES has created
its pid file, which probably means it did basic initializiation.
This can cause test synchronization issues and ultimately failures.
> testbench bugfix: no pid file wait on elasticsearch startup

- tests/clickhouse-errorfile.sh
- tests/clickhouse-wrong-insert-syntax.sh
It looks like the current version of clickhouse does not error out
on some types of errors. So tests need either to be redesigned
or removed.
As such, we temporarily skip them for now.
> testbench: disable some clickhouse tests

- tests/diag.sh
- tests/es-bulk-retry.sh
https://github.com/rsyslog/rsyslog/issues/4684
According to https://discuss.elastic.co/t/unknown-setting-thread-pool-bulk-queue-size/180120
The setting `thread_pool.bulk` has been renamed to `thread_pool.write`
"The bulk threadpool was renamed to write in 6.3.0, and support for the legacy bulk name was removed in 7.0.0 133."
> Fix ElasticSearch Test broken by ES incompatibility

- plugins/external/skeletons/python/mm-python.py
The print message was in python2 syntax. added brackets
> Fixed the print statement to match python3 syntax

- plugins/external/skeletons/python/plugin.py
The semicolon creates a warning in some code editors
> Removed a useless semicolon

- plugins/omsnmp/omsnmp.c
The `omsnmp` module uses the `inet_addr()` function to convert the Internet host address from IPv4 numbers-and-dots notation into binary data in network byte order. If the input is invalid, INADDR_NONE (usually -1) is returned. Use of this function is problematic because -1 is a valid address (255.255.255.255). We should avoid its use in favor of inet_aton(), inet_pton(3), or getaddrinfo(3), which provide a cleaner way to indicate error return [1].
This is just a request to satisfy covscan, so no error is reported at all. 
[1] https://man7.org/linux/man-pages/man3/inet_addr.3.html
> Avoid use of inet_addr() in favor of inet_aton()

- runtime/ruleset.c
The ruleset was incorrectly and unusably named. This was a regeression
from 4a63f8e9629c3c9481a8b6f9d7787e3b3304320b.
Many thanks to github user digirati82 for alerting us.
closes https://github.com/rsyslog/rsyslog/issues/4730
> ruleset bugfix: ruleset queue was incorrectly named

- .github/workflows/run_fedora_34.yml
> CI: add Fedora 34 check run

- tests/diag.sh
This maintains a full stack trace, otherwise can be incomplete in some
cases!
> testbench: Add --keep-debuginfo=yes to default valgrind parameters.

- tests/diag.sh
This option is not known by older valgrind versions. As such, it causes
false positives on older platforms. As the option is not necessary
(only helpful for some border cases), we remove it and add a comment
so that it may be enabled when necessary.
> testbench: do not use valgrind --keep-debuginfo=yes by default

- plugins/imfile/imfile.c
- plugins/imklog/imklog.c
- plugins/imptcp/imptcp.c
- plugins/imudp/imudp.c
- runtime/ratelimit.c
- runtime/ratelimit.h
- tests/imtcp-tls-basic.sh
- tests/imtcp_conndrop_tls-vg.sh
- tests/rscript_http_request-vg.sh
The ```ratelimitNew()``` function used  the ```bReduceRepeatMsgs``` global option to acquire information from the configuration that is going to be loaded. While this function was created to be used(I believe) during "configuration loading time", multiple input plugins use it during runtime. It's true that it has no impact on the current system right now, because both ```loadConf``` and ```runConf``` point to the same config. However, in the future a dynamic configuration reload option might be added.
> Avoid use of loadConf in favor of runConf in ratelimiting during runtime

- outchannel.c
- runtime/rsconf.c
The outchannel resources were not freed when rsyslog was stoped. The PR intends to fix it by invoking ```ochDeleteAll()``` in the rsconf destructor.
> Deallocate outchannel resources in rsconf destructor

- action.c
- grammar/rainerscript.c
- outchannel.c
- outchannel.h
- runtime/dynstats.c
- runtime/lookup.c
- runtime/parser.c
- runtime/perctile_stats.c
- runtime/rsconf.c
- runtime/ruleset.c
- template.c
- tools/rsyslogd.c
The PR intends to clarify the meaning of loadConf and runConf. These were originally introduced to facilitate a later move to dynamic config loads.  Over the years, the use of these pointers has become unclear. 
- loadConf was intended for candidate config (the new one)
- runConf for the currently running config
> Clarify the meaning of loadConf and RunConf

- contrib/omhttp/omhttp.c
- tests/Makefile.am
- tests/omhttp-batch-lokirest-vg.sh
A JSON object was created (valueObj) but not used and also not
released causing a memory leak. This was properly caused by the
initial copy&paste from serializeBatchKafkaRest.
- Also added a valgrind test for lokirest batchmode
Uncomment "--keep-debuginfo" in testcaseif stack traces
are incomplete
closes: https://github.com/rsyslog/rsyslog/issues/4766
> omhttp: Fix memory leak in lokirest batchmode

- .github/workflows/run_journal.yml
Especially as this dependency currently causes the check run to fail.
No point in trying to fix it, as it is not needed. So removing is the
most robust option.
> CI: remove unnecessary dependency

- plugins/omlibdbi/omlibdbi.c
In the original code, there is a use-after-free bug, which renders the sqlite3 output module unusable. The bug lies in the function initConn, the buggy code is as follows:
```
293             char *const dn_org = strdup((char*)pData->dbName);
294             char *const dn = dirname(dn_org);
295             dbi_conn_set_option(pData->conn, is_sqlite3 ? "sqlite3_dbdir" : "sqlite_dbdir",dn);
296             free(dn_org); /* Free original buffer - dirname may return different pointer */
297 
298             char *tmp = strdup((char*)pData->dbName);
299             char *bn = basename(tmp);
300             free(tmp);
301             dbi_conn_set_option(pData->conn, "dbname", bn); 
```
In line 299, the bn points to the middle of the buffer referenced by tmp, which is allocated in line 298. And …
> Fix an use-after-free bug in omlibdbi.c

- runtime/strms_sess.c
Especially as this caused confusion when doing other work inside the code.
see also https://github.com/rsyslog/rsyslog/pull/4760#discussion_r783118550
> cleanup: remove unused variable

- runtime/Makefile.am
- runtime/datetime.c
- runtime/glbl.c
- runtime/glbl.h
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/timezones.c
- runtime/timezones.h
- runtime/typedefs.h
Make timezone specific variables part of the ```rsconf_t``` structure. Later, when dynamic configuration reload feature is introduced, we will need to distinguish between loaded and actually running time zones.
https://github.com/rsyslog/rsyslog/pull/4760 must be merged before this one. Please note that only the last commit is part of this PR, others are part of my previous PR.
> Timezone to rsconf

- plugins/imtcp/imtcp.c
Graceful shutdown of Rsyslog could lead to segmentation faults when
multiple imtcp inputs are being used. That is because the rest of the
tcpsrv threads are left behind running, while their underlying objects
are being disposed by the main thread as part of the module
de-initialization.
Signed-off-by: Gabor Orosz <goro@goro.io>
closes #4776
> Terminate all tcpsrv threads properly

- contrib/imkmsg/kmsg.c
This is a patch for the issue reported in  #4395. 
kmsg is a unique device, which can recover from EPIPE errors. The code in the module checks for this, but the return value from the libc read call always returns -1, and sets the appropriate errno.
Before this patch, the code checks the return value of the read() call against -EPIPE, which never happens. 
This meant that when an EPIPE error actually happens, the fd  is set to -1 and indefinitely retried. rsyslog does not recover from this. Even though the `for` loop in `readikmsg` is broken out of, this function is repeatedly invoked in a `while` loop.
Note: there is an additional improvement possible - `readikmsg` needs better error checking on the fd. I suspect that this was rarely an issue because /dev/kmsg goes truly invalid when the …
> ikmsg: fix EPIPE error check in the /dev/kmsg reader loop

- tests/diag.sh
Newer versions seem to require some new defaults. Maybe this also
helps with some hard-to-explain flakiness in ES test runs.
> testbench: adjust ElasticSearch startup parameters

- plugins/omelasticsearch/omelasticsearch.c
- tests/es-bulk-retry.sh
When bulkmode is enabled, and a batch was processed without any
failures (errors is false), the code that increments the indexSuccess
impstats counter was never reached. As fix, we obtain the numitems
first and add them to the indexSuccess impstats counter if
errors is false.
This fix may solve some of the random elasticsearch testbench failures.
closes: https://github.com/rsyslog/rsyslog/issues/4794
> omelasticsearch: Fix indexSuccess impstats counter in bulkmode

- tests/imtcp-tls-ossl-basic-tlscommands.sh
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
Under io / cpu stress, the OpenSSL tls error can be SSL_ERROR_SYSCALL
instead of SSL_ERROR_SSL. The outcome it the same from the
test perspective.
closes: https://github.com/rsyslog/rsyslog/issues/4784
> testbench: adapt contentcheck for tlscommands tests

- .github/workflows/run_ubuntu_20_distcheck.yml
- tests/Makefile.am
The order of execution was changed to a less optimal (more startups, thus slower) order to work-around a testbench issue. This has been fixed and so we can restore the original order.
> testbench: restore original order of ES test execution

- configure.ac
- plugins/ompgsql/ompgsql.c
- runtime/syslogd-types.h
- tests/pgsql-basic-conninfo-vg.sh
Happy new years! Add another action parameter `conninfo` that allows specifying
a postgres connection string. This enables us to use any of the postgres connection
parameters, particularly `sslmode` and `sslrootcert`.
Per the postgres docs, this connection string can be a URI or several key-value
pairs. https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
Here's an example:
```
module(load="ompgsql")
action(
type="ompgsql"
conninfo="postgresql://postgres:password@localhost/Syslog?sslmode=require"
)
```
This addresses https://github.com/rsyslog/rsyslog/issues/4741 by allowing the
user to specify ssl options as part of the connection string. `libpq` will take
care of the rest.
This also addresses https://github.com/rsyslog/rsyslog/issues/4698 because
`libpq` is not …
> ompgsql: allow connection params via connection string

- action.c
- action.h
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/wti.c
The ```iActionNbr``` variable was used to obtain the total number of actions created during configuration load. The purpose of this PR is to make it part of the ```rsconf_t``` struct.
The functionality is not changed at all, but this change will play a crucial role when dynamic conf reload is introduced.
> Make action counter part of the config

- plugins/imfile/imfile.c
- tests/imfile-rename.sh
When any message is output into a renamed input file, rsyslogd output the following message.
imfile: internal error? inotify provided watch descriptor 7 which we could not find in our tables - ignored
When rsyslogd detects the inode change, it deletes the entry from wdmap[]. But, the watch descriptor is not removed.
Some application like sssd outputs some messages (like "HUP signal was received!!") after HUP signal is received and before switching into the new log file. And, the above messages can be output every log rotation. This commit resolves such a situation.
> imfile: Remove inotify watch descriptor on inode change detected

- grammar/rainerscript.c
In rscript, comparison operations on strings did not work correctly
and returned false results. This is cause by a regression in commit
5cec5dd634e0. While it fixed number comparisons, it introduced new
problems in string comparisons, which were not present before. Note
that most items in rsyslog are strings, so this can actually cause
some problems.
> regression fix: script string comparison did not work correctly

- runtime/glbl.c
The ```glblGetMaxLine()``` might be called even before the main configuration file exists resulting unexpected behavior, most probably segmentation fault. In order to address this problem, I suggest to bring back the old default.
> glblGetMaxLine() fix when config not yet exists, fixes #4810

- action.c
- action.h
- tests/Makefile.am
- tests/action-tx-errfile-maxsize.sh
- tests/diag.sh
- tests/omfwd-errfile-maxsize.sh
action.errorfile.maxsize has been added to enable
option to limit the amount of bytes dumped to
configured errorfile
fixes #4733
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
> Add option to limit error file to configured size

- plugins/imtcp/imtcp.c
- plugins/omelasticsearch/omelasticsearch.c
- runtime/lib_ksils12.c
- runtime/tcpsrv.c
- runtime/wti.c
- threads.c
When the pthread library fails, errno is referenced even though errno is not set.
Fix to refer to the return code of the pthread library instead of errno.
> Don't refer to errno when the pthread library fails

- action.c
- dirty.h
- runtime/queue.c
- runtime/queue.h
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/ruleset.c
- runtime/unicode-helper.h
- tests/runtime-dummy.c
- tools/rsyslogd.c
The intent of this PR is to make the main message queue part of the main config. It will help us to proceed towards dynamic configuration reload.
Besides that I did some refactoring. I divided ```activateMainQueue()``` into two separate functions. The first one, ```loadMainQueue()``` is responsible for interpreting main queue parameters, the second one ```activateMainQueue()``` will start the queue.
I had to move some settings from ```qqueueStart()``` to ```qqueueConstruct()```, because a queue should be fully initialized by the end of construction phase. This is needed in order to compare an already constructed(not yet started) queue with previous queues(queue from previous config that might be the same) during dynamic configuration reload.
> Make the main message queue part of the config

- runtime/parser.c
- runtime/parser.h
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/ruleset.c
- runtime/typedefs.h
The purpose of this PR is to make parser related lists part of the main configuration structure, ```rsconf_t```. Technically speaking, relocate the ```pParsLstRoot``` and ```pDfltParsLst``` global variables into the config.
Among other things, it helps to improve code readability, it's better to have everything in one place. Moreover, it will help us to proceed towards a new future, dynamic configuration reload option as we need to be able to track which parsers are defined in which config.
I needed to change/extend the ```parser``` interface structure as well to specify the parser list functions should work with.
> Move the parser directive to the main config

- contrib/omfile-hardened/omfile-hardened.c
Include of the ```rsconf.h``` header file was missing. The PR resolves that.
Resolves #4827
> Add missing include to fix compilation error, resolves #4827

- tools/rsyslogd.c
After call doHUP(), probably there is a internal log in the list. However, it
will not be wrote out immediately, because the mainloop will be blocked at
pselect in wait_timeout() until a long timeout or next message occur.
More deadly, the log may be lost if the deamon exits unexpectedly.
We might as well put processImInternal() after doHUP(), so that the message
will be flushed out immediately.
Fixes: 723f6fdfa6(rsyslogd: Fix race between signals and main loop timeout)
Signed-off-by: Yun Zhou <yun.zhou@windriver.com>
> rsyslogd: adjust the order of doHUP() and processImInternal()

- .github/workflows/run_ubuntu_18_gtls_only.yml
This makes things a bit more reliable and save us much-needed time
as we want to minimize our maintenance of the docker farm.
> CI: move docker worker to github action

- action.c
Fix getting a lot of messages like:
```
Mar 15 02:56:10 myhost.local rsyslogd[47117]: action 'relp_to_prog' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension. [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2007 ]
```
even when disable `action.reportSuspension` and `action.reportSuspensionContinuation` in config file.
Config file: `/etc/rsyslog.d/rsyslog-pipe.conf`
```
template (name="PipeOut" type="string"
string="%timegenerated:::date-unixtimestamp%|%source%|%programname%|%syslogtag%|%msg%|%syslogfacility-text%|%syslogseverity-text%\n"
)
if ( not ($hostname == $$myhostname and $programname == "my-program" and $msg startswith "[") ) then {
action(
name="pipe_to_prog"
type="ompipe"
Pipe="/var/run/my-program.pipe" …
```
> Fix: check ReportSuspension option before print message about action retry

- runtime/rsconf.c
The default JSON template does not include the programname.
This makes it difficult to know which program wrote which log entry.
> Include programname in a new JSON template

- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/nsdsel_gtls.c
- runtime/tcpsrv.c
- tests/imtcp-tls-basic.sh
There was a rare possibility that the E_AGAIN/E_INTERRUPT handling
could cause an infinite loop (100% CPU Usage), for example when a TLS
handshake is interrupted at a certain stage.
- After gnutls_record_recv is called, and E_AGAIN/E_INTERRUPT error
occurs, we need to do additional read/write direction handling
with gnutls_record_get_direction.
- After the second call of gnutls_record_recv (Expand buffer)
we needed to also check the eror codes for E_AGAIN/E_INTERRUPT
to do propper errorhandling.
see also: https://github.com/rsyslog/rsyslog/issues/4818
> gnutls bugfix: Fix error handling in gtlsRecordRecv

- action.c
- action.h
- tests/Makefile.am
- tests/errfile-basic.sh
- tests/omfwd-errfile-maxsize-filled.sh
- tests/testbench_test_failed_rsyslog
fixes #4821
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
> Ensure error file does not increase appropriately when action.errorfile.maxsize option is enabled

- plugins/omkafka/omkafka.c
The `failedmsg_entry` expects a null-terminated string in `key`, but
here we allocate with malloc and copy a string-with-length-n into only
the first n bytes. If the final byte is null, this is by coincidence
only.
We've observed this by means of seeing random binary data appended to
keys submitted to kafka apparently at random, and this looks like a
smoking gun.
> Fix non-null-terminated-string used with strlen

- plugins/mmdblookup/mmdblookup.c
- [MMDBLOOKUP] wrong copy of buffer following parse of libmaxminddb's return after a successful search sometimes failed to return specific field from data
- [MMDBLOOKUP] support arrays in MMDB entry
- [MMDBLOOKUP] support escaped quotes '"' in MMDB entry
- [MMDBLOOKUP] support '<' characters in MMDB entry, when in a field
- [MMDBLOOKUP] support '}' characters in MMDB entry, when in a field
> MMDBLOOKUP::FIXED:: Fix parsing of data received from mmdb lib

- runtime/tcpsrv.c
nfds should only be decreased for processed streams and not for
streams returning an error code, like RS_RET_RETRY.
> tcpsrv: do not decrease number of to be processed fds on error

- tests/Makefile.am
This leads to test failures e.g. with LLVM sanitizers.
> testbench bugfix: some valgrind tests were run when valgrind disabled

- plugins/imptcp/imptcp.c
> imptcp bugfix: worker thread starvation on extreme traffic

- plugins/omelasticsearch/omelasticsearch.c
- tests/Makefile.am
- tests/diag.sh
- tests/es-basic-es7.0.sh
- tests/es-searchType-empty.sh
Fixes #4387
This patch allows you to explicitly set searchType="", which causes it to be omitted from the JSON request as well as the bulk API url.
I didn't yet test with an actual Elasticsearch server, but testing with just dumping POST requests onto stdout with a custom template, I can't see immediate problems with the output
in bulk mode:
```
{"index":{"_index": "rsyslog-write-default"}}
{"message":"test","fromhost":"localhost","facility":"user","priority":"notice","timereported":"2021-04-06T21:47:38.739697+03:00","timegenerated":"2021-04-06T21:47:38.739815+03:00"}
```
vector tells me the path is `/_bulk`
and in non-bulk mode the path is `/rsyslog-write-default` and the message does not change
Omitting the parameter restores the default behaviour:
```
{"index":{"_index": …
```
> omelastisearch: allow omitting deprecated _type field

- plugins/ommongodb/ommongodb.c
- runtime/rsyslog.h
- tests/diag.sh
- tools/logctl.c
> build error fix: libbson requires out-of-date language constructs

- plugins/imptcp/imptcp.c
- tests/tsan-rt.supp
We do not use a mutex an epd, but we do always access it in
pure sequence. Adding a mutex just to cover this "cosmetic"
would result in uncesseary performance penalty.
> CI: suppress TSAN exception for known-good case

- runtime/stream.c
This error message is most probably rooted in a kernel problem. At
least knowbody knows how it can happen. It's definitely not a
rsyslog issue. We also can recover from it for a long time now
so there is no reason to irritate users by emitteing this
"error" message.
> stream cleanup: move error message to debug log, only

- .github/workflows/run_checks.yml
- drop Fedora 34, add Fedora 36
> CI: further modernizations

- tests/tsan-rt.supp
This is a cosmetic issue, only seen during debug logging. We actually
cannot fix it, as it would alter runtime behaviour too much and would
pontentially render debug runs useless. It also causes no harm.
> CI: add new TSAN suppression

- .github/workflows/run_checks.yml
- .github/workflows/run_journal.yml
- configure.ac
- runtime/Makefile.am
- runtime/stream.c
- runtime/stream.h
- runtime/zlibw.c
- runtime/zstdw.c
- runtime/zstdw.h
- tests/Makefile.am
- tests/diag.sh
- tests/zstd-vg.sh
- tests/zstd.sh
- tools/omfile.c
The zstd library provides better and faster compression than zlib.
This patch integrates zstd as a dynamically-loadable functionality.
As such, no further dependencies need to be added to the rsyslog
base package.
Due to the increased performance, usage of zstd is highly recommended
for high-volume use cases.
> omfile: support for zstd compression

- action.c
During free action worker data table when action destruct, worker instance in worker data table were not null. It resulted in memory leak and this patch fixes this behaviour.
The problem is mentioned here:
https://github.com/rsyslog/rsyslog/issues/4938
> Fix memory leak when free action worker data table

- runtime/nsd_gtls.c
During globally de-initialize GnuTLS, server anon credentials and server DH parameters for anon mode were not null. It resulted in memory leak and this patch fixes this behaviour.
The problem is mentioned here:
https://github.com/rsyslog/rsyslog/issues/4913
> Fix memory leak when globally de-initialize GnuTLS

- plugins/imptcp/imptcp.c
- tests/imptcp_multi_line.sh
- reduce indirect addressing to obtain more speed
- also a fix for an annoying typo
- minor other optimizations
- modernization of one test
> imptcp: slight tuning

- plugins/mmanon/mmanon.c
- tests/Makefile.am
- tests/mmanon_recognize_ipv4.sh
- tests/mmanon_simple_mallformed_ipv4.sh
- Fixed an issue with numbers above int64 in syntax_ipv4.
Numbers that were up to 256 above the max of an int64
could incorrectly be detected as valid ipv4 digit.
- Simplified the IPv4 digit detection function and renamed
to isPosByte.
- added testcasse for malformed IPvc4 addresses
closes: https://github.com/rsyslog/rsyslog/issues/4940
> mmanon: Simplified and fixed IPv4 digit detection.

- plugins/omclickhouse/omclickhouse.c
- DB::NetException
- DB::ParsingExceptions
Signed-off-by: Victor Kustov <ktrace@yandex.ru>
> omclickhouse: capture additional exceptions

- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
closes: https://github.com/rsyslog/rsyslog/issues/4946
> openssl: add more details to LogError in osslLastSSLErrorMsg

- runtime/nsd_ossl.c
- tests/tcpflood.c
We recently enabled OpenSSL stream driver on Solaris and hit two build issues where the `index()` function was missing its header. This simple PR fixes that issue.
> strings.h is missing in several files

- runtime/nsd_ossl.c
- tests/sndrcv_tls_ossl_anon_ciphers.sh
- Add support to split tls commands by semicolon.
- Changed one test with multiple tls commands to use semicolon as
seperator instead of newline.
- Output used TLS Version into debug log.
closes: https://github.com/rsyslog/rsyslog/issues/4852
> openssl: Add support to split tls commands by semicolon

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
- runtime/lmsig_ksi-ls12.c
KSI module in async mode used to request aggregator conf. every time a log
file was opened. When several log files were opened simultaneously
corresponding amount of pointless concurrent conf. requests were posted.
Concurrent conf. requests lead to a bug in libksi, where internal count of
pending requests was not decremented correctly causing system to crash.
Fix for the issue is to optimize the frequency of conf. requests so that only
one conf. requests is handled at once. Instead of checking conf. every time
log file is opened, conf is requested periodically after conf timeout. This will
affect both sync and async mode.
New option for KSI module introduced - sig.confinterval="time, s".
> ksi bugfix: possible crash fixed when several log files are opened

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
There is a worker queue where rsyslog KSI module collects events and signing
requests. When queue is processed thread is periodically put to sleep. Previous
implementation handles signature requests well but sleeps every time after
handling new file open / close event. When several log files are opened or
closed simultaneously process is significantly slowed down. Another issue is
that thread always sleeps 1000ms that may be 2x longer than aggregation round.
This slows down overall signing process.
Fix for the issue is to simply not sleep after file open / close event if there
are next items to be processed. To speed up the signing process, rsyslog uses
KSI aggregator conf. to obtain the aggregation period that is used for the sleep
time configuration.
> ksi bugfix: optimize processing of signer queue to fix redundant delays.

- plugins/imfile/imfile.c
- runtime/stream.c
- runtime/stream.h
- tests/Makefile.am
- tests/imfile-logrotate-async.sh
- tests/inputfilegen.c
A cleaned-up version of https://github.com/rsyslog/rsyslog/pull/4886, where 4886 will finally only contain the new testbench code.
When a to-be-monitored file is being rotated, some messages may be lost or
duplicated. In case of duplication, many file lines may be duplicated
depending on actual timing. The whole bug was primarily timing depenedent
in general. It most often was visible in practice when the monitored
file was very frequently rotated (we had some report with every few
seconds).
Note that while we try hard to not lose any messages, input file
rotation always has some loss potential. This is inevitable if
the monitored file is being truncated.
Also note that this bugfix affects imfile, only. It has nothing to do
and no relation to rsyslog output files being rotated on HUP. …
> imfile bugfix: message loss/duplication when monitored file is rotated

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
- runtime/lmsig_ksi-ls12.c
Async service send timeout is not configurable and request cache size is too
small to handle large amount of signing requests with small amount of permitted
requests per aggregation round. For example user with max_requests = 4 results
cache size 5 * max_requests or at least 256. When signing 300 log files cache
will be too small resulting several unsigned blocks. When signing 200 log file
cache will be adequate, but with rate of 4 signatures per second, it is only
possible to sign 4 * 10 blocks before all requests that are not sent out will
timeout.
Fix for the issue is to make send timeout configurable and make the size of the
cache depend on the value of send timeout. New configuration value
sig.block.signtimeout="time, s" introduced that defines the time window wherein
the block has …
> ksi bugfix: request cache size and send timeout issue fixed.

- plugins/imjournal/imjournal.c
In imjournal module, we destruct ratelimiter after closing journal. But, we should check ratelimiter is NULL or not.
Fix: #4953
> Fix Segmentation fault in close journal

- runtime/rsyslog.h
Commit 829a6f6 "CI: improve use of github action matrix feature;
optimization" has introduced use of #pragma GCC diagnostic in function
doNameLine() of runtime/conf.c. This is not supported by old compilers
like GCC 4.4.7 on el6.
> conf: Fix #pragma GCC diagnostic not allowed inside functions

- runtime/nsd_ossl.c
added due missing rebase in PR #4889
> openssl: fix osslLastSSLErrorMsg call

- runtime/tcpsrv.c
> tcpsrv: cleanup - remove commented out code

- plugins/imtcp/imtcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/allowed-sender-tcp-fail.sh
- tests/allowed-sender-tcp-hostname-fail.sh
- tests/imtcp-connection-msg-recieved.sh
Add this both as module an input parameter. Complements already-existing
config param notifyonconnectionclose and mirrors the similar feature from
imptcp.
The module parameter acts as default, similarly to notifyonconnectionclose.
Note that in contrast to imptcp, we emit IP addresses and not host
names. This sticks with the traditional semantics of imtcp.
Thanks to John Chivian for suggesting the addition.
> imtcp: add option notifyonconnectionopen

- tests/Makefile.am
- tests/diag.sh
- tests/sndrcv_relp-vg-rcvr.sh
- tests/sndrcv_relp-vg-sender.sh
- These tests will help find race conditions hopefully
- fix diag.sh issues running second instance in valgrind mode only
> testbench: Add more valgrind tests for sndrcv (omrelp/imrelp)

- runtime/prop.c
During SetString reassign to pThis->szVal.psz, pThis->szVal.psz might not null. It resulted in memory leak and this patch fixes this behaviour.
The problem is mentioned here:
https://github.com/rsyslog/rsyslog/issues/4961
> Fix memory leak when SetString reassign to pThis->szVal.psz

- action.c
- runtime/glbl.c
- runtime/rsconf.c
- runtime/rsconf.h
- tools/rsyslogd.c
similiar to "abortONUncleanConfig", this parameter aborts rsyslog
when a queue has problems during startup. Some users perfer rsyslog
to terminate in this case. By default, nothing changes.
closes https://github.com/rsyslog/rsyslog/issues/4902
> config: add "abortOnFailedQueueStartup" global config parameter

- m4/atomic_operations.m4
On NetBSD, time_t has for a long time now been __int64_t. On 32-bit CPUs, the compiler is not obliged to define __sync_bool_compare_and_swap_8, so instead this ends up as an undefined symbol when linking rsyslog.  This fix makes rsyslog fall back to the pthread / locking method on these systems, but at least lets the program build.
> atomic_operations.m4: also test these ops on time_t

- runtime/glbl.c
The local hostname is invalidly set to "[localhost]" on rsyslog startup if no global() config object is present in rsyslog.conf. Sending a HUP corrects the hostname.
This is a regression from ba00a9f25293f
closes https://github.com/rsyslog/rsyslog/issues/4975, https://github.com/rsyslog/rsyslog/issues/4825
> core bugfix: local hostname invalid if no global() config object given

- plugins/imjournal/imjournal.c
If SYSLOG_IDENTIFIER is not present in the journal message, then lookup the _COMM field, which stands for the name of the process the journal entry originates from [1]. This is needed in order to be in compliance with the journalctl output.
When I look at the journalctl output and compare it with the one produced by the imjournal module, the identifier is sometimes different. After doing some digging I found out that systemd-journal has an additional fallback(_COMM) when SYSLOG_IDENTIFIER is not specified.
[1] SYSTEMD.JOURNAL-FIELDS(7):
```
_COMM=, _EXE=, _CMDLINE=
The name, the executable path, and the command line of the process the journal entry originates from.
```
Example:
- systemd: ```Sep 22 08:02:42 localhost gnome-shell[2202]: Adding device '/dev/dri/card0' (i915) using atomic …
```
> imjournal: add second fallback to the message identifier

- runtime/lib_ksils12.c
- runtime/lib_ksils12.h
As there is a bug in libksi where too many signing requests may have bene sent out the amount of signing requests will be limited by KSI module until the fix is implemented.
> ksi bugfix: sending of too many signing requests fixed.

- plugins/omkafka/Makefile.am
Because of changes in commit https://github.com/rsyslog/rsyslog/commit/7305c047dbb766e288ab83300d314ab324bd01c4, the kafka modules were not build with static librdkafka regarding of --enable-kafka-static.
Also added missing libraries needed for building with newer static librdkafka.
closes: https://github.com/rsyslog/rsyslog/issues/5025
> kafka: fix building modules with static librdkafka

- tools/rsyslog.conf.5
Note historic difference to BSD syslog selectors.
> rsyslog.conf man page bugfix: description of selectors

- tests/diag.sh
- tests/sndrcv.sh
- tests/sndrcv_failover.sh
- tests/sndrcv_gzip.sh
- tests/sndrcv_kafka-vg-rcvr.sh
- tests/sndrcv_kafka_fail.sh
- tests/sndrcv_kafka_failresume.sh
- tests/sndrcv_relp_dflt_pt.sh
- tests/sndrcv_relp_rebind.sh
- tests/sndrcv_relp_tls.sh
- tests/sndrcv_relp_tls_certvalid.sh
- tests/sndrcv_relp_tls_prio.sh
- tests/sndrcv_tls_anon_hostname.sh
- tests/sndrcv_tls_anon_ipv4.sh
- tests/sndrcv_tls_anon_ipv6.sh
- tests/sndrcv_tls_certvalid.sh
- tests/sndrcv_tls_certvalid_expired.sh
- tests/sndrcv_tls_certvalid_expired_defaultmode.sh
- tests/sndrcv_tls_gtls_serveranon_gtls_clientanon.sh
- tests/sndrcv_tls_gtls_servercert_gtls_clientanon.sh
- tests/sndrcv_tls_ossl_anon_ipv4.sh
- tests/sndrcv_tls_ossl_anon_rebind.sh
- tests/sndrcv_tls_ossl_certvalid_expired.sh
- tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
- tests/sndrcv_udp_nonstdpt.sh
Somehow #4473, was closed when pushing the changes to the original PR. So I continue here with it. Thanks to @VincentZhu007 for the original patch.
In some client-server test cases, messages are supposed to be injected into the instance 2(client), but they are actually injected into instance 1(server), which may lead to false negative results. This patch fixed it by replacing 'injectmsg' with 'injectmsg2', and dealt with some minor issues.
> testbench: fix the wrong message injection object of instance 1

- plugins/omprog/omprog.c
There is a bug when external program *startup* does not return "OK". This can also lead to a misadressing with potentially a segfault (very unlikely). Note that no problem exists once the initializiation phase of the external program is finished and regular message transfer runs.
The problem basically is that for a startup failure, the control data for that external program instance is freed on error. Unfortunately, that state data is needed later on to detect a suspended instance. We now keep the control data even on init failure (as we then need to do normal control options).
closes https://github.com/rsyslog/rsyslog/issues/4967
> omprog bugfix: invalid status handling at called program startup

- tests/diag.sh
- tests/errfile-basic.sh
- tests/omhttp-auth.sh
- tests/omhttp-basic.sh
- tests/omhttp-batch-dynrestpath.sh
- tests/omhttp-batch-fail-with-400.sh
- tests/omhttp-batch-jsonarray-compress.sh
- tests/omhttp-batch-jsonarray-retry.sh
- tests/omhttp-batch-jsonarray.sh
- tests/omhttp-batch-kafkarest-retry.sh
- tests/omhttp-batch-kafkarest.sh
- tests/omhttp-batch-lokirest-retry.sh
- tests/omhttp-batch-lokirest.sh
- tests/omhttp-batch-newline.sh
- tests/omhttp-dynrestpath.sh
- tests/omhttp-httpheaderkey.sh
- tests/omhttp-multiplehttpheaders.sh
- tests/omhttp-retry.sh
- tests/omhttp_server.py
Harden them against races during server port assignment. Prevents testbench flakes.
> testbench: make python http server based tests more reliable

- tools/rsyslog.conf.5
I: rsyslog: typo-in-manual-page explicitely explicitly [usr/share/man/man5/rsyslog.conf.5.gz:225]
I: rsyslog: typo-in-manual-page sevrity severity [usr/share/man/man5/rsyslog.conf.5.gz:223]
> Fix typos spotted by lintian

- template.c
- tests/Makefile.am
- tests/json-onempty-at-end.sh
When
- a list template
- is created with option.jsonf="on"
- and the last list element is a property with onEmpty="skip"
- and that property is actually empty invalid JSON is generated.
The JSON string in this case ends with ", " instead of "}\n". This patch fixes the issue.
closes https://github.com/rsyslog/rsyslog/issues/5050
> core bugfix: template system may generate invalid json

- tests/diag.sh
The older one is no longer available.
> CI: use newer version of zookeeper

- configure.ac
> fix version number for next scheduled stable release

- runtime/nsd_ossl.c
Fix undefined reference for OpenSSL 1.1 or higher.
> openssl: fix undefined reference to CRYPTO_set_id_callback

- grammar/rainerscript.c
- tests/Makefile.am
- tests/func-substring-invld-startpos-vg.sh
- tests/func-substring-invld-startpos.sh
- tests/func-substring-large-endpos.sh
- tests/func-substring-large-neg-endpos.sh
- tests/func-substring-relative-endpos.sh
Now, length can have a negative value -n to denote that the substring should be build between startpos and the character -n chars from the end. This is a shortcut for stripping charactes on "both ends" of the string.
Also, some hardening against invalid startpos and length has been added.
> substring function: enhancement and hardening

- runtime/stringbuf.h
Segfaults can happen when getting the message length with cstrLen().
```
Core was generated by `/usr/sbin/rsyslogd -n'.
Program terminated with signal 11, Segmentation fault.
#0  __memcpy_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1578
1578            movdqu  -16(%rsi), %xmm0
(gdb) bt 
#0  __memcpy_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1578
#1  0x0000555b5dd293b4 in memcpy (__len=<optimized out>, __src=0x2afbf0000010, __dest=<optimized out>) at /usr/include/bits/string3.h:51
#2  MsgSetRawMsg (pThis=0x2afbe00346e0, pszRawMsg=0x2afbf0000010 "", lenMsg=lenMsg@entry=18446744072548766868) at msg.c:2884
#3  0x00002afbcb8c35f8 in enqLine (strtOffs=<optimized out>, cstrLine=0x2afbe00346c0, act=0x2afbe0032350) at imfile.c:1182
#4  pollFileReal …
```
> Fixed wrong type conversion in cstrLen()

- parse.h
- runtime/stream.c
- runtime/stringbuf.c
- runtime/stringbuf.h
Apply the type conversion correction added by PR
https://github.com/rsyslog/rsyslog/pull/5051 to both definitions of cstrLen().
Changed types from int to size_t in multiple occurrences (where cstrLen is used).
closes: https://github.com/rsyslog/rsyslog/issues/5073
> Fixed wrong type conversion in cstrLen() for debug mode as well

- runtime/msg.c
- template.c
- tests/Makefile.am
- tests/template-topos-neg.sh
This will easily permit to drop the last n characters from a property without the need to know the exact length of the string. This is especially useful as the exact length is most often not known beforehand.
> core/template: implement negative position.to

- README.md
See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/.
> Remove halted LGTM badges on README

- plugins/imptcp/imptcp.c
- tests/imptcp-oversize-message-display.sh
If an oversize message was received by imptcp, imptcp reported one error message for EACH oversize character. This could result in a potentially very large number of similar (and useless) messages.
This is a regression from commit f052717178.
closes https://github.com/rsyslog/rsyslog/issues/5078
> imptcp bugfix: spam log on oversize message

- .github/workflows/ci_compile.yml
- .github/workflows/run_kafka_distcheck.yml
This is just the "host" for containers, so no big deal. Looks like Ubuntu 18.04 is no longer supported by github, at least all actions hang in "queued" status without proceeding.
> CI: update base ubuntu image for github actions

- runtime/glbl.c
- runtime/rsconf.c
- runtime/rsconf.h
- tools/rsyslogd.c
The new global option defines how rsyslog should behave in case something went wrong when capabilities were to be dropped. Default value is "on", in which case rsyslog exits on a libcapng related error. If set to "off", an error message describing the problem appears at startup, nothing more. Default value is preserved for backwards compatibility.
The capability dropping had to be moved to a different place, where config parameters are already available.
Closes #5096
> Add new global config option "libcapng.default"

- runtime/msg.c
This was discovered by Konstantin J. Chernov in a practicaly deployment. Here, msg object tag processing caused sporadic segfaults. We did not hear from similiar cases, but there clearly is potential for problems because a mutex lock had insufficient range, thus leading to a potential race.
The patch is directly from Konstantin J. Chernov, thanks for that.
Please note that the mutex lock could be minimized as it is not strictly needed for the pM == NULL case, but this cause is extremely exotic and the resulting code would be harder to understand. Thus we opt to do the locking on funtion level (as usual).
Descriptiond edited by Rainer Gerhards
closes: https://github.com/rsyslog/rsyslog/issues/5110
> core bugfix: potential segfault on busy systems

- .github/workflows/run_journal.yml
- plugins/imjournal/imjournal.c
- tests/imjournal_filecreatemode.sh
The parameter allows to set the default file mode bits when creating new files by the module. As of now, it has only impact on the state file. Other modules that create files such as omfile, imptcp, omprog provide a similar parameter.
If accepted, I can prepare a PR in rsyslog-doc to include it in the documentation part as well.
What do you think?
[UPDATE]
I've set the default permission of the state file to 0644 to provide the same results as we currently have but personally I would limit it to 0600. I appreciate the feedback :)
> imjournal: Add FileCreateMode module parameter

- tests/mmexternal-SegFault-empty-jroot-vg.sh
Fix the typo that makes the test fail.
> tests: mmexternal-SegFault-empty-jroot-vg.sh: fix typo

- tests/diag.sh
> testbench: use newer zookeeper version in tests

- contrib/imhiredis/imhiredis.c
RESP3 protocol wasn't implemented yet, some types weren't available (REDIS_REPLY_DOUBLE)
> IMHIREDIS::FIXED:: Restore compatiblity with hiredis < v1.0.0

- action.c
Unfortunately, defining ```action.resumeintervalmax``` in the configuration did not have any effect at all. Instead, the default value was used, which is ```1800```. This was caused by not having all the letters in lower-case. Fixes #5132
If you start rsyslog with debug enabled, you can see that the parameter was detected correctly:
```
6038.749939940:main thread    : rainerscript.c: action.resumeintervalmax: 10
6038.749947294:main thread    : rainerscript.c: action.resumeinterval: 10
```
But it was not respected when it was assigned to internal variables:
```
6038.750271326:main thread    : ../action.c: Module builtin:omfwd processes this action.
6038.750275355:main thread    : ../action.c: action: program error, non-handled param 'action.resumeintervalmax'
```
I was not expecting this …
> action.resumeintervalmax: the parameter was not respected

- .gitignore
- Makefile.am
- configure.ac
- plugins/omazureeventhubs/Makefile.am
- plugins/omazureeventhubs/omazureeventhubs.c
- tests/Makefile.am
- tests/omazureeventhubs-basic-vg.sh
- tests/omazureeventhubs-basic.sh
- tests/omazureeventhubs-list.sh
- tests/omazureeventhubs-stress.sh
- tests/omazureeventhubs.supp
omazureeventhubs output module uses Apache "Qpid Proton C API" which is a solid
AMQP protocol library implementation that can be integrated
very well into the rsyslog dev environment.
- Implemented Delivery with submitted and accepted state checking
- impstatscounter used in testcases
- saving of failed messages in a failed list with support of saving
and restoring.
- Add testcases (requires ENV variables) to testbench
- Using application/octect-stream (binary) to send messages based on
Microsoft Code Sample:
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-c-getstarted-send
* Note original Microsoft Samplecode is not working anymore, we are using
* QPID Proton Proactor based on
https://github.com/apache/qpid-proton/blob/main/c/examples/send.c
- requires QPID-PROTON Version …
> omazureeventhubs: Initial implementation of new output module

- runtime/nsd_ossl.c
- tests/tcpflood.c
See reference from: https://wiki.openssl.org/index.php/Library_Initialization
closes: https://github.com/rsyslog/rsyslog/issues/4981
> ossl driver: Using newer INIT API for OpenSSL 1.1+ Versions

- configure.ac
- parse.c
- parse.h
- runtime/Makefile.am
- runtime/conf.c
This option is mostly useless, as network functionality depends on the modules loaded by the config. The only real, and important, effect it has is to control auto-load of omfwd - a feature almost all installations depend in (backward compatibility).
This has been clarified in ./configure -help
Also, when --disable-inet is given, rsyslog now executes successfully. The reason for the abort was that previously building of the lmnet component was prevented, but that component is also needed by rsyslog startup itself to query its own (correct) hostname.
closes https://github.com/rsyslog/rsyslog/issues/5188
> build system: make rsyslogd execute when --disable-inet is configured

- dirty.h
- plugins/imdiag/imdiag.c
- tests/diag.sh
- tools/rsyslogd.c
The previous approach was more or less delay based. We have now changed the code to enable imdiag to detect if HUP is underway and wait until it is completed. The new method still employs some kind of timeout, but is now quite reliable. Most importantly, it works great with long-running HUP processing, which can happen e.g. when querying the system name takes long or some actions need longer time to persist their HUP processing.
The new approach will most likely reduce CI flakes and also speed up testbench runs. The speedup happens from not having to wait a full delay in cases where we detect HUP is completed (plus reduced timeout when we cannot clearly detect this - see code comments why the new method is still considered more reliable than the old one).
closes …
> testbench: make waiting for HUP processing more reliable

- runtime/nsd_ossl.c
- runtime/nsdsel_ptcp.c
- tests/tcpflood.c
In OpenSSL 1.1.0 and higher, SSLv23_method causes some errors
in TLS handshake from time to time. As this method is depreceated
since 1.1.0, I have replaced it with the follow up method
TLS_method which is the most generic one.
It fixes the random test failures in tests like
- sndrcv_tls_ossl_anon_rebind.sh
Also added some debug output in OpenSSL error handling, which is
useful when analysing debug files.
closes: https://github.com/rsyslog/rsyslog/issues/5201
> openssl: Replaced depreceated method SSLv23_method with TLS_method

- tests/imptcp_maxsessions.sh
- tests/tcpflood.c
Enhancements to tcpflood plus test changes. For details see individual commits.
> Make imptcp_maxsessions test (much more) reliable

- runtime/lookup.c
- runtime/lookup.h
- runtime/rsconf.c
- tests/Makefile.am
- tests/diag.sh
- tests/lookup_table-hup-backgrounded.sh
- tools/rsyslogd.c
Lookup tables were only reloaded on HUP if the -n option was given and rsyslog no backgrounded. This patch fixes the issue.
closes: https://github.com/rsyslog/rsyslog/issues/4813
> lookup tables bugfix: reload on HUP did not work when backgrounded

- runtime/libgcry.c
This commit clear some undefined behavior in libgcry.c. When testing with Undefined Behavior sanitizer, it led to 5 failed self tests.
> Clear undefined behavior in libgcry.c (GH #5167)

- tests/tcpflood.c
The error code when plain tcp sending failed was improperly returned, resulting in no meaningful error message.
Note: tcpflood is a testbench tool, not part of production rsyslog.
> tcpflood bugfix: plain tcp send error not properly reported

- tools/rsyslogd.c
The ```omprog``` module uses the ```execve()``` function to execute a third party program. 
Some required capabilities were not preserved in the bounding set [1]. This caused problems, e.g. the program could not write to files even if rsyslog was executed as root and privileges were not dropped (default behavior).
As of now, only the ```CAP_DAC_OVERRIDE``` capability is added to the bounding set. Others could be added later, if there is justification behind that.
```
[1] The capability bounding set is a security mechanism that
can be used to limit the capabilities that can be gained
during an execve(2). During an execve, the capability
bounding set is ANDed with the file permitted capability
set, and the result of this operation is assigned to the
thread's  permitted  capability  set. The …
```
> omprog bugfix: Add CAP_DAC_OVERRIDE to the bounding set

- plugins/imrelp/imrelp.c
While existing, if at specific time rsyslog receives a SIGTTIN, it crashes due to 2 issues.
1. debug.unloadModules="off" a double free of pRelpEngine
2. debug.unloadModules="on" it crashes because the signal handler has been unmapped from memory.
This patch covers both issues and fixes #5219.
> Avoid crash on restart in imrelp SIGTTIN handler

- runtime/nsdsel_ptcp.c
It may happen that a socket file descriptor has been closed either while setting up poll() et al or while being inside the system call. This was previously treated as error and caused abort in debug builds. However, it was essentially ignored in production builds.
This has now been fixed and now is always gracefully ignored. This most importantly fixes some flakes in CI runs (which were caused by this situation).
> tcp net subsystem: handle data race gracefully

- runtime/glbl.c
- runtime/rsconf.c
- runtime/rsconf.h
- tools/rsyslogd.c
Defines whether rsyslog should drop capabilities at startup or not. By default, it is set to "on". Until this point, if the project was compiled with ```--enable-libcap-ng``` option, capabilities were automatically dropped. This is configurable now.
> Add new global config option "libcapng.enable"

- tests/diag.sh
Older version can no longer be downloaded. It also makes sense to test with mainstream version.
> testbench: bump zookeeper version to match current offering

- Makefile.am
- configure.ac
This is a clean up following the removal of the service unit in cfd07503ba055100a84d75d1a78a5c6cceb9fdab
> Remove no longer used --with-systemdsystemunitdir configure switch

- tools/omusrmsg.c
Future SUSE versions will get rid of utmp due to a 32bit time_t counter overflow in 2038.
See details at:
https://github.com/thkukuk/utmpx/blob/main/Y2038.md
On systemd based systems logind is an alternative to utmp.
> use logind instead of utmp for wall messages with systemd

- plugins/imjournal/imjournal.c
Allow us to bind the imjournal input to an output module. Thie enable us to block journal reading if the output module is failing. Note that we will only allow one input module for imjournal since we do not have multiple input sources. The memory usage can be high with multiple outputs.
The input module support the `main` argument to select the config to use in the main thread and will be stop stopped if the output source is not accepting data. Other rules in the background will continue.
Tested:
Example Config:
```
template(name="journal-format" type="string"
string="%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag% %msg%\n"
)
ruleset(name="remote" queue.type="direct"){
action(
type="omfwd"
target="IP_ADDRESS"
port="PORT"
protocol="tcp"
template="journal-format"
StreamDriver="ossl" …
```
> imjournal: Support input module

- plugins/imklog/bsd.c
- plugins/imklog/imklog.c
... at least not as expected. It was only honored for kernel-level messages and only when parseKernelTimestamp was "on". Otherwise, the kernel timestamp was always kept inside the message.
closes https://github.com/rsyslog/rsyslog/issues/5160
> imklog bugfix: keepKernelTimestamp=off config param did not work

- plugins/imfile/imfile.c
The state file would remain in the working directory after shutdown, even though deleteStateOnfileDelete is set to "on" and the monitored file was removed. In case there was no other `inotify` event created that would trigger `detect_updates()`, the state file would remain in the system and would contain false information about a to be monitored file.
Fixes: #5258
> imfile: remove state file on file delete fix

- contrib/imkmsg/imkmsg.c
- contrib/imkmsg/imkmsg.h
- contrib/imkmsg/kmsg.c
These parameters permit to control when imkmsg reads the full kernel log upon startup.
Parameter "readMode" provides the following options:
* full-boot - (default) read full klog, but only "immediately" after boot. "Immediately" is hereby meant in seconds of system uptime given in "expectedBootCompleteSeconds"
* full-always - read full klog on every rsyslog startup. Most probably causes messag duplication
* new-only - never emit existing kernel log message, read only new ones.
Note that some message loss can happen if rsyslog is stopped in "full-boot" and "new-only" read mode. The longer rsyslog is inactive, the higher the message loss probability and potential number of messages lost. For typical restart scenarios, this should be minimal. On HUP, no message loss occurs as rsyslog is not …
> imkmsg: add params "readMode" and "expectedBootCompleteSeconds"

- plugins/omazureeventhubs/omazureeventhubs.c
- tests/Makefile.am
- tests/diag.sh
- tests/omazureeventhubs-interrupt-vg.sh
- tests/omazureeventhubs-interrupt.sh
- Added test for connection interrupts (requires root)
- Corrected handling of PN_TRANSPORT_CLOSED.
- Make sure Connection is being reestablished trough tryResume
- Enhanced Debug log output
closes: https://github.com/rsyslog/rsyslog/issues/5269
> omazureeventhubs: Corrected handling of transport closed failures

- runtime/glbl.c
- runtime/net.c
- runtime/net.h
- runtime/rsconf.h
- runtime/rsyslog.h
- tools/rsyslogd.c
Even if hostname FQDN is configured, rsyslog internal messages generated after rsyslog startup and before the first HUP will not necessarily have FQDN but instead only the shortname of the local host. This commit fixes the situation.
Special thanks to github user eciii for doing a great bug analysis and helping us considerably to fix the issue.
closes https://github.com/rsyslog/rsyslog/issues/5218
> core bugfix: rsyslog messages may not always have FQDN

- tests/es-execOnlyWhenPreviousSuspended.sh
executed more code than intended
> testbench: fix "typo" in test case

- plugins/imgssapi/imgssapi.c
The declaration and the implementation must use the same return type to avoid an error -Werror=enum-int-mismatch.
> plugins: fix return type of TCPSessGSSRecv()

- plugins/ommysql/ommysql.c
Due to an invalid code path, ommysql may cause a segfault if database transactions fail into a specific way. The main trigger is a totally irrecoverrable database error which can lead to premature connection close, which is not checked for in all recover code.
This was detected in a setting where a stored procedure is called that rolls back a transaction in itself.
This patch fixes the issue.
closes https://github.com/rsyslog/rsyslog/issues/5288
> ommysql bugfix: potential segfault on database error

- plugins/ommysql/createDB.sql
- plugins/ompgsql/createDB.sql
According to RFC 1035 the hostname without domain may be up to 63 characters long. Consider this when creating SQL databases.
Closes #5309
> plugins: FromHost must be 63 characters long

- .github/workflows/run_checks.yml
- Makefile.am
- configure.ac
- plugins/imdtls/Makefile.am
- plugins/imdtls/imdtls.c
- plugins/omdtls/Makefile.am
- plugins/omdtls/omdtls.c
- runtime/Makefile.am
- runtime/net_ossl.c
- runtime/net_ossl.h
- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- runtime/nsdsel_ossl.c
- runtime/typedefs.h
- tests/Makefile.am
- tests/imdtls-basic-timeout.sh
- tests/imdtls-basic-tlscommands.sh
- tests/imdtls-basic-vg.sh
- tests/imdtls-basic.sh
- tests/imdtls-error-cert.sh
- tests/imdtls-sessionbreak-vg.sh
- tests/imdtls-sessionbreak.sh
- tests/imtcp-tls-ossl-input-basic.sh
- tests/sndrcv_dtls_anon_ciphers.sh
- tests/sndrcv_dtls_certvalid-vg.sh
- tests/sndrcv_dtls_certvalid.sh
- tests/sndrcv_dtls_certvalid_ciphers.sh
- tests/sndrcv_dtls_certvalid_missing.sh
- tests/sndrcv_dtls_certvalid_permitted.sh
- tests/tcpflood.c
Initial implementation of imdtls and omdtls modules
- Extracted basic OpenSSL helper functions into own module net_ossl.h/net_ossl.c
Both are compiled into lmnsd_ossl.
- Cleanup of OpenSSL code, fixed minor compiler and linking issues.
- Added DTLS Sender option DTLS into tcpflood for testbench.
- Add initial implementation of imdtls input module. Added to configure and makefile
- Add initial implementation of omdtls output module. Added to configure and makefile
- Add multiple basic tests for imdtls receiving data by using tcpflood.
- Add multiple send-receive test for imdtls and omdtls based on existing tls tests.
- Add timeout and sessionbreak tests for imdtls stress testing.
closes: https://github.com/rsyslog/rsyslog/issues/5211
> Initial implementation of imdtls and omdtls modules

- plugins/imdtls/Makefile.am
- plugins/imdtls/imdtls.c
- plugins/omdtls/Makefile.am
- plugins/omdtls/omdtls.c
- runtime/net_ossl.c
- runtime/net_ossl.h
- runtime/nsd_ossl.c
Shared net_ossl_* functions are not available if loaded dynamically by module in imdtls or omdtls. The incorrect workarround was that I linked lmnsd_ossl.la into omdtls and imdtls. However that breaks make install when DTLS modules are enabled.
To fix the problem, all net_ossl_ functions are mapped to the net_ossl interface which is dynamically loaded on runtime.
This removes the lmnsd_ossl.la dependency from the omdtls and imdtls makefiles and fixes make install.
it also removes this build warning:
*** Warning: Linking the shared library omdtls.la against the loadable module *** lmnsd_ossl.so is not portable!
closes: https://github.com/rsyslog/rsyslog/issues/5340
> NET-OSSL driver: Created interfaces for exported functions

- plugins/mmdblookup/mmdblookup.c
- tests/mmdb-lookup-wrong-ip-type-vg.sh
- tests/mmdb-lookup-wrong-ip-type.sh
Mmdblookup module used to suspend after erroring on an IPv6 IP lookup on IPv4-only DBs
This commit replaces the suspension of the module by a simple log message, allowing it to keep working for future lookups
> MMDBLOOKUP::FIXED:: Don't suspend action on incompatible IP lookups

- tests/Makefile.am
Thanks to Michael Biebl for alerting us.
closes https://github.com/rsyslog/rsyslog/issues/5337
> testbench bugfix: testbench tarball did not include a test script

- tests/Makefile.am
- tests/diag.sh
3.9.1 can no longer be downloaded, see for latest version: https://downloads.apache.org/zookeeper/
> testbench: Update zookeeper bin download to 3.9.2

- configure.ac
- runtime/net_ossl.c
- runtime/net_ossl.h
Due the changes in commit 679b0b038c81a6456a20179d125085656b21d27c for the new DTLS modules, some code was moved and not conditionally checked like before.
This fixes compile issues where SSL_CONF_cmd API is not available, like in libressl or ancient OpenSSL Versions.
For older OpenSSL Versions than 1.0.2, imdtls and omdtls modules will not be able to build to the missing support of DTLS.
closes: https://github.com/rsyslog/rsyslog/issues/5353
closes: https://github.com/rsyslog/rsyslog/issues/5342
> OpenSSL: Add precompiler checks for libressl in net_ossl

- contrib/omhttp/omhttp.c
fix typos from issue: https://github.com/rsyslog/rsyslog/issues/5357
thank you @ftapajos
> fix typos in stats counters

- runtime/srutils.c
- tests/omprog-defaults.sh
- tests/omprog-if-error.sh
- tests/testsuites/omprog-defaults-bin.sh
This changes the current behaviour from honouring the double quotes in any part of the argument but leaving them in place and passing to the executed binary to requiring quotes exactly at the beginning and at the end of a multi-word argument, and not including them in the actual call.
Testcases added to ensure the expected results.
Fixes #4249.
I will send the corresponding change to rsyslog-doc repository later if you give the green light to this.
> Fix quoting for omprog, improg, mmexternal

- plugins/ompgsql/ompgsql.c
Messages are lost in case of temporary PG operation errors, since `RS_RET_SUSPENDED` not propagated outside. 
Possibly related to https://github.com/rsyslog/rsyslog/issues/1105
> ompgsql: In case of PG not available lets retry instead of dropping messages.

- plugins/omazureeventhubs/omazureeventhubs.c
- tests/Makefile.am
- tests/omazureeventhubs-basic-url.sh
Parameter amqp_address is now handeled correctly. Added testcase for amqp_address parameter.
closes: https://github.com/rsyslog/rsyslog/issues/5413
> omazureeventhubs: Fix implementation of amqp_address parameter

- configure.ac
- runtime/Makefile.am
- runtime/libcry_common.c
- runtime/libcry_common.h
- runtime/libossl.c
- runtime/libossl.h
- runtime/lmcry_ossl.c
- runtime/lmcry_ossl.h
- tools/Makefile.am
- tools/rscryutil.1
- tools/rscryutil.c
This new `ossl` crypto provider encapsulates the ability to use log encryption in the `omfile` module. It provides the same functionality as `gcry`, additionaly:
- Algorithm are not hardcoded. We simply provide everything what can be fetched via the `EVP_CIPHER_fetch()` call. The same applies to the mode parameter.
- It does not add extra dependency to a new package. Distro maintainers who are already using openssl do not need add anything in particular. By default, if rsyslog is compiled with `--enable-openssl`, the ossl crypto provider will also be included in both `omfile` and also `rscryutil`.
- Side-channel vulnerability in libgcrypt - the Marvin Attack
https://lists.gnupg.org/pipermail/gcrypt-devel/2024-March/005607.html (see the whole thread)
Some might be worried about other …
> New crypto provider via OpenSSL library

- runtime/net_ossl.c
- runtime/rsyslog.h
Some old compilers, eg. GCC 4.4.7 on el6 do not support #pragma GCC diagnostic in functions. Rsyslog has PRAGMA_* macros to handle those cases, so let's use them.
> ossl: Fix #pragma GCC diagnostic not allowed inside functions

- runtime/rsyslog.h
The clang Pragma()s were not correctly enabled due to the new gcc version check.
> build fix: regression from recently merged 615cde156c14

- runtime/dnscache.c
- runtime/rsyslog.h
The undefined bahavior sanitizer deteced an integer overflow inside some code. However, this is hash code and the interger overflow is perfectly fine.
> minor: flag function as OK for undefined behaviour

- configure.ac
- runtime/libcry_common.h
- runtime/libgcry.c
- runtime/libgcry.h
- runtime/libossl.c
- runtime/libossl.h
- runtime/lmcry_ossl.c
Very simple refactoring a use case, where `--enable-openssl` is defined but `--enable-libgcrypt` is not:
- Move common defines to a common file that is used by both `ossl` and `gcry`. I haven't realized it sooner, but some defines were put into a wrong file and if rsyslog was compiled without `gcry` support then those specific defines used by `ossl` were not present.
> Refactor ossl crypto provider

- action.c
- plugins/imptcp/imptcp.c
- runtime/glbl.c
- runtime/glbl.h
- runtime/netstrm.c
- runtime/nsd_ptcp.c
- runtime/rsconf.c
- runtime/rsconf.h
- runtime/rsyslog.h
- runtime/tcpclt.c
- runtime/tcpclt.h
- runtime/wtp.c
- tests/Makefile.am
- tests/diag.sh
- tests/minitcpsrvr.c
- tests/omfwd-lb-1target-retry-1_byte_buf-TargetFail.sh
- tests/omfwd-lb-1target-retry-1_byte_buf.sh
- tests/omfwd-lb-1target-retry-full_buf.sh
- tests/omfwd-lb-1target-retry-test_skeleton-TargetFail.sh
- tests/omfwd-lb-1target-retry-test_skeleton.sh
- tests/omfwd-lb-2target-basic.sh
- tests/omfwd-lb-2target-impstats.sh
- tests/omfwd-lb-2target-one_fail.sh
- tests/omfwd-lb-2target-retry.sh
- tests/omfwd-lb-susp.sh
- tests/omfwd_impstats-tcp.sh
- tests/rcvr_fail_restore.sh
- tests/sndrcv_tls_anon_rebind.sh
- tools/omfwd.c
- tools/rsyslogd.c
This patch implements a very simple round-robin load balancer for omfwd. Its intent is to provide a solid base on which more elaborate functionality can be build.
That said, the load balancing basics will be in place, including the handling of failing load balancing targets and imporoved and adapted pstats counters.
The new functionality is fully backwards compatible with previous configuration settings.
New action() config params:
* pool.resumeinterval
New/"changed" rstats counters
Each target receives its own set of pstats counters. Most importantly this is the case for byte counts. That counter retains the same naming, but there may now be multiple of these counters, one for each target ip, port tuple.
New pstats message count to target
Among others, this can be used for checking that …
> omfwd: implement native load balancing - phase 1

- tests/minitcpsrvr.c
The option name in setsockopts is not a bitmask, so SO_REUSEADDR and SO_REUSEPORT can't be ORed together. Instead apply the options via separate calls.
Fixes: #5456
Thanks: Chris Hofstaedtler <zeha@debian.org>
> testbench: correctly apply socket options in minitcpsrvr

- tests/minitcpsrvr.c
Solaris 10 does not support SO_REUSEPORT, which we need for some tests. It is used in minitcpsrvr.c, and will now not be used if not available.
Note that tests requiring that option will also need to be disabled for that platform.
commit which introduced regression: 1c0f9bb
closes https://github.com/rsyslog/rsyslog/issues/5440
> regression fix: build issue on Solaris 10

- tests/diag.sh
Bump zookeper NVR. The old location does not exist unfortunately. This is why many kafka tests are failing.
> test bench fix: bump zookeper NVR

- runtime/nsd_ptcp.c
- tests/Makefile.am
fix regression introduced by 9ac56b286. This spits out a debug message to stderr. That message is removed by this patch here.
closes https://github.com/rsyslog/rsyslog/issues/5485
This also removes a typo in testbench settings which caused CI failures (second commit, done together for convenience).
> nsd_ptcp: remove debugging messages emited to stderr

- plugins/imdtls/imdtls.c
Adding signal.h to plugins/imdtls/imdtls.c fixes this issue: https://bugs.gentoo.org/942294
> Fix build on musl

- grammar/lexer.l
When using the backtick feature with cat and a file that does not exist, an error message is placed where the file content would be. This error message contained a typo in could as well as a missing space between see and error, which have now been fixed.
Fixes #5360
> fix(lexer): typo and missing space when file can't be accessed

- contrib/imhiredis/imhiredis.c
Simple clean of imhiredis to remove some warnings given by GCC
> clean(imhiredis): Fix incorrect variable definitions and missing function prototype

- tools/rsyslogd.c
`systemd restart rsyslog` in the early start of OS will let rsyslog segmentation fault. This cmd will send sigTerm to rsylogd, and rsyslogd will handle the signal in rsyslogdDoDie. If the rsyslogd havn't parse the conf, the runConf will be NULL So check the pointer before reference it.
#5453
> Fix runConf NULL pointer refence

- parse.c
- runtime/modules.c
detected by newer compiler builds
> cleanup: remove variables that are no longer used

- runtime/lib_ksi_queue.c
> libksi: make build under C11 C standard

- runtime/obj.c
- runtime/stringbuf.c
* Better deal with corrupted queue messages
> Do not free the uninitialized cstring.

- plugins/imdiag/imdiag.c
The testbench helper imdiag did not properly set the network stream driver to use but instead relyed on the default one. Depending on timing, this could mean that either ptcp or a configured default driver could be used, e.g. one of the TLS drivers. With TLS, processing did not happen correctly and could lead to abort.
In any case, imdiag was never meant to be used with any other driver than ptcp (plain tcp). It just uses the tcpsrv component in order to not implement another server.
The year-old problem is possibly the cause for some flakiness in some of the TLS tests, for which we could not find the root cause so far.
In any case, we now request the ptcp driver hardcoded, which not only solves the issue but is the proper thing to do.
Note: imdiag is a testbench tool and we do not expect …
> imdiag bugfix: racy network driver selection

- action.c
- runtime/rsconf.c
If the `$ActionQueueSize` legacy parameter was configured with a much higher value than the default, the `queueDiscardMark` option was not automatically adjusted to represent 98% of the actual queue size. This caused a misalignment issue, which does not occur when using the RainerScript syntax.
To reproduce:
Specify `$ActionQueueSize 10000` without altering `$ActionQueueDiscardMark`.
The documentation did not properly reflect the internal state, I created a doc PR as well: https://github.com/rsyslog/rsyslog-doc/pull/1068
> Fix legacy $ActionQueueDiscardMark parameter

- grammar/rainerscript.c
Having a config snippet like the following causes **segmentation fault**, because the function can not be found.
```
if nonExistentFunction(1) then {
stop
}
```
Output:
```
rsyslogd: version 8.2410.0.master, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.d/crash.conf, on or before line 5: function 'nonExistentFunction' not found [v8.2410.0.master try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.d/crash.conf, on or before line 5: Invalid function nonExistentFunction [v8.2410.0.master try https://www.rsyslog.com/e/2207 ]
[1]    123378 segmentation fault  ./tools/rsyslogd -N1
```
I intentionally removed the `rainerscript: internal error: NULL...` part because it was causing too much noise …
> rainerscript: do not try to call a function if it does not exist

- contrib/mmkubernetes/mmkubernetes.c
calloc() parameters were given in wrong order, which is incorrect but no problem in current practice. No need to update any old binaries.
> mmkubernetes: nitfix

- .github/workflows/codeql.yml
libgrok1 seems to be no longer avaiblabe under Ubuntu 24.04, which now is being used for running codeql.
> CI: remove libgrok-related codeql checks

- plugins/imtcp/imtcp.c
- runtime/netstrms.c
- runtime/netstrms.h
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
- tests/Makefile.am
- tests/imtcp-tls-gtls-manycon.sh
- tests/imtcp-tls-ossl-manycon.sh
- tests/manytcp-too-few-tls-vg.sh
- tests/manytcp.sh
A new "socketBacklog" parameter has been added to the imtcp module, allowing
users to override the default TCP SYN backlog size. Previously, the backlog
was set to roughly 10% of the configured max sessions, which remains the
default if the parameter is not specified. This enhancement enables better
configuration for high-performance servers. The parameter name aligns with
the "socketBacklog" parameter in imptcp for consistency.
The "socketBacklog" parameter should be set based on the anticipated connection
rate and the server's ability to handle incoming connections. For high-performance
environments with heavy traffic, a larger value may be needed to avoid dropped
connections during bursts. If unsure, leave the parameter unset to use the default
(10% of max sessions), which is suitable …
> imtcp: add "socketBacklog" parameter to configure TCP backlog size

- plugins/omsnmp/omsnmp.c
inet_pton is part of POSIX, whilst inet_aton is not. Moreover the function is marked as forbidden according to rpmlint: Forbidden function symbols found: inet_aton
I've been inspecting the following logs for all architectures we currently support on Fedora:
```
badfuncs
VERIFY /usr/lib64/rsyslog/omsnmp.so may use forbidden functions on aarch64 Anyone
Suggested remedy:
Forbidden symbols were found in an ELF file in the package. The configuration settings for rpminspect indicate the named symbols are forbidden in packages. If this is deliberate, you may want to disable the badfuncs inspection. If it is not deliberate, check the man pages for the named symbols to see what API functions have replaced the forbidden symbols. Usually a function is marked as deprecated but still provided in order …
```
> Replaced inet_aton with inet_pton for IPv4 address conversion.

- tools/omfwd.c
Parameter names have historically evolved and are sometimes inconsistent between modules (while still having the same semantics and similiar name).
This commit creates three aliases in omfwd to keep stream driver parameter names consistent with the names used in imtcp. Note that we do not create an alias for
"streamdriverpermittedpeers" because the name differ more considerably and we would also need to create an alias in imtcp as well. We will do this only on request.
Note: aliases help, but are not a great solution. They may cause confusion if both names are used together in a single config. So care must be taken when using an alias.
> omfwd: align some parameters with imtcp names

- tests/omhttp-batch-retry-metadata.sh
- tests/omhttp-validate-response.py
The test results were not deterministic. Sometimes it passed, sometimes it failed. The omhttp-validate-response.py script tried to parse the json input line by line, but sometimes the message and response fields are on separate lines, thus it failed to parse.
This patch updates the check program so that it reads in complete lines when parsing fails, thus removing the condition for flakiness.
closes https://github.com/rsyslog/rsyslog/issues/5439
> testbench: fix flaky omhttp-batch-retry-metadata.sh test

- runtime/net_ossl.c
Use well known DH parameters that have built-in support in OpenSSL. From the man page: If "auto" DH parameters are switched on then the parameters will be selected to be consistent with the size of the key associated with the server's certificate.  If there is no certificate (e.g. for PSK ciphersuites), then it it will be consistent with the size of the negotiated symmetric cipher key.
Using the ossl netstream driver, I am not able to create an ```imtcp``` instance, which uses only the following cipher list (the highlight is on the ephemeral DH exchange part) :
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
Configuration snippet:
```
module(load="imtcp"
StreamDriver.Mode="1"
StreamDriver.AuthMode="anon"
StreamDriver.Name="ossl" …
```
> ossl netstream driver: allow ephemeral Diffie-Hellman key exchange

- tests/diag.sh
- tests/snmptrapreceiverv2.py
The system packages on Ubuntu 24 appear to be broken for python3-pysnmp4. And when we update the package using
pip install pyasn1 pysnmp --break-system-packages --upgrade
We need adapt the code, so a new version snmptrapreceiverv2.py has been added which will automatically been chosen if Python is >3.10
closes: https://github.com/rsyslog/rsyslog/issues/5554
> testbench: Added new version of snmptrapreceiver.py for python 3.1x

- tests/diag.sh
- tests/snmptrapreceiver.py
- tests/snmptrapreceiverv2.py
When the snmpreceiver is fully started and listening, the file is created. diag.sh checks for the .started file before proceeding with the textbench
see also: https://github.com/rsyslog/rsyslog/pull/5558
> testbench: Write started dummy file in python snmpreceiver script

- tests/action-tx-single-processing.sh
- tests/diag.sh
- tools/omfwd.c
While this could lead to some inefficiency, it should not have caused any real harm. But with data races it is never sure if more severe issues occur. However, here only very strange use cases can be envisioned where this might be the case.
In any case, the issue is now solved.
This also fixes some TSAN CI "flakes".
> omfwd bugfix: variable was not properly synced across threads

- .github/workflows/ci_compile.yml
The platforms that do not have support for atomic operations become more and more exoctic. Even more so, only Solaris builders now test that inside the rsyslog CI. To "harden" the CI system against a potential (temporary) unavailability of Solaris, we now also do a build where we intentionally disable atomics. This will trigger build issues on all platforms. This method also permits us to detect problems quicker, as the solaris builders are slow.
> CI: add compile check with atomic operations disabled

- runtime/net_ossl.c
- tests/tcpflood.c
If openssl is compiled without support for openssl engines, do not include engine selection. The global option "defaultopensslengine" will not work in this case. It's support is depreciated in newer OpenSSL versions
OpenSSL Engine Support feature relies on an outdated version of OpenSSL and is strictly experimental.  No support or guarantees are provided. Use at your own risk.
closes: https://github.com/rsyslog/rsyslog/issues/5429
> openssl: check for ENGINE support in library

- configure.ac
- contrib/omamqp1/Makefile.am
Use same build parameters in makefile like omazureevents now.
closed: https://github.com/rsyslog/rsyslog/issues/5550
> omamqp1: Fixed build on Ubuntu 24

- runtime/nsd_gtls.c
When forwarding logs to a TLS server, using a blocking socket can lead to indefinite waiting during the gnutls_handshake() call if the server does not respond as expected.
This commit modifies the behavior to use non-blocking sockets, ensuring that the rsyslog client does not hang indefinitely waiting for a response.
Reproducer:
1. Start a dummy (fake) TLS server not doing any TLS handshake via
```
```
2. Have rsyslog running with
```
*.* action(type="omfwd" protocol="tcp" target="127.0.0.1" port="6514"
StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="anon")
```
The gnutls_handshake call will block indefinitely. It will not return anything, so the client will not reinitiate the connection.
> gnutls bugfix: Avoid blocking sockets during TLS handshake

- .github/workflows/run_checks.yml
- .github/workflows/run_journal.yml
> CI: update github CI runners to use ubuntu-latest image

- plugins/ommysql/ommysql.c
Spotted by lintian:
I: rsyslog-mysql: spelling-error-in-binary willl will [usr/lib/x86_64-linux-gnu/rsyslog/ommysql.so]
> Fix typo in debug printf of ommysql

- tests/solaris/prep-libfastjson.sh
- tests/solaris/prep-librelp.sh
This changes two scripts supporting solaris CI builds to use two instead of one threads when building needed dependecies. This should result in a light speedup without overloading the Solaris builders.
Note: OpenCSW provides the builders, and the rsyslog team is thankful for that.
> testbench: speed up solaris builds a bit

- tools/rsyslogd.c
Note: assert() flags to clang, in this case, that we know this condition cannot happen. This was manually reviewed and made certain.
> "fix" clang 18 static analyzer false positives

- tools/rsyslogd.c
found be clang static analyzer, no report from practice. This could potentially happend during early startup when the config was not yet full read while HUP was received.
> core: fix potential NULL ptr access on HUP in very early startup phase

- contrib/omhttp/omhttp.c
clang static analyzer effectively emitted a false positive, but the manual analysis showed a potential real issue (platform-dependend). We also restructured the code so that the false positive goes away.
> omhttp: fix handling of httpProxy variable

- runtime/queue.c
We silently adjust some queue parameters if they are set invalidly. At least for some important settings are now warning messages emitted.
> queue: emit better warning messages on queue param mismatch

- tools/omfwd.c
This segfault occurred on an amd64 Debian 12 device, running rsyslog version 8.2302.0, though the bug seems to be present in the latest version.
When the omfwd module is configured with an IPv4 address as `Target` and an `Address` of IPv6 (or viceversa): 
```
if  prifilt("*.info")  then {
action(type="omfwd" Target="8.8.8.8" Protocol="udp" Address="2001:db8:dead:beef:fe::8")
}
```
or when the Target is a FQDN that resolves to an IPv4 address and an `Address` of IPv6:
```
if  prifilt("*.info")  then {
action(type="omfwd" Target="hola.com" Protocol="udp" Address="2001:db8:dead:beef:fe::8")
}
```
The following segmentation fault occurs:
```
Process 2353 (rsyslogd) of user 0 dumped core.
Module libsystemd.so.0 from deb systemd-252.17-1~deb12u1.amd64
Stack trace of thread 2356:
#0 …
```
> omfwd: fix segfault in UDP freeaddrinfo

- runtime/nsd_gtls.c
found by CoverityScan
see also https://github.com/rsyslog/rsyslog/pull/5329
> gnutls TLS driver: fix small memory leak

- tools/rsyslogd.c
This was detected by Coverity Scan, and we "fix" it to keep Coverity silent. It is a < 100 byte mem leak that occurs once on startup.
> rsyslog startup bugfix: cosmetic memory leak

- grammar/rainerscript.c
We have these expressions in rsyslogd.conf.
set $!rsyslog_FileFormat = exec_template("RSYSLOG_FileFormat")
set $!localheader = re_extract($!rsyslog_FileFormat, "[^ ]+.* +port[0-9]", 0, 0, "");
set $!localpattern = re_extract($!rsyslog_FileFormat, " [^ ]+ +[^ ]+ +port[0-9]", 0, 0, "");
set $!localheader = replace($!localheader, $!localpattern, " ");
We have a message like this arriving.
<30>Feb 24 22:08:21 hostname port03 'label' RXDATA: \n
It was observed that when 2 of these messages arrive in a row, rsyslogd crashes. This is clearly due to memory corruption, as the crash comes from within calloc.
Unlike the crash, valgrind only complained about the first message. It reported that the 'find' variable was being accessed in the replace function, reading past allocated data.
The …
> Fix a buffer overflow when the argument to replace is empty

- tools/rsyslogd.c
> cosmetic: remove clang static analyzer false positive

- runtime/tcpsrv.c
This affects primarily imtcp. The counter was not maintained at all, it now is incremented whenever a processing loop of the worker thread is completed. Note that, for busy senders, can mean a large number of iterations. The other counters tell the the details of operation. That also means that very busy threads can be detected by looking at the ratio of runs vs. actual operations.
This patch also fixes an invalid mutex being locked on systems that do not support atomic instructions (a copy&paste errror).
> tcpsrv: fix non-maintained stats counter "run"

- runtime/tcpsrv.c
- tests/imtcp-impstats.sh
- tests/manytcp.sh
As a result, it did not show up in pstats. Alos, we now use the input name in worker thread to easily identify where they belong to. As thread names have very limited length, the thread naming now is "w<worker-number>/<input-name>".
> tcpsrv bugfix: input name was not properly propagated

- runtime/tcpsrv.c
- runtime/tcpsrv.h
It needs to be decided if this is a useful setting or not.
> add experimental stats for worker awaking via event notification

- plugins/imdiag/imdiag.c
- plugins/imgssapi/imgssapi.c
- plugins/imtcp/imtcp.c
- runtime/netstrm.c
- runtime/netstrm.h
- runtime/nsd.h
- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
- runtime/nsd_ossl.c
- runtime/nsd_ossl.h
- runtime/nsd_ptcp.c
- runtime/tcpsrv.c
- runtime/tcpsrv.h
Depending on circumstances, tcpsrv worker threads did effectively busy-wait on io events to handle. Not always, but often. This was caused be improperly re-arming the inotify subsystem.
This effected overall system performance, but not general rsyslog stability. The bug was introduced on March 1st 2025 into the daily stable build.
closes https://github.com/rsyslog/rsyslog/issues/5623
> tcpsrv bugfix: do not busy wait on io events

- runtime/tcpsrv.c
> tcpsrv: ensure thread name set via pthread is max 15 char

- runtime/nsd_gtls.c
- runtime/nsd_ossl.c
Right now, the remote peer is not reported, even in cases where this would be possible. This patch provides a method to emit a second message with remote peer information in cases where it is possible. This is the case when the remote peer connects via plain tcp but TLS cannot be negotiated, especially because the connection breaks immediately. Most probably this behaviour can be created by load balancer and other tools healt checks.
This patch improves debugging network issues. So it is useful. However, it is far from perfect and if the method prooves to be useful in practice, further work is need to integrate it in a better way into the overall architecture. We may also be able to emit remote peer info in other cases. Stil, we can provide this patch as it offers sufficient value even in …
> tls subsystem: generate better error message on accept failure

- plugins/imklog/imklog.c
The `bKeepKernelStamp` field assignment has been repeated twice,
This line of code is redundant,  need to be deleted and cleaned up.
fix issue: #5396
> imjournal: delete redundant lines in imklog.c

- parse.c
> Fix comment for parsSkipWhitespace

- AGENTS.md
- CONTRIBUTING.md
- README.md
This commit updates all contributor-facing documentation:
- **README.md**: Modernized structure and clarified installation/build sections. Removed obsolete local doc references and replaced with link to rsyslog-doc project.
- **CONTRIBUTING.md**: Refactored for clarity, added guidance for AI-generated code (e.g. commit prefix `AI:`), formalized use of draft PRs for experiments, and removed outdated advice on "testing new releases." Added rationale for continued use of `master` branch due to ecosystem dependencies.
- **AGENTS.md** (new): Introduces clear guidelines for AI-based agents contributing to rsyslog. Includes commit formatting, PR branch expectations, testing environment, and behavioral rules.
**Why now?**
Over the past two years, we've continuously evaluated the evolving …
> docs: restructure contributor docs for clarity and AI agent readiness

- .github/workflows/ci.yml.template
- .github/workflows/ci_compile.yml
- .github/workflows/codeql.yml
- .github/workflows/run_checks.yml
- .github/workflows/run_journal.yml
- .github/workflows/run_kafka_distcheck.yml
see also https://github.com/rsyslog/rsyslog/issues/5666
> ci: skip expensive workflows on doc-only changes

- plugins/imdtls/imdtls.c
- plugins/omdtls/omdtls.c
In order to compile the DTLS input and output modules on FreeBSD we need the function prototypes for pthread_kill(3) from signal.h and close(2) from unistd.h
These patches have been in the FreeBSD port of rsyslog for about 6 months, so high time to upstream them.
> Add header includes to support compilation on FreeBSD

- contrib/imdocker/imdocker.c
The imdocker configuration parser previously copied getcontainerlogoptions into a fixed buffer and allocated exactly the input length for a secondary options string. This risked truncation and missing termination. The new code allocates buffers dynamically and accounts for the trailing null byte.
Summary
Replaced the fixed 256‑byte buffer with a dynamically allocated copy of the configuration string and ensured room for a trailing null byte in option_str.
> imdocker: harden module buffer management

- runtime/lookup.c
- runtime/lookup.h
- runtime/typedefs.h
While we do not like rexeg-matches for performance reasons, they are well known and appreciated by users. With the new table type, we add a lookup capability for partial matches, but at the price of much higher ressource use. It still is useful, e.g. to classify events as "noise" events in a simple manner.
> lookup: add new table type for regex-matches

- outchannel.c
Fixes https://github.com/rsyslog/rsyslog/issues/5047
> outchannel: eleminate type cast for compatibility reasons

- CONTRIBUTING.md
- README.md
- doc/README.md
- doc/source/conf.py
- doc/source/configuration/modules/imfile.rst
- doc/source/configuration/modules/omczmq.rst
This commit addresses several documentation inconsistencies and updates:
- Corrected `README.md` and `CONTRIBUTING.md` to accurately state that documentation is located in the `doc/` directory of this repository, not in a separate `rsyslog-doc` project.
- Added a placeholder file for the `omczmq` module documentation at `doc/source/configuration/modules/omczmq.rst`, as it was previously missing.
- Updated `doc/README.md` to recommend Python 3 and a modern Sphinx version for building documentation, removing outdated Python 2.7 references.
- Updated `doc/source/conf.py` to set `needs_sphinx = '4.5.0'` (from '1.5.1').
- Clarified the "WildCards" section in `doc/source/configuration/modules/imfile.rst` to better reflect current functionality regarding wildcard usage in paths and filenames. …
> Fix: Correct documentation location and update build guidance

- .github/workflows/ci_compile.yml
- .github/workflows/codeql.yml
- .github/workflows/run_checks.yml
- .github/workflows/run_journal.yml
- .github/workflows/run_kafka_distcheck.yml
Enhances the 'compile check' GitHub Actions workflow to intelligently skip resource-intensive compilation when Pull Requests (PRs) only involve documentation or other non-source code modifications.
This optimization improves CI efficiency and reduces build times for documentation-only changes, while still enforcing full compilation for actual code modifications.
Key changes include:
- **Removed `paths-ignore`**: The workflow now always triggers, allowing for granular job control.
- **Introduced `determine_changes_type` job**: This job uses `tj-actions/changed-files` to accurately detect if a PR consists solely of ignored files (e.g., `ChangeLog`, `*.md`, `*.txt`, `doc/**`).
- **Conditional `doc_only_success_check` job**: A lightweight job that runs and passes quickly when only …
> CI: Optimize compile check for doc-only changes

- plugins/omsendertrack/omsendertrack.c
> omsendertrack fix: memory leak in initHashTable

- runtime/tcpsrv.c
This was an overlook during the refactoring of tcpsrv.c earlier in 2025. We kept the line for some tests, but actually it needs to be removed as notifyReArm() now has the proper code to handle these cases.
The left-over TODO could cause confusion during code review.
> tcpsrv cleanup: remove TODO line that was scheduled to be removed

- .github/workflows/ci_compile.yml
Previously, they never ran. Trying now a more robust method.
> CI: (try to) fix running compile checks only on code file changes

- action.c
This was a long standing TODO item for many years. In the meantime, practice has shown that no so config setting is necessary. Too many config options also tend to confuse users.
> cleanup: remove stalled TODO item

- tools/rsyslogd.c
One byte for `\0` should be left in case the message is `sizeof(msgBuf)` bytes or longer.
> fix off-by-one buffer overflow

- tests/test_id.c
This was harmless, but generated build warnings, which can be confusing.
> testbench nitfix: improper format spec corrected

- runtime/tcpsrv.c
- runtime/tcpsrv.h
This patch adds an inQueue flag with its own mutex to each tcpsrv_io_descr_t structure. The flag prevents multiple worker threads from processing the same descriptor at the same time.
The change was motivated by segmentation faults reported in production systems after commit ad1fd21, which introduced a worker thread pool to imtcp. We could not reproduce the faults ourselves, but code analysis suggests several race conditions may exist.
In particular:
- epoll_wait may return the same descriptor multiple times. If it gets enqueued more than once, multiple threads may process and free it in parallel, causing use-after-free errors.
- closeSess releases the session mutex before destroying the session and descriptor. A second thread might still be waiting to acquire the mutex and access the …
> imtcp: prevent double-enqueue of descriptors via inQueue flag

- contrib/imkmsg/kmsg.c
On some systems, EAGAIN and EWOULDBLOCK are defined to the same value, causing a `-Wlogical-op` warning for the redundant logical 'or' in the errno check.
While portable code must check for both cases, this warning is unwanted.
This change uses a preprocessor directive to conditionally compile the check for `errno == EWOULDBLOCK` only on platforms where its value differs from EAGAIN. This silences the warning without affecting portability.
> imkmsg fix: Handle EAGAIN/EWOULDBLOCK check portably

- runtime/nsd_ptcp.c
We received reports of log messages incorrectly referring to "imptcp" even though the imptcp module was not loaded on the system. This caused confusion during troubleshooting.
One such message was:
rsyslogd: imptcp cannot set keepalive intvl - ignored: Bad file descriptor
This message originated from the nsd_ptcp module, but the LogError() calls in EnableKeepAlive() still used "imptcp" as the source name.
This is a regression introduced in commit ad1fd21, which restructured TCP input handling and moved responsibility for keepalive setup to nsd_ptcp, but did not update the associated log messages.
This patch corrects the affected log strings to use "nsd_ptcp", accurately reflecting the code path that emits them.
There is no functional change; the patch improves clarity of log output and …
> nsd_ptcp fix: misleading error messages (regression from ad1fd21)

- AGENTS.md
- doc/source/_ext/rsyslog_lexer.py
- doc/source/configuration/filters.rst
- doc/source/rainerscript/expressions.rst
- grammar/grammar.y
- grammar/lexer.l
- grammar/rainerscript.c
- runtime/ruleset.c
- runtime/stringbuf.c
- runtime/stringbuf.h
- runtime/typedefs.h
- tests/Makefile.am
- tests/endswith-basic.sh
This Implements suffix comparison similar to startswith. Note that we do intentionally not use libestr functions in order to speed up adaption. It would otherwise probably take years for distros to upgrade libestr.
With some help of the Codex AI Agent.
closes https://github.com/rsyslog/rsyslog/issues/1255
> scripting: add endswith operator to property filters and RainerScript

- AGENTS.md
Strict rules break a lot of AI Agent capabilites as we have seen. Repo will most probably soon moved to space-indention.
> AI support: relax indention rules

- configure.ac
Change version tag from ".master" to ".daily" to better reflect its use in the automated daily stable build process. This also aligns with the ongoing effort to eliminate use of the "master" name throughout the repository.
> build: adjust version tag used for daily stable build process

- plugins/impstats/impstats.c
- tests/Makefile.am
- tests/stats-prometheus.sh
This commit extends the impstats input module to support a new "prometheus" format for exporting statistics. The output is generated via statsobj.c, which already provides Prometheus- compatible formatting.
To enable this, a new "format" config option value ("prometheus") was added and recognized by impstats.c. When selected, impstats invokes the appropriate statsobj function to generate output in Prometheus exposition format.
The default behavior remains unchanged. Existing formats such as "json" and "legacy" are not modified.
A new test has been added under tests/ to validate correct Prometheus output generation. The test verifies that the format header and at least one representative metric line conform to the Prometheus text format specification.
This enhancement enables rsyslog to …
> impstats: add support for Prometheus metrics output format

- grammar/rainerscript.h
- runtime/rsyslog.h
Undefine common syslog severity and facility macros before redefining them in rsyslog.h. As rsyslog, we need consistent definitions. This resolves "redefined" warnings when other system headers are included. LOG_CRON remains guarded. Improves build cleanliness.
> fix: Prevent redefinition warnings for syslog macros

- packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
> CI: prepare ubuntu 24.04 testing container to support mmaitag

- plugins/imptcp/imptcp.c
imptcp connection is accepted and right away rsyslog is stopped
detected by Coverity Scan. Not sure if it ever happened in practice.
> imptcp bugfix: potential socket leak

- contrib/imhttp/imhttp.c
- tests/Makefile.am
- tests/imhttp-healthcheck.sh
- tests/imhttp-metrics.sh
This also includes a basic Prometheus scrape entry point, which currently can only be used for health checking.
We plan futher enhancement in this direction.
> imhttp: add simple http health check functionality

- configure.ac
This was originally intended, but for testing it was set to enabled by default. This is now corrected. Not all CI workers support the necessary dependencies.
> build: mmaitag in configure disabled by default

- runtime/rsyslog.h
Reorganized the “Config Settings” section in rsyslog.h to improve readability and documentation:
- Added a banner header for the Config Settings block
- Consolidated general MAXSIZE/BUFSIZE guidelines into a single Doxygen comment
- Provided individual `@brief` comments for each `#define`
- Aligned macro definitions for consistent formatting
No functional changes were made; this is purely a documentation and style cleanup.
> style: reformat Config Settings block with Doxygen comments

- doc/source/conf.py
- doc/source/containers/index.rst
- doc/source/index.rst
- doc/source/proposals/big_restructuring/documentation_review.rst
and some other places with outdated repo link
> doc: fix "edit on github" repo link

- .github/workflows/commit_style_check.yml
- tests/CI/PR_validation.sh
This patch improves the GitHub Actions PR validation workflow:
- Added comprehensive inline documentation for clarity.
- Corrected branch reference from 'master' to 'main' in `tests/CI/PR_validation.sh`.
These changes enhance CI/CD clarity and maintainability.
> CI: Enhance PR validation and update branch name

- packaging/docker/dev_env/ubuntu/doc_base/22.04/Dockerfile
Add sphinxcontrib-mermaid to documentation Docker image
This package is required to build `txt` and `singlehtml` documentation formats, enabling Mermaid diagram rendering in Sphinx documentation.
> Add sphinxcontrib-mermaid to Dockerfile

- doc/source/configuration/modules/omfwd.rst
- doc/source/configuration/modules/omfwd/parameters/basic.rst
- doc/source/configuration/modules/omfwd/parameters/module.rst
- doc/source/development/doc_reference_section_guidelines.rst
This commit reorganizes the `omfwd` module documentation for improved clarity and maintainability.
The large `omfwd.rst` file has been split into smaller, more focused documents:
* `omfwd/parameters/module/index.rst`: Contains parameters that apply globally to the omfwd module.
* `omfwd/parameters/action/index.rst`: Contains parameters specific to individual omfwd actions.
* `omfwd/parameters/action/target.rst`: Extracts the "Target" parameter into its own file. This serves as a proof-of-concept for future parameter-specific pages.
This restructuring is part of an ongoing effort to enhance the `omfwd` documentation. Further improvements to the page are planned.
> doc: Restructure omfwd documentation

- runtime/nsd_gtls.c
- runtime/nsd_gtls.h
When no TLS certificate or key is configured for forwarding actions, repeated connection attempts produced the same warning messages over and over. `gtlsInitCred()` and `gtlsAddOurCert()` now log these warnings only during the initial setup.
Without the patch, they log these messages every time the connection is being reestabilished:
```
Jul 26 13:31:01 vm-tls rsyslogd[6101]: warning: certificate file is not set [v8.2412.0-1.el9 try https://www.rsyslog.com/e/2330 ]
Jul 26 13:31:01 vm-tls rsyslogd[6101]: warning: key file is not set [v8.2412.0-1.el9 try https://www.rsyslog.com/e/2331 ]
Jul 26 13:31:01 vm-tls rsyslogd[6101]: warning: certificate file is not set [v8.2412.0-1.el9 try https://www.rsyslog.com/e/2330 ]
Jul 26 13:31:01 vm-tls rsyslogd[6101]: warning: key file is not set …
```
> gtls: log missing certificate/key only once

- .gemini/config.yml
Gemini Review has proven to be very valuable and we want to ensure it sees every version of the code. While this may look tiring, it helps improve code quality and lessens burden on maintianers.
> CI/AI: trigger Gemini review on each PR code update

- plugins/imjournal/imjournal.c
Initialize cs.fCreateMode to 0644 instead of -1 to prevent state files from being created with all permission bits set when legacy configuration is used. The setModCnf function is only called with modern configuration, leaving cs.fCreateMode at -1 for legacy configs, which results in wrong open() calls.
By default, the state file will now use a hardcoded permission of 0644 for legacy syntax, while remaining configurable through the new syntax. Since rsyslog is the sole consumer of this file (at least should be), I will maintain FileCreateMode at 0644 to avoid introducing additional issues.
Side note: another approach would be to introduce the legacy version of this parameter via:
```
CHKiRet(omsdRegCFSLineHdlr((uchar *)"filecreatemode", 0, eCmdHdlrFileCreateMode, NULL, &cs.fCreateMode, …
```
> imjournal: fix vulnerability in state file creation

- runtime/obj.c
- runtime/obj.h
- runtime/queue.c
Replace opaque/variadic callback usage with explicit, type-safe function signatures to reduce undefined behavior and clarify intent. Adapter helpers bridge the existing APIs without raw variadic casts, enabling the transition incrementally. Callback setup sites are standardized for consistent readability. This tightens the contract on callbacks, eases future refactoring, and makes their roles more self-documenting.
Inspired by https://github.com/rsyslog/rsyslog/pull/5882
With AI support: Codex
> core: migrate callback invocations to type-safe signatures

- doc/source/configuration/modules/imdocker.rst
> doc: imdocker had invalid legacy config stmt info - removed

- doc/source/configuration/modules/imdocker.rst
- doc/source/reference/parameters/imdocker-apiversionstr.rst
- doc/source/reference/parameters/imdocker-defaultfacility.rst
- doc/source/reference/parameters/imdocker-defaultseverity.rst
- doc/source/reference/parameters/imdocker-dockerapiunixsockaddr.rst
- doc/source/reference/parameters/imdocker-escapelf.rst
- doc/source/reference/parameters/imdocker-getcontainerlogoptions.rst
- doc/source/reference/parameters/imdocker-listcontainersoptions.rst
- doc/source/reference/parameters/imdocker-pollinginterval.rst
- doc/source/reference/parameters/imdocker-retrievenewlogsfromstart.rst
Migrates all imdocker module parameter descriptions from the monolithic module page into individual parameter reference files under doc/source/reference/parameters/. Each parameter now has:
- A stable Sphinx label and cross-references
- A concise summary section for use in tables and AI ingestion
- Clear metadata (scope, type, default, introduced version)
- RainerScript usage examples
- "See also" links back to the main module page
The imdocker.rst page now uses a compact parameter list-table with embedded summaries and a hidden toctree linking to full parameter pages. This aligns with the new documentation structure for better maintainability, human readability, and machine ingestion (e.g. for RAG-based assistants).
> doc: refactor imdocker module param docs into structured ref pages

- AGENTS.md
- DEVELOPING.md
- MODULE_AUTHOR_CHECKLIST.md
- doc/ai/module_map.yaml
Added cross-references to doc/ai/module_map.yaml in both developer- facing guides:
- AGENTS.md:
* Mentioned the AI module map in the Repository Overview and Quickstart sections.
* Added a common task instructing contributors to consult the map before making edits.
- DEVELOPING.md:
* Updated “Pointers” to include the AI module map as a source for per-module paths and known locking hints.
This improves discoverability of module locations and expected locking patterns for both AI agents (e.g., Codex) and human contributors, reducing time spent locating code and relevant design notes.
No functional changes; documentation only.
> doc: reference AI module map in AGENTS.md and DEVELOPING.md

- doc/source/development/dev_action_threads.rst
Add "Concurrency & Locking" to dev_action_threads.rst: multiple workers per action; WID is per-worker; shared pData must be mutex/rwlock-protected; direct mode still needs module-side serialization for inherently serial resources.
> doc: add v8 locking note

- plugins/ommysql/ommysql.c
This item was create in 2007 and has proven in ~20yrs of practice to be no issue. Even more so, this is now in legacy code that will no longer be updated at all. So the TODO no longer applies and could be removed.
> ommysql: remove long-standing non-needed TODO item

- action.c
- tests/omhttp-batch-fail-with-400.sh
- tests/omhttp-retry-timeout.sh
- tests/omprog-feedback-mt.sh
- tests/omprog-feedback.sh
- tests/omprog-transactions-failed-messages.sh
Fix transaction suspension handling for issue #2420
- action.c: Add iSuspended flag to prevent infinite loops when transactions
are suspended multiple times. Retry on first suspension
and abort with RS_RET_SUSPENDED on subsequent suspensions.
- tests/omprog-transactions-failed-messages.sh: Remove TODO comment and
workaround code related to issue #2420 (deferred messages within
transactions not being retried), as the underlying issue appears to
be resolved.
- tests/omprog-feedback-timeout.sh: Update expected output to reflect
improved transaction handling behavior. The test now expects additional
message processing cycles and proper timeout handling when the omprog
action is suspended and restarted.
- tests/omprog-feedback.sh: Make robust against timing variations from
new action.c retry …
> Fix transaction suspension handling

- doc/source/configuration/modules/omkafka.rst
- doc/source/rainerscript/constant_strings.rst
- omkafka.rst: add “Set SASL password from an environment variable” section with two paths:
* v8.2508.0+: inline `${VAR}` with adjacency via backticks (`echo sasl.password=${KAFKA_PASSWORD}`)
* pre-8.2508.0: pre-compose `SASL_PWDPARAM` and echo that
- Clarify security notes (env files, /proc visibility) and add anchor label :ref:`omkafka-sasl-password-from-env`
- constant_strings.rst: restructure and expand
* document `${VAR}` support, unbraced `$VAR` termination rules, and adjacency to static text (v8.2508.0)
* keep scope explicit: only `echo`/`cat`, no `$(...)`
* add clear examples and use `rsyslog` lexer for code blocks
* add compatibility guidance for older versions
* add note: backticks can toggle boolean flags such as `config.enabled`
- Motivation: addresses confusion seen in …
> doc: omkafka SASL-from-env example + backticks doc overhaul

- doc/source/index.rst
These cause mayor confusion for rsyslog users. Ensure they know the need to go to the source.
This is probabaly only an interim solution until we have found better ways to address the core issue.
> doc: warn against unofficial and outdated doc clones

- doc/source/conf.py
Add html_baseurl to Sphinx config; set to
'https://www.rsyslog.com/doc/'.
Sphinx will add a canonical link per page, reducing duplicate content in search and consolidating ranking.
The URL matches the production docs root (trailing slash kept). No behavior change for local/offline builds.
> doc: set html_baseurl to emit canonical tags

- .github/workflows/ci.yml.template
- .github/workflows/run_checks.yml
- packaging/docker/dev_env/centos/base/8/Dockerfile
- packaging/docker/dev_env/debian/base/11/Dockerfile
- packaging/docker/dev_env/debian/base/13/Dockerfile
- packaging/docker/dev_env/debian/base/13/build.sh
- packaging/docker/dev_env/debian/base/13/tag-previous.sh
- packaging/docker/dev_env/fedora/base/34/Dockerfile
- packaging/docker/dev_env/fedora/base/41/Dockerfile
- packaging/docker/dev_env/fedora/base/41/build.sh
- packaging/docker/dev_env/fedora/base/41/tag-previous.sh
- packaging/docker/dev_env/fedora/base/42/Dockerfile
- packaging/docker/dev_env/fedora/base/42/build.sh
- packaging/docker/dev_env/fedora/base/42/tag-previous.sh
- packaging/docker/dev_env/suse/base/tumbleweed/Dockerfile
- packaging/docker/dev_env/ubuntu/base/16.04/Dockerfile
- packaging/docker/dev_env/ubuntu/base/18.04/Dockerfile
- packaging/docker/dev_env/ubuntu/base/20.04/Dockerfile
- packaging/docker/dev_env/ubuntu/base/22.04/Dockerfile
- packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
- tests/diag.sh
- tests/snmptrapreceiverv2.py
Modernize our dev/CI matrix to match current distro lines and reduce toolchain drift. This keeps project-provided images aligned with what contributors run locally and moves us toward “project-supported” bases.
Impact: CI matrix refresh only; no runtime behavior change intended.
Before: CI used Fedora 35/36 and Debian 10/11 dev-base images.
After: CI uses Fedora 41/42 and Debian 11/13 dev-base images.
Technically, this adds Dockerfiles for debian:13 and fedora:{41,42}
with updated toolchains and configure options (e.g., enabling dtls on
newer distros). GitHub Actions matrices now target debian_13 and
fedora_{41,42}; run_checks also watches workflow files. Several
dev-base Dockerfiles update the cached ZooKeeper tarball to 3.9.3 and
fix output names. Debian 13 introduces a small libgcrypt …
> ci: add Fedora 41/42 and Debian 13 dev-base images

- contrib/imdocker/imdocker.c
This addresses a small one-time leak in option parsing, reported by clang static analyzer. While it is practically invisible in real use, fixing it improves code hygiene and keeps analyzers clean.
Impact: No user-visible effect; prevents analyzer warnings.
Technical details:
Previously, a buffer created by strdup() for container log options was not always released, leading to a minor leak during config load. The code now allocates once, uses CHKmalloc for safety, and frees the buffer in the finalize step. This ensures consistent memory ownership without altering module behavior. No changes to runtime logging flow, queue semantics, or config parameter interpretation.
> imdocker: fix cosmetic memory leak

- runtime/tcps_sess.c
- runtime/tcps_sess.h
- runtime/tcpsrv.c
While at the time of merge I was confident it would fix a data race, the root cause has now surfaced to be a simple state advancement (single-threaded) bug. See commit c5fd73499 for details. As such I revert this patch. it caused no harm, but complicates code, adds a bit of computation and is no longer needed.
I cannot 100% outrule it might have addressed some edge cases. I know an environment where we can verify this within the next month or so. If, unexpectedly, this shows regressions, we can re-enable the patch. But I am 99.99% sure it is not needed.
see also: https://github.com/rsyslog/rsyslog/pull/5806
see also: https://github.com/rsyslog/rsyslog/pull/5993
> tcpsrv: revert PR 5806 because it was ineffective

- .github/workflows/contributor-welcome.yml
intent is two-fold:
- act welcoming and provide some guidance for PR contributors
- do a bit of checking so maintainer get's an idea if this might be a spammy account (the world is a bad place...). Alos prevent rsyslog from being used for social engineering other repos.
This method will be improved in the future and is work in progress.
Note: rsyslog welcomes small PRs, even single typo fixes, when they are useful to the project. We shall, however, reject frequent single typo fixes from same account and ask them to combine the commits. Reason is this might be a social engineering tactic to make rsyslog itself or other repos build unrooted trust in the account.
> community: add welcome message to first few commits

- .github/workflows/clang-analyzer.yml
- doc/source/concepts/janitor.rst
- doc/source/concepts/messageparser.rst
- doc/source/concepts/multi_ruleset.rst
This commit corrects small wording and spelling issues in janitor.rst.
Improves clarity and consistency in the documentation.
Why: Enhances readability and reduces ambiguity for users.
Impact: No functional changes, docs only.
---
---
```
```
- If key …
> docs: fix minor typos in docs/source

- .github/workflows/run_checks.yml
Saves ressources, gives faster follow-up build, save labor for manual cancel.
---
---
```
```
into the commit message for a clean history.
> CI: cancel hughe task automatically on all runners on re-push

- .github/workflows/doc_build.yml
Too shallow fetch from github made trigger condition unreliable.
> CI: fix doc_build check which was not always built

- runtime/wtp.c
Potential fix for [https://github.com/rsyslog/rsyslog/security/code-scanning/44](https://github.com/rsyslog/rsyslog/security/code-scanning/44)
To fix the problem, remove the commented-out code and the related TODO comment. This will eliminate confusion about whether the code is still needed and prevent readers from being distracted by unused blocks. Only the lines within the flagged region (the TODO comment and the commented-out Solaris code) are to be removed, leaving all actual functioning code (including the #includes above and below) intact. No changes to imports, definitions, or methods are needed, as the code is simply being removed.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 44: Commented-out code

- .github/workflows/clang-analyzer.yml
Also
- auto-abort on re-push
- some minor tweaks
---
---
```
```
into the commit message for a clean history.
> CI: ensure static analyzer script only runs when actually needed

- .github/workflows/ci.yml.template
- .github/workflows/ci_codestyle_check.yml
- .github/workflows/ci_compile.yml
- .github/workflows/codeql.yml
- .github/workflows/commit_style_check.yml
- .github/workflows/doc_build.yml
- .github/workflows/run_checks.yml
- .github/workflows/run_journal.yml
- .github/workflows/run_kafka_distcheck.yml
- .github/workflows/yaml_lint.yml
Add concurrency groups with cancel-in-progress to all pull request workflows so new pushes abort outdated jobs.
Most importantly this saves ressources and also makes follow-up PR runs much quicker.
with the help of ChatGPT
---
---
```
```
- If key info …
> ci: cancel superseded workflow runs

- contrib/omhttp/omhttp.c
- tests/Makefile.am
- tests/omhttp-profile-loki.sh
This change introduces profile-based configuration for omhttp. Profiles
simplify setup for common backends such as Grafana Loki and Splunk HEC by
applying recommended defaults for batching, paths, formats, and retry codes.
This improves usability and avoids error-prone manual tuning.
Impact: HTTP error handling semantics are changed; retry behavior for
3xx and 4xx differs from previous releases.
Technically, HTTP status handling is refactored: transport errors and 5xx
remain retriable, while 3xx (redirection) and 4xx (client errors) are now
treated as permanent failures (`RS_RET_DATAFAIL`). Retry ruleset logic in
batch mode is clarified: if a retry ruleset is configured, messages are
queued there; otherwise, core retry is used. In single-message mode, core
retry is always used.
The new …
> omhttp: add profile support and revise HTTP retry semantics @#5957

- tools/rsyslog.conf.5
This will fix the example given where a Port number is configured. The Port number (514) should be configured as a string value: "514".
> tools/rsyslog.conf.5: fix example Port= value

- tests/diag.sh
Previosly, dev build was targeted, where download also expired. This resulted in CI failures as we could no longer set up kafka environment.
> CI: change zookeeper version to latest stable

- configure.ac
replace `[[ ]]` (actually `[ ]` ) with `test` and `==` with `=`
Signed-off-by: Maciej Barć <xgqt@gentoo.org>
> configure.ac: remove bashisms

- .gemini/config.yml
It looks like our previous config was either for a pre-release or did work albeit not following the (current) published schema.
Now changed it to current form.
> CI: reconfigure gemmini code review bot

- tests/diag.sh
These comoponents have problems from time to time (e.g. tarball no longer available); more verbose output makes simplyfies diagnosis.
---
---
```
```
into the commit message for a …
> CI: more verbose info on kafka/zookeeper install

- configure.ac
Libgcrypt 1.11.0 deprecated libgcrypt-config in favor for gpgrt-config, which doesn't emit -lgcrypt. pkg-config does, though.
See also:
* https://dev.gnupg.org/T7165
* https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=commit;h=2db5b5e995c21c5bd9cd193c2ed1109ba9b1a440
This should fix #5405
I only tested this on Arch Linux.
> WiP: Replace libgcrypt-config with pkg-config

- .github/workflows/run_checks.yml
- devtools/devcontainer.sh
- devtools/run-ci.sh
Replace deprecated bash uploader with Codecov's official uploader. The script now downloads the uploader binary, verifies its SHA256 checksum, and runs it to submit coverage results.
The change keeps run-ci.sh CI-agnostic.
With the help of AI-Agent: ChatGPT
> devtools: use codecov uploader in CI script

- configure.ac
The Sphinx docs build has been failing because conf.py imports
doc/source/conf_helpers.py, which was removed. This PR restores the
helper module so documentation builds succeed again.
Regression introduced by:
https://github.com/rsyslog/rsyslog/commit/ba762b653331f3c97ba2da91cf6a0ab602e6243c
Impact:
- Restores local and CI documentation builds
- No runtime or ABI changes
Before:
- sphinx-build failed with ImportError/ModuleNotFoundError for conf_helpers
After:
- sphinx-build succeeds
Testing:
- sphinx-build -b html doc/source doc/build/html completes locally
- .github/workflows/doc_build.yml expected to pass
AI-Agent: Codex
> doc: restore missing doc files in configure.ac

- .github/workflows/run_checks.yml
We try sid to gain early access to new compiler versions. It needs to be show if sid causes too many false positives (due to its own instability) and if we manage to regenerate the compiler frequently enough.
> CI: replace debian 11 with sid in test runs

- devtools/format-code.sh
This PR modifies the behaviour of `devtools/format-code.sh` to use a configurable version of `clang-format`, and sets it to use `clang-format-18`.
This avoids version ambiguity, which has become a problem due to later versions of the tool typically being installed by more recent versions of Linux distributions.
Ref: https://github.com/rsyslog/rsyslog/pull/5268#issuecomment-3252118980
---
---
``` …
```
> devtools: Specify usage of clang-format-18 to pin v18

- .github/workflows/run_checks.yml
The civetweb library is not packaged in a thread-safe way and as such TSAN always fails due to a civetweb data race by calling gmtime. Nothing to do so far against that.
> CI: disable TSAN chekcs for imhttp which fail due to civetweb

- doc/source/rainerscript/functions/rs-toupper.rst
- grammar/rainerscript.c
- tests/Makefile.am
- tests/rscript_tolower.sh
- tests/rscript_toupper.sh
Add a RainerScript function to convert strings to uppercase. The implementation mirrors tolower() but operates per-byte using toupper(). Tests demonstrate the new function, documentation and ChangeLog entries added.
closes: https://github.com/rsyslog/rsyslog/issues/3666
With the help of AI-Agent: ChatGPT
> rainerscript: add toupper() function

- contrib/imdocker/imdocker.c
- doc/source/configuration/modules/imdocker.rst
- tests/Makefile.am
- tests/imdocker-image-name-vg.sh
- tests/imdocker-image-name.sh
Exposes the image name and tag of the source container (what the Docker API simply calls `Image`) as an additional metadata value alongside the existing ones.
While the ImageID is available today, a SHA hash is not a particularly user-friendly way to identify what is actually generating the logs.
The image name provides a simple, easy-to-read identifier for the common scenario where an unmodified application image is used.
A test for this additional property has been written, however the `devtools/devcontainer.sh` environment does not include Docker, so attempting to run the test locally crashes with `docker: command not found`. 
Modifying this development environment to add Docker is probably beyond the scope of this PR, so I hope that the CI tests will suffice.
Docker [API …
> imdocker: Add image name to metadata fields

- grammar/rainerscript.c
- tests/Makefile.am
- tests/rscript_b64_decode-vg.sh
- tests/rscript_b64_decode.sh
This PR provides a new Rainerscript function: b64_decode.
This function is based on RFC4648.
This replaces https://github.com/rsyslog/rsyslog/pull/5397 which was stalled because rebase was needed, original author had no time to respond and maintainer edits were not permitted. So I create a new branch to finally merge.
I will also add some missing parts, like doc and Makefile integration.
> config script: add b64_decode function

- contrib/omhttp/omhttp.c
- doc/source/configuration/modules/omhttp.rst
- Improve batch sizing: predict serialized size including format overhead and separators to honor batch.maxbytes precisely, minimizing premature flushes and preventing oversize payloads.
- Add computeDeltaExtraOnAppend to check thresholds before appending each record.
- Fix dynrestpath batching: flush only when rest path changes; reinitialize and re-seed path for the next batch; free old path to avoid leaks.
- Preserve backward compatibility: existing config keys and formats unchanged; default retry via core suspend/resume; retry.ruleset supported for advanced per-message retry handling.
- Update module docs to reflect refined flush conditions, dynrestpath semantics, and default retry behavior.
see also: https://github.com/rsyslog/rsyslog/issues/5957
> Implement omhttp batching and performance improvements

- doc/source/configuration/modules/improg.rst
It basically said C stdio and select() are not compatible. This of course is invalid. It is stdio buffering what can cause issues with the module. Provided better advise now.
> doc: improg had a strangely worded limitation listed - corrected

- packaging/docker/dev_env/debian/base/13/Dockerfile
Some module which could have been built on this platform were not enabled, namely: ommongodb, omclickhouse, imkmsg, mmdblookup
see also: https://github.com/rsyslog/rsyslog/issues/5566
> docker: update Debian 13 build to inlcude more modules

- runtime/errmsg.c
- runtime/errmsg.h
most importantly, header file now includes comments that enable tooltip-like behaviour in IDEs. Also includes antipaterns, which is useful for developers and hopefully also for AI to detect them e.g. in code reviews (and get it right in AI-generated code).
@billie-alsup FYI
> core: add doxygen comments to errmsg object

- runtime/Makefile.am
- runtime/net.c
- runtime/net.h
- runtime/netns_socket.c
- runtime/netns_socket.h
- tests/known_issues.supp
- tests/tcp_forwarding_ns_tpl.sh
- tools/omfwd.c
This moves NetworkNamespace functionality into the net module. This allows the same code to be reused across multiple tools and plugins. The first usage is with omfwd, which is changed to use the common net implementation.  Note the net implementation is based on the original omfwd implementation.  Subsequent PRs will be opened for integrating this into omuxsock and imtcp.
The original test case tcp_forwarding_ns_tpl.sh was broken due to use of single quotes rather than double quotes, thus preventing the proper port number argument to be passed to the listener.  Note this test must be run as root.
Development has occurred across Fedora41 and Fedora42, which uses glibc 2.40 and glibc2.41 respectively.  The valgrind suppressions are updated to handle new glibc issues accordingly.
Four new …
> net: Add NetworkNamespace APIs

- doc/source/getting_started/ai-assistants.rst
- doc/source/getting_started/index.rst
Improve discoverability of rsyslog-specific AI helpers for users and contributors. This supports onboarding and troubleshooting and aligns with the project's AI-first strategy.
Impact: docs-only; adds a new page under Getting Started navigation.
> docs/getting_started: add AI assistants page

- packaging/docker/dev_env/debian/base/sid/Dockerfile
there was "workaround" introduced in the container which prevented to detect some issues in libgrypt-related code. This was probably done to get newer version in dev env without the need to adapt code to broken libgrypt API level in new version.
That prevented issues in https://github.com/rsyslog/rsyslog/pull/5406 to be deteced.
> dev container: do not work-around libgcrypt dev interface change

- .github/workflows/run_checks.yml
- .github/workflows/run_kafka_distcheck.yml
- configure.ac
- devtools/devcontainer.sh
- doc/source/configuration/modules/omkafka.rst
- doc/source/reference/parameters/omkafka-kafkaheader.rst
- plugins/omkafka/omkafka.c
- tests/Makefile.am
- tests/omkafka-headers.sh
Add kafkaHeader parameter to define key/value pairs that are attached as headers to every produced message. Require librdkafka v0.11 for header support. Update configure checks, docs and add a regression test.
closes: https://github.com/rsyslog/rsyslog/issues/5185
With help of AI-Agent: OpenAI ChatGPT
---
---
```
```
- Squash related commits …
> omkafka: allow sending static headers

- .github/workflows/run_checks.yml
- tests/diskqueue-multithread-es.sh
- tests/es-basic-abort.sh
- tests/es-basic-bulk.sh
- tests/es-basic-errfile-empty.sh
- tests/es-basic-errfile-popul.sh
- tests/es-basic-es7.14.sh
- tests/es-basic-ha-vg.sh
- tests/es-basic-ha.sh
- tests/es-basic-server.sh
- tests/es-basic-vgthread.sh
- tests/es-basic.sh
- tests/es-bulk-errfile-empty.sh
- tests/es-bulk-errfile-popul-def-format.sh
- tests/es-bulk-errfile-popul-def-interleaved.sh
- tests/es-bulk-errfile-popul-erronly-interleaved.sh
- tests/es-bulk-errfile-popul-erronly.sh
- tests/es-bulk-errfile-popul.sh
- tests/es-bulk-retry.sh
- tests/es-duplicated-ruleset.sh
- tests/es-execOnlyWhenPreviousSuspended.sh
- tests/es-maxbytes-bulk.sh
- tests/es-searchType-empty.sh
- tests/es-writeoperation.sh
Non-technical: test flakiness makes it hard to validate unrelated changes. This aligns omelasticsearch tests with ES 7.14 defaults to get the testbench back to a deterministic state and pave the way for further modernization.
Impact: test behavior changes; one test skipped; CI coverage slightly reduced.
Before: tests mixed ES 6-era types and ad-hoc tarball picks; deprecation checks intermittently failed and retries were brittle. After: tests use the 7.14.1 tarball via diag.sh default, typeless mappings, and `_doc` type in omelasticsearch actions; known-flaky bulk-retry test is skipped for now.
Technical details:
- Add `searchType="_doc"` to all omelasticsearch actions and update index provisioning to typeless mappings compatible with ES 7.14.
- Remove script-level `ES_DOWNLOAD` overrides …
> tests/omelasticsearch: align suite with ES 7.14, reduce flakiness

- tests/diag.sh
- tests/kafka-selftest.sh
We invalidly specified the source distribution, which does not include the necessary class files. This lead to zookeeper start failure and thus no kafka tests being executed.
> CI: fix invalid download name for zookeeper

- AGENTS.md
- ai/rsyslog_code_doc_builder/base_prompt.txt
- contrib/AGENTS.md
- contrib/MODULE_METADATA_TEMPLATE.yaml
- doc/AGENTS.md
- doc/ai/module_map.yaml
- plugins/AGENTS.md
- plugins/MODULE_AGENTS_TEMPLATE.md
- plugins/MODULE_METADATA_TEMPLATE.yaml
- plugins/imkafka/AGENTS.md
- plugins/imkafka/MODULE_METADATA.yaml
- plugins/omelasticsearch/AGENTS.md
- plugins/omelasticsearch/MODULE_METADATA.yaml
- plugins/omkafka/AGENTS.md
- plugins/omkafka/MODULE_METADATA.yaml
- plugins/omruleset/AGENTS.md
- plugins/omruleset/MODULE_METADATA.yaml
- tools/AGENTS.md
- tools/MODULE_METADATA.json
Improve AI-facing documentation to speed up contributor onboarding after the gpt5-codex agent update. The guides clarify bootstrap, testing, and where to find module ownership so agents can work predictably and avoid expensive CI-only paths.
Impact: documentation-only; no runtime changes. Clarifies when to use direct test scripts vs. the autotools harness.
This introduces repository-wide AGENTS guides (root, plugins/, contrib/, tools/, doc/) plus module-focused guides for omelasticsearch, imkafka, omkafka, and omruleset. It adds metadata templates for core and contrib modules, initial MODULE_METADATA.yaml files for the Kafka and ES modules, and a tools/MODULE_METADATA.json for built-ins. The top-level guide now includes quick links, “priming a fresh AI session,” and explicit autotools …
> docs: add agent guides and module metadata scaffolding

- .github/workflows/run_checks.yml
- packaging/docker/dev_env/README.md
- packaging/docker/dev_env/openeuler/base/24.03-lts/Dockerfile
- packaging/docker/dev_env/openeuler/base/24.03-lts/build.sh
- packaging/docker/dev_env/openeuler/base/24.03-lts/tag-previous.sh
Add an openEuler 24.03 LTS development container and wire it into CI to validate builds on that platform.
Why: expand RPM-based coverage and catch distro-specific build issues early.
Impact: CI-only. No runtime or API changes.
Before: no openEuler container or CI job; build breakage went unnoticed. After: dedicated container and matrix entry compile and run unit tests on openEuler.
Notes: module and test coverage may differ on openEuler; track gaps in follow-up issues.
> ci: add openEuler 24.03 LTS container and CI job

- tests/AGENTS.md
- tests/README
This refines testbench docs for both AI agents and human operators. Goal: clearer authoring guidance and a smoother quickstart so agents produce higher-quality tests and contributors run them reliably.
Before/After: scattered guidance across files -> cross-linked docs with explicit helper usage, Valgrind wrapper patterns, and quickstart.
Non-technical rationale:
This improves maintainability and AI readiness by giving agents concrete patterns and reducing duplicate boilerplate. It also aligns operator docs with the harness so CI and local runs behave consistently.
> AI: align AGENTS.md and README; expand harness tips

- template.c
- tests/Makefile.am
- tests/omfile-subtree-jsonf.sh
This PR fixes a bug where `type="subtree"` templates produce empty output when used with modules like `omfwd` that rely on the `lenStr` field to determine message length.
The `tplToString()` function in `template.c` correctly extracts and copies JSON subtree data into the output buffer, but fails to set `iparam->lenStr` to record the actual data length. This causes downstream modules to believe the buffer is empty (lenStr=0), resulting in empty frames being sent over the network or written to files.
**Before this fix:**
- Configurations using `type="subtree"` templates with `omfwd` send **empty TCP/UDP frames**
- Data is correctly extracted but silently dropped due to lenStr=0
- Affects any module that checks lenStr before processing (omfwd, potentially others)
- No error messages are …
> Fix: Subtree Templates Generate Empty Output

- tests/omfwd-lb-1target-retry-test_skeleton-TargetFail.sh
Summary:
- Intermittent failures caused by two intentional TCP drops (-B2 -D900 -a -S5) leading to >100 lost messages due to byte-based drop timing and kernel buffering.
- Increase allowed loss to keep stress characteristics while avoiding flakiness.
What changed:
- tests/omfwd-lb-1target-retry-test_skeleton-TargetFail.sh
- seq_check 0 $((NUMMESSAGES-1)) -m100 -> seq_check 0 $((NUMMESSAGES-1)) -m250
Rationale:
- minitcpsrvr drops on bytes-read thresholds and reopens after a 5s outage; actual loss varies. Two drops can exceed 100 lines. 250 provides sufficient headroom without masking ordering validation.
Raise the allowed loss from -m100 to -m250 in tests/omfwd-lb-1target-retry-test_skeleton-TargetFail.sh to stabilize the test while still verifying ordering.
> tests: stabilize omfwd-lb-1target-retry-1_byte_buf-TargetFail by raising loss tolerance

- .github/workflows/doc_build.yml
- Makefile.am
- configure.ac
Real-world tarballs must be self-contained for doc builds. This change verifies release completeness by building the docs from the tarball, not the checkout.
Impact: Release tarballs now include additional doc assets; CI fails early if a doc-required file is missing.
Before: CI built Sphinx docs directly from the repo tree. Missing files could be masked by in-tree paths. After: CI creates a 'make dist' tarball, unpacks it, and builds docs from that tree to catch omissions.
Technically, the doc workflow installs build deps, runs autoreconf and a minimal './configure', issues 'make dist', unpacks into
'doc-builder/', and runs 'make html' under 'doc-builder/doc'. The artifact path is updated accordingly.
For distribution, 'configure.ac' now composes DOC_FILES from 'doc/source' (*.rst, …
> CI: enhance doc workflow to check tarball completeness

- tests/omfwd-lb-1target-retry-full_buf.sh
- wrap omfwd-lb-1target-retry-full_buf.sh around the shared skeleton so the scenario is retried once before reporting failure, easing TCP buffer timing races
- document follow-on stabilisation ideas for minitcpsrvr coordination and omfwd diagnostics
AI-Agent: Codex
> tests: retry omfwd load-balancer flake before failing

- doc/source/configuration/modules/mmjsonparse.rst
- doc/source/development/engine_overview.rst
- doc/source/reference/parameters/mmjsonparse-allow_trailing.rst
- doc/source/reference/parameters/mmjsonparse-max_scan_bytes.rst
- doc/source/reference/parameters/mmjsonparse-mode.rst
- plugins/mmjsonparse/mmjsonparse.c
- tests/Makefile.am
- tests/mmjsonparse-find-json-basic.sh
- tests/mmjsonparse-find-json-invalid-mode.sh
- tests/mmjsonparse-find-json-invalid.sh
- tests/mmjsonparse-find-json-parser-validation.sh
- tests/mmjsonparse-find-json-scan-limit.sh
- tests/mmjsonparse-find-json-trailing.sh
Plain JSON (often with short textual prefixes) is mainstream in real deployments. This change lets mmjsonparse handle such logs natively, reducing friction compared to the CEE/lumberjack cookie flow.
Impact: Default behavior is unchanged; new mode and parameters are opt-in.
Before: cookie-only JSON. After: find-json parses first top-level {}.
Technical details:
- Add action parameter `mode` with `cookie` (default) and `find-json`. The new mode scans the message for the first `{` and validates a full top-level JSON object using json_tokener; quotes/escapes are respected.
- Add `max_scan_bytes` (default 65536) to bound scanning work and `allow_trailing` (default on) to accept or reject non-whitespace after the JSON object. When scanning fails or is rejected, we keep legacy behavior: return …
> mmjsonparse: add find-json mode to parse embedded JSON
